export { GameOrbitCamera, type CameraFollowListener, type GameOrbitCameraProps } from "./GameOrbitCamera";
export {
  GameFirstPersonCamera,
  readFirstPersonMuzzle,
  type GameFirstPersonCameraProps,
  type ViewmodelProps,
} from "./GameFirstPersonCamera";
export { GameInspectionCamera, type GameInspectionCameraProps } from "./GameInspectionCamera";
export { GameCameraRig, resolveRigKind, type GameCameraRigProps } from "./GameCameraRig";
export {
  PlayerFovProvider,
  PlayerFovSlider,
  usePlayerFov,
  type PlayerFovState,
} from "./PlayerFov";
export {
  PLAYER_FOV_DEFAULT,
  PLAYER_FOV_MAX,
  PLAYER_FOV_MIN,
  PLAYER_FOV_STORAGE_KEY,
  clampPlayerFov,
  composePlayerFov,
  loadPlayerFov,
  resolvePlayerFovBounds,
  savePlayerFov,
  type PlayerFovBounds,
} from "./fovPreference";
export {
  CAMERA_POST_FRAME_PRIORITY,
  CAMERA_RIG_FRAME_PRIORITY,
  ChaseRig,
  CinematicRig,
  LockOnRig,
  ObserverRig,
  RtsRig,
  ShoulderRig,
  SideScrollRig,
  TopDownRig,
  type RigProps,
} from "./cameraRigs";
export {
  applyCameraBlendStep,
  captureCameraBlendFrom,
  createCameraBlendScratch,
  type CameraBlendScratch,
} from "./cameraBlendMath";
export {
  CameraShakeContext,
  cameraShake,
  createCameraShakeChannel,
  defaultCameraShakeChannel,
  useCameraShake,
  type CameraShakeChannel,
} from "./shakeChannel";
export {
  addTrauma,
  angleDelta,
  blendShoulder,
  CALIBRATED_TRAUMA_SHAKE_DECAY_PER_SECOND,
  CALIBRATED_TRAUMA_SHAKE_FREQUENCY,
  CALIBRATED_TRAUMA_SHAKE_MAX_OFFSET,
  CALIBRATED_TRAUMA_SHAKE_MAX_ROLL,
  chaseDesiredPosition,
  chaseLookAt,
  cinematicSample,
  clamp,
  createTrauma,
  crossfadePose,
  forwardVector,
  lerp,
  lockOnPose,
  observerPose,
  resolveChase,
  resolveDirectedCamera,
  resolveObserver,
  resolveShoulder,
  resolveSideScroll,
  resolveSideScrollPose,
  resolveTopDown,
  rightVector,
  rtsPanKeysConflict,
  seatPose,
  shakeOffset,
  shoulderPose,
  sideScrollFollowBlend,
  smoothstep,
  smoothYaw,
  speedToFov,
  springArmStep,
  stepTrauma,
  topDownPose,
  traumaShake,
  yawTo,
  type CameraPose,
  type DirectorCameraValues,
  type ResolvedChase,
  type ResolvedDirectedCamera,
  type ResolvedObserver,
  type ResolvedShoulder,
  type ResolvedSideScroll,
  type ResolvedTopDown,
  type ShakeOffset,
  type StaticCameraValues,
  type TraumaState,
} from "./rigMath";
export {
  cameraFollowStep,
  cameraLookPitch,
  DEFAULT_ORBIT_CAMERA,
  distanceBetween,
  GAME_SIM_FRAME_PRIORITY,
  lerpVec3,
  ORBIT_CAMERA_FRAME_PRIORITY,
  orbitFollowStep,
  orbitYawFromCamera,
  resolveFollowTargetFromPosition,
  resolveOrbitCameraConfig,
  resolveTargetSmoothing,
  seedOrbitFollowState,
  smoothBlend,
  type CameraFollowState,
  type OrbitCameraConfig,
  type OrbitFollowRuntimeState,
  type ResolvedOrbitCameraConfig,
  type Vec3,
} from "./orbitCameraMath";
export {
  resolveInspectionCameraConfig,
  resolveInspectionZoomToCursor,
  seedInspectionCamera,
  type InspectionCameraConfig,
  type InspectionZoomAnchor,
  type ResolvedInspectionCameraConfig,
} from "./inspectionCameraMath";