export { GameOrbitCamera, type CameraFollowListener, type GameOrbitCameraProps } from "./GameOrbitCamera";
export { GameFirstPersonCamera, type GameFirstPersonCameraProps } from "./GameFirstPersonCamera";
export { GameCameraRig, resolveRigKind, type GameCameraRigProps } from "./GameCameraRig";
export {
  CAMERA_POST_FRAME_PRIORITY,
  CAMERA_RIG_FRAME_PRIORITY,
  ChaseRig,
  CinematicRig,
  LockOnRig,
  ObserverRig,
  RtsRig,
  ShoulderRig,
  TopDownRig,
  type RigProps,
} from "./cameraRigs";
export {
  CameraShakeContext,
  cameraShake,
  createCameraShakeChannel,
  defaultCameraShakeChannel,
  useCameraShake,
  type CameraShakeChannel,
} from "./shakeChannel";
export {
  addTrauma,
  angleDelta,
  blendShoulder,
  chaseDesiredPosition,
  chaseLookAt,
  cinematicSample,
  clamp,
  createTrauma,
  crossfadePose,
  forwardVector,
  lerp,
  lockOnPose,
  observerPose,
  resolveChase,
  resolveObserver,
  resolveShoulder,
  resolveTopDown,
  rightVector,
  seatPose,
  shakeOffset,
  shoulderPose,
  smoothstep,
  smoothYaw,
  speedToFov,
  springArmStep,
  stepTrauma,
  topDownPose,
  yawTo,
  type CameraPose,
  type ResolvedChase,
  type ResolvedObserver,
  type ResolvedShoulder,
  type ResolvedTopDown,
  type ShakeOffset,
  type TraumaState,
} from "./rigMath";
export {
  cameraFollowStep,
  cameraLookPitch,
  DEFAULT_ORBIT_CAMERA,
  distanceBetween,
  GAME_SIM_FRAME_PRIORITY,
  lerpVec3,
  ORBIT_CAMERA_FRAME_PRIORITY,
  orbitFollowStep,
  orbitYawFromCamera,
  resolveFollowTargetFromPosition,
  resolveOrbitCameraConfig,
  resolveTargetSmoothing,
  seedOrbitFollowState,
  smoothBlend,
  type CameraFollowState,
  type OrbitCameraConfig,
  type OrbitFollowRuntimeState,
  type ResolvedOrbitCameraConfig,
  type Vec3,
} from "./orbitCameraMath";