import type { NpcDef } from "../../model";

export const NPCS: readonly NpcDef[] = [
  {
    id: "marshal_redbrook",
    name: "Marshal Redbrook",
    zone: "vale",
    position: [4, -294],
    kind: "questgiver",
    dialogueId: "dlg_marshal_redbrook",
  },
  {
    id: "trader_wilkes",
    name: "Trader Wilkes",
    zone: "vale",
    position: [-7, -297],
    kind: "vendor",
    dialogueId: "dlg_trader_wilkes",
    shopId: "shop_eastbrook",
  },
  {
    id: "wilkes_hand",
    name: "Caravan Hand Doss",
    zone: "vale",
    position: [-9, -299],
    kind: "questgiver",
    dialogueId: "dlg_wilkes_hand",
  },
  {
    id: "apothecary_lin",
    name: "Apothecary Lin",
    zone: "vale",
    position: [11, -303],
    kind: "questgiver",
    dialogueId: "dlg_apothecary_lin",
  },
  {
    id: "brother_aldric",
    name: "Brother Aldric",
    zone: "vale",
    position: [-14, -310],
    kind: "questgiver",
    dialogueId: "dlg_brother_aldric",
  },
  {
    id: "fisherman_brandt",
    name: "Fisherman Brandt",
    zone: "vale",
    position: [-16, -294],
    kind: "questgiver",
    dialogueId: "dlg_fisherman_brandt",
  },
  {
    id: "foreman_odell",
    name: "Foreman Odell",
    zone: "vale",
    position: [-4, -314],
    kind: "questgiver",
    dialogueId: "dlg_foreman_odell",
  },
  {
    id: "warden_fenwick",
    name: "Warden Fenwick",
    zone: "marsh",
    position: [3, 4],
    kind: "questgiver",
    dialogueId: "dlg_warden_fenwick",
  },
  {
    id: "provisioner_hale",
    name: "Provisioner Hale",
    zone: "marsh",
    position: [-4, 8],
    kind: "vendor",
    dialogueId: "dlg_provisioner_hale",
    shopId: "shop_fenbridge",
  },
  {
    id: "hale_dockhand",
    name: "Dockhand Sela",
    zone: "marsh",
    position: [-6, 10],
    kind: "questgiver",
    dialogueId: "dlg_hale_dockhand",
  },
  {
    id: "herbalist_yara",
    name: "Herbalist Yara",
    zone: "marsh",
    position: [10, -5],
    kind: "questgiver",
    dialogueId: "dlg_herbalist_yara",
  },
  {
    id: "scout_maren",
    name: "Scout Maren",
    zone: "marsh",
    position: [6, 12],
    kind: "questgiver",
    dialogueId: "dlg_scout_maren",
  },
  {
    id: "brother_aldric_fen",
    name: "Brother Aldric",
    zone: "marsh",
    position: [-8, -4],
    kind: "questgiver",
    dialogueId: "dlg_brother_aldric_fen",
  },
  {
    id: "captain_thessaly",
    name: "Captain Thessaly",
    zone: "peaks",
    position: [4, 304],
    kind: "questgiver",
    dialogueId: "dlg_captain_thessaly",
  },
  {
    id: "quartermaster_bree",
    name: "Quartermaster Bree",
    zone: "peaks",
    position: [-5, 308],
    kind: "vendor",
    dialogueId: "dlg_quartermaster_bree",
    shopId: "shop_highwatch",
  },
  {
    id: "bree_clerk",
    name: "Requisitions Clerk Pell",
    zone: "peaks",
    position: [-7, 310],
    kind: "questgiver",
    dialogueId: "dlg_bree_clerk",
  },
  {
    id: "scout_maren_highwatch",
    name: "Scout Maren",
    zone: "peaks",
    position: [7, 310],
    kind: "questgiver",
    dialogueId: "dlg_scout_maren_highwatch",
  },
  {
    id: "loremaster_caddis",
    name: "Loremaster Caddis",
    zone: "peaks",
    position: [12, 295],
    kind: "questgiver",
    dialogueId: "dlg_loremaster_caddis",
  },
  {
    id: "brother_aldric_highwatch",
    name: "Brother Aldric",
    zone: "peaks",
    position: [-10, 296],
    kind: "questgiver",
    dialogueId: "dlg_brother_aldric_highwatch",
  },
];
