import type { NpcDef } from "../../model";

export const NPCS: readonly NpcDef[] = [
  {
    id: "marshal_redbrook",
    name: "Marshal Redbrook",
    zone: "vale",
    position: [6, -294],
    kind: "questgiver",
    dialogueId: "dlg_marshal_redbrook",
  },
  {
    id: "trader_wilkes",
    name: "Trader Wilkes",
    zone: "vale",
    position: [-7, -297],
    kind: "vendor",
    dialogueId: "dlg_trader_wilkes",
    shopId: "shop_eastbrook",
  },
  {
    id: "brother_aldric",
    name: "Brother Aldric",
    zone: "vale",
    position: [-3, -308],
    kind: "questgiver",
    dialogueId: "dlg_brother_aldric",
  },
  {
    id: "warden_fenwick",
    name: "Warden Fenwick",
    zone: "marsh",
    position: [5, 6],
    kind: "questgiver",
    dialogueId: "dlg_warden_fenwick",
  },
  {
    id: "provisioner_hale",
    name: "Provisioner Hale",
    zone: "marsh",
    position: [-6, 5],
    kind: "vendor",
    dialogueId: "dlg_provisioner_hale",
    shopId: "shop_fenbridge",
  },
  {
    id: "brother_aldric_fen",
    name: "Brother Aldric",
    zone: "marsh",
    position: [2, -8],
    kind: "flavor",
    dialogueId: "dlg_brother_aldric_fen",
  },
  {
    id: "captain_thessaly",
    name: "Captain Thessaly",
    zone: "peaks",
    position: [6, 294],
    kind: "questgiver",
    dialogueId: "dlg_captain_thessaly",
  },
  {
    id: "quartermaster_bree",
    name: "Quartermaster Bree",
    zone: "peaks",
    position: [-6, 304],
    kind: "vendor",
    dialogueId: "dlg_quartermaster_bree",
    shopId: "shop_highwatch",
  },
  {
    id: "brother_aldric_highwatch",
    name: "Brother Aldric",
    zone: "peaks",
    position: [1, 308],
    kind: "flavor",
    dialogueId: "dlg_brother_aldric_highwatch",
  },
];
