/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SkillsIndexRouteImport } from './routes/skills.index'
import { Route as GamesIndexRouteImport } from './routes/games.index'
import { Route as SkillsNameRouteImport } from './routes/skills.$name'
import { Route as GamesGameIdRouteImport } from './routes/games.$gameId'
import { Route as ApiGithubContributionsRouteImport } from './routes/api/github-contributions'
import { Route as ApiGithubRouteImport } from './routes/api/github'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsIndexRoute = SkillsIndexRouteImport.update({
  id: '/skills/',
  path: '/skills/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesIndexRoute = GamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsNameRoute = SkillsNameRouteImport.update({
  id: '/skills/$name',
  path: '/skills/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesGameIdRoute = GamesGameIdRouteImport.update({
  id: '/games/$gameId',
  path: '/games/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubContributionsRoute = ApiGithubContributionsRouteImport.update({
  id: '/api/github-contributions',
  path: '/api/github-contributions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubRoute = ApiGithubRouteImport.update({
  id: '/api/github',
  path: '/api/github',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/github': typeof ApiGithubRoute
  '/api/github-contributions': typeof ApiGithubContributionsRoute
  '/games/$gameId': typeof GamesGameIdRoute
  '/skills/$name': typeof SkillsNameRoute
  '/games/': typeof GamesIndexRoute
  '/skills/': typeof SkillsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/github': typeof ApiGithubRoute
  '/api/github-contributions': typeof ApiGithubContributionsRoute
  '/games/$gameId': typeof GamesGameIdRoute
  '/skills/$name': typeof SkillsNameRoute
  '/games': typeof GamesIndexRoute
  '/skills': typeof SkillsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/github': typeof ApiGithubRoute
  '/api/github-contributions': typeof ApiGithubContributionsRoute
  '/games/$gameId': typeof GamesGameIdRoute
  '/skills/$name': typeof SkillsNameRoute
  '/games/': typeof GamesIndexRoute
  '/skills/': typeof SkillsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/github'
    | '/api/github-contributions'
    | '/games/$gameId'
    | '/skills/$name'
    | '/games/'
    | '/skills/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/github'
    | '/api/github-contributions'
    | '/games/$gameId'
    | '/skills/$name'
    | '/games'
    | '/skills'
  id:
    | '__root__'
    | '/'
    | '/api/github'
    | '/api/github-contributions'
    | '/games/$gameId'
    | '/skills/$name'
    | '/games/'
    | '/skills/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiGithubRoute: typeof ApiGithubRoute
  ApiGithubContributionsRoute: typeof ApiGithubContributionsRoute
  GamesGameIdRoute: typeof GamesGameIdRoute
  SkillsNameRoute: typeof SkillsNameRoute
  GamesIndexRoute: typeof GamesIndexRoute
  SkillsIndexRoute: typeof SkillsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/': {
      id: '/skills/'
      path: '/skills'
      fullPath: '/skills/'
      preLoaderRoute: typeof SkillsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/': {
      id: '/games/'
      path: '/games'
      fullPath: '/games/'
      preLoaderRoute: typeof GamesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/$name': {
      id: '/skills/$name'
      path: '/skills/$name'
      fullPath: '/skills/$name'
      preLoaderRoute: typeof SkillsNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$gameId': {
      id: '/games/$gameId'
      path: '/games/$gameId'
      fullPath: '/games/$gameId'
      preLoaderRoute: typeof GamesGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github-contributions': {
      id: '/api/github-contributions'
      path: '/api/github-contributions'
      fullPath: '/api/github-contributions'
      preLoaderRoute: typeof ApiGithubContributionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github': {
      id: '/api/github'
      path: '/api/github'
      fullPath: '/api/github'
      preLoaderRoute: typeof ApiGithubRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiGithubRoute: ApiGithubRoute,
  ApiGithubContributionsRoute: ApiGithubContributionsRoute,
  GamesGameIdRoute: GamesGameIdRoute,
  SkillsNameRoute: SkillsNameRoute,
  GamesIndexRoute: GamesIndexRoute,
  SkillsIndexRoute: SkillsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
