/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SkillsIndexRouteImport } from './routes/skills.index'
import { Route as GamesIndexRouteImport } from './routes/games.index'
import { Route as ComponentsIndexRouteImport } from './routes/components.index'
import { Route as ApiIndexRouteImport } from './routes/api.index'
import { Route as SkillsNameRouteImport } from './routes/skills.$name'
import { Route as GamesGameIdRouteImport } from './routes/games.$gameId'
import { Route as ApiGithubProxyRouteImport } from './routes/api/github-proxy'
import { Route as ApiGithubContributionsRouteImport } from './routes/api/github-contributions'
import { Route as ApiPkgRouteImport } from './routes/api.$pkg'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsIndexRoute = SkillsIndexRouteImport.update({
  id: '/skills/',
  path: '/skills/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesIndexRoute = GamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsIndexRoute = ComponentsIndexRouteImport.update({
  id: '/components/',
  path: '/components/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIndexRoute = ApiIndexRouteImport.update({
  id: '/api/',
  path: '/api/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsNameRoute = SkillsNameRouteImport.update({
  id: '/skills/$name',
  path: '/skills/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesGameIdRoute = GamesGameIdRouteImport.update({
  id: '/games/$gameId',
  path: '/games/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubProxyRoute = ApiGithubProxyRouteImport.update({
  id: '/api/github-proxy',
  path: '/api/github-proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubContributionsRoute = ApiGithubContributionsRouteImport.update({
  id: '/api/github-contributions',
  path: '/api/github-contributions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPkgRoute = ApiPkgRouteImport.update({
  id: '/api/$pkg',
  path: '/api/$pkg',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/$pkg': typeof ApiPkgRoute
  '/api/github-contributions': typeof ApiGithubContributionsRoute
  '/api/github-proxy': typeof ApiGithubProxyRoute
  '/games/$gameId': typeof GamesGameIdRoute
  '/skills/$name': typeof SkillsNameRoute
  '/api/': typeof ApiIndexRoute
  '/components/': typeof ComponentsIndexRoute
  '/games/': typeof GamesIndexRoute
  '/skills/': typeof SkillsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/$pkg': typeof ApiPkgRoute
  '/api/github-contributions': typeof ApiGithubContributionsRoute
  '/api/github-proxy': typeof ApiGithubProxyRoute
  '/games/$gameId': typeof GamesGameIdRoute
  '/skills/$name': typeof SkillsNameRoute
  '/api': typeof ApiIndexRoute
  '/components': typeof ComponentsIndexRoute
  '/games': typeof GamesIndexRoute
  '/skills': typeof SkillsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/$pkg': typeof ApiPkgRoute
  '/api/github-contributions': typeof ApiGithubContributionsRoute
  '/api/github-proxy': typeof ApiGithubProxyRoute
  '/games/$gameId': typeof GamesGameIdRoute
  '/skills/$name': typeof SkillsNameRoute
  '/api/': typeof ApiIndexRoute
  '/components/': typeof ComponentsIndexRoute
  '/games/': typeof GamesIndexRoute
  '/skills/': typeof SkillsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/api/$pkg'
    | '/api/github-contributions'
    | '/api/github-proxy'
    | '/games/$gameId'
    | '/skills/$name'
    | '/api/'
    | '/components/'
    | '/games/'
    | '/skills/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/api/$pkg'
    | '/api/github-contributions'
    | '/api/github-proxy'
    | '/games/$gameId'
    | '/skills/$name'
    | '/api'
    | '/components'
    | '/games'
    | '/skills'
  id:
    | '__root__'
    | '/'
    | '/sitemap.xml'
    | '/api/$pkg'
    | '/api/github-contributions'
    | '/api/github-proxy'
    | '/games/$gameId'
    | '/skills/$name'
    | '/api/'
    | '/components/'
    | '/games/'
    | '/skills/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPkgRoute: typeof ApiPkgRoute
  ApiGithubContributionsRoute: typeof ApiGithubContributionsRoute
  ApiGithubProxyRoute: typeof ApiGithubProxyRoute
  GamesGameIdRoute: typeof GamesGameIdRoute
  SkillsNameRoute: typeof SkillsNameRoute
  ApiIndexRoute: typeof ApiIndexRoute
  ComponentsIndexRoute: typeof ComponentsIndexRoute
  GamesIndexRoute: typeof GamesIndexRoute
  SkillsIndexRoute: typeof SkillsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/': {
      id: '/skills/'
      path: '/skills'
      fullPath: '/skills/'
      preLoaderRoute: typeof SkillsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/': {
      id: '/games/'
      path: '/games'
      fullPath: '/games/'
      preLoaderRoute: typeof GamesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/': {
      id: '/components/'
      path: '/components'
      fullPath: '/components/'
      preLoaderRoute: typeof ComponentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/': {
      id: '/api/'
      path: '/api'
      fullPath: '/api/'
      preLoaderRoute: typeof ApiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/$name': {
      id: '/skills/$name'
      path: '/skills/$name'
      fullPath: '/skills/$name'
      preLoaderRoute: typeof SkillsNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$gameId': {
      id: '/games/$gameId'
      path: '/games/$gameId'
      fullPath: '/games/$gameId'
      preLoaderRoute: typeof GamesGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github-proxy': {
      id: '/api/github-proxy'
      path: '/api/github-proxy'
      fullPath: '/api/github-proxy'
      preLoaderRoute: typeof ApiGithubProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github-contributions': {
      id: '/api/github-contributions'
      path: '/api/github-contributions'
      fullPath: '/api/github-contributions'
      preLoaderRoute: typeof ApiGithubContributionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$pkg': {
      id: '/api/$pkg'
      path: '/api/$pkg'
      fullPath: '/api/$pkg'
      preLoaderRoute: typeof ApiPkgRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPkgRoute: ApiPkgRoute,
  ApiGithubContributionsRoute: ApiGithubContributionsRoute,
  ApiGithubProxyRoute: ApiGithubProxyRoute,
  GamesGameIdRoute: GamesGameIdRoute,
  SkillsNameRoute: SkillsNameRoute,
  ApiIndexRoute: ApiIndexRoute,
  ComponentsIndexRoute: ComponentsIndexRoute,
  GamesIndexRoute: GamesIndexRoute,
  SkillsIndexRoute: SkillsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
