/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhyRouteImport } from './routes/why'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as CapabilitiesRouteImport } from './routes/capabilities'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GamesIndexRouteImport } from './routes/games.index'
import { Route as GamesIdRouteImport } from './routes/games.$id'
import { Route as ApiGithubProxyRouteImport } from './routes/api/github-proxy'
import { Route as ApiGithubContributionsRouteImport } from './routes/api/github-contributions'

const WhyRoute = WhyRouteImport.update({
  id: '/why',
  path: '/why',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const CapabilitiesRoute = CapabilitiesRouteImport.update({
  id: '/capabilities',
  path: '/capabilities',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesIndexRoute = GamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesIdRoute = GamesIdRouteImport.update({
  id: '/games/$id',
  path: '/games/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubProxyRoute = ApiGithubProxyRouteImport.update({
  id: '/api/github-proxy',
  path: '/api/github-proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubContributionsRoute = ApiGithubContributionsRouteImport.update({
  id: '/api/github-contributions',
  path: '/api/github-contributions',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/capabilities': typeof CapabilitiesRoute
  '/editor': typeof EditorRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/why': typeof WhyRoute
  '/api/github-contributions': typeof ApiGithubContributionsRoute
  '/api/github-proxy': typeof ApiGithubProxyRoute
  '/games/$id': typeof GamesIdRoute
  '/games/': typeof GamesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/capabilities': typeof CapabilitiesRoute
  '/editor': typeof EditorRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/why': typeof WhyRoute
  '/api/github-contributions': typeof ApiGithubContributionsRoute
  '/api/github-proxy': typeof ApiGithubProxyRoute
  '/games/$id': typeof GamesIdRoute
  '/games': typeof GamesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/capabilities': typeof CapabilitiesRoute
  '/editor': typeof EditorRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/why': typeof WhyRoute
  '/api/github-contributions': typeof ApiGithubContributionsRoute
  '/api/github-proxy': typeof ApiGithubProxyRoute
  '/games/$id': typeof GamesIdRoute
  '/games/': typeof GamesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/capabilities'
    | '/editor'
    | '/sitemap.xml'
    | '/why'
    | '/api/github-contributions'
    | '/api/github-proxy'
    | '/games/$id'
    | '/games/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/capabilities'
    | '/editor'
    | '/sitemap.xml'
    | '/why'
    | '/api/github-contributions'
    | '/api/github-proxy'
    | '/games/$id'
    | '/games'
  id:
    | '__root__'
    | '/'
    | '/capabilities'
    | '/editor'
    | '/sitemap.xml'
    | '/why'
    | '/api/github-contributions'
    | '/api/github-proxy'
    | '/games/$id'
    | '/games/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CapabilitiesRoute: typeof CapabilitiesRoute
  EditorRoute: typeof EditorRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WhyRoute: typeof WhyRoute
  ApiGithubContributionsRoute: typeof ApiGithubContributionsRoute
  ApiGithubProxyRoute: typeof ApiGithubProxyRoute
  GamesIdRoute: typeof GamesIdRoute
  GamesIndexRoute: typeof GamesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/why': {
      id: '/why'
      path: '/why'
      fullPath: '/why'
      preLoaderRoute: typeof WhyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capabilities': {
      id: '/capabilities'
      path: '/capabilities'
      fullPath: '/capabilities'
      preLoaderRoute: typeof CapabilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/': {
      id: '/games/'
      path: '/games'
      fullPath: '/games/'
      preLoaderRoute: typeof GamesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$id': {
      id: '/games/$id'
      path: '/games/$id'
      fullPath: '/games/$id'
      preLoaderRoute: typeof GamesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github-proxy': {
      id: '/api/github-proxy'
      path: '/api/github-proxy'
      fullPath: '/api/github-proxy'
      preLoaderRoute: typeof ApiGithubProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github-contributions': {
      id: '/api/github-contributions'
      path: '/api/github-contributions'
      fullPath: '/api/github-contributions'
      preLoaderRoute: typeof ApiGithubContributionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CapabilitiesRoute: CapabilitiesRoute,
  EditorRoute: EditorRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WhyRoute: WhyRoute,
  ApiGithubContributionsRoute: ApiGithubContributionsRoute,
  ApiGithubProxyRoute: ApiGithubProxyRoute,
  GamesIdRoute: GamesIdRoute,
  GamesIndexRoute: GamesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
