import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import * as THREE from 'three';
import {GLTFLoader} from 'three/examples/jsm/loaders/GLTFLoader.js';
import {MeshoptDecoder} from 'three/examples/jsm/libs/meshopt_decoder.module.js';
import {game} from './games/lantern-reach/src/game.config';
import {CLASS_ENTITY_ID} from './games/lantern-reach/src/game/model';
import {createGameContext} from '@jgengine/core/runtime/gameContext';
import {resolveColliders} from '@jgengine/core/scene/colliders';
import {placeAuthoredObjectsFromDocument} from '@jgengine/core/world/authoredObjects';
import {resolvePlayerMovementTuning,stepPlayerMovement,snapshotPlayerMovement,playerMovementTelemetry} from '@jgengine/core/movement/playerMovement';
import {DEFAULT_OBSTACLE_PLAYER_RADIUS,DEFAULT_OBSTACLE_PLAYER_HEIGHT,resolveObstacleVerticalStep} from '@jgengine/core/movement/movementModel';
import {obstacleFromCollider} from '@jgengine/core/movement/solidObstacles';
import {measureLocalBounds,reportMeasuredBounds} from '@jgengine/shell/render/measureBounds';
import {measureLocalCollisionTriangles,reportMeasuredCollisionMesh} from '@jgengine/shell/render/measureCollisionMesh';
import {cloneModelScene,modelPlacementTransform,disposeModelScene} from '@jgengine/shell/render/modelRender';
import {createEditorSession} from '@jgengine/core/editor/commands';
import {importEditorDocumentJson} from '@jgengine/core/editor/document';
import {createAuthoredMovementReader,bindAuthoredMovement} from '@jgengine/core/editor/movementCatalog';
const baseline=JSON.parse(readFileSync(new URL('./ceiling-baseline.json',import.meta.url),'utf8')).objects[0];
const manifest=JSON.parse(readFileSync(new URL('./candidate-package-manifest.json',import.meta.url),'utf8'));
const savedDoc=readFileSync(new URL('./authoring-doc.json',import.meta.url),'utf8');
const document=importEditorDocumentJson(savedDoc);const session=createEditorSession(document);
const reader=createAuthoredMovementReader(()=>session.getState().document,'player-motion',CLASS_ENTITY_ID);
const bound=bindAuthoredMovement(reader,{movement:game.movement,physics:game.game.physics});
const model=(game.objectModels as any)[baseline.catalogId];
const bytes=readFileSync(new URL('./games/lantern-reach/public'+model.url,import.meta.url));
assert.equal(createHash('sha256').update(bytes).digest('hex'),baseline.glbSha256);
const loader=new GLTFLoader().setMeshoptDecoder(MeshoptDecoder);loader.register(parser=>({name:'geometry-numerical-no-image-decode',beforeRoot(){for(const material of parser.json.materials??[]){delete material.normalTexture;delete material.occlusionTexture;delete material.emissiveTexture;if(material.pbrMetallicRoughness){delete material.pbrMetallicRoughness.baseColorTexture;delete material.pbrMetallicRoughness.metallicRoughnessTexture;}}}}));
const gltf=await loader.parseAsync(bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength),'');const content=cloneModelScene(gltf.scene);const frame=new THREE.Group().add(content);const bounds=measureLocalBounds(frame)!;const placement=modelPlacementTransform(frame,model,bounds);const triangles=measureLocalCollisionTriangles(frame,{scale:placement.scale,offset:placement.position})!;
const height=(game.entityModels as any)[CLASS_ENTITY_ID].targetHeight;assert.equal(reader().config.movement?.collisionHeight,height);
const uid='authored-roof-consumer-proof';const defaultHeight=DEFAULT_OBSTACLE_PLAYER_HEIGHT;
const make=()=>{const ctx=createGameContext({definition:game.game,content:game.content,models:{entity:kind=>(game.entityModels as any)[kind],object:kind=>(game.objectModels as any)[kind]},player:{userId:uid,isNew:true}});game.loop.onInit(ctx);game.loop.onNewPlayer(ctx);placeAuthoredObjectsFromDocument(ctx.scene.object,game.editorLayers!,ctx.world.groundHeightAt,{onExisting:'keep'});reportMeasuredBounds(ctx,'object',baseline.catalogId,{min:bounds.min.map((v,i)=>v*placement.scale+placement.position[i]!),max:bounds.max.map((v,i)=>v*placement.scale+placement.position[i]!),meshCount:bounds.meshCount});reportMeasuredCollisionMesh(ctx,'object',baseline.catalogId,triangles);return ctx;};
const tuning=resolvePlayerMovementTuning({world:game.game.world,physics:bound.physics,movement:bound.movement,collision:game.collision});
const setHeight=(value:number)=>{const doc=session.getState().document;const entry=doc.catalogs!.find(c=>c.id==='player-motion')!.entries.find(e=>e.id===CLASS_ENTITY_ID)!;session.dispatch({type:'setCatalogEntry',catalogId:'player-motion',entryId:CLASS_ENTITY_ID,patch:{meta:{...entry.meta,collisionHeight:value}}});assert.equal(reader().config.movement!.collisionHeight,value);};
function walk(ctx:ReturnType<typeof make>,steps=1800){let routeFrames=0,minDistance=Infinity;const samples=[];for(;routeFrames<steps;routeFrames++){const p=ctx.scene.entity.get(uid)!.position;const dx=baseline.selected.position[0]-p[0],dz=baseline.selected.position[2]-p[2],distance=Math.hypot(dx,dz);minDistance=Math.min(minDistance,distance);if(distance<.08)break;stepPlayerMovement(ctx,uid,{held:['moveForward'],analog:{moveForward:Math.min(1,distance/.3)},pointer:null},1/120,tuning,Math.atan2(dx,dz));const position=structuredClone(ctx.scene.entity.get(uid)!.position);samples.push({frame:routeFrames,position,telemetry:structuredClone(playerMovementTelemetry(ctx,uid))});}return{routeFrames,minDistance,reached:routeFrames<steps,position:structuredClone(ctx.scene.entity.get(uid)!.position),samples};}
const ctx=make();const authoredSpawn=structuredClone(ctx.scene.entity.get(uid)!.position);assert.deepEqual(authoredSpawn,baseline.normalSpawnWalk.authoredSpawn);
const roof=ctx.scene.object.get(baseline.marker.id)!;const collider=resolveColliders(ctx.scene.object.collidersOf(roof.instanceId)).find(c=>c.purpose==='physical'&&c.blocks)!;const obstacle=obstacleFromCollider(collider,roof.position,roof.rotationY);
assert.deepEqual(JSON.parse(JSON.stringify(obstacle)),baseline.obstacle);
const initialBlocking=ctx.scene.object.list().flatMap(object=>resolveColliders(ctx.scene.object.collidersOf(object.instanceId)).filter(c=>c.purpose==='physical'&&c.blocks).map(c=>({object,collider:c,obstacle:obstacleFromCollider(c,object.position,object.rotationY)}))).filter(row=>resolveObstacleVerticalStep(authoredSpawn,0,[row.obstacle],DEFAULT_OBSTACLE_PLAYER_RADIUS,height).initialOverlap);writeFileSync(new URL('./initial-height-readiness.json',import.meta.url),JSON.stringify({cohort:manifest.commit,height,authoredSpawn,blocking:initialBlocking},null,2));
const configuredRoute=walk(ctx);assert.equal(configuredRoute.reached,false,'authored body cannot enter lower roof');assert.ok(configuredRoute.samples.every(s=>s.telemetry?.collisionHeight===height&&s.telemetry.requestedCollisionHeight===height&&!s.telemetry.collisionHeightBlocked));
assert.ok(configuredRoute.samples.every(s=>!resolveObstacleVerticalStep(s.position,0,[obstacle],DEFAULT_OBSTACLE_PLAYER_RADIUS,height).initialOverlap));
setHeight(defaultHeight);const short=make();const shortRoute=walk(short);assert.equal(shortRoute.routeFrames,baseline.normalSpawnWalk.routeFrames);assert.deepEqual(shortRoute.position,baseline.normalSpawnWalk.walkedTo);
for(let i=0;i<120;i++)stepPlayerMovement(short,uid,{held:[],pointer:null},1/120,tuning,0);assert.deepEqual(short.scene.entity.get(uid)!.position,baseline.normalSpawnWalk.brakedAt);
setHeight(height);const prior=structuredClone(short.scene.entity.get(uid)!.position);const blocked=[];
for(let i=0;i<12;i++){stepPlayerMovement(short,uid,{held:[],pointer:null},1/120,tuning,0);blocked.push({position:structuredClone(short.scene.entity.get(uid)!.position),telemetry:structuredClone(playerMovementTelemetry(short,uid))});}
assert.ok(blocked.every(s=>s.telemetry!.collisionHeight===defaultHeight&&s.telemetry!.requestedCollisionHeight===height&&s.telemetry!.collisionHeightBlocked));assert.ok(blocked.every(s=>Math.hypot(s.position[0]-prior[0],s.position[2]-prior[2])<1e-8));
const exit=[];for(let i=0;i<240;i++){stepPlayerMovement(short,uid,{held:['moveForward'],pointer:null},1/120,tuning,Math.atan2(authoredSpawn[0]-prior[0],authoredSpawn[2]-prior[2]));exit.push({frame:i,position:structuredClone(short.scene.entity.get(uid)!.position),telemetry:structuredClone(playerMovementTelemetry(short,uid))});if(exit.at(-1)!.telemetry!.collisionHeight===height)break;}
assert.ok(exit.at(-1)!.telemetry!.collisionHeight===height&&!exit.at(-1)!.telemetry!.collisionHeightBlocked,'moving out accepts authored growth');assert.ok(exit.every(s=>!resolveObstacleVerticalStep(s.position,0,[obstacle],DEFAULT_OBSTACLE_PLAYER_RADIUS,s.telemetry!.collisionHeight!).initialOverlap));
const output={label:'unreleased installed public package numerical authored-height route; no native appearance claim',cohort:manifest.commit,tree:manifest.tree,sourceCommit:'45a50523cae2021c412aa83ce50589d806dd96d9',originalWorldUnchanged:true,authoringSliceOnlyFeedsMovementReader:true,fullOriginalSaveBlockedByDawn:true,authoringDocumentSha256:createHash('sha256').update(savedDoc).digest('hex'),catalogId:'player-motion',entryId:CLASS_ENTITY_ID,visualModelHeight:height,roofGlbSha256:baseline.glbSha256,roofMarker:baseline.marker.id,roofObstacle:obstacle,selectedTarget:baseline.selected,authoredSpawn,configuredRoute,shortRoute,blockedGrowth:blocked,exitGrowth:exit,finalSnapshot:snapshotPlayerMovement(short,uid)};
writeFileSync(new URL('./height-route.json',import.meta.url),JSON.stringify(output,null,2));console.log(JSON.stringify({cohort:manifest.commit,configuredHeight:height,configuredMinDistance:configuredRoute.minDistance,configuredReached:configuredRoute.reached,shortRouteFrames:shortRoute.routeFrames,blockedGrowthFrames:blocked.length,growthAcceptedAtExitFrame:exit.at(-1)!.frame}));disposeModelScene(content);
