import type { MobDef } from "../../model";

export const MOBS: readonly MobDef[] = [
  {
    id: "forest_wolf",
    name: "Forest Wolf",
    family: "beast",
    zone: "vale",
    minLevel: 1,
    maxLevel: 2,
    hpBase: 40,
    hpPerLevel: 14,
    dmgBase: 3,
    dmgPerLevel: 1.6,
    attackSpeed: 2.0,
    armorPerLevel: 10,
    moveSpeed: 8,
    aggroRadius: 10,
    count: 10,
    drops: [
      { copper: [6, 10], chance: 1 },
      { itemId: "wolf_fang", chance: 0.45 },
      { itemId: "milepost_boots", chance: 0.1 },
      { itemId: "wolfhide_satchel", chance: 0.02 },
    ],
    packFrenzy: { radius: 12, hasteMult: 1.3, duration: 8 },
  },
  {
    id: "wild_boar",
    name: "Wild Boar",
    family: "beast",
    zone: "vale",
    minLevel: 2,
    maxLevel: 3,
    hpBase: 38,
    hpPerLevel: 16,
    dmgBase: 4,
    dmgPerLevel: 1.8,
    attackSpeed: 2.2,
    armorPerLevel: 14,
    moveSpeed: 7.5,
    aggroRadius: 9,
    count: 10,
    drops: [
      { copper: [9, 15], chance: 1 },
      { itemId: "boar_hide", chance: 0.6 },
      { itemId: "tough_jerky", chance: 0.3 },
      { itemId: "trail_leggings", chance: 0.1 },
    ],
  },
  {
    id: "webwood_spider",
    name: "Sableweb Lurker",
    family: "beast",
    zone: "vale",
    minLevel: 2,
    maxLevel: 4,
    hpBase: 36,
    hpPerLevel: 15,
    dmgBase: 4,
    dmgPerLevel: 1.7,
    attackSpeed: 1.8,
    armorPerLevel: 8,
    moveSpeed: 8,
    aggroRadius: 10,
    count: 10,
    drops: [
      { copper: [11, 18], chance: 1 },
      { itemId: "webwood_silk", chance: 0.55 },
      { itemId: "spider_leg", chance: 0.4 },
    ],
  },
  {
    id: "vale_bandit",
    name: "Vale Bandit",
    family: "humanoid",
    zone: "vale",
    minLevel: 3,
    maxLevel: 5,
    hpBase: 40,
    hpPerLevel: 18,
    dmgBase: 5,
    dmgPerLevel: 2.0,
    attackSpeed: 2.0,
    armorPerLevel: 20,
    moveSpeed: 7,
    aggroRadius: 11,
    count: 10,
    drops: [
      { copper: [19, 31], chance: 1 },
      { itemId: "bandit_bandana", chance: 0.5 },
      { itemId: "linen_scrap", chance: 0.3 },
    ],
  },
  {
    id: "tunnel_rat",
    name: "Deeprock Digger",
    family: "humanoid",
    zone: "vale",
    minLevel: 4,
    maxLevel: 6,
    hpBase: 42,
    hpPerLevel: 18,
    dmgBase: 6,
    dmgPerLevel: 2.0,
    attackSpeed: 2.1,
    armorPerLevel: 16,
    moveSpeed: 7,
    aggroRadius: 10,
    count: 10,
    drops: [
      { copper: [17, 28], chance: 1 },
      { itemId: "tallow_candle", chance: 0.6 },
      { itemId: "blessed_wax", chance: 0.45 },
      { itemId: "linen_scrap", chance: 0.25 },
      { itemId: "mossy_handwraps", chance: 0.15 },
    ],
  },
  {
    id: "restless_bones",
    name: "Restless Bones",
    family: "undead",
    zone: "vale",
    minLevel: 5,
    maxLevel: 7,
    hpBase: 46,
    hpPerLevel: 19,
    dmgBase: 7,
    dmgPerLevel: 2.1,
    attackSpeed: 2.3,
    armorPerLevel: 14,
    moveSpeed: 6.5,
    aggroRadius: 11,
    count: 10,
    drops: [
      { copper: [23, 38], chance: 1 },
      { itemId: "bone_fragments", chance: 0.6 },
      { itemId: "ghostly_essence", chance: 0.55 },
    ],
  },
  {
    id: "mudfin_murloc",
    name: "Mudfin Skulker",
    family: "beast",
    zone: "vale",
    minLevel: 3,
    maxLevel: 5,
    hpBase: 36,
    hpPerLevel: 17,
    dmgBase: 5,
    dmgPerLevel: 1.9,
    attackSpeed: 1.9,
    armorPerLevel: 12,
    moveSpeed: 8,
    aggroRadius: 13,
    count: 10,
    drops: [
      { copper: [14, 23], chance: 1 },
      { itemId: "mudfin_scale", chance: 0.5 },
      { itemId: "linen_scrap", chance: 0.2 },
    ],
  },
  {
    id: "old_greyjaw",
    name: "Old Greyjaw",
    family: "beast",
    zone: "vale",
    minLevel: 4,
    maxLevel: 4,
    hpBase: 110,
    hpPerLevel: 20,
    dmgBase: 5,
    dmgPerLevel: 2.0,
    attackSpeed: 1.8,
    armorPerLevel: 16,
    moveSpeed: 8.5,
    aggroRadius: 12,
    count: 1,
    rare: true,
    drops: [
      { copper: [45, 75], chance: 1 },
      { itemId: "greyjaw_fang", chance: 1 },
      { itemId: "wolf_fang", chance: 1 },
      { itemId: "wolfhide_satchel", chance: 0.35 },
    ],
  },
  {
    id: "mogger",
    name: "Mogger",
    family: "humanoid",
    zone: "vale",
    minLevel: 6,
    maxLevel: 6,
    hpBase: 300,
    hpPerLevel: 58,
    dmgBase: 12,
    dmgPerLevel: 3.5,
    attackSpeed: 2.2,
    armorPerLevel: 34,
    moveSpeed: 7.4,
    aggroRadius: 14,
    count: 1,
    rare: true,
    drops: [
      { copper: [135, 225], chance: 1 },
      { itemId: "linen_scrap", chance: 1 },
      { itemId: "moggers_stomper_boots", chance: 0.3 },
      { itemId: "moggers_shiv", chance: 0.25 },
      { itemId: "cryptstalker_jerkin", chance: 0.25 },
    ],
  },
  {
    id: "mogger_lackey",
    name: "Mogger Lackey",
    family: "humanoid",
    zone: "vale",
    minLevel: 5,
    maxLevel: 6,
    hpBase: 44,
    hpPerLevel: 18,
    dmgBase: 6,
    dmgPerLevel: 2.0,
    attackSpeed: 2.0,
    armorPerLevel: 18,
    moveSpeed: 7.5,
    aggroRadius: 12,
    count: 10,
    drops: [],
  },
  {
    id: "grix_the_tunnelking",
    name: "Grix the Tunnelking",
    family: "humanoid",
    zone: "vale",
    minLevel: 7,
    maxLevel: 7,
    hpBase: 280,
    hpPerLevel: 52,
    dmgBase: 11,
    dmgPerLevel: 3.3,
    attackSpeed: 2.0,
    armorPerLevel: 24,
    moveSpeed: 7,
    aggroRadius: 13,
    count: 1,
    rare: true,
    drops: [
      { copper: [113, 188], chance: 1 },
      { itemId: "tallow_candle", chance: 1 },
      { itemId: "lesser_healing_potion", chance: 1 },
      { itemId: "tunnelkings_spade", chance: 0.3 },
      { itemId: "moggers_copper_cudgel", chance: 0.25 },
      { itemId: "hollowbone_hauberk", chance: 0.25 },
    ],
  },
  {
    id: "captain_verlan",
    name: "Captain Verlan",
    family: "undead",
    zone: "vale",
    minLevel: 7,
    maxLevel: 7,
    hpBase: 280,
    hpPerLevel: 56,
    dmgBase: 12,
    dmgPerLevel: 3.4,
    attackSpeed: 2.6,
    armorPerLevel: 32,
    moveSpeed: 7.4,
    aggroRadius: 13,
    count: 1,
    rare: true,
    drops: [
      { copper: [120, 200], chance: 1 },
      { itemId: "bone_fragments", chance: 1 },
      { itemId: "oathbound_greaves", chance: 0.3 },
      { itemId: "verlans_oathblade", chance: 0.25 },
      { itemId: "hollow_vigil_staff", chance: 0.25 },
      { itemId: "gravewardens_shiv", chance: 0.25 },
    ],
  },
  {
    id: "wraithbinder_maldrec",
    name: "Wraithbinder Maldrec",
    family: "undead",
    zone: "vale",
    minLevel: 7,
    maxLevel: 7,
    hpBase: 320,
    hpPerLevel: 60,
    dmgBase: 12,
    dmgPerLevel: 3.4,
    attackSpeed: 2.3,
    armorPerLevel: 28,
    moveSpeed: 6.8,
    aggroRadius: 13,
    count: 1,
    rare: true,
    drops: [
      { copper: [120, 200], chance: 1 },
      { itemId: "bone_fragments", chance: 1 },
      { itemId: "maldrecs_soulbinder", chance: 0.25 },
      { itemId: "hollowbone_hauberk", chance: 0.25 },
      { itemId: "gravewoven_raiment", chance: 0.25 },
      { itemId: "cryptstalker_jerkin", chance: 0.25 },
    ],
  },
  {
    id: "gorrak",
    name: "Gorrak the Ruthless",
    family: "humanoid",
    zone: "vale",
    minLevel: 6,
    maxLevel: 6,
    hpBase: 160,
    hpPerLevel: 30,
    dmgBase: 8,
    dmgPerLevel: 2.4,
    attackSpeed: 2.4,
    armorPerLevel: 30,
    moveSpeed: 7,
    aggroRadius: 13,
    count: 1,
    boss: true,
    drops: [
      { copper: [188, 313], chance: 1 },
      { itemId: "bandit_bandana", chance: 1 },
      { itemId: "oiled_boots", chance: 0.5 },
      { itemId: "quilted_trousers", chance: 0.5 },
      { itemId: "gorraks_cruel_chopper", chance: 0.25 },
      { itemId: "gorraks_cleaver", chance: 0.3 },
    ],
  },
  {
    id: "mire_prowler",
    name: "Mire Prowler",
    family: "beast",
    zone: "marsh",
    minLevel: 7,
    maxLevel: 8,
    hpBase: 46,
    hpPerLevel: 19,
    dmgBase: 7,
    dmgPerLevel: 2.1,
    attackSpeed: 2.0,
    armorPerLevel: 12,
    moveSpeed: 8.5,
    aggroRadius: 11,
    count: 10,
    drops: [
      { copper: [23, 38], chance: 1 },
      { itemId: "mire_prowler_pelt", chance: 0.6 },
      { itemId: "soggy_moccasin", chance: 0.3 },
      { itemId: "lesser_healing_potion", chance: 0.08 },
    ],
  },
  {
    id: "deepfen_murloc",
    name: "Deepfen Snapper",
    family: "beast",
    zone: "marsh",
    minLevel: 8,
    maxLevel: 9,
    hpBase: 48,
    hpPerLevel: 19,
    dmgBase: 7,
    dmgPerLevel: 2.2,
    attackSpeed: 1.9,
    armorPerLevel: 12,
    moveSpeed: 8,
    aggroRadius: 14,
    count: 10,
    drops: [
      { copper: [26, 44], chance: 1 },
      { itemId: "waterlogged_idol", chance: 0.5 },
      { itemId: "mudfin_scale", chance: 0.4 },
    ],
  },
  {
    id: "mirejaw_the_ravenous",
    name: "Mirejaw the Ravenous",
    family: "beast",
    zone: "marsh",
    minLevel: 10,
    maxLevel: 10,
    hpBase: 320,
    hpPerLevel: 58,
    dmgBase: 15,
    dmgPerLevel: 3.7,
    attackSpeed: 1.8,
    armorPerLevel: 26,
    moveSpeed: 8.2,
    aggroRadius: 14,
    count: 1,
    rare: true,
    drops: [
      { copper: [195, 325], chance: 1 },
      { itemId: "mudfin_scale", chance: 1 },
      { itemId: "mirejaw_biteblade", chance: 0.25 },
      { itemId: "mirejaw_scale_vest", chance: 0.25 },
      { itemId: "fen_reaver_glaive", chance: 0.25 },
      { itemId: "mirejaw_oracle_staff", chance: 0.25 },
    ],
  },
  {
    id: "mirejaw_frenzy",
    name: "Mirejaw Frenzy",
    family: "beast",
    zone: "marsh",
    minLevel: 9,
    maxLevel: 10,
    hpBase: 48,
    hpPerLevel: 18,
    dmgBase: 8,
    dmgPerLevel: 2.2,
    attackSpeed: 1.7,
    armorPerLevel: 12,
    moveSpeed: 8.5,
    aggroRadius: 14,
    count: 10,
    drops: [],
  },
  {
    id: "sloomtooth_the_drowned",
    name: "Sloomtooth the Drowned",
    family: "beast",
    zone: "marsh",
    minLevel: 11,
    maxLevel: 11,
    hpBase: 340,
    hpPerLevel: 60,
    dmgBase: 16,
    dmgPerLevel: 3.8,
    attackSpeed: 1.9,
    armorPerLevel: 28,
    moveSpeed: 8.4,
    aggroRadius: 14,
    count: 1,
    rare: true,
    drops: [
      { copper: [210, 350], chance: 1 },
      { itemId: "mudfin_scale", chance: 1 },
      { itemId: "tidereaver_gaff", chance: 0.25 },
      { itemId: "sloomtooth_tidefang", chance: 0.25 },
      { itemId: "drowned_tide_scepter", chance: 0.25 },
    ],
  },
  {
    id: "mire_widow",
    name: "Mirefen Widow",
    family: "beast",
    zone: "marsh",
    minLevel: 8,
    maxLevel: 10,
    hpBase: 48,
    hpPerLevel: 19,
    dmgBase: 8,
    dmgPerLevel: 2.2,
    attackSpeed: 1.8,
    armorPerLevel: 10,
    moveSpeed: 8,
    aggroRadius: 10,
    count: 10,
    drops: [
      { copper: [29, 48], chance: 1 },
      { itemId: "widow_venom_sac", chance: 0.65 },
      { itemId: "spider_leg", chance: 0.4 },
    ],
  },
  {
    id: "mirefen_broodmother",
    name: "The Broodmother",
    family: "beast",
    zone: "marsh",
    minLevel: 10,
    maxLevel: 10,
    hpBase: 150,
    hpPerLevel: 26,
    dmgBase: 9,
    dmgPerLevel: 2.4,
    attackSpeed: 1.8,
    armorPerLevel: 16,
    moveSpeed: 8,
    aggroRadius: 14,
    count: 1,
    boss: true,
    drops: [
      { copper: [225, 375], chance: 1 },
      { itemId: "marshstrider_boots", chance: 0.4 },
      { itemId: "broodmother_silk_robe", chance: 0.25 },
      { itemId: "spider_leg", chance: 1 },
    ],
  },
  {
    id: "fen_troll",
    name: "Mirefen Troll",
    family: "humanoid",
    zone: "marsh",
    minLevel: 10,
    maxLevel: 12,
    hpBase: 56,
    hpPerLevel: 21,
    dmgBase: 9,
    dmgPerLevel: 2.4,
    attackSpeed: 2.2,
    armorPerLevel: 18,
    moveSpeed: 7.5,
    aggroRadius: 11,
    count: 10,
    drops: [
      { copper: [38, 63], chance: 1 },
      { itemId: "troll_fetish", chance: 0.6 },
      { itemId: "chipped_tusk", chance: 0.4 },
      { itemId: "bogiron_nugget", chance: 0.3 },
      { itemId: "elixir_of_the_bear", chance: 0.07 },
    ],
  },
  {
    id: "grubjaw",
    name: "Grubjaw the Glutton",
    family: "humanoid",
    zone: "marsh",
    minLevel: 12,
    maxLevel: 12,
    hpBase: 130,
    hpPerLevel: 26,
    dmgBase: 10,
    dmgPerLevel: 2.5,
    attackSpeed: 2.2,
    armorPerLevel: 20,
    moveSpeed: 7.5,
    aggroRadius: 13,
    count: 1,
    rare: true,
    drops: [
      { copper: [150, 250], chance: 1 },
      { itemId: "grubjaw_tusk", chance: 1 },
      { itemId: "chipped_tusk", chance: 1 },
    ],
  },
  {
    id: "drowned_dead",
    name: "Drowned Dead",
    family: "undead",
    zone: "marsh",
    minLevel: 9,
    maxLevel: 11,
    hpBase: 52,
    hpPerLevel: 20,
    dmgBase: 8,
    dmgPerLevel: 2.3,
    attackSpeed: 2.3,
    armorPerLevel: 14,
    moveSpeed: 6.5,
    aggroRadius: 11,
    count: 10,
    drops: [
      { copper: [32, 53], chance: 1 },
      { itemId: "bone_fragments", chance: 0.5 },
      { itemId: "cracked_fetish", chance: 0.3 },
    ],
  },
  {
    id: "gravecaller_cultist",
    name: "Gravecaller Cultist",
    family: "humanoid",
    zone: "marsh",
    minLevel: 10,
    maxLevel: 12,
    hpBase: 50,
    hpPerLevel: 20,
    dmgBase: 9,
    dmgPerLevel: 2.4,
    attackSpeed: 2.0,
    armorPerLevel: 20,
    moveSpeed: 7,
    aggroRadius: 11,
    count: 10,
    drops: [
      { copper: [41, 69], chance: 1 },
      { itemId: "linen_scrap", chance: 0.3 },
      { itemId: "tallow_candle", chance: 0.3 },
      { itemId: "gravecaller_sigil", chance: 0.35 },
    ],
  },
  {
    id: "gravecaller_summoner",
    name: "Gravecaller Summoner",
    family: "humanoid",
    zone: "marsh",
    minLevel: 11,
    maxLevel: 12,
    hpBase: 46,
    hpPerLevel: 19,
    dmgBase: 10,
    dmgPerLevel: 2.5,
    attackSpeed: 2.0,
    armorPerLevel: 16,
    moveSpeed: 7,
    aggroRadius: 12,
    count: 5,
    drops: [
      { copper: [45, 75], chance: 1 },
      { itemId: "cult_cipher", chance: 0.6 },
    ],
  },
  {
    id: "gravecaller_mender",
    name: "Gravecaller Mender",
    family: "humanoid",
    zone: "marsh",
    minLevel: 11,
    maxLevel: 12,
    hpBase: 44,
    hpPerLevel: 18,
    dmgBase: 8,
    dmgPerLevel: 2.2,
    attackSpeed: 2.1,
    armorPerLevel: 16,
    moveSpeed: 7,
    aggroRadius: 12,
    count: 5,
    drops: [
      { copper: [44, 73], chance: 1 },
      { itemId: "cult_cipher", chance: 0.4 },
      { itemId: "tallow_candle", chance: 0.3 },
    ],
  },
  {
    id: "sister_nhalia",
    name: "Sister Nhalia",
    family: "humanoid",
    zone: "marsh",
    minLevel: 12,
    maxLevel: 12,
    hpBase: 330,
    hpPerLevel: 60,
    dmgBase: 16,
    dmgPerLevel: 3.8,
    attackSpeed: 2.0,
    armorPerLevel: 30,
    moveSpeed: 7,
    aggroRadius: 13,
    count: 1,
    rare: true,
    drops: [
      { copper: [263, 438], chance: 1 },
      { itemId: "tallow_candle", chance: 1 },
      { itemId: "nhalias_funeral_wraps", chance: 0.25 },
      { itemId: "nhalias_dirgeblade", chance: 0.25 },
    ],
  },
  {
    id: "nhalia_mourner",
    name: "Nhalia Mourner",
    family: "humanoid",
    zone: "marsh",
    minLevel: 11,
    maxLevel: 12,
    hpBase: 46,
    hpPerLevel: 17,
    dmgBase: 8,
    dmgPerLevel: 2.3,
    attackSpeed: 2.0,
    armorPerLevel: 14,
    moveSpeed: 7,
    aggroRadius: 12,
    count: 10,
    drops: [],
  },
  {
    id: "deacon_voss",
    name: "Deacon Voss",
    family: "humanoid",
    zone: "marsh",
    minLevel: 12,
    maxLevel: 12,
    hpBase: 200,
    hpPerLevel: 30,
    dmgBase: 11,
    dmgPerLevel: 2.5,
    attackSpeed: 2.4,
    armorPerLevel: 26,
    moveSpeed: 7,
    aggroRadius: 14,
    count: 1,
    boss: true,
    drops: [
      { copper: [450, 750], chance: 1 },
      { itemId: "tallow_candle", chance: 1 },
      { itemId: "voss_sanctified_mace", chance: 0.25 },
    ],
  },
  {
    id: "bog_bloat",
    name: "Bog Bloat",
    family: "beast",
    zone: "marsh",
    minLevel: 9,
    maxLevel: 11,
    hpBase: 44,
    hpPerLevel: 17,
    dmgBase: 7,
    dmgPerLevel: 2.0,
    attackSpeed: 2.6,
    armorPerLevel: 9,
    moveSpeed: 6,
    aggroRadius: 10,
    count: 10,
    drops: [
      { copper: [30, 50], chance: 1 },
      { itemId: "tangled_weed", chance: 0.5 },
    ],
  },
  {
    id: "ridge_stalker",
    name: "Ridge Stalker",
    family: "beast",
    zone: "peaks",
    minLevel: 13,
    maxLevel: 14,
    hpBase: 58,
    hpPerLevel: 21,
    dmgBase: 10,
    dmgPerLevel: 2.5,
    attackSpeed: 1.9,
    armorPerLevel: 14,
    moveSpeed: 8,
    aggroRadius: 11,
    count: 10,
    drops: [
      { copper: [45, 75], chance: 1 },
      { itemId: "ridge_stalker_pelt", chance: 0.6 },
    ],
  },
  {
    id: "old_cragmaw",
    name: "Old Cragmaw",
    family: "beast",
    zone: "peaks",
    minLevel: 14,
    maxLevel: 14,
    hpBase: 320,
    hpPerLevel: 56,
    dmgBase: 16,
    dmgPerLevel: 4.0,
    attackSpeed: 1.7,
    armorPerLevel: 24,
    moveSpeed: 8.6,
    aggroRadius: 13,
    count: 1,
    rare: true,
    drops: [
      { copper: [165, 275], chance: 1 },
      { itemId: "old_cragmaws_pelt", chance: 1 },
      { itemId: "cragmaw_huntcord", chance: 0.25 },
      { itemId: "cragmaw_prowlboots", chance: 0.3 },
    ],
  },
  {
    id: "deeprock_kobold",
    name: "Deeprock Tunneler",
    family: "humanoid",
    zone: "peaks",
    minLevel: 14,
    maxLevel: 15,
    hpBase: 60,
    hpPerLevel: 22,
    dmgBase: 10,
    dmgPerLevel: 2.5,
    attackSpeed: 2.1,
    armorPerLevel: 18,
    moveSpeed: 7,
    aggroRadius: 10,
    count: 10,
    drops: [
      { copper: [49, 81], chance: 1 },
      { itemId: "glowing_wax", chance: 0.5 },
      { itemId: "tallow_candle", chance: 0.4 },
      { itemId: "healing_potion", chance: 0.08 },
      { itemId: "deathlord_sabatons", chance: 0.001 },
    ],
  },
  {
    id: "ironvein_foreman",
    name: "Ironvein Foreman",
    family: "humanoid",
    zone: "peaks",
    minLevel: 16,
    maxLevel: 16,
    hpBase: 420,
    hpPerLevel: 70,
    dmgBase: 19,
    dmgPerLevel: 4.4,
    attackSpeed: 2.0,
    armorPerLevel: 38,
    moveSpeed: 7,
    aggroRadius: 12,
    count: 1,
    rare: true,
    drops: [
      { copper: [315, 525], chance: 1 },
      { itemId: "glowing_wax", chance: 1 },
      { itemId: "ironvein_pickblade", chance: 0.25 },
      { itemId: "ironvein_lantern_staff", chance: 0.25 },
      { itemId: "gutripper_shiv", chance: 0.25 },
      { itemId: "deathlord_sabatons", chance: 0.25 },
    ],
  },
  {
    id: "ironvein_sapper",
    name: "Ironvein Sapper",
    family: "humanoid",
    zone: "peaks",
    minLevel: 15,
    maxLevel: 16,
    hpBase: 58,
    hpPerLevel: 20,
    dmgBase: 11,
    dmgPerLevel: 2.6,
    attackSpeed: 2.0,
    armorPerLevel: 18,
    moveSpeed: 7.5,
    aggroRadius: 12,
    count: 10,
    drops: [],
  },
  {
    id: "thornpeak_ogre",
    name: "Thornpeak Ogre",
    family: "humanoid",
    zone: "peaks",
    minLevel: 15,
    maxLevel: 16,
    hpBase: 66,
    hpPerLevel: 23,
    dmgBase: 11,
    dmgPerLevel: 2.6,
    attackSpeed: 2.6,
    armorPerLevel: 22,
    moveSpeed: 7,
    aggroRadius: 11,
    count: 10,
    drops: [
      { copper: [56, 94], chance: 1 },
      { itemId: "ogre_toe_ring", chance: 0.35 },
    ],
  },
  {
    id: "ogre_crusher",
    name: "Thornpeak Crusher",
    family: "humanoid",
    zone: "peaks",
    minLevel: 16,
    maxLevel: 17,
    hpBase: 64,
    hpPerLevel: 23,
    dmgBase: 11,
    dmgPerLevel: 2.6,
    attackSpeed: 2.6,
    armorPerLevel: 24,
    moveSpeed: 7,
    aggroRadius: 12,
    count: 5,
    drops: [
      { copper: [150, 250], chance: 1 },
      { itemId: "ogre_toe_ring", chance: 0.5 },
    ],
  },
  {
    id: "warlord_drogmar",
    name: "Warlord Drogmar",
    family: "humanoid",
    zone: "peaks",
    minLevel: 17,
    maxLevel: 17,
    hpBase: 200,
    hpPerLevel: 30,
    dmgBase: 12,
    dmgPerLevel: 2.7,
    attackSpeed: 2.6,
    armorPerLevel: 28,
    moveSpeed: 7,
    aggroRadius: 14,
    count: 1,
    boss: true,
    drops: [
      { copper: [1500, 2500], chance: 1 },
      { itemId: "drogmar_warboots", chance: 0.3 },
      { itemId: "drogmars_skullcleaver", chance: 0.25 },
    ],
  },
  {
    id: "brutok_skullsmasher",
    name: "Brutok Skullsmasher",
    family: "humanoid",
    zone: "peaks",
    minLevel: 17,
    maxLevel: 17,
    hpBase: 360,
    hpPerLevel: 60,
    dmgBase: 16,
    dmgPerLevel: 3.6,
    attackSpeed: 2.7,
    armorPerLevel: 30,
    moveSpeed: 7,
    aggroRadius: 13,
    count: 1,
    rare: true,
    drops: [
      { copper: [240, 400], chance: 1 },
      { itemId: "cracked_ogre_tusk", chance: 1 },
      { itemId: "skullsmasher_warbelt", chance: 0.3 },
      { itemId: "brutoks_maul", chance: 0.25 },
      { itemId: "crag_warden_cudgel", chance: 0.25 },
      { itemId: "skullsplitter_dirk", chance: 0.25 },
    ],
  },
  {
    id: "stormcrag_elemental",
    name: "Stormcrag Elemental",
    family: "elemental",
    zone: "peaks",
    minLevel: 17,
    maxLevel: 18,
    hpBase: 62,
    hpPerLevel: 22,
    dmgBase: 12,
    dmgPerLevel: 2.7,
    attackSpeed: 2.2,
    armorPerLevel: 20,
    moveSpeed: 6.5,
    aggroRadius: 11,
    count: 10,
    drops: [
      { copper: [60, 100], chance: 1 },
      { itemId: "storm_core", chance: 0.55 },
      { itemId: "blessed_embers", chance: 0.55 },
      { itemId: "inert_storm_shard", chance: 0.4 },
    ],
  },
  {
    id: "shardlord_kazzix",
    name: "Shardlord Kazzix",
    family: "elemental",
    zone: "peaks",
    minLevel: 18,
    maxLevel: 18,
    hpBase: 160,
    hpPerLevel: 28,
    dmgBase: 13,
    dmgPerLevel: 2.8,
    attackSpeed: 2.2,
    armorPerLevel: 24,
    moveSpeed: 7,
    aggroRadius: 12,
    count: 1,
    rare: true,
    drops: [
      { copper: [375, 625], chance: 1 },
      { itemId: "kazzix_heartshard", chance: 1 },
      { itemId: "inert_storm_shard", chance: 1 },
    ],
  },
  {
    id: "wyrmcult_zealot",
    name: "Wyrmcult Zealot",
    family: "humanoid",
    zone: "peaks",
    minLevel: 17,
    maxLevel: 19,
    hpBase: 62,
    hpPerLevel: 22,
    dmgBase: 12,
    dmgPerLevel: 2.7,
    attackSpeed: 2.0,
    armorPerLevel: 20,
    moveSpeed: 7,
    aggroRadius: 11,
    count: 10,
    drops: [
      { copper: [68, 113], chance: 1 },
      { itemId: "wyrmcult_orders", chance: 0.5 },
      { itemId: "frayed_prayer_beads", chance: 0.35 },
    ],
  },
  {
    id: "wyrmcult_necromancer",
    name: "Wyrmcult Necromancer",
    family: "humanoid",
    zone: "peaks",
    minLevel: 18,
    maxLevel: 19,
    hpBase: 58,
    hpPerLevel: 21,
    dmgBase: 13,
    dmgPerLevel: 2.8,
    attackSpeed: 2.0,
    armorPerLevel: 16,
    moveSpeed: 7,
    aggroRadius: 11,
    count: 10,
    drops: [
      { copper: [75, 125], chance: 1 },
      { itemId: "ritual_phylactery", chance: 0.55 },
      { itemId: "linen_scrap", chance: 0.3 },
    ],
  },
  {
    id: "boneclad_revenant",
    name: "Boneclad Revenant",
    family: "undead",
    zone: "peaks",
    minLevel: 18,
    maxLevel: 19,
    hpBase: 66,
    hpPerLevel: 23,
    dmgBase: 12,
    dmgPerLevel: 2.7,
    attackSpeed: 2.3,
    armorPerLevel: 18,
    moveSpeed: 6.5,
    aggroRadius: 11,
    count: 10,
    drops: [
      { copper: [75, 125], chance: 1 },
      { itemId: "bone_fragments", chance: 0.6 },
      { itemId: "runed_bone_shard", chance: 0.7 },
      { itemId: "necromancers_legwraps", chance: 0.001 },
    ],
  },
  {
    id: "fallen_captain_aldren",
    name: "Fallen Captain Aldren",
    family: "undead",
    zone: "peaks",
    minLevel: 20,
    maxLevel: 20,
    hpBase: 390,
    hpPerLevel: 72,
    dmgBase: 22,
    dmgPerLevel: 4.2,
    attackSpeed: 2.2,
    armorPerLevel: 42,
    moveSpeed: 7.2,
    aggroRadius: 18,
    count: 1,
    rare: true,
    drops: [
      { copper: [338, 563], chance: 1 },
      { itemId: "captains_crest", chance: 1 },
      { itemId: "bone_fragments", chance: 1 },
    ],
  },
  {
    id: "corrupted_priest_malric",
    name: "Corrupted Priest Malric",
    family: "undead",
    zone: "peaks",
    minLevel: 20,
    maxLevel: 20,
    hpBase: 360,
    hpPerLevel: 68,
    dmgBase: 23,
    dmgPerLevel: 4.3,
    attackSpeed: 2.3,
    armorPerLevel: 26,
    moveSpeed: 6.9,
    aggroRadius: 18,
    count: 1,
    rare: true,
    drops: [
      { copper: [338, 563], chance: 1 },
      { itemId: "priests_sigil", chance: 1 },
      { itemId: "frayed_prayer_beads", chance: 0.5 },
    ],
  },
  {
    id: "deathstalker_voss",
    name: "Deathstalker Voss",
    family: "undead",
    zone: "peaks",
    minLevel: 20,
    maxLevel: 20,
    hpBase: 410,
    hpPerLevel: 74,
    dmgBase: 24,
    dmgPerLevel: 4.5,
    attackSpeed: 2.1,
    armorPerLevel: 44,
    moveSpeed: 7.4,
    aggroRadius: 18,
    count: 1,
    rare: true,
    drops: [
      { copper: [338, 563], chance: 1 },
      { itemId: "royal_seal", chance: 1 },
      { itemId: "bone_fragments", chance: 1 },
    ],
  },
  {
    id: "bound_guardian",
    name: "The Bound Guardian",
    family: "undead",
    zone: "peaks",
    minLevel: 20,
    maxLevel: 20,
    hpBase: 310,
    hpPerLevel: 48,
    dmgBase: 16,
    dmgPerLevel: 3.4,
    attackSpeed: 2.4,
    armorPerLevel: 42,
    moveSpeed: 6.8,
    aggroRadius: 16,
    count: 1,
    boss: true,
    drops: [
      { copper: [900, 1500], chance: 1 },
      { itemId: "kings_signet", chance: 1 },
    ],
  },
  {
    id: "marrowlord_varkas",
    name: "Marrowlord Varkas",
    family: "undead",
    zone: "peaks",
    minLevel: 19,
    maxLevel: 19,
    hpBase: 480,
    hpPerLevel: 80,
    dmgBase: 22,
    dmgPerLevel: 5.0,
    attackSpeed: 2.4,
    armorPerLevel: 44,
    moveSpeed: 6.5,
    aggroRadius: 13,
    count: 1,
    rare: true,
    drops: [
      { copper: [488, 813], chance: 1 },
      { itemId: "bone_fragments", chance: 1 },
      { itemId: "marrowlord_boneboots", chance: 0.3 },
      { itemId: "necromancers_legwraps", chance: 0.25 },
    ],
  },
  {
    id: "varkas_boneguard",
    name: "Varkas Boneguard",
    family: "undead",
    zone: "peaks",
    minLevel: 18,
    maxLevel: 19,
    hpBase: 64,
    hpPerLevel: 22,
    dmgBase: 12,
    dmgPerLevel: 2.8,
    attackSpeed: 2.3,
    armorPerLevel: 20,
    moveSpeed: 6.5,
    aggroRadius: 12,
    count: 10,
    drops: [],
  },
  {
    id: "voskar_emberwing",
    name: "Voskar the Emberwing",
    family: "beast",
    zone: "peaks",
    minLevel: 19,
    maxLevel: 19,
    hpBase: 470,
    hpPerLevel: 78,
    dmgBase: 22,
    dmgPerLevel: 4.9,
    attackSpeed: 2.5,
    armorPerLevel: 42,
    moveSpeed: 7,
    aggroRadius: 13,
    count: 1,
    rare: true,
    drops: [
      { copper: [525, 875], chance: 1 },
      { itemId: "emberwing_cinderscale", chance: 1 },
      { itemId: "emberwing_legguards", chance: 0.25 },
      { itemId: "emberfang_warblade", chance: 0.25 },
    ],
  },
  {
    id: "thunzharr_waking_peak",
    name: "Thunzharr, the Waking Peak",
    family: "elemental",
    zone: "peaks",
    minLevel: 20,
    maxLevel: 20,
    hpBase: 4000,
    hpPerLevel: 800,
    dmgBase: 54,
    dmgPerLevel: 10.3,
    attackSpeed: 2.4,
    armorPerLevel: 46,
    moveSpeed: 11.6,
    aggroRadius: 18,
    count: 1,
    boss: true,
    drops: [
      { itemId: "inert_storm_shard", chance: 1 },
      { itemId: "crownforged_gauntlets", chance: 0.08 },
      { itemId: "nighttalon_grips", chance: 0.08 },
      { itemId: "soulflame_gloves", chance: 0.08 },
      { itemId: "stormcallers_handguards", chance: 0.08 },
      { itemId: "crownforged_girdle", chance: 0.08 },
      { itemId: "nighttalon_waistband", chance: 0.08 },
      { itemId: "soulflame_cord", chance: 0.08 },
      { itemId: "stormcallers_waistguard", chance: 0.08 },
    ],
  },
  {
    id: "thunzharr_stormling",
    name: "Roused Stormling",
    family: "elemental",
    zone: "peaks",
    minLevel: 19,
    maxLevel: 20,
    hpBase: 70,
    hpPerLevel: 24,
    dmgBase: 13,
    dmgPerLevel: 2.9,
    attackSpeed: 2.0,
    armorPerLevel: 22,
    moveSpeed: 7.4,
    aggroRadius: 12,
    count: 10,
    drops: [],
  },
  {
    id: "crypt_shambler",
    name: "Crypt Shambler",
    family: "undead",
    zone: "peaks",
    minLevel: 18,
    maxLevel: 19,
    hpBase: 50,
    hpPerLevel: 20,
    dmgBase: 7,
    dmgPerLevel: 2.2,
    attackSpeed: 2.4,
    armorPerLevel: 18,
    moveSpeed: 6.5,
    aggroRadius: 12,
    count: 5,
    drops: [
      { copper: [68, 113], chance: 1 },
      { itemId: "bone_fragments", chance: 0.8 },
    ],
  },
  {
    id: "hollow_acolyte",
    name: "Hollow Acolyte",
    family: "undead",
    zone: "peaks",
    minLevel: 19,
    maxLevel: 20,
    hpBase: 44,
    hpPerLevel: 18,
    dmgBase: 8,
    dmgPerLevel: 2.3,
    attackSpeed: 2.0,
    armorPerLevel: 14,
    moveSpeed: 7,
    aggroRadius: 12,
    count: 5,
    drops: [
      { copper: [83, 138], chance: 1 },
      { itemId: "linen_scrap", chance: 0.6 },
    ],
  },
  {
    id: "sexton_marrow",
    name: "Sexton Marrow",
    family: "undead",
    zone: "peaks",
    minLevel: 20,
    maxLevel: 20,
    hpBase: 110,
    hpPerLevel: 24,
    dmgBase: 9,
    dmgPerLevel: 2.5,
    attackSpeed: 2.2,
    armorPerLevel: 22,
    moveSpeed: 7,
    aggroRadius: 14,
    count: 4,
    drops: [
      { copper: [300, 500], chance: 1 },
      { itemId: "quilted_trousers", chance: 0.4 },
      { itemId: "oiled_boots", chance: 0.4 },
    ],
  },
  {
    id: "morthen",
    name: "Morthen the Gravecaller",
    family: "undead",
    zone: "peaks",
    minLevel: 20,
    maxLevel: 20,
    hpBase: 2200,
    hpPerLevel: 100,
    dmgBase: 11,
    dmgPerLevel: 2.6,
    attackSpeed: 2.6,
    armorPerLevel: 26,
    moveSpeed: 7,
    aggroRadius: 16,
    count: 1,
    boss: true,
    abilities: [
      { id: "shadow_pulse", name: "Shadow Pulse", intervalSec: 10, amount: 60, radius: 8, school: "shadow" },
    ],
    drops: [
      { copper: [2000, 3000], chance: 1 },
      { itemId: "cryptbone_greaves", chance: 0.34 },
      { itemId: "quilted_trousers", chance: 0.33 },
      { itemId: "oiled_boots", chance: 0.33 },
      { itemId: "greyjaw_hide_boots", chance: 0.25 },
      { itemId: "gravewoven_bag", chance: 0.2 },
      { itemId: "cryptbone_helm", chance: 0.18 },
      { itemId: "cryptbone_pauldrons", chance: 0.18 },
    ],
  },
];

export function mobById(id: string): MobDef | null {
  for (const m of MOBS) {
    if (m.id === id) return m;
  }
  return null;
}
