import type { MobDef } from "../../model";

export const MOBS: readonly MobDef[] = [
  {
    id: "forest_wolf",
    name: "Forest Wolf",
    family: "beast",
    zone: "vale",
    minLevel: 1,
    maxLevel: 2,
    hpBase: 40,
    hpPerLevel: 14,
    dmgBase: 3,
    dmgPerLevel: 1.6,
    attackSpeed: 2.0,
    armorPerLevel: 10,
    moveSpeed: 8,
    aggroRadius: 10,
    count: 12,
    drops: [
      { copper: [6, 10], chance: 1 },
      { itemId: "wolf_fang", chance: 0.45 },
      { itemId: "milepost_boots", chance: 0.1 },
      { itemId: "wolfhide_satchel", chance: 0.02 },
    ],
    packFrenzy: { radius: 12, hasteMult: 1.3, duration: 8 },
  },
  {
    id: "wild_boar",
    name: "Wild Boar",
    family: "beast",
    zone: "vale",
    minLevel: 2,
    maxLevel: 3,
    hpBase: 38,
    hpPerLevel: 16,
    dmgBase: 4,
    dmgPerLevel: 1.8,
    attackSpeed: 2.2,
    armorPerLevel: 14,
    moveSpeed: 7.5,
    aggroRadius: 9,
    count: 10,
    drops: [
      { copper: [9, 15], chance: 1 },
      { itemId: "boar_hide", chance: 0.6 },
      { itemId: "tough_jerky", chance: 0.3 },
      { itemId: "trail_leggings", chance: 0.1 },
    ],
  },
  {
    id: "webwood_spider",
    name: "Sableweb Lurker",
    family: "beast",
    zone: "vale",
    minLevel: 2,
    maxLevel: 4,
    hpBase: 36,
    hpPerLevel: 15,
    dmgBase: 4,
    dmgPerLevel: 1.7,
    attackSpeed: 1.8,
    armorPerLevel: 8,
    moveSpeed: 8,
    aggroRadius: 10,
    count: 8,
    drops: [
      { copper: [11, 18], chance: 1 },
      { itemId: "webwood_silk", chance: 0.55 },
      { itemId: "spider_leg", chance: 0.4 },
    ],
  },
  {
    id: "vale_bandit",
    name: "Vale Bandit",
    family: "humanoid",
    zone: "vale",
    minLevel: 3,
    maxLevel: 5,
    hpBase: 40,
    hpPerLevel: 18,
    dmgBase: 5,
    dmgPerLevel: 2.0,
    attackSpeed: 2.0,
    armorPerLevel: 20,
    moveSpeed: 7,
    aggroRadius: 11,
    count: 9,
    drops: [
      { copper: [19, 31], chance: 1 },
      { itemId: "bandit_bandana", chance: 0.5 },
      { itemId: "linen_scrap", chance: 0.3 },
    ],
  },
  {
    id: "tunnel_rat",
    name: "Deeprock Digger",
    family: "humanoid",
    zone: "vale",
    minLevel: 4,
    maxLevel: 6,
    hpBase: 42,
    hpPerLevel: 18,
    dmgBase: 6,
    dmgPerLevel: 2.0,
    attackSpeed: 2.1,
    armorPerLevel: 16,
    moveSpeed: 7,
    aggroRadius: 10,
    count: 8,
    drops: [
      { copper: [17, 28], chance: 1 },
      { itemId: "tallow_candle", chance: 0.6 },
      { itemId: "blessed_wax", chance: 0.45 },
      { itemId: "linen_scrap", chance: 0.25 },
      { itemId: "mossy_handwraps", chance: 0.15 },
    ],
  },
  {
    id: "restless_bones",
    name: "Restless Bones",
    family: "undead",
    zone: "vale",
    minLevel: 5,
    maxLevel: 7,
    hpBase: 46,
    hpPerLevel: 19,
    dmgBase: 7,
    dmgPerLevel: 2.1,
    attackSpeed: 2.3,
    armorPerLevel: 14,
    moveSpeed: 6.5,
    aggroRadius: 11,
    count: 8,
    drops: [
      { copper: [23, 38], chance: 1 },
      { itemId: "bone_fragments", chance: 0.6 },
      { itemId: "ghostly_essence", chance: 0.55 },
    ],
  },
  {
    id: "mudfin_murloc",
    name: "Mudfin Skulker",
    family: "beast",
    zone: "vale",
    minLevel: 3,
    maxLevel: 5,
    hpBase: 36,
    hpPerLevel: 17,
    dmgBase: 5,
    dmgPerLevel: 1.9,
    attackSpeed: 1.9,
    armorPerLevel: 12,
    moveSpeed: 8,
    aggroRadius: 13,
    count: 8,
    drops: [
      { copper: [14, 23], chance: 1 },
      { itemId: "mudfin_scale", chance: 0.5 },
      { itemId: "linen_scrap", chance: 0.2 },
    ],
  },
  {
    id: "old_greyjaw",
    name: "Old Greyjaw",
    family: "beast",
    zone: "vale",
    minLevel: 4,
    maxLevel: 4,
    hpBase: 110,
    hpPerLevel: 20,
    dmgBase: 5,
    dmgPerLevel: 2.0,
    attackSpeed: 1.8,
    armorPerLevel: 16,
    moveSpeed: 8.5,
    aggroRadius: 12,
    count: 1,
    rare: true,
    drops: [
      { copper: [45, 75], chance: 1 },
      { itemId: "greyjaw_fang", chance: 1 },
      { itemId: "wolf_fang", chance: 1 },
      { itemId: "wolfhide_satchel", chance: 0.35 },
    ],
  },
  {
    id: "mire_prowler",
    name: "Mire Prowler",
    family: "beast",
    zone: "marsh",
    minLevel: 7,
    maxLevel: 8,
    hpBase: 46,
    hpPerLevel: 19,
    dmgBase: 7,
    dmgPerLevel: 2.1,
    attackSpeed: 2.0,
    armorPerLevel: 12,
    moveSpeed: 8.5,
    aggroRadius: 11,
    count: 9,
    drops: [
      { copper: [23, 38], chance: 1 },
      { itemId: "mire_prowler_pelt", chance: 0.6 },
      { itemId: "soggy_moccasin", chance: 0.3 },
      { itemId: "lesser_healing_potion", chance: 0.08 },
    ],
  },
  {
    id: "deepfen_murloc",
    name: "Deepfen Snapper",
    family: "beast",
    zone: "marsh",
    minLevel: 8,
    maxLevel: 9,
    hpBase: 48,
    hpPerLevel: 19,
    dmgBase: 7,
    dmgPerLevel: 2.2,
    attackSpeed: 1.9,
    armorPerLevel: 12,
    moveSpeed: 8,
    aggroRadius: 14,
    count: 8,
    drops: [
      { copper: [26, 44], chance: 1 },
      { itemId: "waterlogged_idol", chance: 0.5 },
      { itemId: "mudfin_scale", chance: 0.4 },
    ],
  },
  {
    id: "mire_widow",
    name: "Mirefen Widow",
    family: "beast",
    zone: "marsh",
    minLevel: 8,
    maxLevel: 10,
    hpBase: 48,
    hpPerLevel: 19,
    dmgBase: 8,
    dmgPerLevel: 2.2,
    attackSpeed: 1.8,
    armorPerLevel: 10,
    moveSpeed: 8,
    aggroRadius: 10,
    count: 8,
    drops: [
      { copper: [29, 48], chance: 1 },
      { itemId: "widow_venom_sac", chance: 0.65 },
      { itemId: "spider_leg", chance: 0.4 },
    ],
  },
  {
    id: "fen_troll",
    name: "Mirefen Troll",
    family: "humanoid",
    zone: "marsh",
    minLevel: 10,
    maxLevel: 12,
    hpBase: 56,
    hpPerLevel: 21,
    dmgBase: 9,
    dmgPerLevel: 2.4,
    attackSpeed: 2.2,
    armorPerLevel: 18,
    moveSpeed: 7.5,
    aggroRadius: 11,
    count: 8,
    drops: [
      { copper: [38, 63], chance: 1 },
      { itemId: "troll_fetish", chance: 0.6 },
      { itemId: "chipped_tusk", chance: 0.4 },
      { itemId: "bogiron_nugget", chance: 0.3 },
      { itemId: "elixir_of_the_bear", chance: 0.07 },
    ],
  },
  {
    id: "drowned_dead",
    name: "Drowned Dead",
    family: "undead",
    zone: "marsh",
    minLevel: 9,
    maxLevel: 11,
    hpBase: 52,
    hpPerLevel: 20,
    dmgBase: 8,
    dmgPerLevel: 2.3,
    attackSpeed: 2.3,
    armorPerLevel: 14,
    moveSpeed: 6.5,
    aggroRadius: 11,
    count: 8,
    drops: [
      { copper: [32, 53], chance: 1 },
      { itemId: "bone_fragments", chance: 0.5 },
      { itemId: "cracked_fetish", chance: 0.3 },
    ],
  },
  {
    id: "gravecaller_cultist",
    name: "Gravecaller Cultist",
    family: "humanoid",
    zone: "marsh",
    minLevel: 10,
    maxLevel: 12,
    hpBase: 50,
    hpPerLevel: 20,
    dmgBase: 9,
    dmgPerLevel: 2.4,
    attackSpeed: 2.0,
    armorPerLevel: 20,
    moveSpeed: 7,
    aggroRadius: 11,
    count: 7,
    drops: [
      { copper: [41, 69], chance: 1 },
      { itemId: "linen_scrap", chance: 0.3 },
      { itemId: "tallow_candle", chance: 0.3 },
      { itemId: "gravecaller_sigil", chance: 0.35 },
    ],
  },
  {
    id: "bog_bloat",
    name: "Bog Bloat",
    family: "beast",
    zone: "marsh",
    minLevel: 9,
    maxLevel: 11,
    hpBase: 44,
    hpPerLevel: 17,
    dmgBase: 7,
    dmgPerLevel: 2.0,
    attackSpeed: 2.6,
    armorPerLevel: 9,
    moveSpeed: 6,
    aggroRadius: 10,
    count: 6,
    drops: [
      { copper: [30, 50], chance: 1 },
      { itemId: "tangled_weed", chance: 0.5 },
    ],
  },
  {
    id: "ridge_stalker",
    name: "Ridge Stalker",
    family: "beast",
    zone: "peaks",
    minLevel: 13,
    maxLevel: 14,
    hpBase: 58,
    hpPerLevel: 21,
    dmgBase: 10,
    dmgPerLevel: 2.5,
    attackSpeed: 1.9,
    armorPerLevel: 14,
    moveSpeed: 8,
    aggroRadius: 11,
    count: 7,
    drops: [
      { copper: [45, 75], chance: 1 },
      { itemId: "ridge_stalker_pelt", chance: 0.6 },
    ],
  },
  {
    id: "deeprock_kobold",
    name: "Deeprock Tunneler",
    family: "humanoid",
    zone: "peaks",
    minLevel: 14,
    maxLevel: 15,
    hpBase: 60,
    hpPerLevel: 22,
    dmgBase: 10,
    dmgPerLevel: 2.5,
    attackSpeed: 2.1,
    armorPerLevel: 18,
    moveSpeed: 7,
    aggroRadius: 10,
    count: 6,
    drops: [
      { copper: [49, 81], chance: 1 },
      { itemId: "glowing_wax", chance: 0.5 },
      { itemId: "tallow_candle", chance: 0.4 },
      { itemId: "healing_potion", chance: 0.08 },
      { itemId: "deathlord_sabatons", chance: 0.001 },
    ],
  },
  {
    id: "thornpeak_ogre",
    name: "Thornpeak Ogre",
    family: "humanoid",
    zone: "peaks",
    minLevel: 15,
    maxLevel: 16,
    hpBase: 66,
    hpPerLevel: 23,
    dmgBase: 11,
    dmgPerLevel: 2.6,
    attackSpeed: 2.6,
    armorPerLevel: 22,
    moveSpeed: 7,
    aggroRadius: 11,
    count: 6,
    drops: [
      { copper: [56, 94], chance: 1 },
      { itemId: "ogre_toe_ring", chance: 0.35 },
    ],
  },
  {
    id: "ironvein_sapper",
    name: "Ironvein Sapper",
    family: "humanoid",
    zone: "peaks",
    minLevel: 15,
    maxLevel: 16,
    hpBase: 58,
    hpPerLevel: 20,
    dmgBase: 11,
    dmgPerLevel: 2.6,
    attackSpeed: 2.0,
    armorPerLevel: 18,
    moveSpeed: 7.5,
    aggroRadius: 12,
    count: 5,
    drops: [],
  },
  {
    id: "stormcrag_elemental",
    name: "Stormcrag Elemental",
    family: "elemental",
    zone: "peaks",
    minLevel: 17,
    maxLevel: 18,
    hpBase: 62,
    hpPerLevel: 22,
    dmgBase: 12,
    dmgPerLevel: 2.7,
    attackSpeed: 2.2,
    armorPerLevel: 20,
    moveSpeed: 6.5,
    aggroRadius: 11,
    count: 6,
    drops: [
      { copper: [60, 100], chance: 1 },
      { itemId: "storm_core", chance: 0.55 },
      { itemId: "blessed_embers", chance: 0.55 },
      { itemId: "inert_storm_shard", chance: 0.4 },
    ],
  },
  {
    id: "wyrmcult_zealot",
    name: "Wyrmcult Zealot",
    family: "humanoid",
    zone: "peaks",
    minLevel: 17,
    maxLevel: 19,
    hpBase: 62,
    hpPerLevel: 22,
    dmgBase: 12,
    dmgPerLevel: 2.7,
    attackSpeed: 2.0,
    armorPerLevel: 20,
    moveSpeed: 7,
    aggroRadius: 11,
    count: 6,
    drops: [
      { copper: [68, 113], chance: 1 },
      { itemId: "wyrmcult_orders", chance: 0.5 },
      { itemId: "frayed_prayer_beads", chance: 0.35 },
    ],
  },
  {
    id: "wyrmcult_necromancer",
    name: "Wyrmcult Necromancer",
    family: "humanoid",
    zone: "peaks",
    minLevel: 18,
    maxLevel: 19,
    hpBase: 58,
    hpPerLevel: 21,
    dmgBase: 13,
    dmgPerLevel: 2.8,
    attackSpeed: 2.0,
    armorPerLevel: 16,
    moveSpeed: 7,
    aggroRadius: 11,
    count: 5,
    drops: [
      { copper: [75, 125], chance: 1 },
      { itemId: "ritual_phylactery", chance: 0.55 },
      { itemId: "linen_scrap", chance: 0.3 },
    ],
  },
  {
    id: "crypt_shambler",
    name: "Crypt Shambler",
    family: "undead",
    zone: "peaks",
    minLevel: 18,
    maxLevel: 19,
    hpBase: 50,
    hpPerLevel: 20,
    dmgBase: 7,
    dmgPerLevel: 2.2,
    attackSpeed: 2.4,
    armorPerLevel: 18,
    moveSpeed: 6.5,
    aggroRadius: 12,
    count: 5,
    drops: [
      { copper: [68, 113], chance: 1 },
      { itemId: "bone_fragments", chance: 0.8 },
    ],
  },
  {
    id: "hollow_acolyte",
    name: "Hollow Acolyte",
    family: "undead",
    zone: "peaks",
    minLevel: 19,
    maxLevel: 20,
    hpBase: 44,
    hpPerLevel: 18,
    dmgBase: 8,
    dmgPerLevel: 2.3,
    attackSpeed: 2.0,
    armorPerLevel: 14,
    moveSpeed: 7,
    aggroRadius: 12,
    count: 5,
    drops: [
      { copper: [83, 138], chance: 1 },
      { itemId: "linen_scrap", chance: 0.6 },
    ],
  },
  {
    id: "sexton_marrow",
    name: "Sexton Marrow",
    family: "undead",
    zone: "peaks",
    minLevel: 20,
    maxLevel: 20,
    hpBase: 110,
    hpPerLevel: 24,
    dmgBase: 9,
    dmgPerLevel: 2.5,
    attackSpeed: 2.2,
    armorPerLevel: 22,
    moveSpeed: 7,
    aggroRadius: 14,
    count: 4,
    drops: [
      { copper: [300, 500], chance: 1 },
      { itemId: "quilted_trousers", chance: 0.4 },
      { itemId: "oiled_boots", chance: 0.4 },
    ],
  },
  {
    id: "morthen",
    name: "Morthen the Gravecaller",
    family: "undead",
    zone: "peaks",
    minLevel: 20,
    maxLevel: 20,
    hpBase: 2200,
    hpPerLevel: 100,
    dmgBase: 11,
    dmgPerLevel: 2.6,
    attackSpeed: 2.6,
    armorPerLevel: 26,
    moveSpeed: 7,
    aggroRadius: 16,
    count: 1,
    boss: true,
    abilities: [
      { id: "shadow_pulse", name: "Shadow Pulse", intervalSec: 10, amount: 60, radius: 8, school: "shadow" },
    ],
    drops: [
      { copper: [2000, 3000], chance: 1 },
      { itemId: "cryptbone_greaves", chance: 0.34 },
      { itemId: "quilted_trousers", chance: 0.33 },
      { itemId: "oiled_boots", chance: 0.33 },
      { itemId: "greyjaw_hide_boots", chance: 0.25 },
      { itemId: "gravewoven_bag", chance: 0.2 },
      { itemId: "cryptbone_helm", chance: 0.18 },
      { itemId: "cryptbone_pauldrons", chance: 0.18 },
    ],
  },
];

export function mobById(id: string): MobDef | null {
  for (const m of MOBS) {
    if (m.id === id) return m;
  }
  return null;
}
