import type { MobDef } from "../../../model";

export const DUNGEON_MOBS: readonly MobDef[] = [
  {
    id: "crypt_shambler",
    name: "Crypt Shambler",
    family: "undead",
    zone: "peaks",
    minLevel: 18,
    maxLevel: 19,
    hpBase: 50,
    hpPerLevel: 20,
    dmgBase: 7,
    dmgPerLevel: 2.2,
    attackSpeed: 2.4,
    armorPerLevel: 18,
    moveSpeed: 6.5,
    aggroRadius: 12,
    count: 5,
    dungeonId: "hollow_crypt",
    drops: [
      { copper: [68, 113], chance: 1 },
      { itemId: "bone_fragments", chance: 0.8 },
    ],
  },
  {
    id: "hollow_acolyte",
    name: "Hollow Acolyte",
    family: "undead",
    zone: "peaks",
    minLevel: 19,
    maxLevel: 20,
    hpBase: 44,
    hpPerLevel: 18,
    dmgBase: 8,
    dmgPerLevel: 2.3,
    attackSpeed: 2.0,
    armorPerLevel: 14,
    moveSpeed: 7,
    aggroRadius: 12,
    count: 5,
    dungeonId: "hollow_crypt",
    drops: [
      { copper: [83, 138], chance: 1 },
      { itemId: "linen_scrap", chance: 0.6 },
    ],
  },
  {
    id: "sexton_marrow",
    name: "Sexton Marrow",
    family: "undead",
    zone: "peaks",
    minLevel: 20,
    maxLevel: 20,
    hpBase: 110,
    hpPerLevel: 24,
    dmgBase: 9,
    dmgPerLevel: 2.5,
    attackSpeed: 2.2,
    armorPerLevel: 22,
    moveSpeed: 7,
    aggroRadius: 14,
    count: 4,
    dungeonId: "hollow_crypt",
    drops: [
      { copper: [300, 500], chance: 1 },
      { itemId: "quilted_trousers", chance: 0.4 },
      { itemId: "oiled_boots", chance: 0.4 },
    ],
  },
  {
    id: "morthen",
    name: "Morthen the Gravecaller",
    family: "undead",
    zone: "peaks",
    minLevel: 20,
    maxLevel: 20,
    hpBase: 2200,
    hpPerLevel: 100,
    dmgBase: 11,
    dmgPerLevel: 2.6,
    attackSpeed: 2.6,
    armorPerLevel: 26,
    moveSpeed: 7,
    aggroRadius: 16,
    count: 1,
    boss: true,
    dungeonId: "hollow_crypt",
    abilities: [
      { id: "shadow_pulse", name: "Shadow Pulse", intervalSec: 10, amount: 60, radius: 8, school: "shadow" },
    ],
    drops: [
      { copper: [2000, 3000], chance: 1 },
      { itemId: "cryptbone_greaves", chance: 0.34 },
      { itemId: "quilted_trousers", chance: 0.33 },
      { itemId: "oiled_boots", chance: 0.33 },
      { itemId: "greyjaw_hide_boots", chance: 0.25 },
      { itemId: "gravewoven_bag", chance: 0.2 },
      { itemId: "cryptbone_helm", chance: 0.18 },
      { itemId: "cryptbone_pauldrons", chance: 0.18 },
    ],
  },
  {
    id: "bastion_revenant",
    name: "Bastion Revenant",
    family: "undead",
    zone: "marsh",
    minLevel: 12,
    maxLevel: 13,
    hpBase: 54,
    hpPerLevel: 21,
    dmgBase: 9,
    dmgPerLevel: 2.4,
    attackSpeed: 2.3,
    armorPerLevel: 18,
    moveSpeed: 6.5,
    aggroRadius: 12,
    count: 10,
    dungeonId: "sunken_bastion",
    drops: [
      { copper: [45, 75], chance: 1 },
      { itemId: "bone_fragments", chance: 0.7 },
      { itemId: "mistveil_cord", chance: 0.06 },
    ],
  },
  {
    id: "knight_commander_olen",
    name: "Knight-Commander Olen",
    family: "undead",
    zone: "marsh",
    minLevel: 13,
    maxLevel: 13,
    hpBase: 120,
    hpPerLevel: 26,
    dmgBase: 11,
    dmgPerLevel: 2.6,
    attackSpeed: 2.2,
    armorPerLevel: 24,
    moveSpeed: 7,
    aggroRadius: 14,
    count: 1,
    boss: true,
    dungeonId: "sunken_bastion",
    drops: [
      { copper: [600, 1000], chance: 1 },
      { itemId: "trollhide_leggings", chance: 0.5 },
      { itemId: "marshstrider_boots", chance: 0.5 },
      { itemId: "fenmist_robe", chance: 0.25 },
      { itemId: "tideguard_greaves", chance: 0.1 },
      { itemId: "tideguard_sabatons", chance: 0.1 },
      { itemId: "eelscale_leggings", chance: 0.1 },
    ],
  },
  {
    id: "vael_the_mistcaller",
    name: "Vael the Fogbinder",
    family: "humanoid",
    zone: "marsh",
    minLevel: 13,
    maxLevel: 13,
    hpBase: 240,
    hpPerLevel: 34,
    dmgBase: 12,
    dmgPerLevel: 2.6,
    attackSpeed: 2.4,
    armorPerLevel: 26,
    moveSpeed: 7,
    aggroRadius: 16,
    count: 1,
    boss: true,
    dungeonId: "sunken_bastion",
    abilities: [{ id: "mist_surge", name: "Mist Surge", intervalSec: 10, amount: 20, radius: 12, school: "shadow" }],
    drops: [
      { copper: [1500, 2500], chance: 1 },
      { itemId: "trollhide_leggings", chance: 0.34 },
      { itemId: "marshstrider_boots", chance: 0.33 },
      { itemId: "fenmist_robe", chance: 0.33 },
      { itemId: "deepfen_pearl", chance: 1 },
      { itemId: "eelskin_tunic", chance: 0.2 },
      { itemId: "tidescale_vest", chance: 0.1 },
      { itemId: "drowned_prayer_leggings", chance: 0.1 },
      { itemId: "drowned_prayer_sandals", chance: 0.1 },
      { itemId: "eelscale_treads", chance: 0.1 },
      { itemId: "mistveil_cord", chance: 0.12 },
      { itemId: "mistveil_grips", chance: 0.12 },
    ],
  },
  {
    id: "korgath_the_bound",
    name: "Korgath the Bound",
    family: "humanoid",
    zone: "peaks",
    minLevel: 20,
    maxLevel: 20,
    hpBase: 260,
    hpPerLevel: 36,
    dmgBase: 14,
    dmgPerLevel: 2.9,
    attackSpeed: 2.8,
    armorPerLevel: 30,
    moveSpeed: 7,
    aggroRadius: 15,
    count: 1,
    boss: true,
    dungeonId: "gravewyrm_sanctum",
    mechanics: { enrage: { belowHpFraction: 0.3, hasteMult: 1.5, damageMult: 1.3 } },
    drops: [
      { copper: [900, 1500], chance: 1 },
      { itemId: "boneplate_vest", chance: 0.34 },
      { itemId: "revenant_silk_robe", chance: 0.33 },
      { itemId: "nightwalk_jerkin", chance: 0.33 },
      { itemId: "zealotsbane_blade", chance: 0.19 },
      { itemId: "korgaths_chainwraps", chance: 0.1 },
      { itemId: "staff_of_velkhar", chance: 0.1 },
      { itemId: "shadowmeld_tunic", chance: 0.1 },
      { itemId: "wyrmcult_grand_robe", chance: 0.1 },
      { itemId: "gravewyrm_sabatons", chance: 0.1 },
      { itemId: "wyrmcult_soulsteps", chance: 0.1 },
      { itemId: "wyrmshadow_treads", chance: 0.05 },
      { itemId: "boundstone_helm", chance: 0.08 },
      { itemId: "gravewyrm_mantle", chance: 0.08 },
    ],
  },
  {
    id: "grand_necromancer_velkhar",
    name: "Grand Necromancer Velkhar",
    family: "humanoid",
    zone: "peaks",
    minLevel: 20,
    maxLevel: 20,
    hpBase: 230,
    hpPerLevel: 33,
    dmgBase: 13,
    dmgPerLevel: 2.8,
    attackSpeed: 2.0,
    armorPerLevel: 20,
    moveSpeed: 7,
    aggroRadius: 15,
    count: 1,
    boss: true,
    dungeonId: "gravewyrm_sanctum",
    mechanics: { summons: { mobId: "raised_bonewalker", count: 2, intervalSec: 20, maxAlive: 4 } },
    drops: [
      { copper: [1200, 2000], chance: 1 },
      { itemId: "boneplate_vest", chance: 0.34 },
      { itemId: "revenant_silk_robe", chance: 0.33 },
      { itemId: "nightwalk_jerkin", chance: 0.33 },
      { itemId: "emberwood_staff", chance: 0.2 },
      { itemId: "boneguard_breastplate", chance: 0.1 },
      { itemId: "shadowmeld_tunic", chance: 0.1 },
      { itemId: "staff_of_velkhar", chance: 0.1 },
      { itemId: "gravewyrm_stalkers_treads", chance: 0.1 },
      { itemId: "deathlord_legguards", chance: 0.05 },
      { itemId: "necromancers_soulsteps", chance: 0.05 },
      { itemId: "wyrmshadow_legguards", chance: 0.05 },
    ],
  },
  {
    id: "korzul_the_gravewyrm",
    name: "Korzul the Gravewyrm",
    family: "beast",
    zone: "peaks",
    minLevel: 20,
    maxLevel: 20,
    hpBase: 420,
    hpPerLevel: 48,
    dmgBase: 15,
    dmgPerLevel: 3.0,
    attackSpeed: 2.6,
    armorPerLevel: 34,
    moveSpeed: 7,
    aggroRadius: 18,
    count: 1,
    boss: true,
    dungeonId: "gravewyrm_sanctum",
    abilities: [
      { id: "necrotic_shockwave", name: "Necrotic Shockwave", intervalSec: 8, amount: 36, radius: 14, school: "shadow" },
    ],
    drops: [
      { copper: [6000, 10000], chance: 1 },
      { itemId: "boneplate_vest", chance: 0.34 },
      { itemId: "revenant_silk_robe", chance: 0.33 },
      { itemId: "nightwalk_jerkin", chance: 0.33 },
      { itemId: "cultist_flayer", chance: 0.1 },
      { itemId: "wyrmfang_greatblade", chance: 0.05 },
      { itemId: "staff_of_the_gravewyrm", chance: 0.05 },
      { itemId: "fang_of_korzul", chance: 0.05 },
      { itemId: "deathlord_warplate", chance: 0.05 },
      { itemId: "necromancers_starshroud", chance: 0.05 },
      { itemId: "wyrmshadow_harness", chance: 0.05 },
      { itemId: "boundstone_girdle", chance: 0.05 },
      { itemId: "gravewyrm_gauntlets", chance: 0.05 },
      { itemId: "deathlords_dread_visage", chance: 0.04 },
      { itemId: "necromancers_soulspire_mantle", chance: 0.04 },
      { itemId: "wyrmshadow_talongrips", chance: 0.04 },
    ],
  },
  {
    id: "nythraxis_scourge_of_thornpeak",
    name: "Nythraxis, Scourge of Thornpeak",
    family: "undead",
    zone: "peaks",
    minLevel: 20,
    maxLevel: 20,
    hpBase: 26087,
    hpPerLevel: 0,
    dmgBase: 54,
    dmgPerLevel: 11.4,
    attackSpeed: 2.6,
    armorPerLevel: 42,
    moveSpeed: 10.5,
    aggroRadius: 22,
    count: 1,
    boss: true,
    dungeonId: "nythraxis_raid",
    mechanics: {
      enrage: { belowHpFraction: 0.3, hasteMult: 1.6, damageMult: 1.5 },
      summons: { mobId: "nythraxis_skeleton_warrior", count: 3, intervalSec: 25, maxAlive: 6 },
    },
    drops: [
      { itemId: "crownforged_dreadhelm", chance: 0.17 },
      { itemId: "nighttalon_crown", chance: 0.16 },
      { itemId: "soulflame_cowl", chance: 0.16 },
      { itemId: "stormcallers_crown", chance: 0.16 },
      { itemId: "nighttalon_shoulderguards", chance: 0.16 },
      { itemId: "soulflame_mantle", chance: 0.16 },
      { itemId: "crownforged_warspaulders", chance: 0.17 },
      { itemId: "stormcallers_spaulders", chance: 0.16 },
      { itemId: "deathless_heartwood", chance: 0.03 },
      { itemId: "kingsbane_last_oath", chance: 0.03 },
    ],
  },
  {
    id: "tidebound_acolyte",
    name: "Tidebound Acolyte",
    family: "humanoid",
    zone: "marsh",
    minLevel: 12,
    maxLevel: 13,
    hpBase: 50,
    hpPerLevel: 20,
    dmgBase: 10,
    dmgPerLevel: 2.5,
    attackSpeed: 2.0,
    armorPerLevel: 14,
    moveSpeed: 7,
    aggroRadius: 12,
    count: 8,
    dungeonId: "sunken_bastion",
    drops: [
      { copper: [48, 80], chance: 1 },
      { itemId: "linen_scrap", chance: 0.5 },
      { itemId: "mistveil_grips", chance: 0.06 },
    ],
  },
  {
    id: "drowned_thrall",
    name: "Drowned Thrall",
    family: "undead",
    zone: "marsh",
    minLevel: 11,
    maxLevel: 11,
    hpBase: 40,
    hpPerLevel: 14,
    dmgBase: 7,
    dmgPerLevel: 2.0,
    attackSpeed: 2.0,
    armorPerLevel: 10,
    moveSpeed: 7.5,
    aggroRadius: 12,
    count: 6,
    dungeonId: "sunken_bastion",
    drops: [],
  },
  {
    id: "sanctum_boneguard",
    name: "Sanctum Boneguard",
    family: "undead",
    zone: "peaks",
    minLevel: 19,
    maxLevel: 19,
    hpBase: 64,
    hpPerLevel: 23,
    dmgBase: 12,
    dmgPerLevel: 2.7,
    attackSpeed: 2.3,
    armorPerLevel: 22,
    moveSpeed: 6.5,
    aggroRadius: 12,
    count: 7,
    dungeonId: "gravewyrm_sanctum",
    drops: [
      { copper: [85, 140], chance: 1 },
      { itemId: "bone_fragments", chance: 0.6 },
      { itemId: "boundstone_helm", chance: 0.04 },
      { itemId: "boundstone_girdle", chance: 0.04 },
    ],
  },
  {
    id: "sanctum_drakonid",
    name: "Sanctum Scaleguard",
    family: "beast",
    zone: "peaks",
    minLevel: 19,
    maxLevel: 20,
    hpBase: 68,
    hpPerLevel: 24,
    dmgBase: 13,
    dmgPerLevel: 2.8,
    attackSpeed: 2.2,
    armorPerLevel: 26,
    moveSpeed: 7,
    aggroRadius: 13,
    count: 7,
    dungeonId: "gravewyrm_sanctum",
    drops: [
      { copper: [90, 150], chance: 1 },
      { itemId: "cracked_wyrm_scale", chance: 0.5 },
      { itemId: "gravewyrm_mantle", chance: 0.05 },
      { itemId: "gravewyrm_gauntlets", chance: 0.05 },
    ],
  },
  {
    id: "raised_bonewalker",
    name: "Raised Bonewalker",
    family: "undead",
    zone: "peaks",
    minLevel: 18,
    maxLevel: 18,
    hpBase: 42,
    hpPerLevel: 15,
    dmgBase: 9,
    dmgPerLevel: 2.2,
    attackSpeed: 2.2,
    armorPerLevel: 12,
    moveSpeed: 7,
    aggroRadius: 12,
    count: 6,
    dungeonId: "gravewyrm_sanctum",
    drops: [],
  },
  {
    id: "abandoned_bonewalker",
    name: "Abandoned Bonewalker",
    family: "undead",
    zone: "vale",
    minLevel: 19,
    maxLevel: 20,
    hpBase: 46,
    hpPerLevel: 16,
    dmgBase: 10,
    dmgPerLevel: 2.3,
    attackSpeed: 2.2,
    armorPerLevel: 13,
    moveSpeed: 7,
    aggroRadius: 12,
    count: 5,
    dungeonId: "nythraxis_crypt",
    drops: [
      { copper: [40, 70], chance: 1 },
      { itemId: "bone_fragments", chance: 0.4 },
      { itemId: "ritual_phylactery", chance: 0.08 },
    ],
  },
  {
    id: "crypt_marrow_priest",
    name: "Crypt Marrow Priest",
    family: "undead",
    zone: "vale",
    minLevel: 20,
    maxLevel: 20,
    hpBase: 60,
    hpPerLevel: 20,
    dmgBase: 12,
    dmgPerLevel: 2.6,
    attackSpeed: 2.4,
    armorPerLevel: 14,
    moveSpeed: 6.5,
    aggroRadius: 13,
    count: 4,
    dungeonId: "nythraxis_crypt",
    drops: [
      { copper: [55, 90], chance: 1 },
      { itemId: "frayed_prayer_beads", chance: 0.3 },
      { itemId: "cryptbone_greaves", chance: 0.05 },
    ],
  },
  {
    id: "drowned_templeguard",
    name: "Drowned Templeguard",
    family: "undead",
    zone: "marsh",
    minLevel: 16,
    maxLevel: 17,
    hpBase: 58,
    hpPerLevel: 22,
    dmgBase: 11,
    dmgPerLevel: 2.6,
    attackSpeed: 2.3,
    armorPerLevel: 20,
    moveSpeed: 6.5,
    aggroRadius: 12,
    count: 7,
    dungeonId: "drowned_temple",
    drops: [
      { copper: [70, 115], chance: 1 },
      { itemId: "bone_fragments", chance: 0.6 },
      { itemId: "pale_pearl", chance: 0.4 },
    ],
  },
  {
    id: "pale_choir_acolyte",
    name: "Pale Choir Acolyte",
    family: "humanoid",
    zone: "marsh",
    minLevel: 16,
    maxLevel: 17,
    hpBase: 54,
    hpPerLevel: 21,
    dmgBase: 11,
    dmgPerLevel: 2.6,
    attackSpeed: 2.0,
    armorPerLevel: 16,
    moveSpeed: 7,
    aggroRadius: 12,
    count: 7,
    dungeonId: "drowned_temple",
    drops: [
      { copper: [75, 125], chance: 1 },
      { itemId: "linen_scrap", chance: 0.4 },
      { itemId: "briny_idol", chance: 0.3 },
    ],
  },
  {
    id: "glimmerscale_lurker",
    name: "Glimmerscale Lurker",
    family: "beast",
    zone: "marsh",
    minLevel: 16,
    maxLevel: 17,
    hpBase: 56,
    hpPerLevel: 21,
    dmgBase: 11,
    dmgPerLevel: 2.7,
    attackSpeed: 1.8,
    armorPerLevel: 16,
    moveSpeed: 8,
    aggroRadius: 13,
    count: 6,
    dungeonId: "drowned_temple",
    drops: [
      { copper: [70, 115], chance: 1 },
      { itemId: "spider_leg", chance: 0.5 },
      { itemId: "moonpale_scale", chance: 0.4 },
    ],
  },
  {
    id: "pearlguard_sentinel",
    name: "Pearlguard Sentinel",
    family: "elemental",
    zone: "marsh",
    minLevel: 17,
    maxLevel: 18,
    hpBase: 64,
    hpPerLevel: 23,
    dmgBase: 12,
    dmgPerLevel: 2.7,
    attackSpeed: 2.2,
    armorPerLevel: 22,
    moveSpeed: 6.5,
    aggroRadius: 12,
    count: 6,
    dungeonId: "drowned_temple",
    drops: [
      { copper: [85, 140], chance: 1 },
      { itemId: "pale_pearl", chance: 0.6 },
      { itemId: "moonpale_scale", chance: 0.4 },
    ],
  },
  {
    id: "choirmother_selthe",
    name: "Choirmother Selthe",
    family: "humanoid",
    zone: "marsh",
    minLevel: 18,
    maxLevel: 18,
    hpBase: 150,
    hpPerLevel: 26,
    dmgBase: 12,
    dmgPerLevel: 2.7,
    attackSpeed: 2.2,
    armorPerLevel: 22,
    moveSpeed: 7,
    aggroRadius: 14,
    count: 1,
    boss: true,
    dungeonId: "drowned_temple",
    drops: [
      { copper: [700, 1150], chance: 1 },
      { itemId: "selthes_seastriders", chance: 0.4 },
      { itemId: "briny_idol", chance: 0.5 },
    ],
  },
  {
    id: "ysolei",
    name: "Ysolei, Avatar of the Drowned Moon",
    family: "beast",
    zone: "marsh",
    minLevel: 18,
    maxLevel: 18,
    hpBase: 300,
    hpPerLevel: 38,
    dmgBase: 14,
    dmgPerLevel: 2.9,
    attackSpeed: 2.5,
    armorPerLevel: 28,
    moveSpeed: 7,
    aggroRadius: 18,
    count: 1,
    boss: true,
    dungeonId: "drowned_temple",
    abilities: [{ id: "lunar_tide", name: "Lunar Tide", intervalSec: 9, amount: 27, radius: 13, school: "frost" }],
    drops: [
      { copper: [1800, 3000], chance: 1 },
      { itemId: "ysols_pearl_greaves", chance: 0.5 },
      { itemId: "moonshroud_breastplate", chance: 0.34 },
      { itemId: "moonshroud_robe", chance: 0.33 },
      { itemId: "moonshroud_tunic", chance: 0.33 },
    ],
  },
  {
    id: "nythraxis_skeleton_warrior",
    name: "Risen Royal Guard",
    family: "undead",
    zone: "peaks",
    minLevel: 20,
    maxLevel: 20,
    hpBase: 150,
    hpPerLevel: 28,
    dmgBase: 26,
    dmgPerLevel: 5.6,
    attackSpeed: 2.2,
    armorPerLevel: 24,
    moveSpeed: 10,
    aggroRadius: 14,
    count: 8,
    dungeonId: "nythraxis_raid",
    drops: [],
  },
];
