import type { MobDef } from "../../../model";

export const MARSH_MOBS: readonly MobDef[] = [
  {
    id: "mire_prowler",
    name: "Mire Prowler",
    family: "beast",
    zone: "marsh",
    minLevel: 7,
    maxLevel: 8,
    hpBase: 46,
    hpPerLevel: 19,
    dmgBase: 7,
    dmgPerLevel: 2.1,
    attackSpeed: 2.0,
    armorPerLevel: 12,
    moveSpeed: 8.5,
    aggroRadius: 11,
    count: 10,
    drops: [
      { copper: [23, 38], chance: 1 },
      { itemId: "mire_prowler_pelt", chance: 0.6 },
      { itemId: "soggy_moccasin", chance: 0.3 },
      { itemId: "lesser_healing_potion", chance: 0.08 },
    ],
  },
  {
    id: "deepfen_murloc",
    name: "Deepfen Snapper",
    family: "beast",
    zone: "marsh",
    minLevel: 8,
    maxLevel: 9,
    hpBase: 48,
    hpPerLevel: 19,
    dmgBase: 7,
    dmgPerLevel: 2.2,
    attackSpeed: 1.9,
    armorPerLevel: 12,
    moveSpeed: 8,
    aggroRadius: 14,
    count: 10,
    drops: [
      { copper: [26, 44], chance: 1 },
      { itemId: "waterlogged_idol", chance: 0.5 },
      { itemId: "mudfin_scale", chance: 0.4 },
    ],
  },
  {
    id: "mirejaw_the_ravenous",
    name: "Mirejaw the Ravenous",
    family: "beast",
    zone: "marsh",
    minLevel: 10,
    maxLevel: 10,
    hpBase: 320,
    hpPerLevel: 58,
    dmgBase: 15,
    dmgPerLevel: 3.7,
    attackSpeed: 1.8,
    armorPerLevel: 26,
    moveSpeed: 8.2,
    aggroRadius: 14,
    count: 1,
    rare: true,
    drops: [
      { copper: [195, 325], chance: 1 },
      { itemId: "mudfin_scale", chance: 1 },
      { itemId: "mirejaw_biteblade", chance: 0.25 },
      { itemId: "mirejaw_scale_vest", chance: 0.25 },
      { itemId: "fen_reaver_glaive", chance: 0.25 },
      { itemId: "mirejaw_oracle_staff", chance: 0.25 },
    ],
  },
  {
    id: "mirejaw_frenzy",
    name: "Mirejaw Frenzy",
    family: "beast",
    zone: "marsh",
    minLevel: 9,
    maxLevel: 10,
    hpBase: 48,
    hpPerLevel: 18,
    dmgBase: 8,
    dmgPerLevel: 2.2,
    attackSpeed: 1.7,
    armorPerLevel: 12,
    moveSpeed: 8.5,
    aggroRadius: 14,
    count: 10,
    drops: [],
  },
  {
    id: "sloomtooth_the_drowned",
    name: "Sloomtooth the Drowned",
    family: "beast",
    zone: "marsh",
    minLevel: 11,
    maxLevel: 11,
    hpBase: 340,
    hpPerLevel: 60,
    dmgBase: 16,
    dmgPerLevel: 3.8,
    attackSpeed: 1.9,
    armorPerLevel: 28,
    moveSpeed: 8.4,
    aggroRadius: 14,
    count: 1,
    rare: true,
    drops: [
      { copper: [210, 350], chance: 1 },
      { itemId: "mudfin_scale", chance: 1 },
      { itemId: "tidereaver_gaff", chance: 0.25 },
      { itemId: "sloomtooth_tidefang", chance: 0.25 },
      { itemId: "drowned_tide_scepter", chance: 0.25 },
    ],
  },
  {
    id: "mire_widow",
    name: "Mirefen Widow",
    family: "beast",
    zone: "marsh",
    minLevel: 8,
    maxLevel: 10,
    hpBase: 48,
    hpPerLevel: 19,
    dmgBase: 8,
    dmgPerLevel: 2.2,
    attackSpeed: 1.8,
    armorPerLevel: 10,
    moveSpeed: 8,
    aggroRadius: 10,
    count: 10,
    drops: [
      { copper: [29, 48], chance: 1 },
      { itemId: "widow_venom_sac", chance: 0.65 },
      { itemId: "spider_leg", chance: 0.4 },
    ],
  },
  {
    id: "mirefen_broodmother",
    name: "The Broodmother",
    family: "beast",
    zone: "marsh",
    minLevel: 10,
    maxLevel: 10,
    hpBase: 150,
    hpPerLevel: 26,
    dmgBase: 9,
    dmgPerLevel: 2.4,
    attackSpeed: 1.8,
    armorPerLevel: 16,
    moveSpeed: 8,
    aggroRadius: 14,
    count: 1,
    boss: true,
    drops: [
      { copper: [225, 375], chance: 1 },
      { itemId: "marshstrider_boots", chance: 0.4 },
      { itemId: "broodmother_silk_robe", chance: 0.25 },
      { itemId: "spider_leg", chance: 1 },
    ],
  },
  {
    id: "fen_troll",
    name: "Mirefen Troll",
    family: "humanoid",
    zone: "marsh",
    minLevel: 10,
    maxLevel: 12,
    hpBase: 56,
    hpPerLevel: 21,
    dmgBase: 9,
    dmgPerLevel: 2.4,
    attackSpeed: 2.2,
    armorPerLevel: 18,
    moveSpeed: 7.5,
    aggroRadius: 11,
    count: 10,
    drops: [
      { copper: [38, 63], chance: 1 },
      { itemId: "troll_fetish", chance: 0.6 },
      { itemId: "chipped_tusk", chance: 0.4 },
      { itemId: "bogiron_nugget", chance: 0.3 },
      { itemId: "elixir_of_the_bear", chance: 0.07 },
    ],
  },
  {
    id: "grubjaw",
    name: "Grubjaw the Glutton",
    family: "humanoid",
    zone: "marsh",
    minLevel: 12,
    maxLevel: 12,
    hpBase: 130,
    hpPerLevel: 26,
    dmgBase: 10,
    dmgPerLevel: 2.5,
    attackSpeed: 2.2,
    armorPerLevel: 20,
    moveSpeed: 7.5,
    aggroRadius: 13,
    count: 1,
    rare: true,
    drops: [
      { copper: [150, 250], chance: 1 },
      { itemId: "grubjaw_tusk", chance: 1 },
      { itemId: "chipped_tusk", chance: 1 },
    ],
  },
  {
    id: "drowned_dead",
    name: "Drowned Dead",
    family: "undead",
    zone: "marsh",
    minLevel: 9,
    maxLevel: 11,
    hpBase: 52,
    hpPerLevel: 20,
    dmgBase: 8,
    dmgPerLevel: 2.3,
    attackSpeed: 2.3,
    armorPerLevel: 14,
    moveSpeed: 6.5,
    aggroRadius: 11,
    count: 10,
    drops: [
      { copper: [32, 53], chance: 1 },
      { itemId: "bone_fragments", chance: 0.5 },
      { itemId: "cracked_fetish", chance: 0.3 },
    ],
  },
  {
    id: "gravecaller_cultist",
    name: "Gravecaller Cultist",
    family: "humanoid",
    zone: "marsh",
    minLevel: 10,
    maxLevel: 12,
    hpBase: 50,
    hpPerLevel: 20,
    dmgBase: 9,
    dmgPerLevel: 2.4,
    attackSpeed: 2.0,
    armorPerLevel: 20,
    moveSpeed: 7,
    aggroRadius: 11,
    count: 10,
    drops: [
      { copper: [41, 69], chance: 1 },
      { itemId: "linen_scrap", chance: 0.3 },
      { itemId: "tallow_candle", chance: 0.3 },
      { itemId: "gravecaller_sigil", chance: 0.35 },
    ],
  },
  {
    id: "gravecaller_summoner",
    name: "Gravecaller Summoner",
    family: "humanoid",
    zone: "marsh",
    minLevel: 11,
    maxLevel: 12,
    hpBase: 46,
    hpPerLevel: 19,
    dmgBase: 10,
    dmgPerLevel: 2.5,
    attackSpeed: 2.0,
    armorPerLevel: 16,
    moveSpeed: 7,
    aggroRadius: 12,
    count: 5,
    drops: [
      { copper: [45, 75], chance: 1 },
      { itemId: "cult_cipher", chance: 0.6 },
    ],
  },
  {
    id: "gravecaller_mender",
    name: "Gravecaller Mender",
    family: "humanoid",
    zone: "marsh",
    minLevel: 11,
    maxLevel: 12,
    hpBase: 44,
    hpPerLevel: 18,
    dmgBase: 8,
    dmgPerLevel: 2.2,
    attackSpeed: 2.1,
    armorPerLevel: 16,
    moveSpeed: 7,
    aggroRadius: 12,
    count: 5,
    drops: [
      { copper: [44, 73], chance: 1 },
      { itemId: "cult_cipher", chance: 0.4 },
      { itemId: "tallow_candle", chance: 0.3 },
    ],
  },
  {
    id: "sister_nhalia",
    name: "Sister Nhalia",
    family: "humanoid",
    zone: "marsh",
    minLevel: 12,
    maxLevel: 12,
    hpBase: 330,
    hpPerLevel: 60,
    dmgBase: 16,
    dmgPerLevel: 3.8,
    attackSpeed: 2.0,
    armorPerLevel: 30,
    moveSpeed: 7,
    aggroRadius: 13,
    count: 1,
    rare: true,
    drops: [
      { copper: [263, 438], chance: 1 },
      { itemId: "tallow_candle", chance: 1 },
      { itemId: "nhalias_funeral_wraps", chance: 0.25 },
      { itemId: "nhalias_dirgeblade", chance: 0.25 },
    ],
  },
  {
    id: "nhalia_mourner",
    name: "Nhalia Mourner",
    family: "humanoid",
    zone: "marsh",
    minLevel: 11,
    maxLevel: 12,
    hpBase: 46,
    hpPerLevel: 17,
    dmgBase: 8,
    dmgPerLevel: 2.3,
    attackSpeed: 2.0,
    armorPerLevel: 14,
    moveSpeed: 7,
    aggroRadius: 12,
    count: 10,
    drops: [],
  },
  {
    id: "deacon_voss",
    name: "Deacon Voss",
    family: "humanoid",
    zone: "marsh",
    minLevel: 12,
    maxLevel: 12,
    hpBase: 200,
    hpPerLevel: 30,
    dmgBase: 11,
    dmgPerLevel: 2.5,
    attackSpeed: 2.4,
    armorPerLevel: 26,
    moveSpeed: 7,
    aggroRadius: 14,
    count: 1,
    boss: true,
    drops: [
      { copper: [450, 750], chance: 1 },
      { itemId: "tallow_candle", chance: 1 },
      { itemId: "voss_sanctified_mace", chance: 0.25 },
    ],
  },
  {
    id: "bog_bloat",
    name: "Bog Bloat",
    family: "beast",
    zone: "marsh",
    minLevel: 9,
    maxLevel: 11,
    hpBase: 44,
    hpPerLevel: 17,
    dmgBase: 7,
    dmgPerLevel: 2.0,
    attackSpeed: 2.6,
    armorPerLevel: 9,
    moveSpeed: 6,
    aggroRadius: 10,
    count: 10,
    drops: [
      { copper: [30, 50], chance: 1 },
      { itemId: "tangled_weed", chance: 0.5 },
    ],
  },
];
