import type { MobDef } from "../../../model";

export const PEAKS_MOBS: readonly MobDef[] = [
  {
    id: "ridge_stalker",
    name: "Ridge Stalker",
    family: "beast",
    zone: "peaks",
    minLevel: 13,
    maxLevel: 14,
    hpBase: 58,
    hpPerLevel: 21,
    dmgBase: 10,
    dmgPerLevel: 2.5,
    attackSpeed: 1.9,
    armorPerLevel: 14,
    moveSpeed: 8,
    aggroRadius: 11,
    count: 10,
    drops: [
      { copper: [45, 75], chance: 1 },
      { itemId: "ridge_stalker_pelt", chance: 0.6 },
    ],
  },
  {
    id: "old_cragmaw",
    name: "Old Cragmaw",
    family: "beast",
    zone: "peaks",
    minLevel: 14,
    maxLevel: 14,
    hpBase: 320,
    hpPerLevel: 56,
    dmgBase: 16,
    dmgPerLevel: 4.0,
    attackSpeed: 1.7,
    armorPerLevel: 24,
    moveSpeed: 8.6,
    aggroRadius: 13,
    count: 1,
    rare: true,
    drops: [
      { copper: [165, 275], chance: 1 },
      { itemId: "old_cragmaws_pelt", chance: 1 },
      { itemId: "cragmaw_huntcord", chance: 0.25 },
      { itemId: "cragmaw_prowlboots", chance: 0.3 },
    ],
  },
  {
    id: "deeprock_kobold",
    name: "Deeprock Tunneler",
    family: "humanoid",
    zone: "peaks",
    minLevel: 14,
    maxLevel: 15,
    hpBase: 60,
    hpPerLevel: 22,
    dmgBase: 10,
    dmgPerLevel: 2.5,
    attackSpeed: 2.1,
    armorPerLevel: 18,
    moveSpeed: 7,
    aggroRadius: 10,
    count: 10,
    drops: [
      { copper: [49, 81], chance: 1 },
      { itemId: "glowing_wax", chance: 0.5 },
      { itemId: "tallow_candle", chance: 0.4 },
      { itemId: "healing_potion", chance: 0.08 },
      { itemId: "deathlord_sabatons", chance: 0.001 },
    ],
  },
  {
    id: "ironvein_foreman",
    name: "Ironvein Foreman",
    family: "humanoid",
    zone: "peaks",
    minLevel: 16,
    maxLevel: 16,
    hpBase: 420,
    hpPerLevel: 70,
    dmgBase: 19,
    dmgPerLevel: 4.4,
    attackSpeed: 2.0,
    armorPerLevel: 38,
    moveSpeed: 7,
    aggroRadius: 12,
    count: 1,
    rare: true,
    drops: [
      { copper: [315, 525], chance: 1 },
      { itemId: "glowing_wax", chance: 1 },
      { itemId: "ironvein_pickblade", chance: 0.25 },
      { itemId: "ironvein_lantern_staff", chance: 0.25 },
      { itemId: "gutripper_shiv", chance: 0.25 },
      { itemId: "deathlord_sabatons", chance: 0.25 },
    ],
  },
  {
    id: "ironvein_sapper",
    name: "Ironvein Sapper",
    family: "humanoid",
    zone: "peaks",
    minLevel: 15,
    maxLevel: 16,
    hpBase: 58,
    hpPerLevel: 20,
    dmgBase: 11,
    dmgPerLevel: 2.6,
    attackSpeed: 2.0,
    armorPerLevel: 18,
    moveSpeed: 7.5,
    aggroRadius: 12,
    count: 10,
    drops: [],
  },
  {
    id: "thornpeak_ogre",
    name: "Thornpeak Ogre",
    family: "humanoid",
    zone: "peaks",
    minLevel: 15,
    maxLevel: 16,
    hpBase: 66,
    hpPerLevel: 23,
    dmgBase: 11,
    dmgPerLevel: 2.6,
    attackSpeed: 2.6,
    armorPerLevel: 22,
    moveSpeed: 7,
    aggroRadius: 11,
    count: 10,
    drops: [
      { copper: [56, 94], chance: 1 },
      { itemId: "ogre_toe_ring", chance: 0.35 },
    ],
  },
  {
    id: "ogre_crusher",
    name: "Thornpeak Crusher",
    family: "humanoid",
    zone: "peaks",
    minLevel: 16,
    maxLevel: 17,
    hpBase: 64,
    hpPerLevel: 23,
    dmgBase: 11,
    dmgPerLevel: 2.6,
    attackSpeed: 2.6,
    armorPerLevel: 24,
    moveSpeed: 7,
    aggroRadius: 12,
    count: 5,
    drops: [
      { copper: [150, 250], chance: 1 },
      { itemId: "ogre_toe_ring", chance: 0.5 },
    ],
  },
  {
    id: "warlord_drogmar",
    name: "Warlord Drogmar",
    family: "humanoid",
    zone: "peaks",
    minLevel: 17,
    maxLevel: 17,
    hpBase: 200,
    hpPerLevel: 30,
    dmgBase: 12,
    dmgPerLevel: 2.7,
    attackSpeed: 2.6,
    armorPerLevel: 28,
    moveSpeed: 7,
    aggroRadius: 14,
    count: 1,
    boss: true,
    drops: [
      { copper: [1500, 2500], chance: 1 },
      { itemId: "drogmar_warboots", chance: 0.3 },
      { itemId: "drogmars_skullcleaver", chance: 0.25 },
    ],
  },
  {
    id: "brutok_skullsmasher",
    name: "Brutok Skullsmasher",
    family: "humanoid",
    zone: "peaks",
    minLevel: 17,
    maxLevel: 17,
    hpBase: 360,
    hpPerLevel: 60,
    dmgBase: 16,
    dmgPerLevel: 3.6,
    attackSpeed: 2.7,
    armorPerLevel: 30,
    moveSpeed: 7,
    aggroRadius: 13,
    count: 1,
    rare: true,
    drops: [
      { copper: [240, 400], chance: 1 },
      { itemId: "cracked_ogre_tusk", chance: 1 },
      { itemId: "skullsmasher_warbelt", chance: 0.3 },
      { itemId: "brutoks_maul", chance: 0.25 },
      { itemId: "crag_warden_cudgel", chance: 0.25 },
      { itemId: "skullsplitter_dirk", chance: 0.25 },
    ],
  },
  {
    id: "stormcrag_elemental",
    name: "Stormcrag Elemental",
    family: "elemental",
    zone: "peaks",
    minLevel: 17,
    maxLevel: 18,
    hpBase: 62,
    hpPerLevel: 22,
    dmgBase: 12,
    dmgPerLevel: 2.7,
    attackSpeed: 2.2,
    armorPerLevel: 20,
    moveSpeed: 6.5,
    aggroRadius: 11,
    count: 10,
    drops: [
      { copper: [60, 100], chance: 1 },
      { itemId: "storm_core", chance: 0.55 },
      { itemId: "blessed_embers", chance: 0.55 },
      { itemId: "inert_storm_shard", chance: 0.4 },
    ],
  },
  {
    id: "shardlord_kazzix",
    name: "Shardlord Kazzix",
    family: "elemental",
    zone: "peaks",
    minLevel: 18,
    maxLevel: 18,
    hpBase: 160,
    hpPerLevel: 28,
    dmgBase: 13,
    dmgPerLevel: 2.8,
    attackSpeed: 2.2,
    armorPerLevel: 24,
    moveSpeed: 7,
    aggroRadius: 12,
    count: 1,
    rare: true,
    drops: [
      { copper: [375, 625], chance: 1 },
      { itemId: "kazzix_heartshard", chance: 1 },
      { itemId: "inert_storm_shard", chance: 1 },
    ],
  },
  {
    id: "wyrmcult_zealot",
    name: "Wyrmcult Zealot",
    family: "humanoid",
    zone: "peaks",
    minLevel: 17,
    maxLevel: 19,
    hpBase: 62,
    hpPerLevel: 22,
    dmgBase: 12,
    dmgPerLevel: 2.7,
    attackSpeed: 2.0,
    armorPerLevel: 20,
    moveSpeed: 7,
    aggroRadius: 11,
    count: 10,
    drops: [
      { copper: [68, 113], chance: 1 },
      { itemId: "wyrmcult_orders", chance: 0.5 },
      { itemId: "frayed_prayer_beads", chance: 0.35 },
    ],
  },
  {
    id: "wyrmcult_necromancer",
    name: "Wyrmcult Necromancer",
    family: "humanoid",
    zone: "peaks",
    minLevel: 18,
    maxLevel: 19,
    hpBase: 58,
    hpPerLevel: 21,
    dmgBase: 13,
    dmgPerLevel: 2.8,
    attackSpeed: 2.0,
    armorPerLevel: 16,
    moveSpeed: 7,
    aggroRadius: 11,
    count: 10,
    drops: [
      { copper: [75, 125], chance: 1 },
      { itemId: "ritual_phylactery", chance: 0.55 },
      { itemId: "linen_scrap", chance: 0.3 },
    ],
  },
  {
    id: "boneclad_revenant",
    name: "Boneclad Revenant",
    family: "undead",
    zone: "peaks",
    minLevel: 18,
    maxLevel: 19,
    hpBase: 66,
    hpPerLevel: 23,
    dmgBase: 12,
    dmgPerLevel: 2.7,
    attackSpeed: 2.3,
    armorPerLevel: 18,
    moveSpeed: 6.5,
    aggroRadius: 11,
    count: 10,
    drops: [
      { copper: [75, 125], chance: 1 },
      { itemId: "bone_fragments", chance: 0.6 },
      { itemId: "runed_bone_shard", chance: 0.7 },
      { itemId: "necromancers_legwraps", chance: 0.001 },
    ],
  },
  {
    id: "fallen_captain_aldren",
    name: "Fallen Captain Aldren",
    family: "undead",
    zone: "peaks",
    minLevel: 20,
    maxLevel: 20,
    hpBase: 390,
    hpPerLevel: 72,
    dmgBase: 22,
    dmgPerLevel: 4.2,
    attackSpeed: 2.2,
    armorPerLevel: 42,
    moveSpeed: 7.2,
    aggroRadius: 18,
    count: 1,
    rare: true,
    drops: [
      { copper: [338, 563], chance: 1 },
      { itemId: "captains_crest", chance: 1 },
      { itemId: "bone_fragments", chance: 1 },
    ],
  },
  {
    id: "corrupted_priest_malric",
    name: "Corrupted Priest Malric",
    family: "undead",
    zone: "peaks",
    minLevel: 20,
    maxLevel: 20,
    hpBase: 360,
    hpPerLevel: 68,
    dmgBase: 23,
    dmgPerLevel: 4.3,
    attackSpeed: 2.3,
    armorPerLevel: 26,
    moveSpeed: 6.9,
    aggroRadius: 18,
    count: 1,
    rare: true,
    drops: [
      { copper: [338, 563], chance: 1 },
      { itemId: "priests_sigil", chance: 1 },
      { itemId: "frayed_prayer_beads", chance: 0.5 },
    ],
  },
  {
    id: "deathstalker_voss",
    name: "Deathstalker Voss",
    family: "undead",
    zone: "peaks",
    minLevel: 20,
    maxLevel: 20,
    hpBase: 410,
    hpPerLevel: 74,
    dmgBase: 24,
    dmgPerLevel: 4.5,
    attackSpeed: 2.1,
    armorPerLevel: 44,
    moveSpeed: 7.4,
    aggroRadius: 18,
    count: 1,
    rare: true,
    drops: [
      { copper: [338, 563], chance: 1 },
      { itemId: "royal_seal", chance: 1 },
      { itemId: "bone_fragments", chance: 1 },
    ],
  },
  {
    id: "bound_guardian",
    name: "The Bound Guardian",
    family: "undead",
    zone: "peaks",
    minLevel: 20,
    maxLevel: 20,
    hpBase: 310,
    hpPerLevel: 48,
    dmgBase: 16,
    dmgPerLevel: 3.4,
    attackSpeed: 2.4,
    armorPerLevel: 42,
    moveSpeed: 6.8,
    aggroRadius: 16,
    count: 1,
    boss: true,
    drops: [
      { copper: [900, 1500], chance: 1 },
      { itemId: "kings_signet", chance: 1 },
    ],
  },
  {
    id: "marrowlord_varkas",
    name: "Marrowlord Varkas",
    family: "undead",
    zone: "peaks",
    minLevel: 19,
    maxLevel: 19,
    hpBase: 480,
    hpPerLevel: 80,
    dmgBase: 22,
    dmgPerLevel: 5.0,
    attackSpeed: 2.4,
    armorPerLevel: 44,
    moveSpeed: 6.5,
    aggroRadius: 13,
    count: 1,
    rare: true,
    drops: [
      { copper: [488, 813], chance: 1 },
      { itemId: "bone_fragments", chance: 1 },
      { itemId: "marrowlord_boneboots", chance: 0.3 },
      { itemId: "necromancers_legwraps", chance: 0.25 },
    ],
  },
  {
    id: "varkas_boneguard",
    name: "Varkas Boneguard",
    family: "undead",
    zone: "peaks",
    minLevel: 18,
    maxLevel: 19,
    hpBase: 64,
    hpPerLevel: 22,
    dmgBase: 12,
    dmgPerLevel: 2.8,
    attackSpeed: 2.3,
    armorPerLevel: 20,
    moveSpeed: 6.5,
    aggroRadius: 12,
    count: 10,
    drops: [],
  },
  {
    id: "voskar_emberwing",
    name: "Voskar the Emberwing",
    family: "beast",
    zone: "peaks",
    minLevel: 19,
    maxLevel: 19,
    hpBase: 470,
    hpPerLevel: 78,
    dmgBase: 22,
    dmgPerLevel: 4.9,
    attackSpeed: 2.5,
    armorPerLevel: 42,
    moveSpeed: 7,
    aggroRadius: 13,
    count: 1,
    rare: true,
    drops: [
      { copper: [525, 875], chance: 1 },
      { itemId: "emberwing_cinderscale", chance: 1 },
      { itemId: "emberwing_legguards", chance: 0.25 },
      { itemId: "emberfang_warblade", chance: 0.25 },
    ],
  },
  {
    id: "thunzharr_waking_peak",
    name: "Thunzharr, the Waking Peak",
    family: "elemental",
    zone: "peaks",
    minLevel: 20,
    maxLevel: 20,
    hpBase: 4000,
    hpPerLevel: 800,
    dmgBase: 54,
    dmgPerLevel: 10.3,
    attackSpeed: 2.4,
    armorPerLevel: 46,
    moveSpeed: 11.6,
    aggroRadius: 18,
    count: 0,
    boss: true,
    abilities: [
      { id: "thunderclap", name: "Thunderclap", intervalSec: 12, amount: 43, radius: 12, school: "nature", windupMs: 800 },
      { id: "seismic_stomp", name: "Seismic Stomp", intervalSec: 24, amount: 23, radius: 11, school: "physical", windupMs: 1000 },
      { id: "stormcall", name: "Stormcall", intervalSec: 40, amount: 80, radius: 30, school: "nature", windupMs: 3500 },
    ],
    mechanics: {
      enrage: { belowHpFraction: 0.2, hasteMult: 1.25, damageMult: 1.5 },
      summons: { mobId: "thunzharr_stormling", count: 1, intervalSec: 30, maxAlive: 2 },
    },
    drops: [
      { itemId: "inert_storm_shard", chance: 1 },
      { itemId: "crownforged_gauntlets", chance: 0.08 },
      { itemId: "nighttalon_grips", chance: 0.08 },
      { itemId: "soulflame_gloves", chance: 0.08 },
      { itemId: "stormcallers_handguards", chance: 0.08 },
      { itemId: "crownforged_girdle", chance: 0.08 },
      { itemId: "nighttalon_waistband", chance: 0.08 },
      { itemId: "soulflame_cord", chance: 0.08 },
      { itemId: "stormcallers_waistguard", chance: 0.08 },
    ],
  },
  {
    id: "thunzharr_stormling",
    name: "Roused Stormling",
    family: "elemental",
    zone: "peaks",
    minLevel: 19,
    maxLevel: 20,
    hpBase: 70,
    hpPerLevel: 24,
    dmgBase: 13,
    dmgPerLevel: 2.9,
    attackSpeed: 2.0,
    armorPerLevel: 22,
    moveSpeed: 7.4,
    aggroRadius: 12,
    count: 0,
    drops: [],
  },
];
