import type { MobDef } from "../../../model";

export const VALE_MOBS: readonly MobDef[] = [
  {
    id: "forest_wolf",
    name: "Forest Wolf",
    family: "beast",
    zone: "vale",
    minLevel: 1,
    maxLevel: 2,
    hpBase: 40,
    hpPerLevel: 14,
    dmgBase: 3,
    dmgPerLevel: 1.6,
    attackSpeed: 2.0,
    armorPerLevel: 10,
    moveSpeed: 8,
    aggroRadius: 10,
    count: 10,
    drops: [
      { copper: [6, 10], chance: 1 },
      { itemId: "wolf_fang", chance: 0.45 },
      { itemId: "milepost_boots", chance: 0.1 },
      { itemId: "wolfhide_satchel", chance: 0.02 },
    ],
    packFrenzy: { radius: 12, hasteMult: 1.3, duration: 8 },
  },
  {
    id: "wild_boar",
    name: "Wild Boar",
    family: "beast",
    zone: "vale",
    minLevel: 2,
    maxLevel: 3,
    hpBase: 38,
    hpPerLevel: 16,
    dmgBase: 4,
    dmgPerLevel: 1.8,
    attackSpeed: 2.2,
    armorPerLevel: 14,
    moveSpeed: 7.5,
    aggroRadius: 9,
    count: 10,
    drops: [
      { copper: [9, 15], chance: 1 },
      { itemId: "boar_hide", chance: 0.6 },
      { itemId: "tough_jerky", chance: 0.3 },
      { itemId: "trail_leggings", chance: 0.1 },
    ],
  },
  {
    id: "webwood_spider",
    name: "Sableweb Lurker",
    family: "beast",
    zone: "vale",
    minLevel: 2,
    maxLevel: 4,
    hpBase: 36,
    hpPerLevel: 15,
    dmgBase: 4,
    dmgPerLevel: 1.7,
    attackSpeed: 1.8,
    armorPerLevel: 8,
    moveSpeed: 8,
    aggroRadius: 10,
    count: 10,
    drops: [
      { copper: [11, 18], chance: 1 },
      { itemId: "webwood_silk", chance: 0.55 },
      { itemId: "spider_leg", chance: 0.4 },
    ],
  },
  {
    id: "vale_bandit",
    name: "Vale Bandit",
    family: "humanoid",
    zone: "vale",
    minLevel: 3,
    maxLevel: 5,
    hpBase: 40,
    hpPerLevel: 18,
    dmgBase: 5,
    dmgPerLevel: 2.0,
    attackSpeed: 2.0,
    armorPerLevel: 20,
    moveSpeed: 7,
    aggroRadius: 11,
    count: 10,
    drops: [
      { copper: [19, 31], chance: 1 },
      { itemId: "bandit_bandana", chance: 0.5 },
      { itemId: "linen_scrap", chance: 0.3 },
    ],
  },
  {
    id: "tunnel_rat",
    name: "Deeprock Digger",
    family: "humanoid",
    zone: "vale",
    minLevel: 4,
    maxLevel: 6,
    hpBase: 42,
    hpPerLevel: 18,
    dmgBase: 6,
    dmgPerLevel: 2.0,
    attackSpeed: 2.1,
    armorPerLevel: 16,
    moveSpeed: 7,
    aggroRadius: 10,
    count: 10,
    drops: [
      { copper: [17, 28], chance: 1 },
      { itemId: "tallow_candle", chance: 0.6 },
      { itemId: "blessed_wax", chance: 0.45 },
      { itemId: "linen_scrap", chance: 0.25 },
      { itemId: "mossy_handwraps", chance: 0.15 },
    ],
  },
  {
    id: "restless_bones",
    name: "Restless Bones",
    family: "undead",
    zone: "vale",
    minLevel: 5,
    maxLevel: 7,
    hpBase: 46,
    hpPerLevel: 19,
    dmgBase: 7,
    dmgPerLevel: 2.1,
    attackSpeed: 2.3,
    armorPerLevel: 14,
    moveSpeed: 6.5,
    aggroRadius: 11,
    count: 10,
    drops: [
      { copper: [23, 38], chance: 1 },
      { itemId: "bone_fragments", chance: 0.6 },
      { itemId: "ghostly_essence", chance: 0.55 },
    ],
  },
  {
    id: "mudfin_murloc",
    name: "Mudfin Skulker",
    family: "beast",
    zone: "vale",
    minLevel: 3,
    maxLevel: 5,
    hpBase: 36,
    hpPerLevel: 17,
    dmgBase: 5,
    dmgPerLevel: 1.9,
    attackSpeed: 1.9,
    armorPerLevel: 12,
    moveSpeed: 8,
    aggroRadius: 13,
    count: 10,
    drops: [
      { copper: [14, 23], chance: 1 },
      { itemId: "mudfin_scale", chance: 0.5 },
      { itemId: "linen_scrap", chance: 0.2 },
    ],
  },
  {
    id: "old_greyjaw",
    name: "Old Greyjaw",
    family: "beast",
    zone: "vale",
    minLevel: 4,
    maxLevel: 4,
    hpBase: 110,
    hpPerLevel: 20,
    dmgBase: 5,
    dmgPerLevel: 2.0,
    attackSpeed: 1.8,
    armorPerLevel: 16,
    moveSpeed: 8.5,
    aggroRadius: 12,
    count: 1,
    rare: true,
    drops: [
      { copper: [45, 75], chance: 1 },
      { itemId: "greyjaw_fang", chance: 1 },
      { itemId: "wolf_fang", chance: 1 },
      { itemId: "wolfhide_satchel", chance: 0.35 },
    ],
  },
  {
    id: "mogger",
    name: "Mogger",
    family: "humanoid",
    zone: "vale",
    minLevel: 6,
    maxLevel: 6,
    hpBase: 300,
    hpPerLevel: 58,
    dmgBase: 12,
    dmgPerLevel: 3.5,
    attackSpeed: 2.2,
    armorPerLevel: 34,
    moveSpeed: 7.4,
    aggroRadius: 14,
    count: 1,
    rare: true,
    drops: [
      { copper: [135, 225], chance: 1 },
      { itemId: "linen_scrap", chance: 1 },
      { itemId: "moggers_stomper_boots", chance: 0.3 },
      { itemId: "moggers_shiv", chance: 0.25 },
      { itemId: "cryptstalker_jerkin", chance: 0.25 },
    ],
  },
  {
    id: "mogger_lackey",
    name: "Mogger Lackey",
    family: "humanoid",
    zone: "vale",
    minLevel: 5,
    maxLevel: 6,
    hpBase: 44,
    hpPerLevel: 18,
    dmgBase: 6,
    dmgPerLevel: 2.0,
    attackSpeed: 2.0,
    armorPerLevel: 18,
    moveSpeed: 7.5,
    aggroRadius: 12,
    count: 10,
    drops: [],
  },
  {
    id: "grix_the_tunnelking",
    name: "Grix the Tunnelking",
    family: "humanoid",
    zone: "vale",
    minLevel: 7,
    maxLevel: 7,
    hpBase: 280,
    hpPerLevel: 52,
    dmgBase: 11,
    dmgPerLevel: 3.3,
    attackSpeed: 2.0,
    armorPerLevel: 24,
    moveSpeed: 7,
    aggroRadius: 13,
    count: 1,
    rare: true,
    drops: [
      { copper: [113, 188], chance: 1 },
      { itemId: "tallow_candle", chance: 1 },
      { itemId: "lesser_healing_potion", chance: 1 },
      { itemId: "tunnelkings_spade", chance: 0.3 },
      { itemId: "moggers_copper_cudgel", chance: 0.25 },
      { itemId: "hollowbone_hauberk", chance: 0.25 },
    ],
  },
  {
    id: "captain_verlan",
    name: "Captain Verlan",
    family: "undead",
    zone: "vale",
    minLevel: 7,
    maxLevel: 7,
    hpBase: 280,
    hpPerLevel: 56,
    dmgBase: 12,
    dmgPerLevel: 3.4,
    attackSpeed: 2.6,
    armorPerLevel: 32,
    moveSpeed: 7.4,
    aggroRadius: 13,
    count: 1,
    rare: true,
    drops: [
      { copper: [120, 200], chance: 1 },
      { itemId: "bone_fragments", chance: 1 },
      { itemId: "oathbound_greaves", chance: 0.3 },
      { itemId: "verlans_oathblade", chance: 0.25 },
      { itemId: "hollow_vigil_staff", chance: 0.25 },
      { itemId: "gravewardens_shiv", chance: 0.25 },
    ],
  },
  {
    id: "wraithbinder_maldrec",
    name: "Wraithbinder Maldrec",
    family: "undead",
    zone: "vale",
    minLevel: 7,
    maxLevel: 7,
    hpBase: 320,
    hpPerLevel: 60,
    dmgBase: 12,
    dmgPerLevel: 3.4,
    attackSpeed: 2.3,
    armorPerLevel: 28,
    moveSpeed: 6.8,
    aggroRadius: 13,
    count: 1,
    rare: true,
    drops: [
      { copper: [120, 200], chance: 1 },
      { itemId: "bone_fragments", chance: 1 },
      { itemId: "maldrecs_soulbinder", chance: 0.25 },
      { itemId: "hollowbone_hauberk", chance: 0.25 },
      { itemId: "gravewoven_raiment", chance: 0.25 },
      { itemId: "cryptstalker_jerkin", chance: 0.25 },
    ],
  },
  {
    id: "gorrak",
    name: "Gorrak the Ruthless",
    family: "humanoid",
    zone: "vale",
    minLevel: 6,
    maxLevel: 6,
    hpBase: 160,
    hpPerLevel: 30,
    dmgBase: 8,
    dmgPerLevel: 2.4,
    attackSpeed: 2.4,
    armorPerLevel: 30,
    moveSpeed: 7,
    aggroRadius: 13,
    count: 1,
    boss: true,
    drops: [
      { copper: [188, 313], chance: 1 },
      { itemId: "bandit_bandana", chance: 1 },
      { itemId: "oiled_boots", chance: 0.5 },
      { itemId: "quilted_trousers", chance: 0.5 },
      { itemId: "gorraks_cruel_chopper", chance: 0.25 },
      { itemId: "gorraks_cleaver", chance: 0.3 },
    ],
  },
];
