import type { JgThemeVars } from "@/components/ui/jg-theme";

import { DANGER_RED, DUNE_GOLD, INDIGO_ROBE, INK, INK_DIM, OASIS_GREEN, PANEL_BG, PANEL_BORDER, SHADOW_OCHRE } from "../palette";

export const duneVars: JgThemeVars = {
  "--jg-accent": DUNE_GOLD,
  "--jg-accent-glow": "rgba(224, 184, 120, 0.5)",
  "--jg-accent-deep": SHADOW_OCHRE,
  "--jg-surface": PANEL_BG,
  "--jg-surface-deep": "#160f09",
  "--jg-edge": PANEL_BORDER,
  "--jg-edge-bright": "#8a6a3c",
  "--jg-text": INK,
  "--jg-text-dim": INK_DIM,
  "--jg-health": OASIS_GREEN,
  "--jg-health-deep": "#204d3c",
  "--jg-mana": INDIGO_ROBE,
  "--jg-mana-deep": "#20264d",
  "--jg-stamina": OASIS_GREEN,
  "--jg-stamina-deep": SHADOW_OCHRE,
  "--jg-xp": INDIGO_ROBE,
  "--jg-xp-deep": "#20264d",
  "--jg-shield": DUNE_GOLD,
  "--jg-shield-deep": SHADOW_OCHRE,
  "--jg-danger": DANGER_RED,
  "--jg-warning": "#d99a3f",
  "--jg-success": OASIS_GREEN,
  "--jg-hostile": "#b0503c",
  "--jg-friendly": OASIS_GREEN,
  "--jg-neutral": DUNE_GOLD,
  "--jg-font-display": "'Iowan Old Style', 'Palatino Linotype', Palatino, Georgia, serif",
  "--jg-font-numeric": "Consolas, 'Cascadia Mono', 'SF Mono', monospace",
  "--jg-font-body": "'Palatino Linotype', Palatino, Georgia, serif",
  "--jg-rarity-common": INK_DIM,
  "--jg-rarity-uncommon": OASIS_GREEN,
  "--jg-rarity-rare": INDIGO_ROBE,
  "--jg-rarity-epic": "#b0503c",
  "--jg-rarity-legendary": DUNE_GOLD,
};
