import type { JgThemeVars } from "@/components/ui/jg-theme";

export const siegeVars: JgThemeVars = {
  "--jg-accent": "#d8973c",
  "--jg-accent-glow": "rgba(216, 151, 60, 0.55)",
  "--jg-accent-deep": "#7a5220",
  "--jg-surface": "#231a10",
  "--jg-surface-deep": "#120d08",
  "--jg-edge": "#5a4326",
  "--jg-edge-bright": "#93744a",
  "--jg-text": "#f3e6cf",
  "--jg-text-dim": "#ab977a",
  "--jg-health": "#6fa347",
  "--jg-health-deep": "#345621",
  "--jg-mana": "#4f87a8",
  "--jg-mana-deep": "#213d4d",
  "--jg-stamina": "#d0b23c",
  "--jg-stamina-deep": "#685919",
  "--jg-xp": "#b06a3a",
  "--jg-xp-deep": "#5a331d",
  "--jg-shield": "#9fb0a3",
  "--jg-shield-deep": "#495a4e",
  "--jg-danger": "#c8442f",
  "--jg-warning": "#dc9a34",
  "--jg-success": "#7bb84f",
  "--jg-hostile": "#c8442f",
  "--jg-friendly": "#4f87a8",
  "--jg-neutral": "#d0b23c",
  "--jg-rarity-common": "#b3a68d",
  "--jg-rarity-uncommon": "#7bb84f",
  "--jg-rarity-rare": "#4f87a8",
  "--jg-rarity-epic": "#9a5cc9",
  "--jg-rarity-legendary": "#d8973c",
  "--jg-font-display": '"Trebuchet MS", "Segoe UI", sans-serif',
  "--jg-font-numeric": 'Consolas, "Cascadia Mono", "SF Mono", "Roboto Mono", monospace',
  "--jg-font-body": '"Segoe UI", system-ui, sans-serif',
};
