// AUTO-GENERATED by `assets reindex-sprites`. Do not edit by hand.
import type { IndexEntry } from "../manifest";

/** Pulled sprite/icon entries grouped by source id. */
export const generatedSpriteBySource: Record<string, IndexEntry[]> = {};

/** Every pulled sprite/icon entry across all sources, flattened. */
export const generatedSpriteIndex: IndexEntry[] = Object.values(generatedSpriteBySource).flat();
