import type { QuestDef } from "@jgengine/core/game/quest";

export const QUESTS: readonly QuestDef[] = [
  {
    id: "q_wolves",
    title: "Wolves at the Door",
    description: "Forest wolves grow bold on the north road out of Eastbrook.\nThin their numbers, 8 Forest Wolves, before they take another traveler.",
    giver: "marshal_redbrook",
    turnIn: "marshal_redbrook",
    objectives: [{ id: "kill_wolves", kind: "kill", target: "forest_wolf", count: 8 }],
    rewards: { xp: { amount: 250 }, economy: { copper: 75 } },
  },
  {
    id: "q_greyjaw",
    title: "The Old Wolf",
    description: "Old Greyjaw is a wolf no trap has held, prowling the deep woods north of the wolf runs.\nBring back his fang.",
    giver: "marshal_redbrook",
    turnIn: "marshal_redbrook",
    requires: ["q_wolves"],
    objectives: [{ id: "collect_fang", kind: "collect", item: "greyjaw_fang", count: 1 }],
    rewards: { xp: { amount: 450 }, economy: { copper: 150 } },
  },
  {
    id: "q_bandits",
    title: "Bandits of the Vale",
    description: "A pack of cutthroats has camped in the southwest hills, robbing wagons.\nDrive them out: slay 10 Vale Bandits.",
    giver: "marshal_redbrook",
    turnIn: "marshal_redbrook",
    requires: ["q_wolves"],
    objectives: [{ id: "kill_bandits", kind: "kill", target: "vale_bandit", count: 10 }],
    rewards: { xp: { amount: 550 }, economy: { copper: 200 } },
  },
  {
    id: "q_ringleader",
    title: "The Ringleader",
    description: "The bandits answer to Gorrak the Ruthless.\nCut off the head and the body will scatter.",
    giver: "marshal_redbrook",
    turnIn: "marshal_redbrook",
    requires: ["q_bandits"],
    objectives: [{ id: "kill_gorrak", kind: "kill", target: "gorrak", count: 1 }],
    rewards: { xp: { amount: 800 }, economy: { copper: 500 } },
  },
  {
    id: "q_mogger",
    title: "Mogger Must Fall",
    description: "Mogger has split carts, flattened fences, and killed enough livestock to empty half the Vale.\nTake companions and put the brute down.",
    giver: "marshal_redbrook",
    turnIn: "marshal_redbrook",
    requires: ["q_gravecallers_trail"],
    objectives: [{ id: "kill_mogger", kind: "kill", target: "mogger", count: 1 }],
    rewards: { xp: { amount: 1200 }, economy: { copper: 900 } },
  },
  {
    id: "q_boars",
    title: "Bristly Boar Hides",
    description: "Boar hide makes the finest travel packs, and the meadows west of town are crawling with the beasts.\nBring 5 Bristly Boar Hides.",
    giver: "wilkes_hand",
    turnIn: "wilkes_hand",
    objectives: [{ id: "collect_hides", kind: "collect", item: "boar_hide", count: 5 }],
    rewards: { xp: { amount: 350 }, economy: { copper: 120 } },
  },
  {
    id: "q_supplies",
    title: "Stolen Supplies",
    description: "Bandits hit the last wagon out of Eastbrook and made off with the goods.\nRecover proof of the raid from their southeast camp.",
    giver: "wilkes_hand",
    turnIn: "wilkes_hand",
    objectives: [{ id: "collect_bandanas", kind: "collect", item: "bandit_bandana", count: 4 }],
    rewards: { xp: { amount: 550 }, economy: { copper: 250 } },
  },
  {
    id: "q_spiders",
    title: "Sableweb Menace",
    description: "The lurkers in the eastern woods spin a silk the apothecary needs, and they have grown too numerous besides.\nCull 6 Sableweb Lurkers and cut 4 silk glands.",
    giver: "apothecary_lin",
    turnIn: "apothecary_lin",
    objectives: [
      { id: "kill_spiders", kind: "kill", target: "webwood_spider", count: 6 },
      { id: "collect_silk", kind: "collect", item: "webwood_silk", count: 4 },
    ],
    rewards: { xp: { amount: 420 }, economy: { copper: 140 } },
  },
  {
    id: "q_murlocs",
    title: "Trouble at the Lake",
    description: "Gurgling fish-men have crawled out of the shallows of Mirror Lake and are fouling the nets.\nDrive the Mudfin back: slay 8.",
    giver: "fisherman_brandt",
    turnIn: "fisherman_brandt",
    objectives: [{ id: "kill_murlocs", kind: "kill", target: "mudfin_murloc", count: 8 }],
    rewards: { xp: { amount: 520 }, economy: { copper: 180 } },
  },
  {
    id: "q_mine",
    title: "Rats in the Mine",
    description: "The copper dig struck a fine vein, then burrowing vermin came boiling out of the hillside.\nPut down 10 Deeprock Diggers.",
    giver: "foreman_odell",
    turnIn: "foreman_odell",
    objectives: [{ id: "kill_diggers", kind: "kill", target: "tunnel_rat", count: 10 }],
    rewards: { xp: { amount: 620 }, economy: { copper: 220 } },
  },
  {
    id: "q_bones",
    title: "The Restless Dead",
    description: "The old chapel yard was a resting place once.\nSomething has stirred the dead from their sleep — return 8 Restless Bones to the earth.",
    giver: "brother_aldric",
    turnIn: "brother_aldric",
    objectives: [{ id: "kill_bones", kind: "kill", target: "restless_bones", count: 8 }],
    rewards: { xp: { amount: 700 }, economy: { copper: 260 }, quests: ["q_whispers"] },
  },
  {
    id: "q_whispers",
    title: "Whispers Below",
    description: "The dead will not stay resting — something calls them back.\nSearch the chapel ruin for the sigil of whoever is calling.",
    giver: "brother_aldric",
    turnIn: "brother_aldric",
    requires: ["q_bones"],
    objectives: [{ id: "collect_sigil", kind: "collect", item: "gravecaller_sigil", count: 1 }],
    rewards: { xp: { amount: 400 }, economy: { copper: 150 }, quests: ["q_rite"] },
  },
  {
    id: "q_names_of_the_dead",
    title: "The Names of the Dead",
    description: "If the Gravecallers raised the dead, the sexton must know whose graves they robbed.\nGather 3 bone fragments bearing carved names from the chapel yard.",
    giver: "brother_aldric",
    turnIn: "brother_aldric",
    requires: ["q_whispers"],
    objectives: [{ id: "collect_bones", kind: "collect", item: "bone_fragments", count: 3 }],
    rewards: { xp: { amount: 600 }, economy: { copper: 250 } },
  },
  {
    id: "q_silence_the_call",
    title: "Silence the Call",
    description: "Every restless soul is one Morthen means to drag from the earth.\nReturn 12 more Restless Bones to their graves before the calling swells into a chorus.",
    giver: "brother_aldric",
    turnIn: "brother_aldric",
    requires: ["q_names_of_the_dead"],
    objectives: [{ id: "kill_bones", kind: "kill", target: "restless_bones", count: 12 }],
    rewards: { xp: { amount: 750 }, economy: { copper: 300 } },
  },
  {
    id: "q_rite",
    title: "The Binding Rite",
    description: "The crypt beneath the chapel must be unsealed to end this.\nGather blessed tallow and ghostly essence for the binding rite.",
    giver: "brother_aldric",
    turnIn: "brother_aldric",
    requires: ["q_whispers"],
    objectives: [
      { id: "collect_wax", kind: "collect", item: "blessed_wax", count: 4 },
      { id: "collect_essence", kind: "collect", item: "ghostly_essence", count: 6 },
    ],
    rewards: { xp: { amount: 700 }, economy: { copper: 500 }, quests: ["q_hollow"] },
  },
  {
    id: "q_hollow",
    title: "Into the Hollow",
    description: "Morthen the Gravecaller waits at the bottom of the Hollow Crypt, ringed by the elite dead he has raised.\nEnd him, and the Vale's dead will finally sleep.",
    giver: "brother_aldric",
    turnIn: "brother_aldric",
    requires: ["q_rite"],
    objectives: [{ id: "kill_morthen", kind: "kill", target: "morthen", count: 1 }],
    rewards: { xp: { amount: 1500 }, economy: { copper: 10000 } },
  },
  {
    id: "q_sexton",
    title: "The Sexton's Bell",
    description: "Sexton Marrow was the first man Morthen raised, guarding his master's door in death as faithfully as he kept the chapel in life.\nGrant the old sexton the rest he was robbed of.",
    giver: "brother_aldric",
    turnIn: "brother_aldric",
    requires: ["q_rite"],
    objectives: [{ id: "kill_sexton", kind: "kill", target: "sexton_marrow", count: 1 }],
    rewards: { xp: { amount: 1000 }, economy: { copper: 600 } },
  },
  {
    id: "q_gravecallers_trail",
    title: "The Gravecaller's Trail",
    description: "Morthen kept a grimoire of his rites and correspondence.\nA fallen wraithbinder still guards the chapel ruin above the crypt — end him and search what remains.",
    giver: "brother_aldric",
    turnIn: "brother_aldric",
    requires: ["q_hollow"],
    objectives: [{ id: "kill_wraithbinder", kind: "kill", target: "wraithbinder_maldrec", count: 1 }],
    rewards: { xp: { amount: 900 }, economy: { copper: 400 } },
  },
  {
    id: "q_fenbridge_muster",
    title: "Muster at Fenbridge",
    description: "Warden Fenwick has sounded the muster horn at Fenbridge.\nTake the causeway north and prove yourself against the mire before presenting Aldric's seal.",
    giver: "brother_aldric",
    turnIn: "warden_fenwick",
    objectives: [{ id: "kill_prowlers", kind: "kill", target: "mire_prowler", count: 3 }],
    rewards: { xp: { amount: 300 }, economy: { copper: 200 } },
  },
  {
    id: "q_prowlers",
    title: "Teeth of the Fen",
    description: "Mire prowlers have learned what a supply mule sounds like and now hunt the causeway itself.\nThin them out — twelve dead prowlers ought to teach the rest fear.",
    giver: "warden_fenwick",
    turnIn: "warden_fenwick",
    objectives: [{ id: "kill_prowlers", kind: "kill", target: "mire_prowler", count: 12 }],
    rewards: { xp: { amount: 800 }, economy: { copper: 300 } },
  },
  {
    id: "q_deepfen",
    title: "The Deepfen Stirs",
    description: "The Deepfen mudfins kept to their shallows for twenty years — now they swarm the east bank.\nCull 12 of the snappers.",
    giver: "warden_fenwick",
    turnIn: "warden_fenwick",
    objectives: [{ id: "kill_snappers", kind: "kill", target: "deepfen_murloc", count: 12 }],
    rewards: { xp: { amount: 1000 }, economy: { copper: 400 } },
  },
  {
    id: "q_deepfen_purge",
    title: "Back to the Shallows",
    description: "The mudfins are dredging cult-make idols from the lake bed.\nBreak the dredging for good: 14 more snappers.",
    giver: "warden_fenwick",
    turnIn: "warden_fenwick",
    requires: ["q_idols"],
    objectives: [{ id: "kill_snappers", kind: "kill", target: "deepfen_murloc", count: 14 }],
    rewards: { xp: { amount: 1100 }, economy: { copper: 450 } },
  },
  {
    id: "q_trolls",
    title: "Mounds of the Mirefen",
    description: "The Mirefen trolls have torn open the old barrow-mounds east of the far lake.\nDrive them off the mounds: 12 trolls dead ought to do it.",
    giver: "warden_fenwick",
    turnIn: "warden_fenwick",
    objectives: [{ id: "kill_trolls", kind: "kill", target: "fen_troll", count: 12 }],
    rewards: { xp: { amount: 1600 }, economy: { copper: 600 } },
  },
  {
    id: "q_deacon",
    title: "The Deacon of the Mire",
    description: "A deacon of the Gravecallers stands at the heart of the cult camp, singing the drowned wardens up out of the lakes.\nPut Deacon Voss in the ground.",
    giver: "warden_fenwick",
    turnIn: "warden_fenwick",
    requires: ["q_summoners"],
    objectives: [{ id: "kill_deacon", kind: "kill", target: "deacon_voss", count: 1 }],
    rewards: { xp: { amount: 2200 }, economy: { copper: 1000 } },
  },
  {
    id: "q_prowler_pelts",
    title: "Pelts for the Causeway",
    description: "Every plank of the causeway rests on pilings wrapped in oiled prowler hide, the only thing the rot will not chew through.\nBring 8 unspoiled pelts.",
    giver: "hale_dockhand",
    turnIn: "hale_dockhand",
    objectives: [{ id: "collect_pelts", kind: "collect", item: "mire_prowler_pelt", count: 8 }],
    rewards: { xp: { amount: 850 }, economy: { copper: 350 } },
  },
  {
    id: "q_fen_supplies",
    title: "The Lost Caravan",
    description: "A caravan out of Eastbrook wrecked on the causeway and its cargo is sinking slow.\nClear the bog bloats swarming the wreck before the marsh finishes the job.",
    giver: "hale_dockhand",
    turnIn: "hale_dockhand",
    objectives: [{ id: "kill_bloats", kind: "kill", target: "bog_bloat", count: 5 }],
    rewards: { xp: { amount: 900 }, economy: { copper: 350 } },
  },
  {
    id: "q_the_codfather",
    title: "The Codfather",
    description: "An old devil rules the Deepfen Shallows — even the Mirefen Widows will not spin their webs near it out of sheer terror.\nDrag it out of its waters.",
    giver: "hale_dockhand",
    turnIn: "hale_dockhand",
    objectives: [{ id: "kill_sloomtooth", kind: "kill", target: "sloomtooth_the_drowned", count: 1 }],
    rewards: { xp: { amount: 950 }, economy: { copper: 450 } },
  },
  {
    id: "q_grubjaw",
    title: "The Glutton",
    description: "There is one troll the others will not dig beside — Grubjaw, the Glutton, who prowls the far eastern mounds.\nBring back his tusk.",
    giver: "hale_dockhand",
    turnIn: "hale_dockhand",
    objectives: [{ id: "collect_tusk", kind: "collect", item: "grubjaw_tusk", count: 1 }],
    rewards: { xp: { amount: 1700 }, economy: { copper: 700 } },
  },
  {
    id: "q_widows",
    title: "Silk and Venom",
    description: "Widow venom is the only thing that draws fen-rot from a wound, and the thicket west of the road has gone from nuisance to horror.\nKill 10 widows and cut 6 venom sacs.",
    giver: "herbalist_yara",
    turnIn: "herbalist_yara",
    objectives: [
      { id: "kill_widows", kind: "kill", target: "mire_widow", count: 10 },
      { id: "collect_venom", kind: "collect", item: "widow_venom_sac", count: 6 },
    ],
    rewards: { xp: { amount: 1200 }, economy: { copper: 450 } },
  },
  {
    id: "q_broodmother",
    title: "The Broodmother",
    description: "Something spins cables thick as a man's wrist over Widow Thicket.\nBurn through 8 more widows and put the old mother down before her clutch opens.",
    giver: "herbalist_yara",
    turnIn: "herbalist_yara",
    requires: ["q_widows"],
    objectives: [
      { id: "kill_widows", kind: "kill", target: "mire_widow", count: 8 },
      { id: "kill_broodmother", kind: "kill", target: "mirefen_broodmother", count: 1 },
    ],
    rewards: { xp: { amount: 1250 }, economy: { copper: 500 } },
  },
  {
    id: "q_troll_fetishes",
    title: "Fetish and Bone",
    description: "The fetishes planted at the troll mounds are not troll-craft — the bones are man-bones, and every one points at the open barrows.\nBring back 8.",
    giver: "scout_maren",
    turnIn: "scout_maren",
    requires: ["q_trolls"],
    objectives: [{ id: "collect_fetishes", kind: "collect", item: "troll_fetish", count: 8 }],
    rewards: { xp: { amount: 1650 }, economy: { copper: 600 } },
  },
  {
    id: "q_cult_camp",
    title: "Robes in the Reeds",
    description: "Grey robes, grey banners: Gravecallers, camped in the open north past the third lake.\nCut down 12 of their cultists.",
    giver: "scout_maren",
    turnIn: "scout_maren",
    objectives: [{ id: "kill_cultists", kind: "kill", target: "gravecaller_cultist", count: 12 }],
    rewards: { xp: { amount: 1800 }, economy: { copper: 700 } },
  },
  {
    id: "q_olen",
    title: "The Knight-Commander's Shame",
    description: "Knight-Commander Olen held the Sunken Bastion when it sank, drowned at his post rather than abandon it.\nGrant him the rest he earned.",
    giver: "scout_maren",
    turnIn: "scout_maren",
    requires: ["q_bastion_door"],
    objectives: [{ id: "kill_olen", kind: "kill", target: "knight_commander_olen", count: 1 }],
    rewards: { xp: { amount: 1800 }, economy: { copper: 800 } },
  },
  {
    id: "q_idols",
    title: "Idols of the Deep",
    description: "The fish-men dredge idols from the lake bottom and clutch them like holy relics.\nTake 5 from the Deepfen snappers.",
    giver: "brother_aldric_fen",
    turnIn: "brother_aldric_fen",
    requires: ["q_deepfen"],
    objectives: [{ id: "collect_idols", kind: "collect", item: "waterlogged_idol", count: 5 }],
    rewards: { xp: { amount: 1050 }, economy: { copper: 400 } },
  },
  {
    id: "q_drowned",
    title: "The Drowned Dead",
    description: "Travelers drowned on the causeway are walking out of the lakes, still hung with the weeds they died in.\nReturn 12 of the Drowned Dead to their rest.",
    giver: "brother_aldric_fen",
    turnIn: "brother_aldric_fen",
    objectives: [{ id: "kill_drowned", kind: "kill", target: "drowned_dead", count: 12 }],
    rewards: { xp: { amount: 1400 }, economy: { copper: 500 } },
  },
  {
    id: "q_drowned_censers",
    title: "Censers from the Deep",
    description: "A chapel drowned with its congregation when the marsh rose, and its dead carry marks of a Gravecaller rite.\nRecover 4 tokens from the chapel yard's drowned.",
    giver: "brother_aldric_fen",
    turnIn: "brother_aldric_fen",
    requires: ["q_drowned"],
    objectives: [{ id: "collect_fetish", kind: "collect", item: "cracked_fetish", count: 4 }],
    rewards: { xp: { amount: 1300 }, economy: { copper: 500 } },
  },
  {
    id: "q_no_rest",
    title: "No Rest in the Reeds",
    description: "The rite binds the drowned to rise wherever the marsh touches, and the marsh touches everything.\nLay 14 more of the Drowned Dead to rest.",
    giver: "brother_aldric_fen",
    turnIn: "brother_aldric_fen",
    requires: ["q_drowned_censers"],
    objectives: [{ id: "kill_drowned", kind: "kill", target: "drowned_dead", count: 14 }],
    rewards: { xp: { amount: 1500 }, economy: { copper: 550 } },
  },
  {
    id: "q_summoners",
    title: "Stopping the Summoning",
    description: "Summoners among the cultists call the drowned up out of the water like hounds to a whistle.\nSilence 8 summoners and bring back 4 of their ciphers.",
    giver: "brother_aldric_fen",
    turnIn: "brother_aldric_fen",
    requires: ["q_cult_camp"],
    objectives: [
      { id: "kill_summoners", kind: "kill", target: "gravecaller_summoner", count: 8 },
      { id: "collect_ciphers", kind: "collect", item: "cult_cipher", count: 4 },
    ],
    rewards: { xp: { amount: 1900 }, economy: { copper: 750 } },
  },
  {
    id: "q_bastion_door",
    title: "The Sunken Bastion",
    description: "The Sunken Bastion's door is warded by grave-stones, and its revenants stand sentinel.\nBreak six of them to unweave the seal.",
    giver: "brother_aldric_fen",
    turnIn: "brother_aldric_fen",
    requires: ["q_deacon"],
    objectives: [{ id: "kill_revenants", kind: "kill", target: "bastion_revenant", count: 6 }],
    rewards: { xp: { amount: 1200 }, economy: { copper: 500 } },
  },
  {
    id: "q_mistcaller",
    title: "The Fogbinder",
    description: "At the bottom of the Bastion waits Vael the Fogbinder, Morthen's master, the voice that has drowned a hundred travelers to raise itself an army.\nTake four companions and end him.",
    giver: "brother_aldric_fen",
    turnIn: "brother_aldric_fen",
    requires: ["q_bastion_door"],
    objectives: [{ id: "kill_vael", kind: "kill", target: "vael_the_mistcaller", count: 1 }],
    rewards: { xp: { amount: 2800 }, economy: { copper: 2500 } },
  },
  {
    id: "q_highwatch_summons",
    title: "The Watch on the Peaks",
    description: "Vael's last words have not faded: the Wyrm stirs beneath the peaks.\nProve yourself on the mountain road before presenting Aldric's word to Captain Thessaly.",
    giver: "brother_aldric_fen",
    turnIn: "captain_thessaly",
    objectives: [{ id: "kill_stalkers", kind: "kill", target: "ridge_stalker", count: 3 }],
    rewards: { xp: { amount: 500 }, economy: { copper: 500 } },
  },
  {
    id: "q_stalkers",
    title: "Stalkers on the Ridge",
    description: "Ridge cats have come down from the high snows hungry, and the patrols bleed for it.\nThin them, twelve to start.",
    giver: "captain_thessaly",
    turnIn: "captain_thessaly",
    objectives: [{ id: "kill_stalkers", kind: "kill", target: "ridge_stalker", count: 12 }],
    rewards: { xp: { amount: 2200 }, economy: { copper: 1000 } },
  },
  {
    id: "q_stalkers_return",
    title: "The Stalkers Return",
    description: "The ridge crawls thicker than before — something is pushing the stalkers down.\nFourteen more, until the culling reveals what.",
    giver: "captain_thessaly",
    turnIn: "captain_thessaly",
    requires: ["q_stalkers"],
    objectives: [{ id: "kill_stalkers", kind: "kill", target: "ridge_stalker", count: 14 }],
    rewards: { xp: { amount: 2400 }, economy: { copper: 1100 } },
  },
  {
    id: "q_old_cragmaw",
    title: "Old Cragmaw",
    description: "Old Cragmaw is a scar-pelted tyrant of a cat that has outlived three generations of its own pack, denning on the western ridge.\nBring a friend and put the old devil down.",
    giver: "captain_thessaly",
    turnIn: "captain_thessaly",
    requires: ["q_stalkers_return"],
    objectives: [{ id: "kill_cragmaw", kind: "kill", target: "old_cragmaw", count: 1 }],
    rewards: { xp: { amount: 2700 }, economy: { copper: 1500 } },
  },
  {
    id: "q_ogre_bounty",
    title: "The Captain's Bounty",
    description: "The clans are bought, and the wall is their first errand.\nFourteen more Thornpeak Ogres, and bounty paid on every one.",
    giver: "captain_thessaly",
    turnIn: "captain_thessaly",
    requires: ["q_ogre_totems"],
    objectives: [{ id: "kill_ogres", kind: "kill", target: "thornpeak_ogre", count: 14 }],
    rewards: { xp: { amount: 3000 }, economy: { copper: 1500 } },
  },
  {
    id: "q_crushers",
    title: "Break the War-Camp",
    description: "Warlord Drogmar's crushers are the spine of his war-camp, each worth three ordinary soldiers.\nBreak ten crushers and the muster breaks with them.",
    giver: "captain_thessaly",
    turnIn: "captain_thessaly",
    objectives: [{ id: "kill_crushers", kind: "kill", target: "ogre_crusher", count: 10 }],
    rewards: { xp: { amount: 3600 }, economy: { copper: 2000 } },
  },
  {
    id: "q_drogmar",
    title: "Warlord Drogmar",
    description: "Warlord Drogmar took the Wyrmcult's coin and swore the clans to the mountain's waking.\nEnd him, for Highwatch.",
    giver: "captain_thessaly",
    turnIn: "captain_thessaly",
    requires: ["q_crushers"],
    objectives: [{ id: "kill_drogmar", kind: "kill", target: "warlord_drogmar", count: 1 }],
    rewards: { xp: { amount: 4000 }, economy: { copper: 2500 } },
  },
  {
    id: "q_revenants",
    title: "The Revenant Fields",
    description: "The cult has called up an old battlefield east of the Sanctum road, bones in rusted plate.\nPut twelve revenants back in the ground.",
    giver: "captain_thessaly",
    turnIn: "captain_thessaly",
    objectives: [{ id: "kill_revenants", kind: "kill", target: "boneclad_revenant", count: 12 }],
    rewards: { xp: { amount: 4300 }, economy: { copper: 2200 } },
  },
  {
    id: "q_revenant_vanguard",
    title: "Bones of the Vanguard",
    description: "The revenants are forming true ranks, drilling with no drummer, mustering for the Sanctum gate.\nBreak fourteen more before that march begins.",
    giver: "captain_thessaly",
    turnIn: "captain_thessaly",
    requires: ["q_revenants"],
    objectives: [{ id: "kill_revenants", kind: "kill", target: "boneclad_revenant", count: 14 }],
    rewards: { xp: { amount: 4500 }, economy: { copper: 2400 } },
  },
  {
    id: "q_stalker_pelts",
    title: "Winter Is Coming to Highwatch",
    description: "Winter on this mountain does not knock, it kicks the door in.\nEight ridge stalker pelts will line enough cloaks to see the wall through the first snows.",
    giver: "bree_clerk",
    turnIn: "bree_clerk",
    objectives: [{ id: "collect_pelts", kind: "collect", item: "ridge_stalker_pelt", count: 8 }],
    rewards: { xp: { amount: 2300 }, economy: { copper: 1000 } },
  },
  {
    id: "q_stalker_cloaks",
    title: "Cloaks for the Watch",
    description: "Every soldier on the wall wants a lined cloak now, and winter takes fingers first.\nTen more pelts from the ridges south of the gate.",
    giver: "bree_clerk",
    turnIn: "bree_clerk",
    requires: ["q_stalker_pelts"],
    objectives: [{ id: "collect_pelts", kind: "collect", item: "ridge_stalker_pelt", count: 10 }],
    rewards: { xp: { amount: 2400 }, economy: { copper: 1200 } },
  },
  {
    id: "q_glowing_wax",
    title: "Strange Wax",
    description: "A lump of wax taken off a Deeprock Tunneler glows and is warm as a heartbeat.\nBring back six lumps of the glowing wax for study.",
    giver: "bree_clerk",
    turnIn: "bree_clerk",
    requires: ["q_kobold_tunnels"],
    objectives: [{ id: "collect_wax", kind: "collect", item: "glowing_wax", count: 6 }],
    rewards: { xp: { amount: 2500 }, economy: { copper: 1200 } },
  },
  {
    id: "q_ogre_edges",
    title: "Ogres at the Foothills",
    description: "The Thornpeak clans never come this far east, yet here they are, camped in the eastern foothills with war paint on.\nCut twelve of them down.",
    giver: "scout_maren_highwatch",
    turnIn: "scout_maren_highwatch",
    objectives: [{ id: "kill_ogres", kind: "kill", target: "thornpeak_ogre", count: 12 }],
    rewards: { xp: { amount: 2900 }, economy: { copper: 1400 } },
  },
  {
    id: "q_ogre_totems",
    title: "Totems of War",
    description: "Around the war-camp the ogres have raised crude totems marking a muster, not a raid.\nTear through the crushers guarding them: six down.",
    giver: "scout_maren_highwatch",
    turnIn: "scout_maren_highwatch",
    requires: ["q_ogre_edges"],
    objectives: [{ id: "kill_crushers", kind: "kill", target: "ogre_crusher", count: 6 }],
    rewards: { xp: { amount: 2800 }, economy: { copper: 1400 } },
  },
  {
    id: "q_korgath",
    title: "The Bound Guardian",
    description: "Korgath is an ogre champion chained at the Sanctum's mouth, fed on rage for longer than anyone alive.\nTake four companions and put him down.",
    giver: "scout_maren_highwatch",
    turnIn: "scout_maren_highwatch",
    requires: ["q_sanctum_gate"],
    objectives: [{ id: "kill_korgath", kind: "kill", target: "korgath_the_bound", count: 1 }],
    rewards: { xp: { amount: 4200 }, economy: { copper: 2500 } },
  },
  {
    id: "q_kobold_tunnels",
    title: "Deeprock Trouble",
    description: "The tunnelers at Deeprock Burrows are digging straight down, as if something were calling them, beneath the wall.\nCollapse the matter: kill twelve.",
    giver: "loremaster_caddis",
    turnIn: "loremaster_caddis",
    objectives: [{ id: "kill_tunnelers", kind: "kill", target: "deeprock_kobold", count: 12 }],
    rewards: { xp: { amount: 2500 }, economy: { copper: 1200 } },
  },
  {
    id: "q_elementals",
    title: "The Mountain Wakes",
    description: "Stormcrag has stood silent a thousand years, and now its very stones get up and walk.\nPut twelve elementals down so the disturbance may be studied.",
    giver: "loremaster_caddis",
    turnIn: "loremaster_caddis",
    objectives: [{ id: "kill_elementals", kind: "kill", target: "stormcrag_elemental", count: 12 }],
    rewards: { xp: { amount: 3600 }, economy: { copper: 1800 } },
  },
  {
    id: "q_shard_cores",
    title: "Cores of the Storm",
    description: "At each elemental's heart sits a storm core, a knot of lightning bound in stone.\nSix of them will show where the disturbance is centered.",
    giver: "loremaster_caddis",
    turnIn: "loremaster_caddis",
    requires: ["q_elementals"],
    objectives: [{ id: "collect_cores", kind: "collect", item: "storm_core", count: 6 }],
    rewards: { xp: { amount: 3700 }, economy: { copper: 1800 } },
  },
  {
    id: "q_kazzix",
    title: "The Shardlord",
    description: "Among the elementals one burns brighter than the rest: Shardlord Kazzix, a storm given shoulders, walking the far crags west of Stormcrag.\nWrench its heartshard free.",
    giver: "loremaster_caddis",
    turnIn: "loremaster_caddis",
    objectives: [{ id: "collect_heartshard", kind: "collect", item: "kazzix_heartshard", count: 1 }],
    rewards: { xp: { amount: 3800 }, economy: { copper: 2000 } },
  },
  {
    id: "q_zealots",
    title: "Chants on the Wind",
    description: "The Wyrmcult no longer hides — they have raised tents below the Sanctum and sing to what sleeps beneath it.\nSilence twelve zealots.",
    giver: "brother_aldric_highwatch",
    turnIn: "brother_aldric_highwatch",
    objectives: [{ id: "kill_zealots", kind: "kill", target: "wyrmcult_zealot", count: 12 }],
    rewards: { xp: { amount: 4000 }, economy: { copper: 2000 } },
  },
  {
    id: "q_cult_orders",
    title: "Orders from Below",
    description: "The zealots move with purpose now, like soldiers before a siege.\nKill eight more and bring back four sets of their written orders.",
    giver: "brother_aldric_highwatch",
    turnIn: "brother_aldric_highwatch",
    requires: ["q_zealots"],
    objectives: [
      { id: "kill_zealots", kind: "kill", target: "wyrmcult_zealot", count: 8 },
      { id: "collect_orders", kind: "collect", item: "wyrmcult_orders", count: 4 },
    ],
    rewards: { xp: { amount: 3800 }, economy: { copper: 1800 } },
  },
  {
    id: "q_necromancers",
    title: "The Phylactery Ring",
    description: "The orders speak of a ring of phylacteries set about the Sanctum to feed it, carried by the cult's necromancers.\nKill eight and bring back three unbroken.",
    giver: "brother_aldric_highwatch",
    turnIn: "brother_aldric_highwatch",
    requires: ["q_cult_orders"],
    objectives: [
      { id: "kill_necromancers", kind: "kill", target: "wyrmcult_necromancer", count: 8 },
      { id: "collect_phylacteries", kind: "collect", item: "ritual_phylactery", count: 3 },
    ],
    rewards: { xp: { amount: 4200 }, economy: { copper: 2200 } },
  },
  {
    id: "q_wyrm_sigils",
    title: "Sigils of the Wyrm",
    description: "The Gravecallers serve Korzul the Gravewyrm, sealed beneath the mountain, and the zealots on the Sanctum Approach carry tokens of the waking rite.\nBring back three.",
    giver: "brother_aldric_highwatch",
    turnIn: "brother_aldric_highwatch",
    requires: ["q_necromancers"],
    objectives: [{ id: "collect_sigils", kind: "collect", item: "frayed_prayer_beads", count: 3 }],
    rewards: { xp: { amount: 3600 }, economy: { copper: 2000 } },
  },
  {
    id: "q_breaking_the_seal",
    title: "Breaking the Seal",
    description: "The seal on the Sanctum was wrought with mountain-fire, and only mountain-fire will let anyone pass without tearing it wide open.\nThe stormcrag elementals carry embers of that first forging: bring back five.",
    giver: "brother_aldric_highwatch",
    turnIn: "brother_aldric_highwatch",
    requires: ["q_wyrm_sigils"],
    objectives: [{ id: "collect_embers", kind: "collect", item: "blessed_embers", count: 5 }],
    rewards: { xp: { amount: 4200 }, economy: { copper: 2200 } },
  },
  {
    id: "q_voice_below",
    title: "The Voice Below",
    description: "The whole cult camp knelt at once, facing the Sanctum — Korzul speaks to them in their sleep now.\nCut down the congregation: ten zealots, six necromancers.",
    giver: "brother_aldric_highwatch",
    turnIn: "brother_aldric_highwatch",
    requires: ["q_breaking_the_seal"],
    objectives: [
      { id: "kill_zealots", kind: "kill", target: "wyrmcult_zealot", count: 10 },
      { id: "kill_necromancers", kind: "kill", target: "wyrmcult_necromancer", count: 6 },
    ],
    rewards: { xp: { amount: 4400 }, economy: { copper: 2400 } },
  },
  {
    id: "q_sanctum_gate",
    title: "The Sanctum Gate",
    description: "The gate of the Gravewyrm Sanctum was shattered into shards rather than see it turned against the cult, scattered in the gate plaza under the eyes of the boneclad dead.\nBring back three.",
    giver: "brother_aldric_highwatch",
    turnIn: "brother_aldric_highwatch",
    requires: ["q_voice_below"],
    objectives: [{ id: "collect_shards", kind: "collect", item: "bone_fragments", count: 3 }],
    rewards: { xp: { amount: 4000 }, economy: { copper: 2000 } },
  },
  {
    id: "q_velkhar",
    title: "The Grand Necromancer",
    description: "Grand Necromancer Velkhar, first of the Gravecallers, stands in the ritual vault below, pouring stolen souls into the Wyrm.\nEnd him, and the tithe ends with him.",
    giver: "brother_aldric_highwatch",
    turnIn: "brother_aldric_highwatch",
    requires: ["q_sanctum_gate"],
    objectives: [{ id: "kill_velkhar", kind: "kill", target: "grand_necromancer_velkhar", count: 1 }],
    rewards: { xp: { amount: 4500 }, economy: { copper: 3000 } },
  },
  {
    id: "q_gravewyrm",
    title: "Korzul the Gravewyrm",
    description: "The Wyrm itself lies half-woken in its hollow, gorged on the dead of the Vale and the fen.\nTake companions into the Wyrm's Hollow and finish what began in a chapel yard so long ago.",
    giver: "brother_aldric_highwatch",
    turnIn: "brother_aldric_highwatch",
    requires: ["q_sanctum_gate"],
    objectives: [{ id: "kill_korzul", kind: "kill", target: "korzul_the_gravewyrm", count: 1 }],
    rewards: { xp: { amount: 5300 }, economy: { copper: 25000 } },
  },
  {
    id: "q_nythraxis_restless_dead",
    title: "Unrest in the Bonefields",
    description: "The dead no longer wander aimlessly — they gather and march through the northern bonefields beyond Highwatch.\nBring back proof of what is driving the Boneclad Revenants.",
    giver: "brother_aldric_highwatch",
    turnIn: "brother_aldric_highwatch",
    objectives: [{ id: "collect_shards", kind: "collect", item: "runed_bone_shard", count: 10 }],
    rewards: { xp: { amount: 4200 }, economy: { copper: 2000 } },
  },
  {
    id: "q_nythraxis_graves",
    title: "Graves of the Forgotten",
    description: "Three risen champions guard old graves around the northern battlefield: Captain Aldren, High Priest Malric, Royal Assassin Voss.\nBreak all three and learn what they remember.",
    giver: "brother_aldric_highwatch",
    turnIn: "brother_aldric_highwatch",
    requires: ["q_nythraxis_restless_dead"],
    objectives: [
      { id: "kill_aldren", kind: "kill", target: "fallen_captain_aldren", count: 1 },
      { id: "kill_malric", kind: "kill", target: "corrupted_priest_malric", count: 1 },
      { id: "kill_voss", kind: "kill", target: "deathstalker_voss", count: 1 },
    ],
    rewards: { xp: { amount: 4300 }, economy: { copper: 2200 } },
  },
  {
    id: "q_nythraxis_sealed_crypt",
    title: "The Abandoned Crypt",
    description: "The visions point to the abandoned crypt in the western cliff, where a keystone and a diary name the signet of King Nythraxis.\nRecover all three relics.",
    giver: "brother_aldric_highwatch",
    turnIn: "brother_aldric_highwatch",
    requires: ["q_nythraxis_graves"],
    objectives: [
      { id: "collect_crest", kind: "collect", item: "captains_crest", count: 1 },
      { id: "collect_sigil", kind: "collect", item: "priests_sigil", count: 1 },
      { id: "collect_seal", kind: "collect", item: "royal_seal", count: 1 },
    ],
    rewards: { xp: { amount: 4600 }, economy: { copper: 2500 } },
  },
  {
    id: "q_nythraxis_bound_guardian",
    title: "The Bound Guardian",
    description: "The King's Signet was sealed behind an ancient guardian so no one could reach the tomb of Nythraxis by accident or ambition.\nBreak the guardian and bring back the signet.",
    giver: "brother_aldric_highwatch",
    turnIn: "brother_aldric_highwatch",
    requires: ["q_nythraxis_sealed_crypt"],
    objectives: [
      { id: "kill_guardian", kind: "kill", target: "bound_guardian", count: 1 },
      { id: "collect_signet", kind: "collect", item: "kings_signet", count: 1 },
    ],
    rewards: { xp: { amount: 5200 }, economy: { copper: 3500 } },
  },
  {
    id: "q_nythraxis_scourges_end",
    title: "Scourge's End",
    description: "Nythraxis was a king once, and the ruin beneath Thornpeak is still bound to his will.\nEnter the crypt with allies you trust and break the deathless crown.",
    giver: "brother_aldric_highwatch",
    turnIn: "brother_aldric_highwatch",
    requires: ["q_nythraxis_bound_guardian"],
    objectives: [{ id: "kill_nythraxis", kind: "kill", target: "nythraxis_scourge_of_thornpeak", count: 1 }],
    rewards: { economy: { copper: 25000 } },
  },
];
