import type { QuestDef } from "@jgengine/core/game/quest";

export const QUESTS: readonly QuestDef[] = [
  {
    id: "wolves_at_the_door",
    title: "Wolves at the Door",
    description: "Forest wolves harry the north road out of Eastbrook.\nThin their numbers before they take another traveler.",
    giver: "marshal_redbrook",
    turnIn: "marshal_redbrook",
    objectives: [{ id: "kill_wolves", kind: "kill", target: "forest_wolf", count: 8 }],
    rewards: { xp: { amount: 250 }, economy: { copper: 75 } },
  },
  {
    id: "wolf_fang_bounty",
    title: "Fang Bounty",
    description: "Wolf fangs fetch coin from traders up the northern road.\nBring six intact fangs.",
    giver: "marshal_redbrook",
    turnIn: "marshal_redbrook",
    objectives: [{ id: "collect_fangs", kind: "collect", item: "wolf_fang", count: 6 }],
    rewards: { xp: { amount: 280 }, economy: { copper: 90 } },
  },
  {
    id: "boar_cull",
    title: "Boar Cull",
    description: "Wild boars are trampling the eastern meadow crops.\nCull the herd before harvest is lost.",
    giver: "marshal_redbrook",
    turnIn: "marshal_redbrook",
    objectives: [{ id: "kill_boars", kind: "kill", target: "wild_boar", count: 10 }],
    rewards: { xp: { amount: 320 }, economy: { copper: 110 } },
  },
  {
    id: "bristly_boar_hides",
    title: "Bristly Boar Hides",
    description: "Boar hide makes the finest travel packs.\nBring five bristly hides and it will be worth your time.",
    giver: "marshal_redbrook",
    turnIn: "marshal_redbrook",
    objectives: [{ id: "collect_hides", kind: "collect", item: "boar_hide", count: 5 }],
    rewards: { xp: { amount: 350 }, economy: { copper: 120 } },
  },
  {
    id: "teeth_of_the_fen",
    title: "Teeth of the Fen",
    description: "Mire prowlers have learned what a supply mule sounds like.\nThin them out before they take the causeway.",
    giver: "warden_fenwick",
    turnIn: "warden_fenwick",
    objectives: [{ id: "kill_prowlers", kind: "kill", target: "mire_prowler", count: 12 }],
    rewards: { xp: { amount: 800 }, economy: { copper: 300 } },
  },
  {
    id: "pelts_for_the_causeway",
    title: "Pelts for the Causeway",
    description: "Oiled prowler hide is the only thing the rot won't chew through.\nBring eight unspoiled pelts.",
    giver: "warden_fenwick",
    turnIn: "warden_fenwick",
    objectives: [{ id: "collect_pelts", kind: "collect", item: "mire_prowler_pelt", count: 8 }],
    rewards: { xp: { amount: 850 }, economy: { copper: 320 } },
  },
  {
    id: "mirefen_widows",
    title: "Mirefen Widows",
    description: "Widow spiders choke the western thicket in webs thick as sailcloth.\nCull their numbers.",
    giver: "warden_fenwick",
    turnIn: "warden_fenwick",
    objectives: [{ id: "kill_widows", kind: "kill", target: "mire_widow", count: 10 }],
    rewards: { xp: { amount: 780 }, economy: { copper: 280 } },
  },
  {
    id: "venom_for_the_apothecary",
    title: "Venom for the Apothecary",
    description: "Venom sacs steady the fever draughts brewed at Fenbridge.\nBring six sacs, unruptured.",
    giver: "warden_fenwick",
    turnIn: "warden_fenwick",
    objectives: [{ id: "collect_venom", kind: "collect", item: "widow_venom_sac", count: 6 }],
    rewards: { xp: { amount: 820 }, economy: { copper: 300 } },
  },
  {
    id: "ridge_stalkers",
    title: "Ridge Stalkers",
    description: "Ridge stalkers prowl the switchback trail above Highwatch.\nDrive them back from the wall.",
    giver: "captain_thessaly",
    turnIn: "captain_thessaly",
    objectives: [{ id: "kill_stalkers", kind: "kill", target: "ridge_stalker", count: 10 }],
    rewards: { xp: { amount: 1400 }, economy: { copper: 450 } },
  },
  {
    id: "stalker_pelts",
    title: "Stalker Pelts",
    description: "Stalker hide makes the warmest cloaks this side of the peaks.\nBring eight pelts.",
    giver: "captain_thessaly",
    turnIn: "captain_thessaly",
    objectives: [{ id: "collect_stalker_pelts", kind: "collect", item: "ridge_stalker_pelt", count: 8 }],
    rewards: { xp: { amount: 1450 }, economy: { copper: 470 } },
  },
  {
    id: "deeprock_tunnelers",
    title: "Deeprock Tunnelers",
    description: "Deeprock tunnelers riddle the mountain's roots below Highwatch.\nClear them out before the wall undermines itself.",
    giver: "captain_thessaly",
    turnIn: "captain_thessaly",
    objectives: [{ id: "kill_kobolds", kind: "kill", target: "deeprock_kobold", count: 10 }],
    rewards: { xp: { amount: 1500 }, economy: { copper: 500 } },
  },
  {
    id: "glowing_wax",
    title: "Glowing Wax",
    description: "Deeprock wax burns steady even in mountain wind.\nBring six lumps for the watch fires.",
    giver: "captain_thessaly",
    turnIn: "captain_thessaly",
    objectives: [{ id: "collect_wax", kind: "collect", item: "glowing_wax", count: 6 }],
    rewards: { xp: { amount: 1550 }, economy: { copper: 520 } },
  },
  {
    id: "the_restless_dead",
    title: "The Restless Dead",
    description: "The old chapel yard was a resting place once.\nSomething has stirred the dead from their sleep — return them to it.",
    giver: "brother_aldric",
    turnIn: "brother_aldric",
    objectives: [{ id: "kill_bones", kind: "kill", target: "restless_bones", count: 8 }],
    rewards: { xp: { amount: 700 }, economy: { copper: 260 }, quests: ["whispers_below"] },
  },
  {
    id: "whispers_below",
    title: "Whispers Below",
    description: "The dead will not stay resting — something calls them back.\nSearch the chapel ruin for the sigil of whoever is calling.",
    giver: "brother_aldric",
    turnIn: "brother_aldric",
    requires: ["the_restless_dead"],
    objectives: [{ id: "collect_sigil", kind: "collect", item: "gravecaller_sigil", count: 1 }],
    rewards: { xp: { amount: 400 }, economy: { copper: 150 }, quests: ["the_binding_rite"] },
  },
  {
    id: "the_binding_rite",
    title: "The Binding Rite",
    description: "The crypt beneath the chapel must be unsealed to end this.\nGather blessed tallow and ghostly essence for the binding rite.",
    giver: "brother_aldric",
    turnIn: "brother_aldric",
    requires: ["whispers_below"],
    objectives: [
      { id: "collect_wax", kind: "collect", item: "blessed_wax", count: 4 },
      { id: "collect_essence", kind: "collect", item: "ghostly_essence", count: 6 },
    ],
    rewards: { xp: { amount: 700 }, economy: { copper: 500 }, quests: ["into_the_hollow"] },
  },
  {
    id: "into_the_hollow",
    title: "Into the Hollow",
    description: "Morthen the Gravecaller waits at the bottom of the Hollow Crypt.\nEnd him, and the Vale's dead will finally sleep.",
    giver: "brother_aldric",
    turnIn: "brother_aldric",
    requires: ["the_binding_rite"],
    objectives: [{ id: "kill_morthen", kind: "kill", target: "morthen", count: 1 }],
    rewards: { xp: { amount: 3000 }, economy: { copper: 15000 } },
  },
];
