import { defineKeyedStore } from "@jgengine/core/store/defineKeyedStore";
export const classStore = defineKeyedStore((userId) => `class:${userId}`, null);
export const equipStore = defineKeyedStore((userId) => `equip:${userId}`, () => ({}));
export const deadStore = defineKeyedStore((userId) => `dead:${userId}`, false);
export const castStore = defineKeyedStore((userId) => `cast:${userId}`, null);
export const panelStore = defineKeyedStore((userId) => `panel:${userId}`, null);
export const shopStore = defineKeyedStore((userId) => `shop:${userId}`, null);
export const dialogueStore = defineKeyedStore((userId) => `dialogue:${userId}`, null);
export const autoAttackStore = defineKeyedStore((userId) => `autoattack:${userId}`, false);
export const aurasStore = defineKeyedStore((instanceId) => `auras:${instanceId}`, () => []);
export const barStore = defineKeyedStore((userId) => `bar:${userId}`, () => []);
export const specStore = defineKeyedStore((userId) => `spec:${userId}`, null);
export const talentsStore = defineKeyedStore((userId) => `talents:${userId}`, null);
export const restedStore = defineKeyedStore((userId) => `rested:${userId}`, 0);
export const bankStore = defineKeyedStore((userId) => `bank:${userId}`, false);
export const professionsStore = defineKeyedStore((userId) => `profs:${userId}`, () => ({ mining: 1, logging: 1, herbalism: 1, fishing: 1, crafting: 1 }));
export const nameStore = defineKeyedStore((userId) => `name:${userId}`, null);
export const cinematicStore = defineKeyedStore((userId) => `cinematic:${userId}`, false);
export const deathStatsStore = defineKeyedStore((userId) => `deathstats:${userId}`, null);
export const corpseStore = defineKeyedStore((userId) => `corpse:${userId}`, null);
export const fishingStore = defineKeyedStore((userId) => `fishing:${userId}`, null);
export const petStore = defineKeyedStore((userId) => `pet:${userId}`, null);
export const yumiStore = defineKeyedStore((userId) => `yumi:${userId}`, null);
export const valeCupStore = defineKeyedStore((userId) => `valecup:${userId}`, null);
export const mailOpenStore = defineKeyedStore((userId) => `mail:${userId}`, false);
export const marketOpenStore = defineKeyedStore((userId) => `market:${userId}`, false);
export const mailViewStore = defineKeyedStore((userId) => `mailView:${userId}`, null);
export const delveStore = defineKeyedStore((userId) => `delve:${userId}`, null);
export const fiestaStore = defineKeyedStore((userId) => `fiesta:${userId}`, null);
export const fiestaRecordStore = defineKeyedStore((userId) => `arenaFiesta:${userId}`, () => ({ wins: 0, losses: 0 }));
