import { buildPuzzle } from "../logic/build";
import type { Puzzle, PuzzleSpec, SizeGroup } from "../logic/types";

const SPECS: readonly PuzzleSpec[] = [
  {
    id: "heart",
    name: "Heart",
    group: "5×5",
    size: 5,
    palette: { H: "#e94b6a" },
    art: [".H.H.", "HHHHH", "HHHHH", ".HHH.", "..H.."],
  },
  {
    id: "cross",
    name: "Cross",
    group: "5×5",
    size: 5,
    palette: { P: "#e23b4e" },
    art: ["..P..", "..P..", "PPPPP", "..P..", "..P.."],
  },
  {
    id: "diamond",
    name: "Diamond",
    group: "5×5",
    size: 5,
    palette: { D: "#38bdf8" },
    art: ["..D..", ".DDD.", "DDDDD", ".DDD.", "..D.."],
  },
  {
    id: "arrow",
    name: "Arrow",
    group: "5×5",
    size: 5,
    palette: { A: "#f59e0b" },
    art: ["..A..", ".AAA.", "AAAAA", "..A..", "..A.."],
  },
  {
    id: "house",
    name: "House",
    group: "5×5",
    size: 5,
    palette: { R: "#c2410c", W: "#fbbf24" },
    art: ["..R..", ".RRR.", "RRRRR", "WW.WW", "WW.WW"],
  },
  {
    id: "ghost",
    name: "Ghost",
    group: "5×5",
    size: 5,
    palette: { G: "#a78bfa", E: "#1e1b2e" },
    art: [".GGG.", "GGGGG", "GEGEG", "GGGGG", "G.G.G"],
  },
  {
    id: "mushroom",
    name: "Mushroom",
    group: "10×10",
    size: 10,
    palette: { C: "#e2495f", S: "#f8fafc", W: "#f5e6c8" },
    art: [
      "...CCCC...",
      "..CCCCCC..",
      ".CCCCCCCC.",
      "CCCCCCCCCC",
      "CCSSCCSSCC",
      ".CCCCCCCC.",
      "...WWWW...",
      "...WWWW...",
      "...WWWW...",
      "..WWWWWW..",
    ],
  },
  {
    id: "rocket",
    name: "Rocket",
    group: "10×10",
    size: 10,
    palette: { R: "#dc2626", W: "#60a5fa", F: "#f59e0b" },
    art: [
      "....RR....",
      "...RRRR...",
      "..RRRRRR..",
      "..RRWWRR..",
      "..RRWWRR..",
      "..RRRRRR..",
      "..RRRRRR..",
      ".RRRRRRRR.",
      "FF.RRRR.FF",
      ".F..FF..F.",
    ],
  },
  {
    id: "anchor",
    name: "Anchor",
    group: "10×10",
    size: 10,
    palette: { A: "#475569" },
    art: [
      "....AA....",
      "...A..A...",
      "...A..A...",
      "....AA....",
      "..AAAAAA..",
      "....AA....",
      "....AA....",
      "A...AA...A",
      "AA.AAAA.AA",
      "AAAAAAAAAA",
    ],
  },
  {
    id: "duck",
    name: "Duck",
    group: "10×10",
    size: 10,
    palette: { D: "#f6c445", B: "#f97316", E: "#1f2937" },
    art: [
      ".....DDD..",
      "....DDDDD.",
      "....DEDDD.",
      "..BBDDDDD.",
      "....DDDDD.",
      "...DDDDDDD",
      "..DDDDDDDD",
      "..DDDDDDDD",
      "...DDDDDD.",
      "....DDDD..",
    ],
  },
  {
    id: "fish",
    name: "Fish",
    group: "10×10",
    size: 10,
    palette: { F: "#22d3ee", T: "#0891b2", E: "#0b1120" },
    art: [
      "..........",
      "...FFFF...",
      "..FFFFFF..",
      ".FFFFFFF.T",
      ".FEFFFFFTT",
      ".FFFFFFFTT",
      ".FFFFFFF.T",
      "..FFFFFF..",
      "...FFFF...",
      "..........",
    ],
  },
  {
    id: "tree",
    name: "Tree",
    group: "10×10",
    size: 10,
    palette: { L: "#22a35a", T: "#7c4a1e" },
    art: [
      "....LL....",
      "...LLLL...",
      "..LLLLLL..",
      ".LLLLLLLL.",
      "LLLLLLLLLL",
      ".LLLLLLLL.",
      "..LLLLLL..",
      "....TT....",
      "....TT....",
      "...TTTT...",
    ],
  },
  {
    id: "camera",
    name: "Camera",
    group: "10×10",
    size: 10,
    palette: { C: "#334155", L: "#38bdf8", F: "#e2e8f0" },
    art: [
      "..........",
      "...FF.....",
      ".CCCCCCCC.",
      ".CCCCCCCC.",
      ".CCCLLCCC.",
      ".CCLLLLCC.",
      ".CCLLLLCC.",
      ".CCCLLCCC.",
      ".CCCCCCCC.",
      "..........",
    ],
  },
  {
    id: "umbrella",
    name: "Umbrella",
    group: "10×10",
    size: 10,
    palette: { U: "#ec4899", H: "#64748b" },
    art: [
      "....UU....",
      "..UUUUUU..",
      ".UUUUUUUU.",
      "UUUUUUUUUU",
      ".....H....",
      ".....H....",
      ".....H....",
      ".....H....",
      "....HH....",
      "...HH.....",
    ],
  },
  {
    id: "butterfly",
    name: "Butterfly",
    group: "15×15",
    size: 15,
    palette: { B: "#8b5cf6", Y: "#f59e0b" },
    art: [
      "..BB.......BB..",
      ".BBBB.....BBBB.",
      "BBBBBB...BBBBBB",
      "BBBBBBB.BBBBBBB",
      "BBBBBBBYBBBBBBB",
      "BBBBBBBYBBBBBBB",
      "BBBBBBBYBBBBBBB",
      ".BBBBBBYBBBBBB.",
      "..BBBBBYBBBBB..",
      ".BBBBBBYBBBBBB.",
      "BBBBBBBYBBBBBBB",
      "BBBBBBBYBBBBBBB",
      "BBBBBB.Y.BBBBBB",
      ".BBBB..Y..BBBB.",
      "..BB.......BB..",
    ],
  },
  {
    id: "sailboat",
    name: "Sailboat",
    group: "15×15",
    size: 15,
    palette: { S: "#f1f5f9", H: "#b45309", W: "#38bdf8" },
    art: [
      ".......S.......",
      ".......SS......",
      ".......SSS.....",
      ".......SSSS....",
      ".......SSSSS...",
      ".......SSSSSS..",
      ".......SSSSSSS.",
      ".......S.......",
      ".HHHHHHHHHHHHH.",
      ".HHHHHHHHHHHHH.",
      "..HHHHHHHHHHH..",
      "...HHHHHHHHH...",
      "....HHHHHHH....",
      "WWWWWWWWWWWWWWW",
      "WWWWWWWWWWWWWWW",
    ],
  },
  {
    id: "flower",
    name: "Flower",
    group: "15×15",
    size: 15,
    palette: { P: "#ec4899", C: "#facc15", S: "#22a35a", L: "#16a34a" },
    art: [
      "......PPP......",
      "....PPPPPPP....",
      "...PPPPPPPPP...",
      "...PPPPPPPPP...",
      "..PPPPCCCPPPP..",
      ".PPPPPCCCPPPPP.",
      "PPPPPPCCCPPPPPP",
      "PPPPPPCCCPPPPPP",
      "PPPPPPCCCPPPPPP",
      ".PPPPPCCCPPPPP.",
      "..PPPPCCCPPPP..",
      "......SSS......",
      "......SSS......",
      "..LLLLSSSLLLL..",
      "...LLLSSSLLL...",
    ],
  },
  {
    id: "star",
    name: "Star",
    group: "15×15",
    size: 15,
    palette: { Y: "#facc15" },
    art: [
      ".......Y.......",
      ".......Y.......",
      "......YYY......",
      "......YYY......",
      ".....YYYYY.....",
      "YYYYYYYYYYYYYYY",
      ".YYYYYYYYYYYYY.",
      "..YYYYYYYYYYY..",
      "...YYYYYYYYY...",
      "...YYYYYYYYY...",
      "..YYYY...YYYY..",
      "..YYY.....YYY..",
      ".YYY.......YYY.",
      ".YY.........YY.",
      "Y.............Y",
    ],
  },
  {
    id: "cat",
    name: "Cat",
    group: "15×15",
    size: 15,
    palette: { K: "#52525b", E: "#0f172a", P: "#f472b6" },
    art: [
      "..K.........K..",
      "..KK.......KK..",
      "..KKK.....KKK..",
      "..KKKKKKKKKKK..",
      "..KKKKKKKKKKK..",
      "..KKEKKKKKEKK..",
      "..KKKKKKKKKKK..",
      "..KKKKKPKKKKK..",
      "..KKKKKKKKKKK..",
      "..KKKKKKKKKKK..",
      "..KKKKKKKKKKK..",
      "..KKKKKKKKKKK..",
      "..KKK.KKK.KKK..",
      "..KKK.KKK.KKK..",
      "...............",
    ],
  },
  {
    id: "key",
    name: "Key",
    group: "15×15",
    size: 15,
    palette: { K: "#eab308" },
    art: [
      "...............",
      "....KKKKK......",
      "...KKKKKKK.....",
      "..KKKKKKKKK....",
      "..KKKKKKKKK....",
      "..KKKKKKKKK....",
      "..KKKKKKKKK....",
      "...KKKKKKK.....",
      "....KKKKK......",
      "......KK.......",
      "......KK.......",
      "......KKK......",
      "......KK.......",
      "......KKKK.....",
      "......KK.......",
    ],
  },
];

export const PUZZLES: readonly Puzzle[] = SPECS.map(buildPuzzle);

export const PUZZLE_BY_ID: ReadonlyMap<string, Puzzle> = new Map(
  PUZZLES.map((p) => [p.id, p]),
);

export const SIZE_GROUPS: readonly SizeGroup[] = ["5×5", "10×10", "15×15"];

export function puzzlesInGroup(group: SizeGroup): readonly Puzzle[] {
  return PUZZLES.filter((p) => p.group === group);
}

export function puzzleById(id: string): Puzzle | undefined {
  return PUZZLE_BY_ID.get(id);
}
