import type { ClassDef } from "../../model";

export const DRUID_CLASS: readonly ClassDef[] = [
  {
    id: "druid",
    name: "Druid",
    icon: "leaf",
    color: "#FF7D0A",
    resource: "mana",
    baseHp: 45,
    hpPerLevel: 13,
    baseResource: 95,
    resourcePerLevel: 22,
    baseStats: { str: 15, agi: 15, sta: 17, int: 19, spi: 20, armor: 30 },
    statsPerLevel: { str: 1, agi: 1, sta: 2, int: 2, spi: 2, armor: 6 },
    startWeapon: "gnarled_staff",
    abilities: [
      {
        id: "wrath",
        name: "Wildbolt",
        icon: "leaf",
        school: "nature",
        kind: "damage",
        levelReq: 1,
        cost: 20,
        castTime: 1.5,
        cooldown: 0,
        range: 30,
        base: 14.5,
        perLevel: 2.8,
      },
      {
        id: "healing_touch",
        name: "Wildmend",
        icon: "heart",
        school: "nature",
        kind: "heal",
        levelReq: 1,
        cost: 25,
        castTime: 2.5,
        cooldown: 0,
        range: 30,
        base: 44,
        perLevel: 8.2,
        selfTarget: true,
      },
      {
        id: "mark_of_the_wild",
        name: "Wildward",
        icon: "amulet",
        school: "nature",
        kind: "buff",
        levelReq: 1,
        cost: 20,
        castTime: 0,
        cooldown: 0,
        range: 30,
        base: 5,
        perLevel: 0,
        duration: 1800,
        selfTarget: true,
      },
      {
        id: "moonfire",
        name: "Lunar Tempest",
        icon: "crystal",
        school: "arcane",
        kind: "dot",
        levelReq: 4,
        cost: 25,
        castTime: 0,
        cooldown: 0,
        range: 30,
        base: 12,
        perLevel: 1.6,
        duration: 9,
        tickInterval: 3,
      },
      {
        id: "rejuvenation",
        name: "Wildbloom",
        icon: "apple",
        school: "nature",
        kind: "hot",
        levelReq: 4,
        cost: 25,
        castTime: 0,
        cooldown: 0,
        range: 30,
        base: 32,
        perLevel: 4.7,
        duration: 12,
        tickInterval: 3,
        selfTarget: true,
      },
      {
        id: "thorns",
        name: "Briarguard",
        icon: "cloak",
        school: "nature",
        kind: "buff",
        levelReq: 6,
        cost: 20,
        castTime: 0,
        cooldown: 0,
        range: 30,
        base: 3,
        perLevel: 0.3,
        duration: 600,
        selfTarget: true,
      },
      {
        id: "entangling_roots",
        name: "Gripping Roots",
        icon: "wood",
        school: "nature",
        kind: "dot",
        levelReq: 8,
        cost: 35,
        castTime: 1.5,
        cooldown: 0,
        range: 30,
        base: 0,
        perLevel: 1.8,
        duration: 12,
        tickInterval: 3,
        cc: { kind: "root", durationSec: 12 },
      },
      {
        id: "bear_form",
        name: "Bruin Form",
        icon: "shield",
        school: "physical",
        kind: "buff",
        levelReq: 10,
        cost: 30,
        castTime: 0,
        cooldown: 0,
        range: 0,
        base: 65,
        perLevel: 0,
        duration: 3600,
        selfTarget: true,
      },
      {
        id: "maul",
        name: "Bonecrush",
        icon: "hammer",
        school: "physical",
        kind: "damage",
        levelReq: 10,
        cost: 15,
        castTime: 0,
        cooldown: 0,
        range: 5,
        base: 18,
        perLevel: 0.5,
      },
      {
        id: "demoralizing_roar",
        name: "Craven Roar",
        icon: "arrowDown",
        school: "physical",
        kind: "buff",
        levelReq: 10,
        cost: 10,
        castTime: 0,
        cooldown: 0,
        range: 0,
        base: 20,
        perLevel: 0.8,
        duration: 20,
        aoeRadius: 8,
        selfTarget: false,
        buffStat: "attackPower",
        buffAmount: -20,
        buffPerLevel: -0.8,
      },
      {
        id: "cat_form",
        name: "Wolf Form",
        icon: "feather",
        school: "physical",
        kind: "buff",
        levelReq: 12,
        cost: 30,
        castTime: 0,
        cooldown: 0,
        range: 0,
        base: 71,
        perLevel: 0,
        duration: 3600,
        selfTarget: true,
      },
      {
        id: "prowl",
        name: "Stalk",
        icon: "eye",
        school: "physical",
        kind: "buff",
        levelReq: 12,
        cost: 0,
        castTime: 0,
        cooldown: 0,
        range: 0,
        base: 50,
        perLevel: 0,
        duration: 3600,
        selfTarget: true,
      },
      {
        id: "rake",
        name: "Flense",
        icon: "dagger",
        school: "physical",
        kind: "dot",
        levelReq: 12,
        cost: 35,
        castTime: 0,
        cooldown: 0,
        range: 5,
        base: 30,
        perLevel: 1.0,
        duration: 9,
        tickInterval: 3,
      },
      {
        id: "claw",
        name: "Claw",
        icon: "fist",
        school: "physical",
        kind: "damage",
        levelReq: 12,
        cost: 45,
        castTime: 0,
        cooldown: 0,
        range: 5,
        base: 12,
        perLevel: 0.4,
      },
      {
        id: "regrowth",
        name: "Second Bloom",
        icon: "gem",
        school: "nature",
        kind: "heal",
        levelReq: 14,
        cost: 55,
        castTime: 2.0,
        cooldown: 0,
        range: 30,
        base: 57,
        perLevel: 0,
        selfTarget: true,
      },
      {
        id: "ferocious_bite",
        name: "Gorebite",
        icon: "skull",
        school: "physical",
        kind: "damage",
        levelReq: 14,
        cost: 35,
        castTime: 0,
        cooldown: 0,
        range: 5,
        base: 52,
        perLevel: 0,
      },
      {
        id: "barkskin",
        name: "Oakhide",
        icon: "chestplate",
        school: "nature",
        kind: "buff",
        levelReq: 16,
        cost: 30,
        castTime: 0,
        cooldown: 60,
        range: 0,
        base: 150,
        perLevel: 0,
        duration: 15,
        selfTarget: true,
        buffStat: "armor",
        buffAmount: 150,
        buffPerLevel: 0,
      },
      {
        id: "swipe",
        name: "Sweeping Claws",
        icon: "axe",
        school: "physical",
        kind: "aoe",
        levelReq: 16,
        cost: 20,
        castTime: 0,
        cooldown: 0,
        range: 0,
        base: 13.5,
        perLevel: 0,
        aoeRadius: 5,
      },
      {
        id: "starfire",
        name: "Skyfall",
        icon: "star",
        school: "arcane",
        kind: "damage",
        levelReq: 18,
        cost: 80,
        castTime: 3.0,
        cooldown: 0,
        range: 30,
        base: 96,
        perLevel: 0,
      },
      {
        id: "travel_form",
        name: "Fleet Form",
        icon: "wing",
        school: "nature",
        kind: "buff",
        levelReq: 16,
        cost: 30,
        castTime: 0,
        cooldown: 0,
        range: 0,
        base: 140,
        perLevel: 0,
        duration: 3600,
        selfTarget: true,
      },
      {
        id: "dash",
        name: "Dash",
        icon: "sprint",
        school: "physical",
        kind: "buff",
        levelReq: 18,
        cost: 0,
        castTime: 0,
        cooldown: 60,
        range: 0,
        base: 150,
        perLevel: 0,
        duration: 15,
        selfTarget: true,
      },
      {
        id: "insect_swarm",
        name: "Stinging Swarm",
        icon: "poison",
        school: "nature",
        kind: "dot",
        levelReq: 20,
        cost: 45,
        castTime: 0,
        cooldown: 0,
        range: 30,
        base: 48,
        perLevel: 0,
        duration: 12,
        tickInterval: 3,
      },
      {
        id: "tigers_fury",
        name: "Wolfsblood",
        icon: "buffArrow",
        school: "physical",
        kind: "buff",
        levelReq: 20,
        cost: 30,
        castTime: 0,
        cooldown: 0,
        range: 0,
        base: 40,
        perLevel: 0,
        duration: 6,
        selfTarget: true,
        buffStat: "attackPower",
        buffAmount: 40,
        buffPerLevel: 0,
      },
      {
        id: "rip",
        name: "Rip",
        icon: "debuffArrow",
        school: "physical",
        kind: "dot",
        levelReq: 20,
        cost: 30,
        castTime: 0,
        cooldown: 0,
        range: 5,
        base: 60,
        perLevel: 0,
        duration: 12,
        tickInterval: 2,
      },
      {
        id: "hurricane",
        name: "Hurricane",
        icon: "lightning",
        school: "nature",
        kind: "aoe",
        levelReq: 18,
        cost: 90,
        castTime: 0,
        cooldown: 12,
        range: 30,
        base: 14,
        perLevel: 0,
        aoeRadius: 8,
        duration: 6,
        tickInterval: 1,
      },
      {
        id: "growl",
        name: "Menace",
        icon: "pin",
        school: "physical",
        kind: "buff",
        levelReq: 10,
        cost: 0,
        castTime: 0,
        cooldown: 10,
        range: 8,
        base: 0,
        perLevel: 0,
        selfTarget: true,
        cc: { kind: "taunt", durationSec: 3 },
      },
      {
        id: "bash",
        name: "Concuss",
        icon: "hourglass",
        school: "physical",
        kind: "buff",
        levelReq: 16,
        cost: 10,
        castTime: 0,
        cooldown: 60,
        range: 8,
        base: 0,
        perLevel: 0,
        selfTarget: true,
        cc: { kind: "stun", durationSec: 2 },
      },
      {
        id: "enrage",
        name: "Stoke",
        icon: "fire",
        school: "physical",
        kind: "buff",
        levelReq: 16,
        cost: 0,
        castTime: 0,
        cooldown: 60,
        range: 0,
        base: 0,
        perLevel: 0,
        selfTarget: true,
        selfResource: 20,
      },
      {
        id: "pounce",
        name: "Slinkstrike",
        icon: "boots",
        school: "physical",
        kind: "buff",
        levelReq: 18,
        cost: 50,
        castTime: 0,
        cooldown: 0,
        range: 8,
        base: 0,
        perLevel: 0,
        selfTarget: true,
        cc: { kind: "stun", durationSec: 2 },
      },
      {
        id: "hibernate",
        name: "Slumber",
        icon: "potionBlue",
        school: "nature",
        kind: "buff",
        levelReq: 18,
        cost: 50,
        castTime: 1.5,
        cooldown: 0,
        range: 30,
        base: 0,
        perLevel: 0,
        selfTarget: true,
        cc: { kind: "stun", durationSec: 8 },
      },
    ],
  },
];
