import type { ClassDef } from "../../model";

export const HUNTER_CLASS: readonly ClassDef[] = [
  {
    id: "hunter",
    name: "Hunter",
    icon: "bow",
    color: "#ABD473",
    resource: "mana",
    baseHp: 50,
    hpPerLevel: 15,
    baseResource: 80,
    resourcePerLevel: 18,
    baseStats: { str: 14, agi: 25, sta: 19, int: 13, spi: 14, armor: 45 },
    statsPerLevel: { str: 1, agi: 3, sta: 2, int: 1, spi: 1, armor: 8 },
    startWeapon: "rusty_hatchet",
    abilities: [
      {
        id: "raptor_strike",
        name: "Gutting Strike",
        icon: "axe",
        school: "physical",
        kind: "damage",
        levelReq: 1,
        cost: 15,
        castTime: 0,
        cooldown: 6,
        range: 5,
        base: 5,
        perLevel: 1.2,
      },
      {
        id: "aspect_of_the_hawk",
        name: "Harrier's Guise",
        icon: "wing",
        school: "nature",
        kind: "buff",
        levelReq: 1,
        cost: 20,
        castTime: 0,
        cooldown: 0,
        range: 0,
        base: 20,
        perLevel: 1.7,
        duration: 1800,
        selfTarget: true,
        buffStat: "attackPower",
        buffAmount: 20,
        buffPerLevel: 1.7,
      },
      {
        id: "serpent_sting",
        name: "Venom Barb",
        icon: "poison",
        school: "nature",
        kind: "dot",
        levelReq: 4,
        cost: 15,
        castTime: 0,
        cooldown: 0,
        range: 35,
        base: 20,
        perLevel: 1.9,
        duration: 15,
        tickInterval: 3,
      },
      {
        id: "arcane_shot",
        name: "Fell Shot",
        icon: "arrow",
        school: "arcane",
        kind: "damage",
        levelReq: 6,
        cost: 25,
        castTime: 0,
        cooldown: 6,
        range: 35,
        base: 15,
        perLevel: 1.5,
      },
      {
        id: "concussive_shot",
        name: "Rattling Shot",
        icon: "crossbow",
        school: "physical",
        kind: "damage",
        levelReq: 8,
        cost: 20,
        castTime: 0,
        cooldown: 12,
        range: 35,
        base: 5,
        perLevel: 0,
      },
      {
        id: "mongoose_bite",
        name: "Counterfang",
        icon: "fist",
        school: "physical",
        kind: "damage",
        levelReq: 10,
        cost: 10,
        castTime: 0,
        cooldown: 5,
        range: 5,
        base: 12,
        perLevel: 0.7,
      },
      {
        id: "wing_clip",
        name: "Fettering Slash",
        icon: "boots",
        school: "physical",
        kind: "damage",
        levelReq: 10,
        cost: 20,
        castTime: 0,
        cooldown: 0,
        range: 5,
        base: 4,
        perLevel: 0,
      },
      {
        id: "aspect_of_the_monkey",
        name: "Marten's Guise",
        icon: "leaf",
        school: "nature",
        kind: "buff",
        levelReq: 10,
        cost: 20,
        castTime: 0,
        cooldown: 0,
        range: 0,
        base: 8,
        perLevel: 0,
        duration: 1800,
        selfTarget: true,
      },
      {
        id: "aspect_of_the_cheetah",
        name: "Courser's Guise",
        icon: "sprint",
        school: "nature",
        kind: "buff",
        levelReq: 14,
        cost: 20,
        castTime: 0,
        cooldown: 0,
        range: 0,
        base: 130,
        perLevel: 0,
        duration: 1800,
        selfTarget: true,
      },
      {
        id: "aimed_shot",
        name: "Long Draw",
        icon: "bow",
        school: "physical",
        kind: "damage",
        levelReq: 16,
        cost: 50,
        castTime: 3.0,
        cooldown: 6,
        range: 35,
        base: 56,
        perLevel: 0,
      },
      {
        id: "rapid_fire",
        name: "Fevered Draw",
        icon: "lightning",
        school: "physical",
        kind: "buff",
        levelReq: 20,
        cost: 0,
        castTime: 0,
        cooldown: 300,
        range: 0,
        base: 140,
        perLevel: 0,
        duration: 15,
        selfTarget: true,
      },
      {
        id: "volley",
        name: "Volley",
        icon: "arrowUp",
        school: "physical",
        kind: "aoe",
        levelReq: 18,
        cost: 60,
        castTime: 0,
        cooldown: 8,
        range: 35,
        base: 14,
        perLevel: 0,
        aoeRadius: 8,
        duration: 3,
        tickInterval: 0.5,
      },
      {
        id: "call_pet",
        name: "Call Pet",
        icon: "feather",
        school: "nature",
        kind: "buff",
        levelReq: 1,
        cost: 0,
        castTime: 0,
        cooldown: 5,
        range: 0,
        base: 0,
        perLevel: 0,
        selfTarget: true,
      },
      {
        id: "dismiss_pet",
        name: "Dismiss Pet",
        icon: "cloak",
        school: "nature",
        kind: "buff",
        levelReq: 1,
        cost: 0,
        castTime: 0,
        cooldown: 2,
        range: 0,
        base: 0,
        perLevel: 0,
        selfTarget: true,
      },
      {
        id: "revive_pet",
        name: "Revive Pet",
        icon: "heart",
        school: "nature",
        kind: "buff",
        levelReq: 1,
        cost: 40,
        castTime: 2,
        cooldown: 20,
        range: 0,
        base: 0,
        perLevel: 0,
        selfTarget: true,
      },
    ],
  },
];
