import type { ClassDef } from "../../model";

export const MAGE_CLASS: readonly ClassDef[] = [
  {
    id: "mage",
    name: "Mage",
    icon: "staff",
    color: "#69CCF0",
    resource: "mana",
    baseHp: 40,
    hpPerLevel: 12,
    baseResource: 100,
    resourcePerLevel: 24,
    baseStats: { str: 10, agi: 12, sta: 14, int: 24, spi: 22, armor: 25 },
    statsPerLevel: { str: 0, agi: 0, sta: 1, int: 3, spi: 2, armor: 4 },
    startWeapon: "gnarled_staff",
    abilities: [
      {
        id: "fireball",
        name: "Cinderbolt",
        icon: "fire",
        school: "fire",
        kind: "damage",
        levelReq: 1,
        cost: 30,
        castTime: 1.5,
        cooldown: 0,
        range: 30,
        base: 20.5,
        perLevel: 2.6,
      },
      {
        id: "frost_armor",
        name: "Hoarfrost Mantle",
        icon: "cloak",
        school: "frost",
        kind: "buff",
        levelReq: 1,
        cost: 20,
        castTime: 0,
        cooldown: 0,
        range: 0,
        base: 30,
        perLevel: 2.2,
        duration: 1800,
        selfTarget: true,
        buffStat: "armor",
        buffAmount: 30,
        buffPerLevel: 2.2,
      },
      {
        id: "arcane_intellect",
        name: "Aether Insight",
        icon: "tome",
        school: "arcane",
        kind: "buff",
        levelReq: 1,
        cost: 25,
        castTime: 0,
        cooldown: 0,
        range: 0,
        base: 5,
        perLevel: 0,
        duration: 1800,
        selfTarget: true,
        buffStat: "int",
        buffAmount: 5,
        buffPerLevel: 0,
      },
      {
        id: "frostbolt",
        name: "Rimelance",
        icon: "frost",
        school: "frost",
        kind: "damage",
        levelReq: 4,
        cost: 25,
        castTime: 1.5,
        cooldown: 0,
        range: 30,
        base: 19,
        perLevel: 2.8,
      },
      {
        id: "fire_blast",
        name: "Cinderfall",
        icon: "gem",
        school: "fire",
        kind: "damage",
        levelReq: 6,
        cost: 40,
        castTime: 0,
        cooldown: 8,
        range: 20,
        base: 31,
        perLevel: 2.4,
      },
      {
        id: "arcane_missiles",
        name: "Aether Darts",
        icon: "star",
        school: "arcane",
        kind: "dot",
        levelReq: 8,
        cost: 50,
        castTime: 0,
        cooldown: 0,
        range: 30,
        base: 24,
        perLevel: 2.3,
        duration: 3,
        tickInterval: 1,
      },
      {
        id: "frost_nova",
        name: "Icebind",
        icon: "potionBlue",
        school: "frost",
        kind: "aoe",
        levelReq: 10,
        cost: 35,
        castTime: 0,
        cooldown: 22,
        range: 0,
        base: 6.5,
        perLevel: 0.4,
        aoeRadius: 10,
        duration: 8,
        cc: { kind: "root", durationSec: 8 },
      },
      {
        id: "polymorph",
        name: "Bewitch",
        icon: "hourglass",
        school: "arcane",
        kind: "buff",
        levelReq: 8,
        cost: 50,
        castTime: 1.5,
        cooldown: 0,
        range: 30,
        base: 0,
        perLevel: 0,
        selfTarget: true,
        cc: { kind: "stun", durationSec: 15 },
      },
      {
        id: "arcane_explosion",
        name: "Aetherburst",
        icon: "crystal",
        school: "arcane",
        kind: "aoe",
        levelReq: 14,
        cost: 60,
        castTime: 0,
        cooldown: 0,
        range: 0,
        base: 28.5,
        perLevel: 0,
        aoeRadius: 10,
      },
      {
        id: "scorch",
        name: "Scald",
        icon: "torch",
        school: "fire",
        kind: "damage",
        levelReq: 16,
        cost: 35,
        castTime: 1.5,
        cooldown: 0,
        range: 30,
        base: 36,
        perLevel: 0,
      },
      {
        id: "pyroblast",
        name: "Pyrelance",
        icon: "bomb",
        school: "fire",
        kind: "damage",
        levelReq: 20,
        cost: 125,
        castTime: 6.0,
        cooldown: 0,
        range: 30,
        base: 197.5,
        perLevel: 0,
      },
      {
        id: "ice_barrier",
        name: "Frostveil",
        icon: "shield",
        school: "frost",
        kind: "buff",
        levelReq: 20,
        cost: 90,
        castTime: 0,
        cooldown: 30,
        range: 0,
        base: 130,
        perLevel: 0,
        duration: 60,
        selfTarget: true,
      },
      {
        id: "flamestrike",
        name: "Flamestrike",
        icon: "lightning",
        school: "fire",
        kind: "aoe",
        levelReq: 20,
        cost: 80,
        castTime: 0,
        cooldown: 12,
        range: 30,
        base: 39,
        perLevel: 0,
        aoeRadius: 7,
      },
    ],
  },
];
