import type { ClassDef } from "../../model";

export const PRIEST_CLASS: readonly ClassDef[] = [
  {
    id: "priest",
    name: "Priest",
    icon: "wand",
    color: "#FFFFF0",
    resource: "mana",
    baseHp: 38,
    hpPerLevel: 11,
    baseResource: 110,
    resourcePerLevel: 26,
    baseStats: { str: 10, agi: 11, sta: 13, int: 22, spi: 24, armor: 20 },
    statsPerLevel: { str: 0, agi: 0, sta: 1, int: 2, spi: 3, armor: 4 },
    startWeapon: "gnarled_staff",
    abilities: [
      {
        id: "smite",
        name: "Smite",
        icon: "star",
        school: "holy",
        kind: "damage",
        levelReq: 1,
        cost: 20,
        castTime: 2.0,
        cooldown: 0,
        range: 30,
        base: 17.5,
        perLevel: 3.0,
      },
      {
        id: "lesser_heal",
        name: "Whispered Prayer",
        icon: "feather",
        school: "holy",
        kind: "heal",
        levelReq: 1,
        cost: 30,
        castTime: 2.0,
        cooldown: 0,
        range: 30,
        base: 52.5,
        perLevel: 3.8,
        selfTarget: true,
      },
      {
        id: "power_word_fortitude",
        name: "Litany of Resolve",
        icon: "amulet",
        school: "holy",
        kind: "buff",
        levelReq: 1,
        cost: 30,
        castTime: 0,
        cooldown: 0,
        range: 30,
        base: 5,
        perLevel: 0,
        duration: 1800,
        selfTarget: true,
        buffStat: "sta",
        buffAmount: 5,
        buffPerLevel: 0,
      },
      {
        id: "shadow_word_pain",
        name: "Dirge of Decay",
        icon: "skull",
        school: "shadow",
        kind: "dot",
        levelReq: 4,
        cost: 25,
        castTime: 0,
        cooldown: 0,
        range: 30,
        base: 30,
        perLevel: 3.0,
        duration: 18,
        tickInterval: 3,
      },
      {
        id: "power_word_shield",
        name: "Psalm of Warding",
        icon: "shield",
        school: "holy",
        kind: "buff",
        levelReq: 6,
        cost: 45,
        castTime: 0,
        cooldown: 6,
        range: 30,
        base: 48,
        perLevel: 5.4,
        duration: 30,
        selfTarget: true,
      },
      {
        id: "renew",
        name: "Lingering Grace",
        icon: "leaf",
        school: "holy",
        kind: "hot",
        levelReq: 8,
        cost: 30,
        castTime: 0,
        cooldown: 0,
        range: 30,
        base: 45,
        perLevel: 5.3,
        duration: 15,
        tickInterval: 3,
        selfTarget: true,
      },
      {
        id: "mind_blast",
        name: "Mindfracture",
        icon: "eye",
        school: "shadow",
        kind: "damage",
        levelReq: 10,
        cost: 50,
        castTime: 1.5,
        cooldown: 8,
        range: 30,
        base: 44,
        perLevel: 2.6,
      },
      {
        id: "heal",
        name: "Solemn Prayer",
        icon: "heart",
        school: "holy",
        kind: "heal",
        levelReq: 14,
        cost: 95,
        castTime: 2.5,
        cooldown: 0,
        range: 30,
        base: 180,
        perLevel: 3.9,
        selfTarget: true,
      },
      {
        id: "mind_flay",
        name: "Litany of Woe",
        icon: "hourglass",
        school: "shadow",
        kind: "dot",
        levelReq: 16,
        cost: 45,
        castTime: 0,
        cooldown: 0,
        range: 20,
        base: 36,
        perLevel: 0,
        duration: 3,
        tickInterval: 1,
      },
      {
        id: "flash_heal",
        name: "Urgent Prayer",
        icon: "wing",
        school: "holy",
        kind: "heal",
        levelReq: 20,
        cost: 75,
        castTime: 1.5,
        cooldown: 0,
        range: 30,
        base: 131,
        perLevel: 0,
        selfTarget: true,
      },
    ],
  },
];
