import type { ClassDef } from "../../model";

export const ROGUE_CLASS: readonly ClassDef[] = [
  {
    id: "rogue",
    name: "Rogue",
    icon: "dagger",
    color: "#FFF569",
    resource: "energy",
    baseHp: 45,
    hpPerLevel: 15,
    baseResource: 100,
    resourcePerLevel: 0,
    baseStats: { str: 17, agi: 25, sta: 17, int: 11, spi: 12, armor: 40 },
    statsPerLevel: { str: 1, agi: 3, sta: 1, int: 0, spi: 0, armor: 8 },
    startWeapon: "rusty_dagger",
    abilities: [
      {
        id: "sinister_strike",
        name: "Wicked Slash",
        icon: "dagger",
        school: "physical",
        kind: "damage",
        levelReq: 1,
        cost: 45,
        castTime: 0,
        cooldown: 0,
        range: 5,
        base: 3,
        perLevel: 0.8,
      },
      {
        id: "eviscerate",
        name: "Dirt Nap",
        icon: "gauntlet",
        school: "physical",
        kind: "damage",
        levelReq: 1,
        cost: 35,
        castTime: 0,
        cooldown: 0,
        range: 5,
        base: 25,
        perLevel: 2.4,
      },
      {
        id: "garrote",
        name: "Throat Wire",
        icon: "crosshairIcon",
        school: "physical",
        kind: "dot",
        levelReq: 1,
        cost: 50,
        castTime: 0,
        cooldown: 0,
        range: 5,
        base: 60,
        perLevel: 4.0,
        duration: 18,
        tickInterval: 3,
      },
      {
        id: "backstab",
        name: "Craven Thrust",
        icon: "sword",
        school: "physical",
        kind: "damage",
        levelReq: 4,
        cost: 60,
        castTime: 0,
        cooldown: 0,
        range: 5,
        base: 11,
        perLevel: 1.2,
      },
      {
        id: "gouge",
        name: "Eye Jab",
        icon: "fist",
        school: "physical",
        kind: "damage",
        levelReq: 6,
        cost: 45,
        castTime: 0,
        cooldown: 10,
        range: 5,
        base: 8.5,
        perLevel: 0.4,
      },
      {
        id: "cheap_shot",
        name: "Gut Punch",
        icon: "boots",
        school: "physical",
        kind: "damage",
        levelReq: 8,
        cost: 60,
        castTime: 0,
        cooldown: 0,
        range: 5,
        base: 7,
        perLevel: 0,
      },
      {
        id: "evasion",
        name: "Ghostfoot",
        icon: "cloak",
        school: "physical",
        kind: "buff",
        levelReq: 8,
        cost: 0,
        castTime: 0,
        cooldown: 300,
        range: 0,
        base: 50,
        perLevel: 0,
        duration: 15,
        selfTarget: true,
      },
      {
        id: "slice_and_dice",
        name: "Cutthroat Tempo",
        icon: "buffArrow",
        school: "physical",
        kind: "buff",
        levelReq: 10,
        cost: 25,
        castTime: 0,
        cooldown: 0,
        range: 0,
        base: 130,
        perLevel: 0,
        duration: 9,
        selfTarget: true,
      },
      {
        id: "sprint",
        name: "Swift Heels",
        icon: "sprint",
        school: "physical",
        kind: "buff",
        levelReq: 10,
        cost: 0,
        castTime: 0,
        cooldown: 300,
        range: 0,
        base: 170,
        perLevel: 0,
        duration: 15,
        selfTarget: true,
      },
      {
        id: "crippling_poison",
        name: "Leaden Venom",
        icon: "poison",
        school: "nature",
        kind: "damage",
        levelReq: 12,
        cost: 40,
        castTime: 0,
        cooldown: 0,
        range: 5,
        base: 4,
        perLevel: 0,
      },
      {
        id: "ambush",
        name: "Lurker's Strike",
        icon: "spear",
        school: "physical",
        kind: "damage",
        levelReq: 16,
        cost: 60,
        castTime: 0,
        cooldown: 0,
        range: 5,
        base: 28,
        perLevel: 0,
      },
      {
        id: "rupture",
        name: "Bleed Out",
        icon: "debuffArrow",
        school: "physical",
        kind: "dot",
        levelReq: 16,
        cost: 25,
        castTime: 0,
        cooldown: 0,
        range: 5,
        base: 96,
        perLevel: 0,
        duration: 16,
        tickInterval: 2,
      },
      {
        id: "vanish",
        name: "Smokestep",
        icon: "wing",
        school: "physical",
        kind: "buff",
        levelReq: 18,
        cost: 0,
        castTime: 0,
        cooldown: 300,
        range: 0,
        base: 50,
        perLevel: 0,
        duration: 10,
        selfTarget: true,
      },
      {
        id: "instant_poison",
        name: "Adder's Bite",
        icon: "potionRed",
        school: "nature",
        kind: "buff",
        levelReq: 18,
        cost: 40,
        castTime: 0,
        cooldown: 0,
        range: 0,
        base: 8,
        perLevel: 0,
        duration: 1800,
        selfTarget: true,
      },
      {
        id: "deadly_poison",
        name: "Festering Venom",
        icon: "potionBlue",
        school: "nature",
        kind: "buff",
        levelReq: 20,
        cost: 40,
        castTime: 0,
        cooldown: 0,
        range: 0,
        base: 14,
        perLevel: 0,
        duration: 1800,
        selfTarget: true,
      },
      {
        id: "stealth",
        name: "Duskveil",
        icon: "eye",
        school: "physical",
        kind: "buff",
        levelReq: 2,
        cost: 0,
        castTime: 0,
        cooldown: 10,
        range: 0,
        base: 50,
        perLevel: 0,
        duration: 3600,
        selfTarget: true,
      },
      {
        id: "kidney_shot",
        name: "Low Blow",
        icon: "hourglass",
        school: "physical",
        kind: "buff",
        levelReq: 14,
        cost: 25,
        castTime: 0,
        cooldown: 20,
        range: 0,
        base: 0,
        perLevel: 0,
        selfTarget: true,
        cc: { kind: "stun", durationSec: 4 },
      },
      {
        id: "sap",
        name: "Sap",
        icon: "star",
        school: "physical",
        kind: "buff",
        levelReq: 10,
        cost: 65,
        castTime: 0,
        cooldown: 0,
        range: 0,
        base: 0,
        perLevel: 0,
        selfTarget: true,
        cc: { kind: "stun", durationSec: 8 },
      },
      {
        id: "adrenaline_rush",
        name: "Quickened Blood",
        icon: "lightning",
        school: "physical",
        kind: "buff",
        levelReq: 20,
        cost: 0,
        castTime: 0,
        cooldown: 180,
        range: 0,
        base: 0,
        perLevel: 0,
        selfTarget: true,
        selfResource: 100,
      },
      {
        id: "expose_armor",
        name: "Armor Breach",
        icon: "gear",
        school: "physical",
        kind: "buff",
        levelReq: 14,
        cost: 25,
        castTime: 0,
        cooldown: 0,
        range: 0,
        base: 0,
        perLevel: 0,
        selfTarget: true,
        cc: { kind: "armorShred", durationSec: 30, amount: 170 },
      },
    ],
  },
];
