import type { ClassDef } from "../../model";

export const SHAMAN_CLASS: readonly ClassDef[] = [
  {
    id: "shaman",
    name: "Shaman",
    icon: "lightning",
    color: "#0070DE",
    resource: "mana",
    baseHp: 48,
    hpPerLevel: 15,
    baseResource: 90,
    resourcePerLevel: 22,
    baseStats: { str: 18, agi: 16, sta: 20, int: 18, spi: 18, armor: 40 },
    statsPerLevel: { str: 1, agi: 1, sta: 2, int: 2, spi: 2, armor: 10 },
    startWeapon: "training_mace",
    abilities: [
      {
        id: "lightning_bolt",
        name: "Arc Bolt",
        icon: "lightning",
        school: "nature",
        kind: "damage",
        levelReq: 1,
        cost: 15,
        castTime: 1.5,
        cooldown: 0,
        range: 30,
        base: 16,
        perLevel: 3.6,
      },
      {
        id: "rockbiter_weapon",
        name: "Stonebound Weapon",
        icon: "ore",
        school: "nature",
        kind: "buff",
        levelReq: 1,
        cost: 20,
        castTime: 0,
        cooldown: 0,
        range: 0,
        base: 5,
        perLevel: 0.5,
        duration: 300,
        selfTarget: true,
      },
      {
        id: "healing_wave",
        name: "Mending Waters",
        icon: "heart",
        school: "nature",
        kind: "heal",
        levelReq: 1,
        cost: 25,
        castTime: 1.5,
        cooldown: 0,
        range: 30,
        base: 40,
        perLevel: 6.2,
        selfTarget: true,
      },
      {
        id: "earth_shock",
        name: "Earthen Jolt",
        icon: "stone",
        school: "nature",
        kind: "damage",
        levelReq: 4,
        cost: 30,
        castTime: 0,
        cooldown: 6,
        range: 20,
        base: 20.5,
        perLevel: 2.1,
      },
      {
        id: "lightning_shield",
        name: "Thunder Ward",
        icon: "shield",
        school: "nature",
        kind: "buff",
        levelReq: 8,
        cost: 25,
        castTime: 0,
        cooldown: 0,
        range: 0,
        base: 13,
        perLevel: 0.9,
        duration: 600,
        selfTarget: true,
      },
      {
        id: "flame_shock",
        name: "Cinder Jolt",
        icon: "fire",
        school: "fire",
        kind: "dot",
        levelReq: 10,
        cost: 35,
        castTime: 0,
        cooldown: 6,
        range: 20,
        base: 28,
        perLevel: 1.1,
        duration: 12,
        tickInterval: 3,
      },
      {
        id: "flametongue_weapon",
        name: "Pyrebrand Weapon",
        icon: "torch",
        school: "fire",
        kind: "buff",
        levelReq: 10,
        cost: 25,
        castTime: 0,
        cooldown: 0,
        range: 0,
        base: 8,
        perLevel: 0.3,
        duration: 300,
        selfTarget: true,
      },
      {
        id: "frost_shock",
        name: "Rime Jolt",
        icon: "frost",
        school: "frost",
        kind: "damage",
        levelReq: 14,
        cost: 50,
        castTime: 0,
        cooldown: 6,
        range: 20,
        base: 39,
        perLevel: 0,
      },
      {
        id: "frostbrand_weapon",
        name: "Rimebound Weapon",
        icon: "potionBlue",
        school: "frost",
        kind: "buff",
        levelReq: 12,
        cost: 25,
        castTime: 0,
        cooldown: 0,
        range: 0,
        base: 8,
        perLevel: 0.3,
        duration: 300,
        selfTarget: true,
      },
      {
        id: "ghost_wolf",
        name: "Shadewolf",
        icon: "sprint",
        school: "nature",
        kind: "buff",
        levelReq: 16,
        cost: 35,
        castTime: 2.0,
        cooldown: 0,
        range: 0,
        base: 140,
        perLevel: 0,
        duration: 3600,
        selfTarget: true,
      },
      {
        id: "stormstrike",
        name: "Ancestral Strike",
        icon: "hammer",
        school: "physical",
        kind: "damage",
        levelReq: 20,
        cost: 40,
        castTime: 0,
        cooldown: 12,
        range: 5,
        base: 26,
        perLevel: 0,
      },
      {
        id: "earthquake",
        name: "Earthquake",
        icon: "crystal",
        school: "nature",
        kind: "aoe",
        levelReq: 18,
        cost: 80,
        castTime: 0,
        cooldown: 12,
        range: 30,
        base: 15,
        perLevel: 0,
        aoeRadius: 8,
        duration: 6,
        tickInterval: 1.5,
      },
    ],
  },
];
