import type { ClassDef } from "../../model";

export const WARLOCK_CLASS: readonly ClassDef[] = [
  {
    id: "warlock",
    name: "Warlock",
    icon: "skull",
    color: "#9482C9",
    resource: "mana",
    baseHp: 42,
    hpPerLevel: 12,
    baseResource: 105,
    resourcePerLevel: 25,
    baseStats: { str: 11, agi: 12, sta: 15, int: 21, spi: 21, armor: 22 },
    statsPerLevel: { str: 0, agi: 0, sta: 1, int: 3, spi: 2, armor: 4 },
    startWeapon: "gnarled_staff",
    abilities: [
      {
        id: "shadow_bolt",
        name: "Gloom Bolt",
        icon: "skull",
        school: "shadow",
        kind: "damage",
        levelReq: 1,
        cost: 25,
        castTime: 1.7,
        cooldown: 0,
        range: 30,
        base: 15.5,
        perLevel: 3.4,
      },
      {
        id: "demon_skin",
        name: "Fiendhide",
        icon: "chestplate",
        school: "shadow",
        kind: "buff",
        levelReq: 1,
        cost: 20,
        castTime: 0,
        cooldown: 0,
        range: 0,
        base: 30,
        perLevel: 2.8,
        duration: 1800,
        selfTarget: true,
        buffStat: "armor",
        buffAmount: 30,
        buffPerLevel: 2.8,
      },
      {
        id: "immolate",
        name: "Burning Pact",
        icon: "fire",
        school: "fire",
        kind: "dot",
        levelReq: 1,
        cost: 25,
        castTime: 2.0,
        cooldown: 0,
        range: 30,
        base: 20,
        perLevel: 2.2,
        duration: 15,
        tickInterval: 3,
      },
      {
        id: "corruption",
        name: "Blackrot",
        icon: "poison",
        school: "shadow",
        kind: "dot",
        levelReq: 4,
        cost: 35,
        castTime: 2.0,
        cooldown: 0,
        range: 30,
        base: 40,
        perLevel: 2.5,
        duration: 18,
        tickInterval: 3,
      },
      {
        id: "curse_of_agony",
        name: "Hex of Anguish",
        icon: "eye",
        school: "shadow",
        kind: "dot",
        levelReq: 8,
        cost: 25,
        castTime: 0,
        cooldown: 0,
        range: 30,
        base: 36,
        perLevel: 2.3,
        duration: 24,
        tickInterval: 3,
      },
      {
        id: "drain_life",
        name: "Consume",
        icon: "amulet",
        school: "shadow",
        kind: "dot",
        levelReq: 10,
        cost: 35,
        castTime: 0,
        cooldown: 0,
        range: 20,
        base: 35,
        perLevel: 2.8,
        duration: 5,
        tickInterval: 1,
      },
      {
        id: "searing_pain",
        name: "Sear",
        icon: "torch",
        school: "fire",
        kind: "damage",
        levelReq: 16,
        cost: 35,
        castTime: 1.5,
        cooldown: 0,
        range: 30,
        base: 34,
        perLevel: 0,
      },
      {
        id: "shadowburn",
        name: "Duskfire",
        icon: "bomb",
        school: "shadow",
        kind: "damage",
        levelReq: 20,
        cost: 70,
        castTime: 0,
        cooldown: 15,
        range: 20,
        base: 61,
        perLevel: 0,
      },
      {
        id: "rain_of_fire",
        name: "Rain of Fire",
        icon: "star",
        school: "fire",
        kind: "aoe",
        levelReq: 18,
        cost: 85,
        castTime: 0,
        cooldown: 10,
        range: 30,
        base: 16,
        perLevel: 0,
        aoeRadius: 7,
        duration: 4,
        tickInterval: 1,
      },
      {
        id: "life_tap",
        name: "Hard Bargain",
        icon: "heart",
        school: "shadow",
        kind: "buff",
        levelReq: 6,
        cost: 0,
        castTime: 0,
        cooldown: 0,
        range: 0,
        base: 0,
        perLevel: 0,
        selfTarget: true,
        selfResource: 30,
      },
      {
        id: "fear",
        name: "Harrow",
        icon: "hourglass",
        school: "shadow",
        kind: "buff",
        levelReq: 14,
        cost: 40,
        castTime: 1.5,
        cooldown: 0,
        range: 20,
        base: 0,
        perLevel: 0,
        selfTarget: true,
        cc: { kind: "stun", durationSec: 8 },
      },
      {
        id: "summon_imp",
        name: "Summon Emberkin",
        icon: "wing",
        school: "shadow",
        kind: "buff",
        levelReq: 1,
        cost: 30,
        castTime: 2,
        cooldown: 10,
        range: 0,
        base: 0,
        perLevel: 0,
        selfTarget: true,
      },
      {
        id: "summon_voidwalker",
        name: "Summon Gloomshade",
        icon: "shield",
        school: "shadow",
        kind: "buff",
        levelReq: 10,
        cost: 50,
        castTime: 2.5,
        cooldown: 10,
        range: 0,
        base: 0,
        perLevel: 0,
        selfTarget: true,
      },
      {
        id: "summon_felhunter",
        name: "Summon Spellhound",
        icon: "fist",
        school: "shadow",
        kind: "buff",
        levelReq: 14,
        cost: 50,
        castTime: 2.5,
        cooldown: 10,
        range: 0,
        base: 0,
        perLevel: 0,
        selfTarget: true,
      },
      {
        id: "summon_succubus",
        name: "Summon Duskborn",
        icon: "ring",
        school: "shadow",
        kind: "buff",
        levelReq: 16,
        cost: 50,
        castTime: 2.5,
        cooldown: 10,
        range: 0,
        base: 0,
        perLevel: 0,
        selfTarget: true,
      },
    ],
  },
];
