import type { ClassDef } from "../../model";

export const WARRIOR_CLASS: readonly ClassDef[] = [
  {
    id: "warrior",
    name: "Warrior",
    icon: "sword",
    color: "#C79C6E",
    resource: "rage",
    baseHp: 50,
    hpPerLevel: 18,
    baseResource: 100,
    resourcePerLevel: 0,
    baseStats: { str: 23, agi: 20, sta: 22, int: 10, spi: 11, armor: 50 },
    statsPerLevel: { str: 2, agi: 1, sta: 2, int: 0, spi: 0, armor: 12 },
    startWeapon: "worn_sword",
    abilities: [
      {
        id: "heroic_strike",
        name: "Reaver Strike",
        icon: "sword",
        school: "physical",
        kind: "damage",
        levelReq: 1,
        cost: 15,
        castTime: 0,
        cooldown: 0,
        range: 5,
        base: 11,
        perLevel: 1.8,
      },
      {
        id: "battle_shout",
        name: "Iron Bellow",
        icon: "buffArrow",
        school: "physical",
        kind: "buff",
        levelReq: 1,
        cost: 10,
        castTime: 0,
        cooldown: 0,
        range: 0,
        base: 10,
        perLevel: 0,
        duration: 120,
        selfTarget: true,
        buffStat: "attackPower",
        buffAmount: 10,
        buffPerLevel: 0,
      },
      {
        id: "commanding_shout",
        name: "Bolstering Cry",
        icon: "heart",
        school: "physical",
        kind: "buff",
        levelReq: 14,
        cost: 10,
        castTime: 0,
        cooldown: 0,
        range: 0,
        base: 6,
        perLevel: 0.3,
        duration: 120,
        selfTarget: true,
        buffStat: "sta",
        buffAmount: 6,
        buffPerLevel: 0.3,
      },
      {
        id: "rend",
        name: "Deep Gash",
        icon: "debuffArrow",
        school: "physical",
        kind: "dot",
        levelReq: 4,
        cost: 10,
        castTime: 0,
        cooldown: 0,
        range: 5,
        base: 15,
        perLevel: 1.2,
        duration: 9,
        tickInterval: 3,
      },
      {
        id: "thunder_clap",
        name: "Quaking Blow",
        icon: "lightning",
        school: "physical",
        kind: "aoe",
        levelReq: 6,
        cost: 20,
        castTime: 0,
        cooldown: 4,
        range: 0,
        base: 13,
        perLevel: 1.5,
        aoeRadius: 8,
      },
      {
        id: "hamstring",
        name: "Hobbling Cut",
        icon: "boots",
        school: "physical",
        kind: "damage",
        levelReq: 8,
        cost: 10,
        castTime: 0,
        cooldown: 0,
        range: 5,
        base: 5,
        perLevel: 0.4,
      },
      {
        id: "overpower",
        name: "Redhand",
        icon: "gauntlet",
        school: "physical",
        kind: "damage",
        levelReq: 10,
        cost: 5,
        castTime: 0,
        cooldown: 5,
        range: 5,
        base: 5,
        perLevel: 0.6,
      },
      {
        id: "execute",
        name: "Early Grave",
        icon: "skull",
        school: "physical",
        kind: "damage",
        levelReq: 14,
        cost: 15,
        castTime: 0,
        cooldown: 0,
        range: 5,
        base: 67.5,
        perLevel: 0,
      },
      {
        id: "slam",
        name: "Brute Swing",
        icon: "hammer",
        school: "physical",
        kind: "damage",
        levelReq: 16,
        cost: 15,
        castTime: 1.5,
        cooldown: 0,
        range: 5,
        base: 25,
        perLevel: 0,
      },
      {
        id: "cleave",
        name: "Reaping Arc",
        icon: "axe",
        school: "physical",
        kind: "aoe",
        levelReq: 18,
        cost: 20,
        castTime: 0,
        cooldown: 0,
        range: 0,
        base: 23,
        perLevel: 0,
        aoeRadius: 5,
      },
      {
        id: "defensive_stance",
        name: "Guarded Stance",
        icon: "shield",
        school: "physical",
        kind: "buff",
        levelReq: 10,
        cost: 0,
        castTime: 0,
        cooldown: 1,
        range: 0,
        base: 90,
        perLevel: 0,
        duration: 3600,
        selfTarget: true,
      },
      {
        id: "demoralizing_shout",
        name: "Direhowl",
        icon: "arrowDown",
        school: "physical",
        kind: "buff",
        levelReq: 14,
        cost: 10,
        castTime: 0,
        cooldown: 0,
        range: 0,
        base: 30,
        perLevel: 0.8,
        duration: 30,
        aoeRadius: 10,
        selfTarget: false,
        buffStat: "attackPower",
        buffAmount: -30,
        buffPerLevel: -0.8,
      },
      {
        id: "taunt",
        name: "Goad",
        icon: "pin",
        school: "physical",
        kind: "buff",
        levelReq: 10,
        cost: 0,
        castTime: 0,
        cooldown: 10,
        range: 8,
        base: 0,
        perLevel: 0,
        selfTarget: true,
        cc: { kind: "taunt", durationSec: 3 },
      },
      {
        id: "sunder_armor",
        name: "Armor Shear",
        icon: "crosshairIcon",
        school: "physical",
        kind: "buff",
        levelReq: 10,
        cost: 15,
        castTime: 0,
        cooldown: 0,
        range: 0,
        base: 0,
        perLevel: 0,
        selfTarget: true,
        cc: { kind: "armorShred", durationSec: 30, amount: 25 },
      },
      {
        id: "bloodrage",
        name: "Blood Toll",
        icon: "fire",
        school: "physical",
        kind: "buff",
        levelReq: 10,
        cost: 0,
        castTime: 0,
        cooldown: 60,
        range: 0,
        base: 0,
        perLevel: 0,
        selfTarget: true,
        selfResource: 10,
      },
    ],
  },
];
