import { existsSync, mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

import { extractPackageSurface, type ApiExport, type ApiPackage } from "./apiSurface";
import { collectAdoption, collectSkillTokens } from "./apiAdoption";
import { PACKAGE_SKILLS, SKILL_DIRS, skillForModule } from "./skillRouting";
import { runOrphanRatchet } from "./orphanRatchet";

const BASELINE_PATH = "scripts/api-doc-baseline.json";
const ORPHAN_BASELINE_PATH = "scripts/api-orphan-baseline.json";
const OUT_NAME = "api.md";
const GENERATED_HEADER =
  "<!-- GENERATED by scripts/gen-skill-api.ts — do not edit. Regenerate: bun run gen:skill-api -->";

interface ModuleRef {
  importPath: string;
  exports: ApiExport[];
}

type SkillModules = Map<string, ModuleRef[]>;

function exportKey(importPath: string, name: string): string {
  return `${importPath}#${name}`;
}

function collectSkillModules(root: string): { skills: SkillModules; undocumented: string[] } {
  const skills: SkillModules = new Map(SKILL_DIRS.map((s) => [s, []]));
  const undocumented: string[] = [];
  const packages = ["core", ...Object.keys(PACKAGE_SKILLS)];

  for (const pkg of packages) {
    const surface: ApiPackage = extractPackageSurface(join(root, "packages", pkg));
    for (const module of surface.modules) {
      const skill = skillForModule(pkg, module.path);
      if (skill === null) continue;
      const importPath = `@jgengine/${pkg}/${module.path}`.replace(/\/index$/, "");
      skills.get(skill)?.push({ importPath, exports: module.exports });
      for (const e of module.exports) {
        if (e.doc === undefined || e.doc === "") undocumented.push(exportKey(importPath, e.name));
      }
    }
  }
  for (const refs of skills.values())
    refs.sort((a, b) => (a.importPath < b.importPath ? -1 : a.importPath > b.importPath ? 1 : 0));
  return { skills, undocumented };
}

function renderSkillApi(skill: string, modules: ModuleRef[]): string {
  const lines: string[] = [GENERATED_HEADER, "", `# ${skill} — exported API surface`, ""];
  for (const module of modules) {
    lines.push(`## ${module.importPath}`);
    lines.push("");
    for (const e of module.exports) {
      const doc = e.doc !== undefined && e.doc !== "" ? e.doc : "⚠ undocumented";
      lines.push(`- \`${e.name}\` (${e.kind}): ${e.signature} — ${doc}`);
    }
    lines.push("");
  }
  return `${lines.join("\n").trimEnd()}\n`;
}

function readBaseline(root: string, relPath: string): Set<string> {
  const path = join(root, relPath);
  if (!existsSync(path)) return new Set();
  return new Set(JSON.parse(readFileSync(path, "utf8")) as string[]);
}

function writeBaseline(root: string, relPath: string, entries: readonly string[]): void {
  writeFileSync(join(root, relPath), `${JSON.stringify([...entries].sort(), null, 2)}\n`);
}

const ORPHAN_GATED_KINDS = new Set(["function", "class"]);

function collectOrphans(root: string, skills: SkillModules): string[] {
  const adoption = collectAdoption(root);
  const orphans: string[] = [];
  for (const [skill, refs] of skills) {
    const tokens = collectSkillTokens(root, skill);
    for (const ref of refs) {
      if (adoption.namespaceModules.has(ref.importPath)) continue;
      for (const e of ref.exports) {
        if (!ORPHAN_GATED_KINDS.has(e.kind)) continue;
        if (adoption.names.has(e.name) || tokens.has(e.name)) continue;
        orphans.push(exportKey(ref.importPath, e.name));
      }
    }
  }
  return orphans;
}

function main(): void {
  const check = process.argv.includes("--check");
  const seed = process.argv.includes("--seed-baseline");
  const root = fileURLToPath(new URL("..", import.meta.url));
  const failures: string[] = [];

  const { skills, undocumented } = collectSkillModules(root);
  const undocumentedSet = new Set(undocumented);
  const baseline = readBaseline(root, BASELINE_PATH);

  const newDebt = undocumented.filter((key) => !baseline.has(key));
  const prunedBaseline = [...baseline].filter((key) => undocumentedSet.has(key));
  const staleBaseline = baseline.size - prunedBaseline.length;

  if (!seed && newDebt.length > 0) {
    failures.push(
      `${newDebt.length} exported symbol(s) lack a JSDoc description (new or changed exports must be documented):`,
      ...newDebt.map((key) => `  ${key}`),
    );
  }

  const orphans = collectOrphans(root, skills);
  const orphanSet = new Set(orphans);
  const orphanBaselineExists = existsSync(join(root, ORPHAN_BASELINE_PATH));
  const orphanBaseline = readBaseline(root, ORPHAN_BASELINE_PATH);

  const newOrphans = orphans.filter((key) => !orphanBaseline.has(key));
  const prunedOrphanBaseline = [...orphanBaseline].filter((key) => orphanSet.has(key));
  const staleOrphanBaseline = orphanBaseline.size - prunedOrphanBaseline.length;

  if (!seed && orphanBaselineExists && newOrphans.length > 0) {
    failures.push(
      `${newOrphans.length} exported primitive(s) have no game adopter and no skill example — surface them in the domain SKILL.md, use them in a game, or mark @internal:`,
      ...newOrphans.map((key) => `  ${key}`),
    );
  }

  if (check) failures.push(...runOrphanRatchet(root));

  const outDir = check ? mkdtempSync(join(tmpdir(), "jg-skill-api-")) : undefined;
  for (const skill of SKILL_DIRS) {
    const modules = skills.get(skill) ?? [];
    const content = renderSkillApi(skill, modules);
    const committedPath = join(root, ".claude", "skills", skill, OUT_NAME);
    if (check) {
      const committed = existsSync(committedPath) ? readFileSync(committedPath, "utf8") : "";
      if (committed !== content) {
        writeFileSync(join(outDir ?? tmpdir(), `${skill}.api.md`), content);
        failures.push(`.claude/skills/${skill}/${OUT_NAME} is stale — run: bun run gen:skill-api`);
      }
    } else {
      writeFileSync(committedPath, content);
      console.log(`OK ${skill}: ${modules.length} modules -> .claude/skills/${skill}/${OUT_NAME}`);
    }
  }

  if (check) {
    if (staleBaseline > 0) {
      failures.push(
        `${BASELINE_PATH} has ${staleBaseline} stale entr(ies) for symbols now documented or removed — run: bun run gen:skill-api`,
      );
    }
    if (orphanBaselineExists && staleOrphanBaseline > 0) {
      failures.push(
        `${ORPHAN_BASELINE_PATH} has ${staleOrphanBaseline} stale entr(ies) for primitives now adopted or removed — run: bun run gen:skill-api`,
      );
    }
  } else if (seed) {
    writeBaseline(root, BASELINE_PATH, undocumented);
    writeBaseline(root, ORPHAN_BASELINE_PATH, orphans);
    console.log(`Seeded ${BASELINE_PATH} with ${undocumented.length} undocumented exports`);
    console.log(`Seeded ${ORPHAN_BASELINE_PATH} with ${orphans.length} orphaned primitives`);
  } else {
    writeBaseline(root, BASELINE_PATH, prunedBaseline);
    if (staleBaseline > 0) console.log(`Pruned ${staleBaseline} entries from ${BASELINE_PATH}`);
    if (!orphanBaselineExists) {
      writeBaseline(root, ORPHAN_BASELINE_PATH, orphans);
      console.log(`Seeded ${ORPHAN_BASELINE_PATH} with ${orphans.length} orphaned primitives`);
    } else {
      writeBaseline(root, ORPHAN_BASELINE_PATH, prunedOrphanBaseline);
      if (staleOrphanBaseline > 0) console.log(`Pruned ${staleOrphanBaseline} entries from ${ORPHAN_BASELINE_PATH}`);
    }
  }

  if (failures.length > 0) {
    console.error(`\ncheck-skill-api failed:\n${failures.map((f) => `  ${f}`).join("\n")}\n`);
    process.exit(1);
  }
  const total = [...skills.values()].reduce((n, m) => n + m.length, 0);
  console.log(
    `skill-api ok: ${total} modules across ${SKILL_DIRS.length} skills, ${undocumentedSet.size} baseline-tracked undocumented exports, ${orphanSet.size} baseline-tracked orphaned primitives`,
  );
}

if (import.meta.main) main();
