import { existsSync, mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

import { extractPackageSurface } from "./apiSurface";
import { PACKAGE_SKILLS, SKILL_DIRS, skillForModule } from "./skillRouting";

const OUT_NAME = "capabilities.md";
const GENERATED_HEADER =
  "<!-- GENERATED by scripts/gen-capability-index.ts — do not edit. Regenerate: bun run gen:capabilities -->";

interface CapabilityEntry {
  slug: string;
  intent: string;
  name: string;
  kind: string;
  importPath: string;
}

type SkillCapabilities = Map<string, CapabilityEntry[]>;

function collect(root: string): SkillCapabilities {
  const skills: SkillCapabilities = new Map(SKILL_DIRS.map((s) => [s, []]));
  const packages = ["core", ...Object.keys(PACKAGE_SKILLS)];

  for (const pkg of packages) {
    const surface = extractPackageSurface(join(root, "packages", pkg));
    for (const module of surface.modules) {
      const skill = skillForModule(pkg, module.path);
      if (skill === null) continue;
      const importPath = `@jgengine/${pkg}/${module.path}`.replace(/\/index$/, "");
      for (const e of module.exports) {
        if (e.capabilities === undefined) continue;
        for (const cap of e.capabilities) {
          skills.get(skill)?.push({ slug: cap.slug, intent: cap.intent, name: e.name, kind: e.kind, importPath });
        }
      }
    }
  }
  for (const [skill, entries] of skills) skills.set(skill, dedupe(entries));
  return skills;
}

function dedupe(entries: CapabilityEntry[]): CapabilityEntry[] {
  const best = new Map<string, CapabilityEntry>();
  for (const entry of entries) {
    const key = `${entry.slug}#${entry.name}`;
    const current = best.get(key);
    if (current === undefined || entry.importPath.length < current.importPath.length) best.set(key, entry);
  }
  return [...best.values()];
}

function importLine(name: string, importPath: string): string {
  return `import { ${name} } from "${importPath}"`;
}

function renderSkill(skill: string, entries: CapabilityEntry[]): string {
  const lines: string[] = [GENERATED_HEADER, "", `# ${skill} — capability index`, ""];
  if (entries.length === 0) {
    lines.push("No capabilities tagged in this domain yet.");
    return `${lines.join("\n").trimEnd()}\n`;
  }
  lines.push(
    "Reach for these before hand-rolling. Each row is *the thing you need* → *the primitive that already does it*.",
    "",
  );
  const bySlug = new Map<string, CapabilityEntry[]>();
  for (const entry of entries) {
    const list = bySlug.get(entry.slug) ?? [];
    list.push(entry);
    bySlug.set(entry.slug, list);
  }
  for (const slug of [...bySlug.keys()].sort()) {
    const list = (bySlug.get(slug) ?? []).sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0));
    const intent = list.find((e) => e.intent !== "")?.intent ?? slug;
    lines.push(`## ${slug} — ${intent}`, "");
    for (const entry of list) {
      lines.push(`- \`${entry.name}\` (${entry.kind}) · \`${importLine(entry.name, entry.importPath)}\``);
    }
    lines.push("");
  }
  return `${lines.join("\n").trimEnd()}\n`;
}

function main(): void {
  const check = process.argv.includes("--check");
  const root = fileURLToPath(new URL("..", import.meta.url));
  const skills = collect(root);
  const failures: string[] = [];
  const outDir = check ? mkdtempSync(join(tmpdir(), "jg-capability-")) : undefined;

  let total = 0;
  for (const skill of SKILL_DIRS) {
    const entries = skills.get(skill) ?? [];
    total += entries.length;
    const content = renderSkill(skill, entries);
    const committedPath = join(root, ".claude", "skills", skill, OUT_NAME);
    if (check) {
      const committed = existsSync(committedPath) ? readFileSync(committedPath, "utf8") : "";
      if (committed !== content) {
        writeFileSync(join(outDir ?? tmpdir(), `${skill}.${OUT_NAME}`), content);
        failures.push(`.claude/skills/${skill}/${OUT_NAME} is stale — run: bun run gen:capabilities`);
      }
    } else {
      writeFileSync(committedPath, content);
      console.log(`OK ${skill}: ${entries.length} capabilities -> .claude/skills/${skill}/${OUT_NAME}`);
    }
  }

  if (failures.length > 0) {
    console.error(`\ncheck-capabilities failed:\n${failures.map((f) => `  ${f}`).join("\n")}\n`);
    process.exit(1);
  }
  console.log(`capabilities ok: ${total} tagged primitives across ${SKILL_DIRS.length} skills`);
}

if (import.meta.main) main();
