import { existsSync, mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

import { extractPackageSurface, type ApiExport, type ApiPackage } from "./apiSurface";

const MAIN = "jgengine";

const CORE_DOMAIN_SKILLS: Record<string, string> = {
  ai: "jgengine-world",
  anim: "jgengine-world",
  audio: "jgengine-world",
  behaviour: "jgengine-gameplay",
  board: "jgengine-gameplay",
  cards: "jgengine-gameplay",
  cartridge: MAIN,
  combat: "jgengine-combat",
  commands: MAIN,
  crafting: "jgengine-gameplay",
  data: "jgengine-gameplay",
  devtools: MAIN,
  economy: "jgengine-gameplay",
  editor: "jgengine-editor",
  faction: "jgengine-world",
  format: "jgengine-ui",
  game: "jgengine-gameplay",
  input: "jgengine-gameplay",
  interaction: "jgengine-world",
  inventory: "jgengine-gameplay",
  item: "jgengine-gameplay",
  math: "jgengine-world",
  meta: MAIN,
  movement: "jgengine-world",
  multiplayer: "jgengine-multiplayer",
  nav: "jgengine-world",
  physics: "jgengine-world",
  puzzle: "jgengine-gameplay",
  random: "jgengine-gameplay",
  render: "jgengine-ui",
  runtime: MAIN,
  scene: "jgengine-world",
  sensor: "jgengine-world",
  session: "jgengine-gameplay",
  settings: "jgengine-ui",
  stats: "jgengine-combat",
  survival: "jgengine-procedural",
  tactics: "jgengine-combat",
  time: "jgengine-world",
  turn: "jgengine-gameplay",
  ui: "jgengine-ui",
  visibility: "jgengine-world",
  world: "jgengine-world",
};

const CORE_INTERNAL_DOMAINS = new Set(["assets", "store"]);

const PACKAGE_SKILLS: Record<string, string> = {
  editor: "jgengine-editor",
  ws: "jgengine-multiplayer",
  sql: "jgengine-multiplayer",
  convex: "jgengine-multiplayer",
  node: "jgengine-multiplayer",
  react: "jgengine-ui",
  shell: "jgengine-ui",
  assets: "jgengine-assets",
  github: MAIN,
  jgengine: MAIN,
};

const SKILL_DIRS = [
  MAIN,
  "jgengine-world",
  "jgengine-procedural",
  "jgengine-combat",
  "jgengine-gameplay",
  "jgengine-multiplayer",
  "jgengine-ui",
  "jgengine-assets",
  "jgengine-editor",
] as const;

const BASELINE_PATH = "scripts/api-doc-baseline.json";
const OUT_NAME = "api.md";
const GENERATED_HEADER =
  "<!-- GENERATED by scripts/gen-skill-api.ts — do not edit. Regenerate: bun run gen:skill-api -->";

interface ModuleRef {
  importPath: string;
  exports: ApiExport[];
}

type SkillModules = Map<string, ModuleRef[]>;

function exportKey(importPath: string, name: string): string {
  return `${importPath}#${name}`;
}

function skillForModule(pkg: string, modulePath: string): string | null {
  if (pkg !== "core") return PACKAGE_SKILLS[pkg] ?? null;
  const domain = modulePath.split("/")[0];
  if (domain === undefined || CORE_INTERNAL_DOMAINS.has(domain)) return null;
  if (!modulePath.includes("/")) return MAIN;
  const skill = CORE_DOMAIN_SKILLS[domain];
  if (skill === undefined) {
    throw new Error(
      `core domain "${domain}" has no skill assignment — add it to CORE_DOMAIN_SKILLS in scripts/gen-skill-api.ts`,
    );
  }
  return skill;
}

function collectSkillModules(root: string): { skills: SkillModules; undocumented: string[] } {
  const skills: SkillModules = new Map(SKILL_DIRS.map((s) => [s, []]));
  const undocumented: string[] = [];
  const packages = ["core", ...Object.keys(PACKAGE_SKILLS)];

  for (const pkg of packages) {
    const surface: ApiPackage = extractPackageSurface(join(root, "packages", pkg));
    for (const module of surface.modules) {
      const skill = skillForModule(pkg, module.path);
      if (skill === null) continue;
      const importPath = `@jgengine/${pkg}/${module.path}`.replace(/\/index$/, "");
      skills.get(skill)?.push({ importPath, exports: module.exports });
      for (const e of module.exports) {
        if (e.doc === undefined || e.doc === "") undocumented.push(exportKey(importPath, e.name));
      }
    }
  }
  for (const refs of skills.values())
    refs.sort((a, b) => (a.importPath < b.importPath ? -1 : a.importPath > b.importPath ? 1 : 0));
  return { skills, undocumented };
}

function renderSkillApi(skill: string, modules: ModuleRef[]): string {
  const lines: string[] = [GENERATED_HEADER, "", `# ${skill} — exported API surface`, ""];
  for (const module of modules) {
    lines.push(`## ${module.importPath}`);
    lines.push("");
    for (const e of module.exports) {
      const doc = e.doc !== undefined && e.doc !== "" ? e.doc : "⚠ undocumented";
      lines.push(`- \`${e.name}\` (${e.kind}): ${e.signature} — ${doc}`);
    }
    lines.push("");
  }
  return `${lines.join("\n").trimEnd()}\n`;
}

function readBaseline(root: string): Set<string> {
  const path = join(root, BASELINE_PATH);
  if (!existsSync(path)) return new Set();
  return new Set(JSON.parse(readFileSync(path, "utf8")) as string[]);
}

function writeBaseline(root: string, entries: readonly string[]): void {
  writeFileSync(join(root, BASELINE_PATH), `${JSON.stringify([...entries].sort(), null, 2)}\n`);
}

function main(): void {
  const check = process.argv.includes("--check");
  const seed = process.argv.includes("--seed-baseline");
  const root = fileURLToPath(new URL("..", import.meta.url));
  const failures: string[] = [];

  const { skills, undocumented } = collectSkillModules(root);
  const undocumentedSet = new Set(undocumented);
  const baseline = readBaseline(root);

  const newDebt = undocumented.filter((key) => !baseline.has(key));
  const prunedBaseline = [...baseline].filter((key) => undocumentedSet.has(key));
  const staleBaseline = baseline.size - prunedBaseline.length;

  if (!seed && newDebt.length > 0) {
    failures.push(
      `${newDebt.length} exported symbol(s) lack a JSDoc description (new or changed exports must be documented):`,
      ...newDebt.map((key) => `  ${key}`),
    );
  }

  const outDir = check ? mkdtempSync(join(tmpdir(), "jg-skill-api-")) : undefined;
  for (const skill of SKILL_DIRS) {
    const modules = skills.get(skill) ?? [];
    const content = renderSkillApi(skill, modules);
    const committedPath = join(root, ".claude", "skills", skill, OUT_NAME);
    if (check) {
      const committed = existsSync(committedPath) ? readFileSync(committedPath, "utf8") : "";
      if (committed !== content) {
        writeFileSync(join(outDir ?? tmpdir(), `${skill}.api.md`), content);
        failures.push(`.claude/skills/${skill}/${OUT_NAME} is stale — run: bun run gen:skill-api`);
      }
    } else {
      writeFileSync(committedPath, content);
      console.log(`OK ${skill}: ${modules.length} modules -> .claude/skills/${skill}/${OUT_NAME}`);
    }
  }

  if (check) {
    if (staleBaseline > 0) {
      failures.push(
        `${BASELINE_PATH} has ${staleBaseline} stale entr(ies) for symbols now documented or removed — run: bun run gen:skill-api`,
      );
    }
  } else if (seed) {
    writeBaseline(root, undocumented);
    console.log(`Seeded ${BASELINE_PATH} with ${undocumented.length} undocumented exports`);
  } else {
    writeBaseline(root, prunedBaseline);
    if (staleBaseline > 0) console.log(`Pruned ${staleBaseline} entries from ${BASELINE_PATH}`);
  }

  if (failures.length > 0) {
    console.error(`\ncheck-skill-api failed:\n${failures.map((f) => `  ${f}`).join("\n")}\n`);
    process.exit(1);
  }
  const total = [...skills.values()].reduce((n, m) => n + m.length, 0);
  console.log(
    `skill-api ok: ${total} modules across ${SKILL_DIRS.length} skills, ${undocumentedSet.size} baseline-tracked undocumented exports`,
  );
}

if (import.meta.main) main();
