import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";

import { SKILL_DIRS } from "./skillRouting";

const root = fileURLToPath(new URL("..", import.meta.url));
const baselinePath = join(root, "scripts/api-doc-baseline.json");
const orphanBaselinePath = join(root, "scripts/api-orphan-baseline.json");
const skills = SKILL_DIRS;
const trackedPaths = [
  baselinePath,
  orphanBaselinePath,
  ...skills.map((skill) => join(root, ".claude/skills", skill, "api.md")),
];

for (const dependency of ["node_modules/ts-morph", "node_modules/typescript"]) {
  if (!existsSync(join(root, dependency))) {
    console.error(`skill-api generation refused: ${dependency} is missing; finish bun install first`);
    process.exit(1);
  }
}

const before = new Map(trackedPaths.map((path) => [path, existsSync(path) ? readFileSync(path, "utf8") : ""]));
const previousBaseline = JSON.parse(before.get(baselinePath) ?? "[]") as string[];

const result = spawnSync("bun", ["scripts/gen-skill-api.ts", ...process.argv.slice(2)], {
  cwd: root,
  encoding: "utf8",
  stdio: "inherit",
});

function restore(): void {
  for (const [path, content] of before) writeFileSync(path, content);
}

const generationCompleted = result.status === 0 || result.status === 2;
if (!generationCompleted) {
  restore();
  process.exit(result.status ?? 1);
}

try {
  const nextBaseline = JSON.parse(readFileSync(baselinePath, "utf8")) as string[];
  const removed = previousBaseline.length - nextBaseline.length;
  const suspiciousDrop = removed > 100 && nextBaseline.length < previousBaseline.length * 0.9;
  if (suspiciousDrop) {
    restore();
    console.error(
      `skill-api generation refused: baseline dropped by ${removed} entries; this usually means an incomplete install or parser failure`,
    );
    process.exit(1);
  }

  for (const path of trackedPaths.slice(2)) {
    const content = readFileSync(path, "utf8");
    if (!content.startsWith("<!-- GENERATED by scripts/gen-skill-api.ts")) {
      restore();
      console.error(`skill-api generation refused: ${path} is not a valid generated file`);
      process.exit(1);
    }
  }
} catch (error) {
  restore();
  console.error(`skill-api generation validation failed: ${String(error)}`);
  process.exit(1);
}

if (result.status === 2) {
  console.error(
    "skill-api: generated files kept; gate failures above still need fixing. " +
      "If they list newly tagged/exported symbols, run `bun run gen:capabilities` first, then re-run `bun run gen:skill-api` — " +
      "skill-api reads the capability index, so a stale one reports symbols as undocumented until capabilities is regenerated.",
  );
  process.exit(2);
}
