import { existsSync, mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

import { extractPackageSurface, type ApiExport, type ApiPackage } from "./apiSurface";
import { collectAdoption, hasPublicIntentEvidence } from "./apiAdoption";
import { CORE_BARREL_SKILLS, PACKAGE_SKILLS, SKILL_DIRS, skillForModule } from "./skillRouting";
import { runOrphanRatchet } from "./orphanRatchet";

const BASELINE_PATH = "scripts/api-doc-baseline.json";
const ORPHAN_BASELINE_PATH = "scripts/api-orphan-baseline.json";
const OUT_NAME = "api.md";
const GENERATED_HEADER =
  "<!-- GENERATED by scripts/gen-skill-api.ts — do not edit. Regenerate: bun run gen:skill-api -->";

interface ModuleRef {
  importPath: string;
  pkg: string;
  srcFile: string;
  exports: ApiExport[];
}

type SkillModules = Map<string, ModuleRef[]>;

function exportKey(importPath: string, name: string): string {
  return `${importPath}#${name}`;
}

function collectSkillModules(root: string): { skills: SkillModules; undocumented: string[] } {
  const skills: SkillModules = new Map(SKILL_DIRS.map((s) => [s, []]));
  const undocumented: string[] = [];
  const packages = ["core", ...Object.keys(PACKAGE_SKILLS)];

  for (const pkg of packages) {
    const surface: ApiPackage = extractPackageSurface(join(root, "packages", pkg));
    for (const module of surface.modules) {
      const skill = skillForModule(pkg, module.path);
      if (skill === null) continue;
      const importPath = `@jgengine/${pkg}/${module.path}`.replace(/\/index$/, "");
      const srcBase = join(root, "packages", pkg, "src", module.path);
      const srcFile = existsSync(`${srcBase}.tsx`) ? `${srcBase}.tsx` : `${srcBase}.ts`;
      skills.get(skill)?.push({ importPath, pkg, srcFile, exports: module.exports });
      for (const e of module.exports) {
        if (e.doc === undefined || e.doc === "") undocumented.push(exportKey(importPath, e.name));
      }
    }
  }
  for (const refs of skills.values())
    refs.sort((a, b) => (a.importPath < b.importPath ? -1 : a.importPath > b.importPath ? 1 : 0));
  return { skills, undocumented };
}

const MAX_FIELDS_LENGTH = 240;
const MAX_USER_DOC_LENGTH = 140;

function clip(text: string, max: number): string {
  return text.length > max ? `${text.slice(0, max)}…` : text;
}

function continuesOnNextLine(current: string, source: string, next: number): boolean {
  const tail = current.trimEnd();
  if (tail === "") return false;
  if (/(?:[:|&]|=>)$/.test(tail)) return true;
  const following = source.slice(next).trimStart()[0];
  return following === "|" || following === "&" || following === ".";
}

/** Top-level members of the interface body that starts at `open` (the index of its `{`). */
function interfaceMembers(source: string, open: number): string[] {
  const members: string[] = [];
  let depth = 0;
  let current = "";
  for (let i = open + 1; i < source.length; i++) {
    const ch = source[i]!;
    if (ch === "{" || ch === "(" || ch === "[" || (ch === "<" && source[i + 1] !== "=")) depth++;
    else if (ch === "}" || ch === ")" || ch === "]" || (ch === ">" && source[i - 1] !== "=")) {
      if (depth === 0 && ch === "}") break;
      depth--;
    }
    if (depth === 0 && ch === "\n" && continuesOnNextLine(current, source, i + 1)) current += " ";
    else if (depth === 0 && (ch === ";" || ch === "," || ch === "\n")) {
      members.push(current);
      current = "";
    } else current += ch;
  }
  members.push(current);
  return members
    .map((m) => m.replace(/\s+/g, " ").replace(/([([{<]) /g, "$1").replace(/,? ([)\]}>])/g, "$1").trim())
    .filter((m) => m !== "");
}

/** Field lists for every interface declared in a module source, keyed by name. */
function interfaceFields(srcFile: string): Map<string, string> {
  const fields = new Map<string, string>();
  if (!existsSync(srcFile)) return fields;
  const source = readFileSync(srcFile, "utf8")
    .replace(/\/\*[\s\S]*?\*\//g, "")
    .replace(/(^|\s)\/\/.*$/gm, "$1");
  for (const match of source.matchAll(/\binterface\s+([A-Za-z_$][\w$]*)/g)) {
    let i = (match.index ?? 0) + match[0].length;
    let angle = 0;
    for (; i < source.length; i++) {
      const ch = source[i]!;
      if (ch === "<") angle++;
      else if (ch === ">" && source[i - 1] !== "=") angle--;
      else if (ch === "{" && angle === 0) break;
    }
    if (i >= source.length) continue;
    const members = interfaceMembers(source, i);
    fields.set(match[1]!, members.length === 0 ? "{}" : clip(`{ ${members.join("; ")} }`, MAX_FIELDS_LENGTH));
  }
  return fields;
}

interface Consumer {
  name: string;
  importPath: string;
  doc: string;
}

/**
 * Documented functions/classes/consts whose signature names a type, so an undocumented options or
 * result type points at the call that gives it meaning instead of forcing a source read.
 */
function buildConsumerIndex(all: readonly ModuleRef[]): (name: string, importPath: string) => Consumer | undefined {
  const documented: Consumer[] = [];
  const signatures: string[] = [];
  for (const module of all) {
    for (const e of module.exports) {
      if (e.kind !== "function" && e.kind !== "class" && e.kind !== "const") continue;
      if (e.doc === undefined || e.doc === "") continue;
      documented.push({ name: e.name, importPath: module.importPath, doc: e.doc });
      signatures.push(e.signature);
    }
  }
  return (name, importPath) => {
    const word = new RegExp(`(^|[^\\w$])${name.replace(/\$/g, "\\$")}([^\\w$]|$)`);
    let fallback: Consumer | undefined;
    for (let i = 0; i < documented.length; i++) {
      const candidate = documented[i]!;
      if (candidate.name === name || !word.test(signatures[i]!)) continue;
      if (candidate.importPath === importPath) return candidate;
      fallback ??= candidate;
    }
    return fallback;
  };
}

function undocumentedNote(e: ApiExport, module: ModuleRef, consumerOf: ReturnType<typeof buildConsumerIndex>): string {
  if (e.kind !== "interface" && e.kind !== "type") return "⚠ undocumented";
  const consumer = consumerOf(e.name, module.importPath);
  if (consumer === undefined) return "⚠ undocumented";
  const where = consumer.importPath === module.importPath ? "" : ` (${consumer.importPath})`;
  const [sentence] = consumer.doc.split(/(?<=\.)\s/);
  return `⚠ undocumented · used by \`${consumer.name}\`${where}: ${clip(sentence ?? consumer.doc, MAX_USER_DOC_LENGTH)}`;
}

/** Interface bodies declared anywhere in a package, for exports re-exported through a barrel; ambiguous names map to undefined. */
function buildPackageFields(all: readonly ModuleRef[]): (pkg: string, name: string) => string | undefined {
  const byPackage = new Map<string, Map<string, string | undefined>>();
  const seenFiles = new Set<string>();
  for (const module of all) {
    if (seenFiles.has(module.srcFile)) continue;
    seenFiles.add(module.srcFile);
    const names = byPackage.get(module.pkg) ?? new Map<string, string | undefined>();
    byPackage.set(module.pkg, names);
    for (const [name, body] of interfaceFields(module.srcFile)) {
      names.set(name, names.has(name) && names.get(name) !== body ? undefined : body);
    }
  }
  return (pkg, name) => byPackage.get(pkg)?.get(name);
}

function renderSkillApi(
  skill: string,
  modules: ModuleRef[],
  consumerOf: ReturnType<typeof buildConsumerIndex>,
  packageFields: ReturnType<typeof buildPackageFields>,
): string {
  const lines: string[] = [GENERATED_HEADER, "", `# ${skill} — exported API surface`, ""];
  for (const module of modules) {
    lines.push(`## ${module.importPath}`);
    lines.push("");
    let fields: Map<string, string> | undefined;
    for (const e of module.exports) {
      const documented = e.doc !== undefined && e.doc !== "";
      let signature = e.signature;
      if (!documented && e.kind === "interface") {
        fields ??= interfaceFields(module.srcFile);
        const body = fields.get(e.name) ?? packageFields(module.pkg, e.name);
        if (body !== undefined && !signature.endsWith("…")) signature = `${signature} ${body}`;
      }
      const doc = documented ? e.doc : undocumentedNote(e, module, consumerOf);
      lines.push(`- \`${e.name}\` (${e.kind}): ${signature} — ${doc}`);
    }
    lines.push("");
  }
  return `${lines.join("\n").trimEnd()}\n`;
}

function readBaseline(root: string, relPath: string): Set<string> {
  const path = join(root, relPath);
  if (!existsSync(path)) return new Set();
  return new Set(JSON.parse(readFileSync(path, "utf8")) as string[]);
}

function writeBaseline(root: string, relPath: string, entries: readonly string[]): void {
  writeFileSync(join(root, relPath), `${JSON.stringify([...entries].sort(), null, 2)}\n`);
}

function collectCommittedApiKeys(root: string): Set<string> {
  const keys = new Set<string>();
  for (const skill of SKILL_DIRS) {
    const path = join(root, ".claude", "skills", skill, OUT_NAME);
    if (!existsSync(path)) continue;
    let importPath = "";
    for (const line of readFileSync(path, "utf8").split(/\r?\n/)) {
      const heading = line.match(/^## (@jgengine\/\S+)$/)?.[1];
      if (heading !== undefined) {
        importPath = heading;
        continue;
      }
      const name = line.match(/^- `([^`]+)` \(/)?.[1];
      if (importPath !== "" && name !== undefined) keys.add(exportKey(importPath, name));
    }
  }
  return keys;
}

const ORPHAN_GATED_KINDS = new Set(["function", "class"]);
const CURATED_CORE_BARRELS = new Set(Object.keys(CORE_BARREL_SKILLS).map((name) => `@jgengine/core/${name}`));

export function isCanonicalDeclarationImport(importPath: string): boolean {
  return !CURATED_CORE_BARRELS.has(importPath);
}

function collectOrphans(root: string, skills: SkillModules): string[] {
  const adoption = collectAdoption(root);
  const orphans: string[] = [];
  for (const [skill, refs] of skills) {
    for (const ref of refs) {
      if (!isCanonicalDeclarationImport(ref.importPath)) continue;
      for (const e of ref.exports) {
        if (!ORPHAN_GATED_KINDS.has(e.kind)) continue;
        if (hasPublicIntentEvidence(adoption, skill, ref.importPath, e.name, e.capabilities?.length ?? 0)) continue;
        orphans.push(exportKey(ref.importPath, e.name));
      }
    }
  }
  return orphans;
}

function main(): void {
  const check = process.argv.includes("--check");
  const seed = process.argv.includes("--seed-baseline");
  const root = fileURLToPath(new URL("..", import.meta.url));
  const failures: string[] = [];

  const extractedPackages = ["core", ...Object.keys(PACKAGE_SKILLS)];
  const missingDist = extractedPackages.filter((pkg) => !existsSync(join(root, "packages", pkg, "dist")));
  if (missingDist.length > 0) {
    console.error(
      `skill-api refused: missing dist for ${missingDist.join(", ")} — run \`bun run build\` first (extraction silently drops modules that resolve through unbuilt packages)`,
    );
    process.exit(1);
  }

  const { skills, undocumented } = collectSkillModules(root);
  const undocumentedSet = new Set(undocumented);
  const baseline = readBaseline(root, BASELINE_PATH);

  const newDebt = undocumented.filter((key) => !baseline.has(key));
  const prunedBaseline = [...baseline].filter((key) => undocumentedSet.has(key));
  const staleBaseline = baseline.size - prunedBaseline.length;

  if (!seed && newDebt.length > 0) {
    failures.push(
      `${newDebt.length} exported symbol(s) lack a JSDoc description (new or changed exports must be documented):`,
      ...newDebt.map((key) => `  ${key}`),
    );
  }

  const orphanBaselineExists = existsSync(join(root, ORPHAN_BASELINE_PATH));
  const orphanBaseline = readBaseline(root, ORPHAN_BASELINE_PATH);
  const committedApiKeys = collectCommittedApiKeys(root);
  const unprovenExports = collectOrphans(root, skills);
  const orphans = seed
    ? unprovenExports
    : unprovenExports.filter((key) => orphanBaseline.has(key) || !committedApiKeys.has(key));
  const orphanSet = new Set(orphans);

  const newOrphans = orphans.filter((key) => !orphanBaseline.has(key));
  const prunedOrphanBaseline = [...orphanBaseline].filter((key) => orphanSet.has(key));
  const staleOrphanBaseline = orphanBaseline.size - prunedOrphanBaseline.length;

  if (!seed && orphanBaselineExists && newOrphans.length > 0) {
    failures.push(
      `${newOrphans.length} exported primitive(s) have no exact consumer import or @capability intent — adopt them, tag their public intent, or mark @internal:`,
      ...newOrphans.map((key) => `  ${key}`),
    );
  }

  if (check) failures.push(...runOrphanRatchet(root));

  const outDir = check ? mkdtempSync(join(tmpdir(), "jg-skill-api-")) : undefined;
  const allModules = [...skills.values()].flat();
  const consumerOf = buildConsumerIndex(allModules);
  const packageFields = buildPackageFields(allModules);
  for (const skill of SKILL_DIRS) {
    const modules = skills.get(skill) ?? [];
    const content = renderSkillApi(skill, modules, consumerOf, packageFields);
    const committedPath = join(root, ".claude", "skills", skill, OUT_NAME);
    if (check) {
      const committed = existsSync(committedPath) ? readFileSync(committedPath, "utf8") : "";
      if (committed !== content) {
        writeFileSync(join(outDir ?? tmpdir(), `${skill}.api.md`), content);
        failures.push(`.claude/skills/${skill}/${OUT_NAME} is stale — run: bun run gen:skill-api`);
      }
    } else {
      writeFileSync(committedPath, content);
      console.log(`OK ${skill}: ${modules.length} modules -> .claude/skills/${skill}/${OUT_NAME}`);
    }
  }

  if (check) {
    if (staleBaseline > 0) {
      failures.push(
        `${BASELINE_PATH} has ${staleBaseline} stale entr(ies) for symbols now documented or removed — run: bun run gen:skill-api`,
      );
    }
    if (orphanBaselineExists && staleOrphanBaseline > 0) {
      failures.push(
        `${ORPHAN_BASELINE_PATH} has ${staleOrphanBaseline} stale entr(ies) for primitives now adopted or removed — run: bun run gen:skill-api`,
      );
    }
  } else if (seed) {
    writeBaseline(root, BASELINE_PATH, undocumented);
    writeBaseline(root, ORPHAN_BASELINE_PATH, orphans);
    console.log(`Seeded ${BASELINE_PATH} with ${undocumented.length} undocumented exports`);
    console.log(`Seeded ${ORPHAN_BASELINE_PATH} with ${orphans.length} orphaned primitives`);
  } else {
    writeBaseline(root, BASELINE_PATH, prunedBaseline);
    if (staleBaseline > 0) console.log(`Pruned ${staleBaseline} entries from ${BASELINE_PATH}`);
    if (!orphanBaselineExists) {
      writeBaseline(root, ORPHAN_BASELINE_PATH, orphans);
      console.log(`Seeded ${ORPHAN_BASELINE_PATH} with ${orphans.length} orphaned primitives`);
    } else {
      writeBaseline(root, ORPHAN_BASELINE_PATH, prunedOrphanBaseline);
      if (staleOrphanBaseline > 0) console.log(`Pruned ${staleOrphanBaseline} entries from ${ORPHAN_BASELINE_PATH}`);
    }
  }

  if (failures.length > 0) {
    console.error(`\ncheck-skill-api failed:\n${failures.map((f) => `  ${f}`).join("\n")}\n`);
    process.exit(check ? 1 : 2);
  }
  const total = [...skills.values()].reduce((n, m) => n + m.length, 0);
  console.log(
    `skill-api ok: ${total} modules across ${SKILL_DIRS.length} skills, ${undocumentedSet.size} baseline-tracked undocumented exports, ${orphanSet.size} baseline-tracked orphaned primitives`,
  );
}

if (import.meta.main) main();
