import type { JgThemeVars } from "@/components/ui/jg-theme";

export const voltNeonVars: JgThemeVars = {
  "--jg-accent": "#9ef01a",
  "--jg-accent-glow": "rgba(158, 240, 26, 0.55)",
  "--jg-accent-deep": "#5f8f0e",
  "--jg-surface": "#20242b",
  "--jg-surface-deep": "#14171b",
  "--jg-edge": "#3a4048",
  "--jg-edge-bright": "#57616d",
  "--jg-text": "#eef2f5",
  "--jg-text-dim": "#9aa4ad",
  "--jg-health": "#9ef01a",
  "--jg-health-deep": "#5f8f0e",
  "--jg-mana": "#4cc9f0",
  "--jg-mana-deep": "#276c85",
  "--jg-stamina": "#ff7b00",
  "--jg-stamina-deep": "#8a4200",
  "--jg-xp": "#4cc9f0",
  "--jg-xp-deep": "#276c85",
  "--jg-shield": "#4cc9f0",
  "--jg-shield-deep": "#276c85",
  "--jg-danger": "#ff4136",
  "--jg-warning": "#ff7b00",
  "--jg-success": "#9ef01a",
  "--jg-hostile": "#ff4136",
  "--jg-friendly": "#4cc9f0",
  "--jg-neutral": "#eef2f5",
  "--jg-font-display": "'Segoe UI', system-ui, sans-serif",
  "--jg-font-numeric": "Consolas, 'Cascadia Mono', 'SF Mono', 'Roboto Mono', monospace",
  "--jg-font-body": "'Segoe UI', system-ui, sans-serif",
  "--jg-rarity-common": "#9aa4ad",
  "--jg-rarity-uncommon": "#9ef01a",
  "--jg-rarity-rare": "#4cc9f0",
  "--jg-rarity-epic": "#ff7b00",
  "--jg-rarity-legendary": "#eef2f5",
};
