import type { ItemDef } from "../model";

export const ITEMS: readonly ItemDef[] = [
  { id: "worn_sword", name: "Pitted Shortsword", icon: "sword", kind: "weapon", quality: "common", slot: "mainHand", weapon: { min: 2, max: 5, speed: 2 }, sellPrice: 10, buyPrice: 40, shops: ["shop_eastbrook"] },
  { id: "gnarled_staff", name: "Bogoak Staff", icon: "staff", kind: "weapon", quality: "common", slot: "mainHand", weapon: { min: 3, max: 6, speed: 2.9 }, stats: { int: 1 }, sellPrice: 12, buyPrice: 48, shops: ["shop_eastbrook"] },
  { id: "rusty_dagger", name: "Rusty Dagger", icon: "dagger", kind: "weapon", quality: "common", slot: "mainHand", weapon: { min: 2, max: 4, speed: 1.8 }, sellPrice: 10, buyPrice: 40, shops: ["shop_eastbrook"] },
  { id: "training_mace", name: "Training Mace", icon: "hammer", kind: "weapon", quality: "common", slot: "mainHand", weapon: { min: 2, max: 5, speed: 2.6 }, sellPrice: 10, buyPrice: 40, shops: ["shop_eastbrook"] },
  { id: "rusty_hatchet", name: "Rusty Hatchet", icon: "axe", kind: "weapon", quality: "common", slot: "mainHand", weapon: { min: 2, max: 5, speed: 2.2 }, sellPrice: 10, buyPrice: 40, shops: ["shop_eastbrook"] },

  { id: "eastbrook_arming_sword", name: "Eastbrook Arming Sword", icon: "sword", kind: "weapon", quality: "common", slot: "mainHand", weapon: { min: 5, max: 9, speed: 2.2 }, sellPrice: 140, buyPrice: 560, shops: ["shop_eastbrook"] },
  { id: "bronzework_mace", name: "Bronzework Mace", icon: "hammer", kind: "weapon", quality: "common", slot: "mainHand", weapon: { min: 6, max: 10, speed: 2.6 }, sellPrice: 140, buyPrice: 560, shops: ["shop_eastbrook"] },
  { id: "vale_carving_knife", name: "Vale Carving Knife", icon: "dagger", kind: "weapon", quality: "common", slot: "mainHand", weapon: { min: 4, max: 7, speed: 1.8 }, sellPrice: 120, buyPrice: 480, shops: ["shop_eastbrook"] },
  { id: "hickory_shortstaff", name: "Hickory Shortstaff", icon: "staff", kind: "weapon", quality: "common", slot: "mainHand", weapon: { min: 6, max: 11, speed: 3 }, stats: { int: 1 }, sellPrice: 150, buyPrice: 600, shops: ["shop_eastbrook"] },
  { id: "redbrook_blade", name: "Redbrook Militia Blade", icon: "sword", kind: "weapon", quality: "uncommon", slot: "mainHand", weapon: { min: 6, max: 11, speed: 2.2 }, stats: { str: 2 }, sellPrice: 120 },
  { id: "keen_dirk", name: "Keen Dirk", icon: "dagger", kind: "weapon", quality: "uncommon", slot: "mainHand", weapon: { min: 4, max: 8, speed: 1.7 }, stats: { agi: 2 }, sellPrice: 120 },
  { id: "gravecaller_blade", name: "Gravecaller's Broadblade", icon: "sword", kind: "weapon", quality: "rare", slot: "mainHand", weapon: { min: 9, max: 16, speed: 2.4 }, stats: { str: 4, sta: 3 }, sellPrice: 800 },
  { id: "widowfang_dirk", name: "Widowfang Dirk", icon: "dagger", kind: "weapon", quality: "rare", slot: "mainHand", weapon: { min: 6, max: 10, speed: 1.7 }, stats: { agi: 4, sta: 3 }, sellPrice: 800 },

  { id: "recruit_tunic", name: "Levyman's Tunic", icon: "chestplate", kind: "armor", quality: "common", slot: "chest", armor: 20, sellPrice: 5, buyPrice: 20, shops: ["shop_eastbrook"] },
  { id: "apprentice_robe", name: "Threadbare Robe", icon: "chestplate", kind: "armor", quality: "common", slot: "chest", armor: 8, sellPrice: 5, buyPrice: 20, shops: ["shop_eastbrook"] },
  { id: "footpad_jerkin", name: "Cutpurse Jerkin", icon: "chestplate", kind: "armor", quality: "common", slot: "chest", armor: 14, sellPrice: 5, buyPrice: 20, shops: ["shop_eastbrook"] },
  { id: "hobnail_boots", name: "Hobnailed Boots", icon: "boots", kind: "armor", quality: "common", slot: "feet", armor: 18, sellPrice: 90, buyPrice: 360, shops: ["shop_eastbrook"] },
  { id: "eastbrook_wool_trousers", name: "Eastbrook Wool Trousers", icon: "chestplate", kind: "armor", quality: "common", slot: "legs", armor: 24, sellPrice: 110, buyPrice: 440, shops: ["shop_eastbrook"] },
  { id: "oiled_boots", name: "Oiled Leather Boots", icon: "boots", kind: "armor", quality: "uncommon", slot: "feet", armor: 25, stats: { agi: 1 }, sellPrice: 80, buyPrice: 320, shops: ["shop_eastbrook"] },
  { id: "quilted_trousers", name: "Quilted Trousers", icon: "chestplate", kind: "armor", quality: "uncommon", slot: "legs", armor: 30, stats: { sta: 2 }, sellPrice: 90, buyPrice: 360, shops: ["shop_eastbrook"] },
  { id: "cryptbone_helm", name: "Cryptbone Helm", icon: "helmet", kind: "armor", quality: "uncommon", slot: "head", armor: 48, stats: { sta: 3 }, sellPrice: 185 },
  { id: "mistveil_grips", name: "Mistveil Grips", icon: "gauntlet", kind: "armor", quality: "uncommon", slot: "hands", armor: 36, stats: { agi: 2, sta: 1 }, sellPrice: 165 },
  { id: "hollowbone_hauberk", name: "Hollowbone Hauberk", icon: "chestplate", kind: "armor", quality: "rare", slot: "chest", armor: 105, stats: { str: 3, sta: 3 }, sellPrice: 700 },
  { id: "gravewoven_raiment", name: "Gravewoven Raiment", icon: "chestplate", kind: "armor", quality: "rare", slot: "chest", armor: 38, stats: { int: 3, spi: 3 }, sellPrice: 700 },

  { id: "bogiron_mace", name: "Bogiron Mace", icon: "hammer", kind: "weapon", quality: "common", slot: "mainHand", weapon: { min: 8, max: 14, speed: 2.6 }, sellPrice: 250, buyPrice: 1000, shops: ["shop_fenbridge"] },
  { id: "fenreed_staff", name: "Fenreed Staff", icon: "staff", kind: "weapon", quality: "common", slot: "mainHand", weapon: { min: 9, max: 16, speed: 3 }, stats: { int: 1 }, sellPrice: 250, buyPrice: 1000, shops: ["shop_fenbridge"] },
  { id: "mirefen_skinner", name: "Mirefen Skinner", icon: "dagger", kind: "weapon", quality: "common", slot: "mainHand", weapon: { min: 6, max: 10, speed: 1.8 }, sellPrice: 250, buyPrice: 1000, shops: ["shop_fenbridge"] },
  { id: "deacons_cleaver", name: "Deacon's Cleaver", icon: "axe", kind: "weapon", quality: "uncommon", slot: "mainHand", weapon: { min: 11, max: 18, speed: 2.4 }, stats: { str: 4 }, sellPrice: 300 },
  { id: "tidereaver_gaff", name: "Tidereaver Gaff", icon: "spear", kind: "weapon", quality: "rare", slot: "mainHand", weapon: { min: 17, max: 28, speed: 2.5 }, stats: { str: 5, sta: 4 }, sellPrice: 1400 },
  { id: "drowned_tide_scepter", name: "Drowned Tide Scepter", icon: "staff", kind: "weapon", quality: "rare", slot: "mainHand", weapon: { min: 16, max: 28, speed: 3 }, stats: { int: 6, spi: 3 }, sellPrice: 1400 },

  { id: "bogiron_hauberk", name: "Bogiron Hauberk", icon: "chestplate", kind: "armor", quality: "common", slot: "chest", armor: 100, sellPrice: 300, buyPrice: 1200, shops: ["shop_fenbridge"] },
  { id: "marshcloth_robe", name: "Marshcloth Robe", icon: "chestplate", kind: "armor", quality: "common", slot: "chest", armor: 32, sellPrice: 200, buyPrice: 800, shops: ["shop_fenbridge"] },
  { id: "reedwoven_jerkin", name: "Reedwoven Jerkin", icon: "chestplate", kind: "armor", quality: "common", slot: "chest", armor: 62, sellPrice: 250, buyPrice: 1000, shops: ["shop_fenbridge"] },
  { id: "fenwalker_boots", name: "Fenwalker Boots", icon: "boots", kind: "armor", quality: "common", slot: "feet", armor: 30, sellPrice: 150, buyPrice: 600, shops: ["shop_fenbridge"] },
  { id: "reedwoven_trousers", name: "Reedwoven Trousers", icon: "chestplate", kind: "armor", quality: "common", slot: "legs", armor: 40, sellPrice: 180, buyPrice: 720, shops: ["shop_fenbridge"] },
  { id: "drownedguard_breastplate", name: "Drownedguard Breastplate", icon: "chestplate", kind: "armor", quality: "uncommon", slot: "chest", armor: 130, stats: { sta: 4 }, sellPrice: 350 },
  { id: "marshstrider_boots", name: "Marshstrider Boots", icon: "boots", kind: "armor", quality: "uncommon", slot: "feet", armor: 40, stats: { agi: 2, sta: 2 }, sellPrice: 250 },
  { id: "tidescale_vest", name: "Tidescale Vest", icon: "chestplate", kind: "armor", quality: "rare", slot: "chest", armor: 90, stats: { sta: 3, agi: 2 }, sellPrice: 1100 },

  { id: "highwatch_warblade", name: "Highwatch Warblade", icon: "sword", kind: "weapon", quality: "common", slot: "mainHand", weapon: { min: 15, max: 24, speed: 2.3 }, sellPrice: 600, buyPrice: 2400, shops: ["shop_highwatch"] },
  { id: "craghorn_staff", name: "Craghorn Staff", icon: "staff", kind: "weapon", quality: "common", slot: "mainHand", weapon: { min: 16, max: 27, speed: 3 }, stats: { int: 2 }, sellPrice: 600, buyPrice: 2400, shops: ["shop_highwatch"] },
  { id: "icevein_dirk", name: "Icevein Dirk", icon: "dagger", kind: "weapon", quality: "common", slot: "mainHand", weapon: { min: 10, max: 16, speed: 1.8 }, sellPrice: 600, buyPrice: 2400, shops: ["shop_highwatch"] },
  { id: "brutoks_maul", name: "Brutok's Maul", icon: "hammer", kind: "weapon", quality: "rare", slot: "mainHand", weapon: { min: 24, max: 37, speed: 2.7 }, stats: { str: 8, sta: 3 }, sellPrice: 2000 },
  { id: "crag_warden_cudgel", name: "Crag Warden Cudgel", icon: "hammer", kind: "weapon", quality: "rare", slot: "mainHand", weapon: { min: 23, max: 36, speed: 3 }, stats: { int: 8, spi: 4 }, sellPrice: 2000 },
  { id: "skullsplitter_dirk", name: "Skullsplitter Dirk", icon: "dagger", kind: "weapon", quality: "rare", slot: "mainHand", weapon: { min: 15, max: 23, speed: 1.7 }, stats: { agi: 8, sta: 3 }, sellPrice: 2000 },

  { id: "highwatch_breastplate", name: "Highwatch Breastplate", icon: "chestplate", kind: "armor", quality: "common", slot: "chest", armor: 160, sellPrice: 700, buyPrice: 2800, shops: ["shop_highwatch"] },
  { id: "peakwool_robe", name: "Peakwool Robe", icon: "chestplate", kind: "armor", quality: "common", slot: "chest", armor: 50, sellPrice: 500, buyPrice: 2000, shops: ["shop_highwatch"] },
  { id: "stalkerhide_jerkin", name: "Stalkerhide Jerkin", icon: "chestplate", kind: "armor", quality: "common", slot: "chest", armor: 95, sellPrice: 600, buyPrice: 2400, shops: ["shop_highwatch"] },
  { id: "cragwalker_boots", name: "Cragwalker Boots", icon: "boots", kind: "armor", quality: "common", slot: "feet", armor: 55, sellPrice: 400, buyPrice: 1600, shops: ["shop_highwatch"] },
  { id: "windguard_leggings", name: "Windguard Leggings", icon: "chestplate", kind: "armor", quality: "common", slot: "legs", armor: 70, sellPrice: 450, buyPrice: 1800, shops: ["shop_highwatch"] },
  { id: "cragmaw_prowlboots", name: "Cragmaw Prowlboots", icon: "boots", kind: "armor", quality: "rare", slot: "feet", armor: 58, stats: { agi: 5, sta: 3 }, sellPrice: 750 },
  { id: "emberwing_legguards", name: "Emberwing Legguards", icon: "chestplate", kind: "armor", quality: "rare", slot: "legs", armor: 120, stats: { sta: 6, str: 4 }, sellPrice: 2200 },
  { id: "boneguard_breastplate", name: "Boneguard Breastplate", icon: "chestplate", kind: "armor", quality: "rare", slot: "chest", armor: 210, stats: { sta: 8, str: 5 }, sellPrice: 2500 },

  { id: "milepost_boots", name: "Milepost Boots", icon: "boots", kind: "armor", quality: "uncommon", slot: "feet", armor: 8, stats: { agi: 1 }, sellPrice: 15 },
  { id: "wolfhide_satchel", name: "Wolfhide Satchel", icon: "backpack", kind: "armor", quality: "uncommon", slot: "trinket", armor: 3, stats: { agi: 1, sta: 1 }, sellPrice: 45 },
  { id: "trail_leggings", name: "Trail Leggings", icon: "chestplate", kind: "armor", quality: "uncommon", slot: "legs", armor: 14, stats: { sta: 1 }, sellPrice: 30 },
  { id: "mossy_handwraps", name: "Mossy Handwraps", icon: "gauntlet", kind: "armor", quality: "uncommon", slot: "hands", armor: 18, stats: { agi: 1 }, sellPrice: 40 },
  { id: "deathlord_sabatons", name: "Deathlord Sabatons", icon: "boots", kind: "armor", quality: "rare", slot: "feet", armor: 62, stats: { str: 4, sta: 3 }, sellPrice: 900 },
  { id: "cryptbone_greaves", name: "Cryptbone Greaves", icon: "chestplate", kind: "armor", quality: "rare", slot: "legs", armor: 150, stats: { str: 6, sta: 5 }, sellPrice: 2800 },
  { id: "cryptbone_pauldrons", name: "Cryptbone Pauldrons", icon: "chestplate", kind: "armor", quality: "rare", slot: "chest", armor: 135, stats: { sta: 5, str: 4 }, sellPrice: 2600 },
  { id: "greyjaw_hide_boots", name: "Greyjaw Hide Boots", icon: "boots", kind: "armor", quality: "uncommon", slot: "feet", armor: 70, stats: { agi: 3, sta: 2 }, sellPrice: 550 },
  { id: "gravewoven_bag", name: "Gravewoven Satchel", icon: "backpack", kind: "armor", quality: "rare", slot: "trinket", armor: 12, stats: { int: 4, spi: 3 }, sellPrice: 1300 },

  { id: "baked_bread", name: "Cottage Loaf", icon: "bread", kind: "consumable", quality: "common", heal: 61, sellPrice: 6, buyPrice: 24, shops: ["shop_eastbrook", "shop_fenbridge", "shop_highwatch"], stack: 20 },
  { id: "spring_water", name: "Cold Well Water", icon: "potionBlue", kind: "consumable", quality: "common", restore: 76, sellPrice: 6, buyPrice: 24, shops: ["shop_eastbrook", "shop_fenbridge", "shop_highwatch"], stack: 20 },
  { id: "minor_healing_potion", name: "Minor Healing Potion", icon: "potionRed", kind: "consumable", quality: "common", heal: 90, sellPrice: 8, buyPrice: 32, shops: ["shop_eastbrook"], stack: 20 },
  { id: "minor_mana_potion", name: "Minor Mana Potion", icon: "potionBlue", kind: "consumable", quality: "common", restore: 120, sellPrice: 8, buyPrice: 32, shops: ["shop_eastbrook"], stack: 20 },
  { id: "lesser_healing_potion", name: "Lesser Healing Potion", icon: "potionRed", kind: "consumable", quality: "common", heal: 150, sellPrice: 16, buyPrice: 64, shops: ["shop_fenbridge"], stack: 20 },
  { id: "healing_potion", name: "Healing Potion", icon: "potionRed", kind: "consumable", quality: "common", heal: 280, sellPrice: 32, buyPrice: 128, shops: ["shop_fenbridge", "shop_highwatch"], stack: 20 },
  { id: "mana_potion", name: "Mana Potion", icon: "potionBlue", kind: "consumable", quality: "common", restore: 360, sellPrice: 32, buyPrice: 128, shops: ["shop_fenbridge", "shop_highwatch"], stack: 20 },
  { id: "trail_hardtack", name: "Highwatch Trail Hardtack", icon: "bread", kind: "consumable", quality: "common", heal: 552, sellPrice: 75, buyPrice: 300, shops: ["shop_highwatch"], stack: 20 },
  { id: "meltwater_flask", name: "Meltwater Flask", icon: "potionBlue", kind: "consumable", quality: "common", restore: 672, sellPrice: 75, buyPrice: 300, shops: ["shop_highwatch"], stack: 20 },
  { id: "tough_jerky", name: "Tough Boar Jerky", icon: "meat", kind: "consumable", quality: "common", heal: 55, sellPrice: 8, stack: 20 },
  { id: "elixir_of_the_bear", name: "Elixir of the Bear", icon: "potionRed", kind: "consumable", quality: "uncommon", heal: 260, sellPrice: 45, stack: 20 },

  { id: "wolf_fang", name: "Cracked Wolf Fang", icon: "skull", kind: "junk", quality: "poor", sellPrice: 4, stack: 20 },
  { id: "bandit_bandana", name: "Red Bandana", icon: "cloak", kind: "junk", quality: "poor", sellPrice: 6, stack: 20 },
  { id: "mudfin_scale", name: "Slimy Mudfin Scale", icon: "fish", kind: "junk", quality: "poor", sellPrice: 5, stack: 20 },
  { id: "tallow_candle", name: "Greasy Tallow Lump", icon: "torch", kind: "junk", quality: "poor", sellPrice: 5, stack: 20 },
  { id: "spider_leg", name: "Twitching Spider Leg", icon: "skull", kind: "junk", quality: "poor", sellPrice: 4, stack: 20 },
  { id: "bone_fragments", name: "Bone Fragments", icon: "skull", kind: "junk", quality: "poor", sellPrice: 7, stack: 20 },
  { id: "linen_scrap", name: "Linen Scrap", icon: "cloak", kind: "junk", quality: "poor", sellPrice: 3, stack: 20 },
  { id: "bogiron_nugget", name: "Bogiron Nugget", icon: "ore", kind: "junk", quality: "poor", sellPrice: 12, stack: 20 },
  { id: "soggy_moccasin", name: "Soggy Moccasin", icon: "boots", kind: "junk", quality: "poor", sellPrice: 9, stack: 20 },
  { id: "cracked_fetish", name: "Cracked Fetish", icon: "skull", kind: "junk", quality: "poor", sellPrice: 14, stack: 20 },
  { id: "chipped_tusk", name: "Chipped Tusk", icon: "skull", kind: "junk", quality: "poor", sellPrice: 15, stack: 20 },
  { id: "deepfen_pearl", name: "Deepfen Pearl", icon: "gem", kind: "junk", quality: "poor", sellPrice: 600, stack: 20 },
  { id: "old_cragmaws_pelt", name: "Old Cragmaw's Pelt", icon: "cloak", kind: "junk", quality: "common", sellPrice: 300, stack: 20 },
  { id: "emberwing_cinderscale", name: "Emberwing Cinderscale", icon: "fire", kind: "junk", quality: "common", sellPrice: 320, stack: 20 },
  { id: "ogre_toe_ring", name: "Ogre Toe Ring", icon: "ring", kind: "junk", quality: "poor", sellPrice: 25, stack: 20 },
  { id: "cracked_ogre_tusk", name: "Cracked Ogre Tusk", icon: "skull", kind: "junk", quality: "poor", sellPrice: 42, stack: 20 },
  { id: "inert_storm_shard", name: "Inert Storm Shard", icon: "crystal", kind: "junk", quality: "poor", sellPrice: 28, stack: 20 },
  { id: "frayed_prayer_beads", name: "Frayed Prayer Beads", icon: "amulet", kind: "junk", quality: "poor", sellPrice: 30, stack: 20 },
  { id: "cracked_wyrm_scale", name: "Cracked Wyrm Scale", icon: "crystal", kind: "junk", quality: "poor", sellPrice: 35, stack: 20 },
  { id: "boar_hide", name: "Bristly Boar Hide", icon: "cloak", kind: "junk", quality: "poor", sellPrice: 8, stack: 20 },
  { id: "webwood_silk", name: "Webwood Silk", icon: "cloak", kind: "junk", quality: "poor", sellPrice: 9, stack: 20 },
  { id: "blessed_wax", name: "Blessed Tallow Wax", icon: "torch", kind: "junk", quality: "poor", sellPrice: 10, stack: 20 },
  { id: "ghostly_essence", name: "Ghostly Essence", icon: "crystal", kind: "junk", quality: "common", sellPrice: 13, stack: 20 },
  { id: "mire_prowler_pelt", name: "Mire Prowler Pelt", icon: "cloak", kind: "junk", quality: "poor", sellPrice: 16, stack: 20 },
  { id: "waterlogged_idol", name: "Waterlogged Idol", icon: "amulet", kind: "junk", quality: "common", sellPrice: 22, stack: 20 },
  { id: "widow_venom_sac", name: "Widow Venom Sac", icon: "poison", kind: "junk", quality: "poor", sellPrice: 18, stack: 20 },
  { id: "troll_fetish", name: "Troll Fetish", icon: "skull", kind: "junk", quality: "poor", sellPrice: 20, stack: 20 },
  { id: "tangled_weed", name: "Tangled Bog Weed", icon: "leaf", kind: "junk", quality: "poor", sellPrice: 12, stack: 20 },
  { id: "ridge_stalker_pelt", name: "Ridge Stalker Pelt", icon: "cloak", kind: "junk", quality: "poor", sellPrice: 32, stack: 20 },
  { id: "glowing_wax", name: "Glowing Deeprock Wax", icon: "torch", kind: "junk", quality: "poor", sellPrice: 30, stack: 20 },
  { id: "blessed_embers", name: "Blessed Embers", icon: "fire", kind: "junk", quality: "common", sellPrice: 38, stack: 20 },
  { id: "wyrmcult_orders", name: "Wyrmcult Orders", icon: "scroll", kind: "junk", quality: "poor", sellPrice: 36, stack: 20 },
  { id: "ritual_phylactery", name: "Ritual Phylactery", icon: "skull", kind: "junk", quality: "common", sellPrice: 42, stack: 20 },

  { id: "greyjaw_fang", name: "Old Greyjaw's Fang", icon: "skull", kind: "quest", quality: "common" },
  { id: "morthen_grimoire", name: "Morthen's Grimoire", icon: "tome", kind: "quest", quality: "common" },
  { id: "kazzix_heartshard", name: "Kazzix's Heartshard", icon: "crystal", kind: "quest", quality: "common" },
  { id: "kings_signet", name: "King's Signet", icon: "ring", kind: "quest", quality: "rare" },
  { id: "storm_core", name: "Storm Core", icon: "crystal", kind: "quest", quality: "common" },
  { id: "gravecaller_sigil", name: "Gravecaller's Sigil", icon: "skull", kind: "quest", quality: "common" },
];

const ITEMS_BY_ID = new Map(ITEMS.map((item) => [item.id, item]));

export function itemDefById(id: string): ItemDef | null {
  return ITEMS_BY_ID.get(id) ?? null;
}
