import type { ItemDef } from "../model";

export const ITEMS: readonly ItemDef[] = [
  { id: "worn_sword", name: "Pitted Shortsword", icon: "sword", kind: "weapon", quality: "common", slot: "mainhand", weapon: { min: 2, max: 5, speed: 2 }, sellPrice: 10, buyPrice: 40, shops: ["shop_eastbrook"] },
  { id: "gnarled_staff", name: "Bogoak Staff", icon: "staff", kind: "weapon", quality: "common", slot: "mainhand", weapon: { min: 3, max: 6, speed: 2.9 }, stats: { int: 1 }, sellPrice: 12, buyPrice: 48, shops: ["shop_eastbrook"] },
  { id: "rusty_dagger", name: "Rusty Dagger", icon: "dagger", kind: "weapon", quality: "common", slot: "mainhand", weapon: { min: 2, max: 4, speed: 1.8 }, sellPrice: 10, buyPrice: 40, shops: ["shop_eastbrook"] },
  { id: "training_mace", name: "Training Mace", icon: "hammer", kind: "weapon", quality: "common", slot: "mainhand", weapon: { min: 2, max: 5, speed: 2.6 }, sellPrice: 10, buyPrice: 40, shops: ["shop_eastbrook"] },
  { id: "rusty_hatchet", name: "Rusty Hatchet", icon: "axe", kind: "weapon", quality: "common", slot: "mainhand", weapon: { min: 2, max: 5, speed: 2.2 }, sellPrice: 10, buyPrice: 40, shops: ["shop_eastbrook"] },
  { id: "redbrook_blade", name: "Redbrook Militia Blade", icon: "sword", kind: "weapon", quality: "uncommon", slot: "mainhand", weapon: { min: 6, max: 11, speed: 2.2 }, stats: { str: 2 }, sellPrice: 120 },
  { id: "apprentice_staff", name: "Vale Apprentice Staff", icon: "staff", kind: "weapon", quality: "uncommon", slot: "mainhand", weapon: { min: 7, max: 12, speed: 3 }, stats: { int: 3, sta: 1 }, sellPrice: 120 },
  { id: "keen_dirk", name: "Keen Dirk", icon: "dagger", kind: "weapon", quality: "uncommon", slot: "mainhand", weapon: { min: 4, max: 8, speed: 1.7 }, stats: { agi: 2 }, sellPrice: 120 },
  { id: "bristleback_maul", name: "Gallowglass Hammer", icon: "hammer", kind: "weapon", quality: "uncommon", slot: "mainhand", weapon: { min: 7, max: 12, speed: 2.8 }, stats: { str: 2, sta: 1 }, sellPrice: 160 },
  { id: "gorraks_cruel_chopper", name: "Gorrak's Cruel Chopper", icon: "axe", kind: "weapon", quality: "uncommon", slot: "mainhand", weapon: { min: 8, max: 13, speed: 2.4 }, stats: { str: 2, sta: 1 }, sellPrice: 180 },
  { id: "tunnelkings_spade", name: "Tunnelking's Spade", icon: "spear", kind: "weapon", quality: "uncommon", slot: "mainhand", weapon: { min: 9, max: 15, speed: 2.7 }, stats: { str: 3, sta: 2 }, sellPrice: 190 },
  { id: "moggers_copper_cudgel", name: "Mogger's Copper Cudgel", icon: "hammer", kind: "weapon", quality: "rare", slot: "mainhand", weapon: { min: 9, max: 15, speed: 2.6 }, stats: { str: 3, sta: 2 }, sellPrice: 850 },
  { id: "moggers_shiv", name: "Mogger's Shiv", icon: "dagger", kind: "weapon", quality: "rare", slot: "mainhand", weapon: { min: 6, max: 11, speed: 1.7 }, stats: { agi: 4, sta: 2 }, sellPrice: 850 },
  { id: "valeborn_spellblade", name: "Valeborn Spellblade", icon: "sword", kind: "weapon", quality: "rare", slot: "mainhand", weapon: { min: 8, max: 14, speed: 2.2 }, stats: { int: 4, spi: 2 }, sellPrice: 850 },
  { id: "eastbrook_arming_sword", name: "Eastbrook Arming Sword", icon: "sword", kind: "weapon", quality: "common", slot: "mainhand", weapon: { min: 5, max: 9, speed: 2.2 }, sellPrice: 140, buyPrice: 560, shops: ["shop_eastbrook"] },
  { id: "bronzework_mace", name: "Bronzework Mace", icon: "hammer", kind: "weapon", quality: "common", slot: "mainhand", weapon: { min: 6, max: 10, speed: 2.6 }, sellPrice: 140, buyPrice: 560, shops: ["shop_eastbrook"] },
  { id: "vale_carving_knife", name: "Vale Carving Knife", icon: "dagger", kind: "weapon", quality: "common", slot: "mainhand", weapon: { min: 4, max: 7, speed: 1.8 }, sellPrice: 120, buyPrice: 480, shops: ["shop_eastbrook"] },
  { id: "hickory_shortstaff", name: "Hickory Shortstaff", icon: "staff", kind: "weapon", quality: "common", slot: "mainhand", weapon: { min: 6, max: 11, speed: 3 }, stats: { int: 1 }, sellPrice: 150, buyPrice: 600, shops: ["shop_eastbrook"] },
  { id: "gravecaller_blade", name: "Gravecaller's Broadblade", icon: "sword", kind: "weapon", quality: "rare", slot: "mainhand", weapon: { min: 9, max: 16, speed: 2.4 }, stats: { str: 4, sta: 3 }, sellPrice: 800 },
  { id: "widowfang_dirk", name: "Widowfang Dirk", icon: "dagger", kind: "weapon", quality: "rare", slot: "mainhand", weapon: { min: 6, max: 10, speed: 1.7 }, stats: { agi: 4, sta: 3 }, sellPrice: 800 },
  { id: "gravecaller_staff", name: "Staff of the Hollow", icon: "staff", kind: "weapon", quality: "rare", slot: "mainhand", weapon: { min: 10, max: 17, speed: 3 }, stats: { int: 5, spi: 2 }, sellPrice: 800 },
  { id: "verlans_oathblade", name: "Verlan's Oathblade", icon: "sword", kind: "weapon", quality: "rare", slot: "mainhand", weapon: { min: 10, max: 16, speed: 2.5 }, stats: { str: 4, sta: 2 }, sellPrice: 880 },
  { id: "hollow_vigil_staff", name: "Staff of the Hollow Vigil", icon: "staff", kind: "weapon", quality: "rare", slot: "mainhand", weapon: { min: 11, max: 18, speed: 3 }, stats: { int: 5, spi: 2 }, sellPrice: 880 },
  { id: "gravewardens_shiv", name: "Gravewarden's Shiv", icon: "dagger", kind: "weapon", quality: "rare", slot: "mainhand", weapon: { min: 7, max: 11, speed: 1.7 }, stats: { agi: 4, sta: 2 }, sellPrice: 880 },
  { id: "maldrecs_soulbinder", name: "Maldrec's Soulbinder", icon: "sword", kind: "weapon", quality: "rare", slot: "mainhand", weapon: { min: 11, max: 18, speed: 3 }, stats: { int: 4, spi: 3 }, sellPrice: 850 },
  { id: "gorraks_cleaver", name: "Gorrak's Cleaver", icon: "axe", kind: "weapon", quality: "uncommon", slot: "mainhand", weapon: { min: 8, max: 14, speed: 2.5 }, stats: { str: 3 }, sellPrice: 180 },
  { id: "crossroads_saber", name: "Crossroads Saber", icon: "sword", kind: "weapon", quality: "uncommon", slot: "mainhand", weapon: { min: 8, max: 14, speed: 2.5 }, stats: { str: 2 }, sellPrice: 170 },
  { id: "tradesman_hatchet", name: "Tradesman's Hatchet", icon: "axe", kind: "weapon", quality: "uncommon", slot: "mainhand", weapon: { min: 7, max: 13, speed: 2.3 }, stats: { str: 1, sta: 1 }, sellPrice: 160 },
  { id: "drovers_staff", name: "Drover's Staff", icon: "staff", kind: "weapon", quality: "uncommon", slot: "mainhand", weapon: { min: 9, max: 15, speed: 3 }, stats: { int: 3, spi: 2 }, sellPrice: 175 },
  { id: "caravan_warden_dirk", name: "Caravan Warden Dirk", icon: "dagger", kind: "weapon", quality: "uncommon", slot: "mainhand", weapon: { min: 5, max: 9, speed: 1.7 }, stats: { agi: 3 }, sellPrice: 170 },
  { id: "deacons_cleaver", name: "Deacon's Cleaver", icon: "axe", kind: "weapon", quality: "uncommon", slot: "mainhand", weapon: { min: 11, max: 18, speed: 2.4 }, stats: { str: 4 }, sellPrice: 300 },
  { id: "staff_of_drowned_prayers", name: "Staff of Drowned Prayers", icon: "staff", kind: "weapon", quality: "uncommon", slot: "mainhand", weapon: { min: 12, max: 20, speed: 3 }, stats: { int: 5, spi: 2 }, sellPrice: 300 },
  { id: "mistbinder_kris", name: "Mistbinder Kris", icon: "dagger", kind: "weapon", quality: "uncommon", slot: "mainhand", weapon: { min: 7, max: 12, speed: 1.7 }, stats: { agi: 4 }, sellPrice: 300 },
  { id: "voss_sanctified_mace", name: "Voss's Sanctified Mace", icon: "hammer", kind: "weapon", quality: "uncommon", slot: "mainhand", weapon: { min: 12, max: 20, speed: 2.6 }, stats: { int: 3, spi: 2 }, sellPrice: 420 },
  { id: "mirejaw_biteblade", name: "Mirejaw Biteblade", icon: "dagger", kind: "weapon", quality: "uncommon", slot: "mainhand", weapon: { min: 8, max: 14, speed: 1.7 }, stats: { agi: 5, sta: 2 }, sellPrice: 480 },
  { id: "tidereaver_gaff", name: "Tidereaver Gaff", icon: "spear", kind: "weapon", quality: "rare", slot: "mainhand", weapon: { min: 17, max: 28, speed: 2.5 }, stats: { str: 5, sta: 4 }, sellPrice: 1400 },
  { id: "sloomtooth_tidefang", name: "Sloomtooth's Tidefang", icon: "dagger", kind: "weapon", quality: "rare", slot: "mainhand", weapon: { min: 10, max: 17, speed: 1.7 }, stats: { agi: 6, sta: 3 }, sellPrice: 1400 },
  { id: "drowned_tide_scepter", name: "Drowned Tide Scepter", icon: "sword", kind: "weapon", quality: "rare", slot: "mainhand", weapon: { min: 16, max: 28, speed: 3 }, stats: { int: 6, spi: 3 }, sellPrice: 1400 },
  { id: "fen_reaver_glaive", name: "Fen Reaver Glaive", icon: "spear", kind: "weapon", quality: "rare", slot: "mainhand", weapon: { min: 16, max: 26, speed: 2.4 }, stats: { str: 5, sta: 3 }, sellPrice: 1400 },
  { id: "nhalias_dirgeblade", name: "Nhalia's Dirgeblade", icon: "dagger", kind: "weapon", quality: "rare", slot: "mainhand", weapon: { min: 10, max: 16, speed: 1.7 }, stats: { agi: 6, sta: 3 }, sellPrice: 1400 },
  { id: "mirejaw_oracle_staff", name: "Mirejaw Oracle Staff", icon: "staff", kind: "weapon", quality: "rare", slot: "mainhand", weapon: { min: 16, max: 27, speed: 3 }, stats: { int: 6, spi: 3 }, sellPrice: 1400 },
  { id: "mistcallers_edge", name: "Fogbinder's Edge", icon: "sword", kind: "weapon", quality: "rare", slot: "mainhand", weapon: { min: 14, max: 23, speed: 2.3 }, stats: { str: 4, sta: 3 }, sellPrice: 1200 },
  { id: "vaels_mist_staff", name: "Vael's Mist-Staff", icon: "staff", kind: "weapon", quality: "rare", slot: "mainhand", weapon: { min: 15, max: 26, speed: 3 }, stats: { int: 6, spi: 3 }, sellPrice: 1200 },
  { id: "riptide_dirk", name: "Riptide Dirk", icon: "dagger", kind: "weapon", quality: "rare", slot: "mainhand", weapon: { min: 9, max: 15, speed: 1.7 }, stats: { agi: 5, sta: 2 }, sellPrice: 1200 },
  { id: "bogiron_mace", name: "Bogiron Mace", icon: "hammer", kind: "weapon", quality: "common", slot: "mainhand", weapon: { min: 8, max: 14, speed: 2.6 }, sellPrice: 250, buyPrice: 1000, shops: ["shop_fenbridge"] },
  { id: "fenreed_staff", name: "Fenreed Staff", icon: "staff", kind: "weapon", quality: "common", slot: "mainhand", weapon: { min: 9, max: 16, speed: 3 }, stats: { int: 1 }, sellPrice: 250, buyPrice: 1000, shops: ["shop_fenbridge"] },
  { id: "mirefen_skinner", name: "Mirefen Skinner", icon: "dagger", kind: "weapon", quality: "common", slot: "mainhand", weapon: { min: 6, max: 10, speed: 1.8 }, sellPrice: 250, buyPrice: 1000, shops: ["shop_fenbridge"] },
  { id: "zealotsbane_blade", name: "Zealotsbane Blade", icon: "sword", kind: "weapon", quality: "uncommon", slot: "mainhand", weapon: { min: 18, max: 29, speed: 2.3 }, stats: { str: 6, sta: 2 }, sellPrice: 900 },
  { id: "emberwood_staff", name: "Emberwood Staff", icon: "staff", kind: "weapon", quality: "uncommon", slot: "mainhand", weapon: { min: 20, max: 33, speed: 3 }, stats: { int: 6, spi: 2 }, sellPrice: 900 },
  { id: "cultist_flayer", name: "Cultist Flayer", icon: "dagger", kind: "weapon", quality: "uncommon", slot: "mainhand", weapon: { min: 12, max: 19, speed: 1.7 }, stats: { agi: 8 }, sellPrice: 900 },
  { id: "ironvein_pickblade", name: "Ironvein Pickblade", icon: "dagger", kind: "weapon", quality: "uncommon", slot: "mainhand", weapon: { min: 13, max: 21, speed: 1.8 }, stats: { agi: 7, sta: 2 }, sellPrice: 950 },
  { id: "ironvein_lantern_staff", name: "Ironvein Lantern Staff", icon: "staff", kind: "weapon", quality: "uncommon", slot: "mainhand", weapon: { min: 19, max: 31, speed: 3 }, stats: { int: 7, spi: 3 }, sellPrice: 950 },
  { id: "emberfang_warblade", name: "Emberfang Warblade", icon: "sword", kind: "weapon", quality: "rare", slot: "mainhand", weapon: { min: 26, max: 41, speed: 2.5 }, stats: { str: 8, sta: 3 }, sellPrice: 2400 },
  { id: "brutoks_maul", name: "Brutok's Maul", icon: "hammer", kind: "weapon", quality: "rare", slot: "mainhand", weapon: { min: 24, max: 37, speed: 2.7 }, stats: { str: 8, sta: 3 }, sellPrice: 2000 },
  { id: "crag_warden_cudgel", name: "Crag Warden Cudgel", icon: "hammer", kind: "weapon", quality: "rare", slot: "mainhand", weapon: { min: 23, max: 36, speed: 3 }, stats: { int: 8, spi: 4 }, sellPrice: 2000 },
  { id: "skullsplitter_dirk", name: "Skullsplitter Dirk", icon: "dagger", kind: "weapon", quality: "rare", slot: "mainhand", weapon: { min: 15, max: 23, speed: 1.7 }, stats: { agi: 8, sta: 3 }, sellPrice: 2000 },
  { id: "drogmars_skullcleaver", name: "Drogmar's Skullcleaver", icon: "axe", kind: "weapon", quality: "rare", slot: "mainhand", weapon: { min: 22, max: 35, speed: 2.6 }, stats: { str: 7, sta: 4 }, sellPrice: 2000 },
  { id: "ogre_bonecharm_staff", name: "Ogre Bonecharm Staff", icon: "staff", kind: "weapon", quality: "rare", slot: "mainhand", weapon: { min: 24, max: 38, speed: 3 }, stats: { int: 9, spi: 4 }, sellPrice: 2000 },
  { id: "gutripper_shiv", name: "Gutripper Shiv", icon: "dagger", kind: "weapon", quality: "rare", slot: "mainhand", weapon: { min: 14, max: 22, speed: 1.7 }, stats: { agi: 8, sta: 3 }, sellPrice: 2000 },
  { id: "staff_of_velkhar", name: "Staff of Velkhar", icon: "staff", kind: "weapon", quality: "rare", slot: "mainhand", weapon: { min: 27, max: 43, speed: 3 }, stats: { int: 9, spi: 4 }, sellPrice: 2500 },
  { id: "wyrmfang_greatblade", name: "Wyrmfang Greatblade", icon: "sword", kind: "weapon", quality: "epic", slot: "mainhand", weapon: { min: 30, max: 48, speed: 2.6 }, stats: { str: 11, sta: 7 }, sellPrice: 8000 },
  { id: "staff_of_the_gravewyrm", name: "Staff of the Gravewyrm", icon: "staff", kind: "weapon", quality: "epic", slot: "mainhand", weapon: { min: 32, max: 52, speed: 3 }, stats: { int: 12, spi: 6 }, sellPrice: 8000 },
  { id: "fang_of_korzul", name: "Fang of Korzul", icon: "dagger", kind: "weapon", quality: "epic", slot: "mainhand", weapon: { min: 19, max: 30, speed: 1.7 }, stats: { agi: 12, sta: 6 }, sellPrice: 8000 },
  { id: "highwatch_warblade", name: "Highwatch Warblade", icon: "sword", kind: "weapon", quality: "common", slot: "mainhand", weapon: { min: 15, max: 24, speed: 2.3 }, sellPrice: 600, buyPrice: 2400, shops: ["shop_highwatch"] },
  { id: "craghorn_staff", name: "Craghorn Staff", icon: "staff", kind: "weapon", quality: "common", slot: "mainhand", weapon: { min: 16, max: 27, speed: 3 }, stats: { int: 2 }, sellPrice: 600, buyPrice: 2400, shops: ["shop_highwatch"] },
  { id: "icevein_dirk", name: "Icevein Dirk", icon: "dagger", kind: "weapon", quality: "common", slot: "mainhand", weapon: { min: 10, max: 16, speed: 1.8 }, sellPrice: 600, buyPrice: 2400, shops: ["shop_highwatch"] },
  { id: "recruit_tunic", name: "Levyman's Tunic", icon: "chestplate", kind: "armor", quality: "common", slot: "chest", armor: 20, sellPrice: 5 },
  { id: "apprentice_robe", name: "Threadbare Robe", icon: "chestplate", kind: "armor", quality: "common", slot: "chest", armor: 8, sellPrice: 5 },
  { id: "footpad_jerkin", name: "Cutpurse Jerkin", icon: "chestplate", kind: "armor", quality: "common", slot: "chest", armor: 14, sellPrice: 5 },
  { id: "militia_vest", name: "Militia Chainvest", icon: "chestplate", kind: "armor", quality: "uncommon", slot: "chest", armor: 90, stats: { sta: 2 }, sellPrice: 150 },
  { id: "woven_robe", name: "Valewoven Robe", icon: "chestplate", kind: "armor", quality: "uncommon", slot: "chest", armor: 30, stats: { int: 3, spi: 2 }, sellPrice: 150 },
  { id: "shadow_jerkin", name: "Shadowstitch Jerkin", icon: "chestplate", kind: "armor", quality: "uncommon", slot: "chest", armor: 55, stats: { agi: 3 }, sellPrice: 150 },
  { id: "oiled_boots", name: "Oiled Leather Boots", icon: "boots", kind: "armor", quality: "uncommon", slot: "feet", armor: 25, stats: { agi: 1 }, sellPrice: 80 },
  { id: "quilted_trousers", name: "Quilted Trousers", icon: "chestplate", kind: "armor", quality: "uncommon", slot: "legs", armor: 30, stats: { sta: 2 }, sellPrice: 90 },
  { id: "greyjaw_pelt_cloak", name: "Greyjaw's Pelt Leggings", icon: "chestplate", kind: "armor", quality: "uncommon", slot: "legs", armor: 35, stats: { sta: 1, agi: 1 }, sellPrice: 110 },
  { id: "greyjaw_hide_boots", name: "Greyjaw Hide Boots", icon: "boots", kind: "armor", quality: "uncommon", slot: "feet", armor: 28, stats: { agi: 1, sta: 1 }, sellPrice: 130 },
  { id: "sableweb_slippers", name: "Sableweb Slippers", icon: "boots", kind: "armor", quality: "uncommon", slot: "feet", armor: 18, stats: { int: 2, spi: 1 }, sellPrice: 150 },
  { id: "moggers_stomper_boots", name: "Mogger's Stomper Boots", icon: "boots", kind: "armor", quality: "uncommon", slot: "feet", armor: 32, stats: { agi: 2, sta: 1 }, sellPrice: 180 },
  { id: "cryptbone_greaves", name: "Cryptbone Greaves", icon: "chestplate", kind: "armor", quality: "uncommon", slot: "legs", armor: 48, stats: { sta: 2 }, sellPrice: 180 },
  { id: "cryptbone_helm", name: "Cryptbone Helm", icon: "helmet", kind: "armor", quality: "uncommon", slot: "helmet", armor: 48, stats: { sta: 3 }, sellPrice: 185 },
  { id: "cryptbone_pauldrons", name: "Cryptbone Pauldrons", icon: "chestplate", kind: "armor", quality: "uncommon", slot: "shoulder", armor: 36, stats: { sta: 2 }, sellPrice: 140 },
  { id: "mistveil_cord", name: "Mistveil Cord", icon: "chestplate", kind: "armor", quality: "uncommon", slot: "waist", armor: 30, stats: { sta: 2, agi: 1 }, sellPrice: 150 },
  { id: "mistveil_grips", name: "Mistveil Grips", icon: "gauntlet", kind: "armor", quality: "uncommon", slot: "gloves", armor: 36, stats: { agi: 2, sta: 1 }, sellPrice: 165 },
  { id: "boundstone_helm", name: "Boundstone Helm", icon: "helmet", kind: "armor", quality: "rare", slot: "helmet", armor: 105, stats: { sta: 6, str: 5 }, sellPrice: 460 },
  { id: "boundstone_girdle", name: "Boundstone Girdle", icon: "chestplate", kind: "armor", quality: "rare", slot: "waist", armor: 60, stats: { sta: 6, str: 3 }, sellPrice: 340 },
  { id: "gravewyrm_mantle", name: "Gravewyrm Mantle", icon: "chestplate", kind: "armor", quality: "rare", slot: "shoulder", armor: 82, stats: { agi: 7, sta: 3 }, sellPrice: 410 },
  { id: "gravewyrm_gauntlets", name: "Gravewyrm Gauntlets", icon: "gauntlet", kind: "armor", quality: "rare", slot: "gloves", armor: 72, stats: { str: 5, sta: 4 }, sellPrice: 390 },
  { id: "wolfhide_satchel", name: "Wolfhide Satchel", icon: "backpack", kind: "armor", quality: "uncommon", slot: "trinket", armor: 3, stats: { agi: 1, sta: 1 }, sellPrice: 45 },
  { id: "gravewoven_bag", name: "Gravewoven Satchel", icon: "backpack", kind: "armor", quality: "rare", slot: "trinket", armor: 12, stats: { int: 4, spi: 3 }, sellPrice: 1300 },
  { id: "eastbrook_chain_vest", name: "Eastbrook Chainmail Vest", icon: "chestplate", kind: "armor", quality: "common", slot: "chest", armor: 60, sellPrice: 180, buyPrice: 720, shops: ["shop_eastbrook"] },
  { id: "valespun_robe", name: "Valespun Robe", icon: "chestplate", kind: "armor", quality: "common", slot: "chest", armor: 22, sellPrice: 140, buyPrice: 560, shops: ["shop_eastbrook"] },
  { id: "tanned_leather_jerkin", name: "Tanned Leather Jerkin", icon: "chestplate", kind: "armor", quality: "common", slot: "chest", armor: 40, sellPrice: 160, buyPrice: 640, shops: ["shop_eastbrook"] },
  { id: "hobnail_boots", name: "Hobnailed Boots", icon: "boots", kind: "armor", quality: "common", slot: "feet", armor: 18, sellPrice: 90, buyPrice: 360, shops: ["shop_eastbrook"] },
  { id: "eastbrook_wool_trousers", name: "Eastbrook Wool Trousers", icon: "chestplate", kind: "armor", quality: "common", slot: "legs", armor: 24, sellPrice: 110, buyPrice: 440, shops: ["shop_eastbrook"] },
  { id: "marrowtread_boots", name: "Marrowtread Boots", icon: "boots", kind: "armor", quality: "rare", slot: "feet", armor: 45, stats: { sta: 2, str: 1 }, sellPrice: 500 },
  { id: "sextons_slippers", name: "Sexton's Slippers", icon: "boots", kind: "armor", quality: "rare", slot: "feet", armor: 20, stats: { int: 2, spi: 2 }, sellPrice: 500 },
  { id: "gravewalker_softboots", name: "Gravewalker Softboots", icon: "boots", kind: "armor", quality: "rare", slot: "feet", armor: 32, stats: { agi: 3 }, sellPrice: 500 },
  { id: "hollowbone_hauberk", name: "Hollowbone Hauberk", icon: "chestplate", kind: "armor", quality: "rare", slot: "chest", armor: 105, stats: { str: 3, sta: 3 }, sellPrice: 700 },
  { id: "gravewoven_raiment", name: "Gravewoven Raiment", icon: "chestplate", kind: "armor", quality: "rare", slot: "chest", armor: 38, stats: { int: 3, spi: 3 }, sellPrice: 700 },
  { id: "cryptstalker_jerkin", name: "Gravestalker Jerkin", icon: "chestplate", kind: "armor", quality: "rare", slot: "chest", armor: 65, stats: { agi: 4, sta: 2 }, sellPrice: 700 },
  { id: "hollowbound_legguards", name: "Hollowbound Legguards", icon: "chestplate", kind: "armor", quality: "rare", slot: "legs", armor: 62, stats: { sta: 3 }, sellPrice: 600 },
  { id: "gravepath_treads", name: "Gravepath Treads", icon: "boots", kind: "armor", quality: "rare", slot: "feet", armor: 42, stats: { sta: 2 }, sellPrice: 600 },
  { id: "oathbound_greaves", name: "Oathbound Greaves", icon: "chestplate", kind: "armor", quality: "uncommon", slot: "legs", armor: 52, stats: { sta: 2, str: 1 }, sellPrice: 200 },
  { id: "bramblehide_jerkin", name: "Bramblehide Jerkin", icon: "chestplate", kind: "armor", quality: "uncommon", slot: "chest", armor: 40, stats: { sta: 2, agi: 1 }, sellPrice: 120 },
  { id: "monarch_crown_helm", name: "Monarch's Crown", icon: "helmet", kind: "armor", quality: "rare", slot: "helmet", armor: 46, stats: { sta: 3, agi: 2, str: 1 }, sellPrice: 320 },
  { id: "roadwardens_helm", name: "Roadwarden's Helm", icon: "helmet", kind: "armor", quality: "uncommon", slot: "helmet", armor: 45, stats: { sta: 2 }, sellPrice: 130 },
  { id: "wayfarers_hood", name: "Wayfarer's Hood", icon: "helmet", kind: "armor", quality: "uncommon", slot: "helmet", armor: 30, stats: { agi: 2 }, sellPrice: 120 },
  { id: "acolytes_circlet", name: "Acolyte's Circlet", icon: "helmet", kind: "armor", quality: "uncommon", slot: "helmet", armor: 16, stats: { int: 2, spi: 1 }, sellPrice: 120 },
  { id: "reinforced_pauldrons", name: "Reinforced Pauldrons", icon: "chestplate", kind: "armor", quality: "uncommon", slot: "shoulder", armor: 50, stats: { str: 1, sta: 1 }, sellPrice: 140 },
  { id: "embroidered_mantle", name: "Embroidered Mantle", icon: "chestplate", kind: "armor", quality: "uncommon", slot: "shoulder", armor: 14, stats: { int: 2 }, sellPrice: 110 },
  { id: "sturdy_belt", name: "Sturdy Traveler's Belt", icon: "chestplate", kind: "armor", quality: "uncommon", slot: "waist", armor: 35, stats: { sta: 2 }, sellPrice: 100 },
  { id: "silk_sash", name: "Woven Silk Sash", icon: "chestplate", kind: "armor", quality: "uncommon", slot: "waist", armor: 10, stats: { int: 2, spi: 1 }, sellPrice: 100 },
  { id: "roughspun_gloves", name: "Roughspun Gloves", icon: "gauntlet", kind: "armor", quality: "uncommon", slot: "gloves", armor: 28, stats: { agi: 1, sta: 1 }, sellPrice: 95 },
  { id: "bristlehide_spaulders", name: "Bristlehide Spaulders", icon: "chestplate", kind: "armor", quality: "uncommon", slot: "shoulder", armor: 40, stats: { agi: 1, sta: 2 }, sellPrice: 150 },
  { id: "sableweb_cord", name: "Sableweb Cord", icon: "chestplate", kind: "armor", quality: "uncommon", slot: "waist", armor: 11, stats: { agi: 1, int: 2 }, sellPrice: 150 },
  { id: "mossy_handwraps", name: "Mossgrown Handwraps", icon: "gauntlet", kind: "armor", quality: "uncommon", slot: "gloves", armor: 12, stats: { int: 1, spi: 2 }, sellPrice: 140 },
  { id: "outrider_brigandine", name: "Outrider Brigandine", icon: "chestplate", kind: "armor", quality: "uncommon", slot: "chest", armor: 95, stats: { str: 1, sta: 2 }, sellPrice: 165 },
  { id: "caravan_quilted_vest", name: "Caravan Quilted Vest", icon: "chestplate", kind: "armor", quality: "uncommon", slot: "chest", armor: 40, stats: { sta: 2 }, sellPrice: 130 },
  { id: "wanderers_chestguard", name: "Wanderer's Chestguard", icon: "chestplate", kind: "armor", quality: "uncommon", slot: "chest", armor: 60, stats: { agi: 2, sta: 1 }, sellPrice: 150 },
  { id: "outrider_legguards", name: "Outrider Legguards", icon: "chestplate", kind: "armor", quality: "uncommon", slot: "legs", armor: 70, stats: { sta: 2 }, sellPrice: 150 },
  { id: "trail_leggings", name: "Trailworn Leggings", icon: "chestplate", kind: "armor", quality: "uncommon", slot: "legs", armor: 45, stats: { agi: 2 }, sellPrice: 120 },
  { id: "pilgrims_leggings", name: "Pilgrim's Leggings", icon: "chestplate", kind: "armor", quality: "uncommon", slot: "legs", armor: 24, stats: { int: 2, spi: 1 }, sellPrice: 120 },
  { id: "outrider_sabatons", name: "Outrider Sabatons", icon: "boots", kind: "armor", quality: "uncommon", slot: "feet", armor: 55, stats: { sta: 2 }, sellPrice: 130 },
  { id: "milepost_boots", name: "Milepost Boots", icon: "boots", kind: "armor", quality: "uncommon", slot: "feet", armor: 30, stats: { agi: 1, sta: 1 }, sellPrice: 110 },
  { id: "drownedguard_breastplate", name: "Drownedguard Breastplate", icon: "chestplate", kind: "armor", quality: "uncommon", slot: "chest", armor: 130, stats: { sta: 4 }, sellPrice: 350 },
  { id: "fenmist_robe", name: "Fenmist Robe", icon: "chestplate", kind: "armor", quality: "uncommon", slot: "chest", armor: 45, stats: { int: 5, spi: 3 }, sellPrice: 350 },
  { id: "eelskin_tunic", name: "Eelskin Tunic", icon: "chestplate", kind: "armor", quality: "uncommon", slot: "chest", armor: 80, stats: { agi: 5 }, sellPrice: 350 },
  { id: "trollhide_leggings", name: "Trollhide Leggings", icon: "chestplate", kind: "armor", quality: "uncommon", slot: "legs", armor: 55, stats: { sta: 3, str: 2 }, sellPrice: 280 },
  { id: "marshstrider_boots", name: "Marshstrider Boots", icon: "boots", kind: "armor", quality: "uncommon", slot: "feet", armor: 40, stats: { agi: 2, sta: 2 }, sellPrice: 250 },
  { id: "broodmother_silk_robe", name: "Broodmother's Silk Robe", icon: "chestplate", kind: "armor", quality: "uncommon", slot: "chest", armor: 42, stats: { int: 4, spi: 2 }, sellPrice: 300 },
  { id: "mirejaw_scale_vest", name: "Mirejaw Scale Vest", icon: "chestplate", kind: "armor", quality: "uncommon", slot: "chest", armor: 115, stats: { str: 2, sta: 3 }, sellPrice: 480 },
  { id: "nhalias_funeral_wraps", name: "Nhalia's Funeral Wraps", icon: "chestplate", kind: "armor", quality: "uncommon", slot: "legs", armor: 48, stats: { int: 5, spi: 2 }, sellPrice: 480 },
  { id: "knight_commanders_greaves", name: "Knight-Commander's Greaves", icon: "chestplate", kind: "armor", quality: "rare", slot: "legs", armor: 95, stats: { sta: 4 }, sellPrice: 1000 },
  { id: "tidescale_vest", name: "Tidescale Vest", icon: "chestplate", kind: "armor", quality: "rare", slot: "chest", armor: 90, stats: { sta: 3, agi: 2 }, sellPrice: 1100 },
  { id: "tideguard_greaves", name: "Tideguard Greaves", icon: "chestplate", kind: "armor", quality: "rare", slot: "legs", armor: 125, stats: { str: 3, sta: 5 }, sellPrice: 1100 },
  { id: "tideguard_sabatons", name: "Tideguard Sabatons", icon: "boots", kind: "armor", quality: "rare", slot: "feet", armor: 105, stats: { str: 2, sta: 4 }, sellPrice: 1100 },
  { id: "drowned_prayer_leggings", name: "Drowned Prayer Leggings", icon: "chestplate", kind: "armor", quality: "rare", slot: "legs", armor: 48, stats: { int: 6, spi: 4 }, sellPrice: 1100 },
  { id: "drowned_prayer_sandals", name: "Drowned Prayer Sandals", icon: "boots", kind: "armor", quality: "rare", slot: "feet", armor: 42, stats: { int: 5, spi: 3 }, sellPrice: 1100 },
  { id: "eelscale_leggings", name: "Eelscale Leggings", icon: "chestplate", kind: "armor", quality: "rare", slot: "legs", armor: 86, stats: { agi: 6, sta: 3 }, sellPrice: 1100 },
  { id: "eelscale_treads", name: "Eelscale Treads", icon: "boots", kind: "armor", quality: "rare", slot: "feet", armor: 72, stats: { agi: 5, sta: 3 }, sellPrice: 1100 },
  { id: "bogiron_hauberk", name: "Bogiron Hauberk", icon: "chestplate", kind: "armor", quality: "common", slot: "chest", armor: 100, sellPrice: 300, buyPrice: 1200, shops: ["shop_fenbridge"] },
  { id: "marshcloth_robe", name: "Marshcloth Robe", icon: "chestplate", kind: "armor", quality: "common", slot: "chest", armor: 32, sellPrice: 200, buyPrice: 800, shops: ["shop_fenbridge"] },
  { id: "reedwoven_jerkin", name: "Reedwoven Jerkin", icon: "chestplate", kind: "armor", quality: "common", slot: "chest", armor: 62, sellPrice: 250, buyPrice: 1000, shops: ["shop_fenbridge"] },
  { id: "fenwalker_boots", name: "Fenwalker Boots", icon: "boots", kind: "armor", quality: "common", slot: "feet", armor: 30, sellPrice: 150, buyPrice: 600, shops: ["shop_fenbridge"] },
  { id: "reedwoven_trousers", name: "Reedwoven Trousers", icon: "chestplate", kind: "armor", quality: "common", slot: "legs", armor: 40, sellPrice: 180, buyPrice: 720, shops: ["shop_fenbridge"] },
  { id: "ridgestalker_treads", name: "Ridgestalker Treads", icon: "boots", kind: "armor", quality: "uncommon", slot: "feet", armor: 50, stats: { agi: 3, sta: 2 }, sellPrice: 600 },
  { id: "cragmaw_prowlboots", name: "Cragmaw Prowlboots", icon: "boots", kind: "armor", quality: "rare", slot: "feet", armor: 58, stats: { agi: 5, sta: 3 }, sellPrice: 750 },
  { id: "cragmaw_huntcord", name: "Cragmaw's Huntcord", icon: "chestplate", kind: "armor", quality: "rare", slot: "waist", armor: 44, stats: { agi: 5, sta: 3 }, sellPrice: 340 },
  { id: "boneplate_vest", name: "Boneplate Vest", icon: "chestplate", kind: "armor", quality: "uncommon", slot: "chest", armor: 170, stats: { sta: 5, str: 3 }, sellPrice: 800 },
  { id: "revenant_silk_robe", name: "Revenant Silk Robe", icon: "chestplate", kind: "armor", quality: "uncommon", slot: "chest", armor: 60, stats: { int: 5, spi: 3 }, sellPrice: 800 },
  { id: "nightwalk_jerkin", name: "Nightwalk Jerkin", icon: "chestplate", kind: "armor", quality: "uncommon", slot: "chest", armor: 105, stats: { agi: 6, sta: 2 }, sellPrice: 800 },
  { id: "drogmar_warboots", name: "Drogmar's Warboots", icon: "boots", kind: "armor", quality: "uncommon", slot: "feet", armor: 85, stats: { str: 3, sta: 4 }, sellPrice: 950 },
  { id: "marrowlord_boneboots", name: "Marrowlord Boneboots", icon: "boots", kind: "armor", quality: "uncommon", slot: "feet", armor: 90, stats: { sta: 5, str: 2 }, sellPrice: 1050 },
  { id: "skullsmasher_warbelt", name: "Skullsmasher's Warbelt", icon: "chestplate", kind: "armor", quality: "uncommon", slot: "chest", armor: 96, stats: { sta: 5, str: 3 }, sellPrice: 1050 },
  { id: "emberwing_legguards", name: "Emberwing Legguards", icon: "chestplate", kind: "armor", quality: "rare", slot: "legs", armor: 120, stats: { sta: 6, str: 4 }, sellPrice: 2200 },
  { id: "stormshard_leggings", name: "Stormshard Leggings", icon: "chestplate", kind: "armor", quality: "rare", slot: "legs", armor: 110, stats: { sta: 5 }, sellPrice: 1800 },
  { id: "korgaths_chainwraps", name: "Korgath's Chainwraps", icon: "chestplate", kind: "armor", quality: "rare", slot: "legs", armor: 125, stats: { sta: 12 }, sellPrice: 2200 },
  { id: "boneguard_breastplate", name: "Boneguard Breastplate", icon: "chestplate", kind: "armor", quality: "rare", slot: "chest", armor: 210, stats: { sta: 8, str: 5 }, sellPrice: 2500 },
  { id: "shadowmeld_tunic", name: "Nightveil Tunic", icon: "chestplate", kind: "armor", quality: "rare", slot: "chest", armor: 130, stats: { agi: 9, sta: 4 }, sellPrice: 2500 },
  { id: "gravewyrm_scale_hauberk", name: "Gravewyrm Scale Hauberk", icon: "chestplate", kind: "armor", quality: "rare", slot: "chest", armor: 230, stats: { sta: 8, str: 5 }, sellPrice: 3000 },
  { id: "wyrmcult_grand_robe", name: "Wyrmcult Grand Robe", icon: "chestplate", kind: "armor", quality: "rare", slot: "chest", armor: 75, stats: { int: 9, spi: 4 }, sellPrice: 3000 },
  { id: "wyrmscale_jerkin", name: "Wyrmscale Jerkin", icon: "chestplate", kind: "armor", quality: "rare", slot: "chest", armor: 145, stats: { agi: 9, sta: 4 }, sellPrice: 3000 },
  { id: "gravewyrm_stalkers_treads", name: "Gravewyrm Stalker's Treads", icon: "boots", kind: "armor", quality: "rare", slot: "feet", armor: 105, stats: { agi: 5, sta: 3 }, sellPrice: 3200 },
  { id: "gravewyrm_sabatons", name: "Gravewyrm Sabatons", icon: "boots", kind: "armor", quality: "rare", slot: "feet", armor: 145, stats: { str: 4, sta: 4 }, sellPrice: 3200 },
  { id: "wyrmcult_soulsteps", name: "Wyrmcult Soulsteps", icon: "boots", kind: "armor", quality: "rare", slot: "feet", armor: 68, stats: { int: 5, spi: 3 }, sellPrice: 3200 },
  { id: "deathlord_warplate", name: "Barrowlord Warplate", icon: "chestplate", kind: "armor", quality: "epic", slot: "chest", armor: 270, stats: { str: 8, sta: 10 }, sellPrice: 9000 },
  { id: "necromancers_starshroud", name: "Mournweave Starshroud", icon: "chestplate", kind: "armor", quality: "epic", slot: "chest", armor: 92, stats: { int: 11, spi: 7 }, sellPrice: 9000 },
  { id: "wyrmshadow_harness", name: "Nightfang Harness", icon: "chestplate", kind: "armor", quality: "epic", slot: "chest", armor: 170, stats: { agi: 12, sta: 6 }, sellPrice: 9000 },
  { id: "deathlord_legguards", name: "Barrowlord Legguards", icon: "chestplate", kind: "armor", quality: "epic", slot: "legs", armor: 240, stats: { str: 8, sta: 8 }, sellPrice: 9000 },
  { id: "deathlord_sabatons", name: "Barrowlord Sabatons", icon: "boots", kind: "armor", quality: "epic", slot: "feet", armor: 205, stats: { str: 7, sta: 8 }, sellPrice: 9000 },
  { id: "necromancers_soulsteps", name: "Mournweave Soulsteps", icon: "boots", kind: "armor", quality: "epic", slot: "feet", armor: 80, stats: { int: 8, spi: 4 }, sellPrice: 9000 },
  { id: "necromancers_legwraps", name: "Mournweave Legwraps", icon: "chestplate", kind: "armor", quality: "epic", slot: "legs", armor: 86, stats: { int: 13, spi: 7 }, sellPrice: 9000 },
  { id: "wyrmshadow_treads", name: "Nightfang Treads", icon: "boots", kind: "armor", quality: "epic", slot: "feet", armor: 145, stats: { agi: 7, sta: 5 }, sellPrice: 9000 },
  { id: "wyrmshadow_legguards", name: "Nightfang Legguards", icon: "chestplate", kind: "armor", quality: "epic", slot: "legs", armor: 155, stats: { agi: 10, sta: 6 }, sellPrice: 9000 },
  { id: "deathlords_dread_visage", name: "Barrowlord Dread Visage", icon: "helmet", kind: "armor", quality: "epic", slot: "helmet", armor: 245, stats: { str: 7, sta: 8 }, sellPrice: 9000 },
  { id: "necromancers_soulspire_mantle", name: "Mournweave Soulspire Mantle", icon: "chestplate", kind: "armor", quality: "epic", slot: "shoulder", armor: 70, stats: { int: 9, spi: 5 }, sellPrice: 9000 },
  { id: "wyrmshadow_talongrips", name: "Nightfang Talongrips", icon: "gauntlet", kind: "armor", quality: "epic", slot: "gloves", armor: 110, stats: { agi: 9, sta: 4 }, sellPrice: 9000 },
  { id: "crownforged_gauntlets", name: "Bonewrought Gauntlets", icon: "gauntlet", kind: "armor", quality: "epic", slot: "gloves", armor: 180, stats: { str: 6, sta: 7 }, sellPrice: 3600 },
  { id: "nighttalon_grips", name: "Direfang Grips", icon: "gauntlet", kind: "armor", quality: "epic", slot: "gloves", armor: 110, stats: { agi: 8, sta: 5 }, sellPrice: 3600 },
  { id: "soulflame_gloves", name: "Wraithfire Gloves", icon: "gauntlet", kind: "armor", quality: "epic", slot: "gloves", armor: 60, stats: { int: 8, sta: 5 }, sellPrice: 3600 },
  { id: "stormcallers_handguards", name: "Galecall Handguards", icon: "gauntlet", kind: "armor", quality: "epic", slot: "gloves", armor: 130, stats: { int: 8, sta: 5 }, sellPrice: 3600 },
  { id: "crownforged_girdle", name: "Bonewrought Girdle", icon: "chestplate", kind: "armor", quality: "epic", slot: "waist", armor: 150, stats: { str: 7, sta: 6 }, sellPrice: 3600 },
  { id: "nighttalon_waistband", name: "Direfang Waistband", icon: "chestplate", kind: "armor", quality: "epic", slot: "waist", armor: 95, stats: { agi: 8, sta: 5 }, sellPrice: 3600 },
  { id: "soulflame_cord", name: "Wraithfire Cord", icon: "chestplate", kind: "armor", quality: "epic", slot: "waist", armor: 50, stats: { int: 8, spi: 5 }, sellPrice: 3600 },
  { id: "stormcallers_waistguard", name: "Galecall Waistguard", icon: "chestplate", kind: "armor", quality: "epic", slot: "waist", armor: 110, stats: { int: 8, sta: 5 }, sellPrice: 3600 },
  { id: "crownforged_dreadhelm", name: "Bonewrought Dreadhelm", icon: "helmet", kind: "armor", quality: "epic", slot: "helmet", armor: 310, stats: { str: 8, sta: 9 }, sellPrice: 12000 },
  { id: "crownforged_warspaulders", name: "Bonewrought Warspaulders", icon: "chestplate", kind: "armor", quality: "epic", slot: "shoulder", armor: 260, stats: { str: 7, sta: 8 }, sellPrice: 12000 },
  { id: "nighttalon_crown", name: "Direfang Crown", icon: "helmet", kind: "armor", quality: "epic", slot: "helmet", armor: 190, stats: { agi: 10, sta: 7 }, sellPrice: 12000 },
  { id: "nighttalon_shoulderguards", name: "Direfang Shoulderguards", icon: "chestplate", kind: "armor", quality: "epic", slot: "shoulder", armor: 165, stats: { agi: 9, sta: 6 }, sellPrice: 12000 },
  { id: "soulflame_cowl", name: "Wraithfire Cowl", icon: "helmet", kind: "armor", quality: "epic", slot: "helmet", armor: 105, stats: { int: 11, sta: 6 }, sellPrice: 12000 },
  { id: "soulflame_mantle", name: "Wraithfire Mantle", icon: "chestplate", kind: "armor", quality: "epic", slot: "shoulder", armor: 92, stats: { int: 9, sta: 6 }, sellPrice: 12000 },
  { id: "stormcallers_crown", name: "Galecall Crown", icon: "helmet", kind: "armor", quality: "epic", slot: "helmet", armor: 225, stats: { int: 10, sta: 7 }, sellPrice: 12000 },
  { id: "stormcallers_spaulders", name: "Galecall Spaulders", icon: "chestplate", kind: "armor", quality: "epic", slot: "shoulder", armor: 190, stats: { int: 8, sta: 7 }, sellPrice: 12000 },
  { id: "highwatch_breastplate", name: "Highwatch Breastplate", icon: "chestplate", kind: "armor", quality: "common", slot: "chest", armor: 160, sellPrice: 700, buyPrice: 2800, shops: ["shop_highwatch"] },
  { id: "peakwool_robe", name: "Peakwool Robe", icon: "chestplate", kind: "armor", quality: "common", slot: "chest", armor: 50, sellPrice: 500, buyPrice: 2000, shops: ["shop_highwatch"] },
  { id: "stalkerhide_jerkin", name: "Stalkerhide Jerkin", icon: "chestplate", kind: "armor", quality: "common", slot: "chest", armor: 95, sellPrice: 600, buyPrice: 2400, shops: ["shop_highwatch"] },
  { id: "cragwalker_boots", name: "Cragwalker Boots", icon: "boots", kind: "armor", quality: "common", slot: "feet", armor: 55, sellPrice: 400, buyPrice: 1600, shops: ["shop_highwatch"] },
  { id: "windguard_leggings", name: "Windguard Leggings", icon: "chestplate", kind: "armor", quality: "common", slot: "legs", armor: 70, sellPrice: 450, buyPrice: 1800, shops: ["shop_highwatch"] },
  { id: "baked_bread", name: "Cottage Loaf", icon: "bread", kind: "consumable", quality: "common", heal: 61, sellPrice: 6, buyPrice: 24, shops: ["shop_eastbrook", "shop_fenbridge", "shop_highwatch"], stack: 20 },
  { id: "spring_water", name: "Cold Well Water", icon: "potionBlue", kind: "consumable", quality: "common", restore: 76, sellPrice: 6, buyPrice: 24, shops: ["shop_eastbrook", "shop_fenbridge", "shop_highwatch"], stack: 20 },
  { id: "raw_mirror_trout", name: "Raw Mirror Trout", icon: "fish", kind: "consumable", quality: "common", heal: 61, sellPrice: 3, stack: 20 },
  { id: "raw_river_perch", name: "Raw River Perch", icon: "fish", kind: "consumable", quality: "common", heal: 45, sellPrice: 2, stack: 20 },
  { id: "raw_marsh_pike", name: "Raw Marsh Pike", icon: "fish", kind: "consumable", quality: "common", heal: 90, sellPrice: 6, stack: 20 },
  { id: "raw_bog_eel", name: "Raw Bog Eel", icon: "fish", kind: "consumable", quality: "common", heal: 90, sellPrice: 6, stack: 20 },
  { id: "raw_frostgill_trout", name: "Raw Frostgill Trout", icon: "fish", kind: "consumable", quality: "common", heal: 117, sellPrice: 10, stack: 20 },
  { id: "raw_stonescale_carp", name: "Raw Slatefin Carp", icon: "fish", kind: "consumable", quality: "common", heal: 117, sellPrice: 10, stack: 20 },
  { id: "glimmerfin_koi", name: "Glimmerfin Koi", icon: "fish", kind: "consumable", quality: "uncommon", heal: 117, sellPrice: 75, stack: 20 },
  { id: "roasted_boar", name: "Spitted Boar Haunch", icon: "meat", kind: "consumable", quality: "common", heal: 117, sellPrice: 12, buyPrice: 48, shops: ["shop_eastbrook"], stack: 20 },
  { id: "minor_healing_potion", name: "Minor Healing Potion", icon: "potionRed", kind: "consumable", quality: "common", heal: 90, sellPrice: 8, buyPrice: 32, shops: ["shop_eastbrook"], stack: 20 },
  { id: "minor_mana_potion", name: "Minor Mana Potion", icon: "potionBlue", kind: "consumable", quality: "common", restore: 120, sellPrice: 8, buyPrice: 32, shops: ["shop_eastbrook"], stack: 20 },
  { id: "lesser_healing_potion", name: "Lesser Healing Potion", icon: "potionRed", kind: "consumable", quality: "common", heal: 150, sellPrice: 16, buyPrice: 64, shops: ["shop_fenbridge", "shop_highwatch"], stack: 20 },
  { id: "lesser_mana_potion", name: "Lesser Mana Potion", icon: "potionBlue", kind: "consumable", quality: "common", restore: 200, sellPrice: 16, buyPrice: 64, shops: ["shop_fenbridge", "shop_highwatch"], stack: 20 },
  { id: "healing_potion", name: "Healing Potion", icon: "potionRed", kind: "consumable", quality: "common", heal: 280, sellPrice: 32, buyPrice: 128, shops: ["shop_fenbridge", "shop_highwatch"], stack: 20 },
  { id: "mana_potion", name: "Mana Potion", icon: "potionBlue", kind: "consumable", quality: "common", restore: 360, sellPrice: 32, buyPrice: 128, shops: ["shop_fenbridge", "shop_highwatch"], stack: 20 },
  { id: "conjured_water", name: "Conjured Rainwater", icon: "potionBlue", kind: "consumable", quality: "common", restore: 76, sellPrice: 0, stack: 20 },
  { id: "conjured_water2", name: "Conjured Wellwater", icon: "potionBlue", kind: "consumable", quality: "common", restore: 288, sellPrice: 0, stack: 20 },
  { id: "conjured_water3", name: "Conjured Clearwater", icon: "potionBlue", kind: "consumable", quality: "common", restore: 672, sellPrice: 0, stack: 20 },
  { id: "conjured_bread", name: "Conjured Oatcake", icon: "bread", kind: "consumable", quality: "common", heal: 61, sellPrice: 0, stack: 20 },
  { id: "conjured_bread2", name: "Conjured Black Loaf", icon: "bread", kind: "consumable", quality: "common", heal: 243, sellPrice: 0, stack: 20 },
  { id: "conjured_bread3", name: "Conjured Honeycake", icon: "bread", kind: "consumable", quality: "common", heal: 552, sellPrice: 0, stack: 20 },
  { id: "brightwood_venison", name: "Brightwood Venison", icon: "meat", kind: "consumable", quality: "common", heal: 92, sellPrice: 4, stack: 20 },
  { id: "tough_jerky", name: "Salted Jerky", icon: "meat", kind: "consumable", quality: "common", heal: 61, sellPrice: 2, buyPrice: 8, shops: ["shop_eastbrook"], stack: 20 },
  { id: "elixir_of_the_bear", name: "Elixir of the Bear", icon: "potionRed", kind: "consumable", quality: "uncommon", heal: 260, sellPrice: 45, stack: 20 },
  { id: "fenbridge_rye", name: "Fenbridge Rye Loaf", icon: "bread", kind: "consumable", quality: "common", heal: 243, sellPrice: 25, buyPrice: 100, shops: ["shop_fenbridge"], stack: 20 },
  { id: "marsh_mint_tea", name: "Marsh Mint Tea", icon: "potionBlue", kind: "consumable", quality: "common", restore: 288, sellPrice: 25, buyPrice: 100, shops: ["shop_fenbridge"], stack: 20 },
  { id: "smoked_eel", name: "Smoked Mirefen Eel", icon: "fish", kind: "consumable", quality: "common", heal: 432, sellPrice: 60, buyPrice: 240, shops: ["shop_fenbridge"], stack: 20 },
  { id: "silvermist_cordial", name: "Silvermist Cordial", icon: "potionBlue", kind: "consumable", quality: "common", restore: 436, sellPrice: 60, buyPrice: 240, shops: ["shop_fenbridge"], stack: 20 },
  { id: "trail_hardtack", name: "Highwatch Trail Hardtack", icon: "bread", kind: "consumable", quality: "common", heal: 552, sellPrice: 75, buyPrice: 300, shops: ["shop_highwatch"], stack: 20 },
  { id: "meltwater_flask", name: "Meltwater Flask", icon: "potionBlue", kind: "consumable", quality: "common", restore: 672, sellPrice: 75, buyPrice: 300, shops: ["shop_highwatch"], stack: 20 },
  { id: "roast_mountain_goat", name: "Roast Mountain Goat", icon: "meat", kind: "consumable", quality: "common", heal: 874, sellPrice: 150, buyPrice: 600, shops: ["shop_highwatch"], stack: 20 },
  { id: "glacier_melt", name: "Glacier Melt", icon: "potionBlue", kind: "consumable", quality: "common", restore: 900, sellPrice: 150, buyPrice: 600, shops: ["shop_highwatch"], stack: 20 },
  { id: "thorium_ore", name: "Thorium Ore", icon: "ore", kind: "junk", quality: "rare", sellPrice: 15, stack: 20 },
  { id: "arcanite_bar", name: "Arcanite Bar", icon: "gem", kind: "junk", quality: "epic", sellPrice: 40, stack: 20 },
  { id: "ashwood_log", name: "Ashwood Log", icon: "leaf", kind: "junk", quality: "rare", sellPrice: 15, stack: 20 },
  { id: "elderwood_log", name: "Elderwood Log", icon: "leaf", kind: "junk", quality: "epic", sellPrice: 40, stack: 20 },
  { id: "goldleaf_herb", name: "Goldleaf Herb", icon: "leaf", kind: "junk", quality: "rare", sellPrice: 15, stack: 20 },
  { id: "sunpetal_herb", name: "Sunpetal Herb", icon: "leaf", kind: "junk", quality: "epic", sellPrice: 40, stack: 20 },
  { id: "tangled_weed", name: "Tangled Weed", icon: "leaf", kind: "junk", quality: "poor", sellPrice: 1, stack: 20 },
  { id: "soggy_boot", name: "Soggy Boot", icon: "boots", kind: "junk", quality: "poor", sellPrice: 1, stack: 20 },
  { id: "soft_down", name: "Soft Down Tuft", icon: "gem", kind: "junk", quality: "poor", sellPrice: 4, stack: 20 },
  { id: "amber_hide", name: "Amber Hide", icon: "cloak", kind: "junk", quality: "poor", sellPrice: 9, stack: 20 },
  { id: "stag_antler", name: "Branching Antler", icon: "gem", kind: "junk", quality: "poor", sellPrice: 8, stack: 20 },
  { id: "wolf_fang", name: "Cracked Wolf Fang", icon: "skull", kind: "junk", quality: "poor", sellPrice: 4, stack: 20 },
  { id: "bandit_bandana", name: "Red Bandana", icon: "cloak", kind: "junk", quality: "poor", sellPrice: 6, stack: 20 },
  { id: "mudfin_scale", name: "Slimy Mudfin Scale", icon: "gem", kind: "junk", quality: "poor", sellPrice: 5, stack: 20 },
  { id: "tallow_candle", name: "Greasy Tallow Lump", icon: "torch", kind: "junk", quality: "poor", sellPrice: 5, stack: 20 },
  { id: "spider_leg", name: "Twitching Spider Leg", icon: "gem", kind: "junk", quality: "poor", sellPrice: 4, stack: 20 },
  { id: "bone_fragments", name: "Bone Fragments", icon: "skull", kind: "junk", quality: "poor", sellPrice: 7, stack: 20 },
  { id: "linen_scrap", name: "Linen Scrap", icon: "cloak", kind: "junk", quality: "poor", sellPrice: 3, stack: 20 },
  { id: "bogiron_nugget", name: "Bogiron Nugget", icon: "ore", kind: "junk", quality: "poor", sellPrice: 12, stack: 20 },
  { id: "soggy_moccasin", name: "Soggy Moccasin", icon: "cloak", kind: "junk", quality: "poor", sellPrice: 9, stack: 20 },
  { id: "cracked_fetish", name: "Cracked Fetish", icon: "skull", kind: "junk", quality: "poor", sellPrice: 14, stack: 20 },
  { id: "chipped_tusk", name: "Chipped Tusk", icon: "skull", kind: "junk", quality: "poor", sellPrice: 15, stack: 20 },
  { id: "deepfen_pearl", name: "Deepfen Pearl", icon: "gem", kind: "junk", quality: "poor", sellPrice: 600, stack: 20 },
  { id: "old_cragmaws_pelt", name: "Old Cragmaw's Pelt", icon: "cloak", kind: "junk", quality: "common", sellPrice: 300, stack: 20 },
  { id: "emberwing_cinderscale", name: "Emberwing Cinderscale", icon: "gem", kind: "junk", quality: "common", sellPrice: 320, stack: 20 },
  { id: "ogre_toe_ring", name: "Ogre Toe Ring", icon: "ring", kind: "junk", quality: "poor", sellPrice: 25, stack: 20 },
  { id: "cracked_ogre_tusk", name: "Cracked Ogre Tusk", icon: "skull", kind: "junk", quality: "poor", sellPrice: 42, stack: 20 },
  { id: "inert_storm_shard", name: "Inert Storm Shard", icon: "crystal", kind: "junk", quality: "poor", sellPrice: 28, stack: 20 },
  { id: "frayed_prayer_beads", name: "Frayed Prayer Beads", icon: "amulet", kind: "junk", quality: "poor", sellPrice: 30, stack: 20 },
  { id: "cracked_wyrm_scale", name: "Cracked Wyrm Scale", icon: "gem", kind: "junk", quality: "poor", sellPrice: 35, stack: 20 },
  { id: "boar_hide", name: "Bristly Boar Hide", icon: "cloak", kind: "quest", quality: "common", sellPrice: 0 },
  { id: "gravecaller_sigil", name: "Gravecaller's Sigil", icon: "skull", kind: "quest", quality: "common", sellPrice: 0 },
  { id: "blessed_wax", name: "Blessed Tallow", icon: "scroll", kind: "quest", quality: "common", sellPrice: 0 },
  { id: "ghostly_essence", name: "Ghostly Essence", icon: "scroll", kind: "quest", quality: "common", sellPrice: 0 },
  { id: "webwood_silk", name: "Sableweb Silk Gland", icon: "cloak", kind: "quest", quality: "common", sellPrice: 0 },
  { id: "supply_crate", name: "Stolen Supply Crate", icon: "chest", kind: "quest", quality: "common", sellPrice: 0 },
  { id: "greyjaw_fang", name: "Old Greyjaw's Fang", icon: "skull", kind: "quest", quality: "common", sellPrice: 0 },
  { id: "weathered_ledger_page", name: "Weathered Ledger Page", icon: "tome", kind: "quest", quality: "common", sellPrice: 0 },
  { id: "morthen_grimoire", name: "Morthen's Grimoire", icon: "tome", kind: "quest", quality: "common", sellPrice: 0 },
  { id: "fen_muster_order", name: "Fenbridge Muster Order", icon: "scroll", kind: "quest", quality: "common", sellPrice: 0 },
  { id: "mire_prowler_pelt", name: "Mire Prowler Pelt", icon: "cloak", kind: "quest", quality: "common", sellPrice: 0 },
  { id: "lost_caravan_goods", name: "Lost Caravan Goods", icon: "chest", kind: "quest", quality: "common", sellPrice: 0 },
  { id: "the_codfather", name: "The Codfather", icon: "scroll", kind: "quest", quality: "common", sellPrice: 0 },
  { id: "waterlogged_idol", name: "Waterlogged Idol", icon: "amulet", kind: "quest", quality: "common", sellPrice: 0 },
  { id: "widow_venom_sac", name: "Widow Venom Sac", icon: "scroll", kind: "quest", quality: "common", sellPrice: 0 },
  { id: "rusted_censer", name: "Rusted Censer", icon: "torch", kind: "quest", quality: "common", sellPrice: 0 },
  { id: "troll_fetish", name: "Mirefen Troll Fetish", icon: "scroll", kind: "quest", quality: "common", sellPrice: 0 },
  { id: "grubjaw_tusk", name: "Grubjaw's Tusk", icon: "scroll", kind: "quest", quality: "common", sellPrice: 0 },
  { id: "cult_cipher", name: "Gravecaller Cipher", icon: "scroll", kind: "quest", quality: "common", sellPrice: 0 },
  { id: "bastion_ward_stone", name: "Bastion Ward Stone", icon: "stone", kind: "quest", quality: "common", sellPrice: 0 },
  { id: "unknown_alien_weaponry", name: "Unknown Alien Weaponry", icon: "scroll", kind: "quest", quality: "rare", sellPrice: 0 },
  { id: "highwatch_summons", name: "Highwatch Summons", icon: "scroll", kind: "quest", quality: "common", sellPrice: 0 },
  { id: "ridge_stalker_pelt", name: "Ridge Stalker Pelt", icon: "cloak", kind: "quest", quality: "common", sellPrice: 0 },
  { id: "glowing_wax", name: "Glowing Wax", icon: "scroll", kind: "quest", quality: "common", sellPrice: 0 },
  { id: "ogre_war_totem", name: "Ogre War Totem", icon: "scroll", kind: "quest", quality: "common", sellPrice: 0 },
  { id: "storm_core", name: "Storm Core", icon: "crystal", kind: "quest", quality: "common", sellPrice: 0 },
  { id: "kazzix_heartshard", name: "Kazzix's Heartshard", icon: "crystal", kind: "quest", quality: "common", sellPrice: 0 },
  { id: "wyrmcult_orders", name: "Wyrmcult Orders", icon: "scroll", kind: "quest", quality: "common", sellPrice: 0 },
  { id: "ritual_phylactery", name: "Ritual Phylactery", icon: "star", kind: "quest", quality: "common", sellPrice: 0 },
  { id: "gravewyrm_sigil", name: "Gravewyrm Sigil", icon: "skull", kind: "quest", quality: "common", sellPrice: 0 },
  { id: "blessed_embers", name: "Blessed Embers", icon: "scroll", kind: "quest", quality: "common", sellPrice: 0 },
  { id: "sanctum_key_shard", name: "Sanctum Key Shard", icon: "crystal", kind: "quest", quality: "common", sellPrice: 0 },
  { id: "runed_bone_shard", name: "Runed Bone Shard", icon: "crystal", kind: "quest", quality: "common", sellPrice: 0 },
  { id: "grave_sir_aldren", name: "Grave of Captain Aldren", icon: "cross", kind: "quest", quality: "common", sellPrice: 0 },
  { id: "grave_high_priest_malric", name: "Grave of High Priest Malric", icon: "cross", kind: "quest", quality: "common", sellPrice: 0 },
  { id: "grave_captain_voss", name: "Grave of Royal Assassin Voss", icon: "cross", kind: "quest", quality: "common", sellPrice: 0 },
  { id: "ancient_crypt_door", name: "Ancient Crypt Door", icon: "scroll", kind: "quest", quality: "common", sellPrice: 0 },
  { id: "captains_crest", name: "Crypt Keystone Upper", icon: "skull", kind: "quest", quality: "common", sellPrice: 0 },
  { id: "priests_sigil", name: "Crypt Keystone Lower", icon: "skull", kind: "quest", quality: "common", sellPrice: 0 },
  { id: "royal_seal", name: "Ancient Diary", icon: "tome", kind: "quest", quality: "common", sellPrice: 0 },
  { id: "crypt_keystone", name: "Crypt Keystone", icon: "crystal", kind: "quest", quality: "uncommon", sellPrice: 0 },
  { id: "crypt_ritual_circle", name: "Ritual Circle", icon: "star", kind: "quest", quality: "common", sellPrice: 0 },
  { id: "kings_signet", name: "King's Signet", icon: "ring", kind: "quest", quality: "rare", sellPrice: 0 },
  { id: "pale_pearl", name: "Pale Pearl", icon: "gem", kind: "junk", quality: "poor", sellPrice: 30, stack: 20 },
  { id: "moonpale_scale", name: "Moonpale Scale", icon: "gem", kind: "junk", quality: "poor", sellPrice: 26, stack: 20 },
  { id: "briny_idol", name: "Briny Idol", icon: "amulet", kind: "junk", quality: "poor", sellPrice: 32, stack: 20 },
  { id: "selthes_seastriders", name: "Selthe's Sea-Striders", icon: "boots", kind: "armor", quality: "rare", slot: "feet", armor: 75, stats: { agi: 4, sta: 3 }, sellPrice: 1200 },
  { id: "ysols_pearl_greaves", name: "Ysolei's Pearl Greaves", icon: "chestplate", kind: "armor", quality: "rare", slot: "legs", armor: 130, stats: { sta: 6, spi: 3 }, sellPrice: 2000 },
  { id: "moonshroud_breastplate", name: "Moonwrack Breastplate", icon: "chestplate", kind: "armor", quality: "rare", slot: "chest", armor: 200, stats: { sta: 7, str: 4 }, sellPrice: 2400 },
  { id: "moonshroud_robe", name: "Moonwrack Robe", icon: "chestplate", kind: "armor", quality: "rare", slot: "chest", armor: 70, stats: { int: 10, spi: 5 }, sellPrice: 2400 },
  { id: "moonshroud_tunic", name: "Moonwrack Tunic", icon: "chestplate", kind: "armor", quality: "rare", slot: "chest", armor: 125, stats: { agi: 9, sta: 4 }, sellPrice: 2400 },
  { id: "deathless_heartwood", name: "Heartwood of the Deathless Crown", icon: "staff", kind: "weapon", quality: "epic", slot: "mainhand", weapon: { min: 42, max: 68, speed: 3.2 }, stats: { int: 14, spi: 17, sta: 13 }, sellPrice: 25000 },
  { id: "kingsbane_last_oath", name: "Thronebane, Last Oath of Thornpeak", icon: "sword", kind: "weapon", quality: "epic", slot: "mainhand", weapon: { min: 46, max: 74, speed: 2.8 }, stats: { str: 15, agi: 15, sta: 14 }, sellPrice: 25000 },
];

const ITEMS_BY_ID = new Map(ITEMS.map((item) => [item.id, item]));

export function itemDefById(id: string): ItemDef | null {
  return ITEMS_BY_ID.get(id) ?? null;
}
