import type { AssetPack } from "../manifest";

/**
 * Kenney.nl CC0 asset packs.
 *
 * Each pack is distributed as a ZIP containing multiple formats.
 * The CLI extracts the `Models/GLTF format/` folder.
 *
 * Download links are scraped from the source page at runtime because
 * Kenney uses content-hashed CDN URLs.
 */

export const kenneyPacks: AssetPack[] = [
  {
    id: "kenney-nature",
    name: "Nature Kit",
    source: "Kenney",
    modelCount: 329,
    sourceUrl: "https://kenney.nl/assets/nature-kit",
    zipGlbPath: "Models/GLTF format",
    categories: ["nature", "tree", "rock", "plant", "foliage"],
  },
  {
    id: "kenney-weapon-pack",
    name: "Weapon Pack",
    source: "Kenney",
    modelCount: 40,
    sourceUrl: "https://kenney.nl/assets/weapon-pack",
    zipGlbPath: "Models/GLTF format",
    categories: ["weapon", "sword", "gun", "shield", "axe"],
  },
  {
    id: "kenney-space-kit",
    name: "Space Kit",
    source: "Kenney",
    modelCount: 215,
    sourceUrl: "https://kenney.nl/assets/space-kit",
    zipGlbPath: "Models/GLTF format",
    categories: ["vehicle", "spaceship", "sci-fi", "prop"],
  },
  {
    id: "kenney-fantasy-town-kit",
    name: "Fantasy Town Kit",
    source: "Kenney",
    modelCount: 220,
    sourceUrl: "https://kenney.nl/assets/fantasy-town-kit",
    zipGlbPath: "Models/GLTF format",
    categories: ["building", "house", "prop", "fantasy"],
  },
  {
    id: "kenney-graveyard-kit",
    name: "Graveyard Kit",
    source: "Kenney",
    modelCount: 110,
    sourceUrl: "https://kenney.nl/assets/graveyard-kit",
    zipGlbPath: "Models/GLTF format",
    categories: ["prop", "graveyard", "fantasy", "nature"],
  },
  {
    id: "kenney-medieval-kit",
    name: "Medieval Kit",
    source: "Kenney",
    modelCount: 80,
    sourceUrl: "https://kenney.nl/assets/medieval-kit",
    zipGlbPath: "Models/GLTF format",
    categories: ["building", "weapon", "prop", "medieval"],
  },
  {
    id: "kenney-pirate-kit",
    name: "Pirate Kit",
    source: "Kenney",
    modelCount: 220,
    sourceUrl: "https://kenney.nl/assets/pirate-kit",
    zipGlbPath: "Models/GLTF format",
    categories: ["vehicle", "ship", "prop", "pirate"],
  },
  {
    id: "kenney-platformer-kit",
    name: "Platformer Kit",
    source: "Kenney",
    modelCount: 180,
    sourceUrl: "https://kenney.nl/assets/platformer-kit",
    zipGlbPath: "Models/GLTF format",
    categories: ["prop", "platform", "collectible", "nature"],
  },
  {
    id: "kenney-car-kit",
    name: "Car Kit",
    source: "Kenney",
    modelCount: 50,
    sourceUrl: "https://kenney.nl/assets/car-kit",
    zipGlbPath: "Models/GLTF format",
    categories: ["vehicle", "car", "transport"],
  },
  {
    id: "kenney-furniture-kit",
    name: "Furniture Kit",
    source: "Kenney",
    modelCount: 95,
    sourceUrl: "https://kenney.nl/assets/furniture-kit",
    zipGlbPath: "Models/GLTF format",
    categories: ["furniture", "prop", "interior"],
  },
  {
    id: "kenney-minigolf-kit",
    name: "Minigolf Kit",
    source: "Kenney",
    modelCount: 100,
    sourceUrl: "https://kenney.nl/assets/minigolf-kit",
    zipGlbPath: "Models/GLTF format",
    categories: ["prop", "sport", "obstacle"],
  },
  {
    id: "kenney-survival-kit",
    name: "Survival Kit",
    source: "Kenney",
    modelCount: 75,
    sourceUrl: "https://kenney.nl/assets/survival-kit",
    zipGlbPath: "Models/GLTF format",
    categories: ["item", "tool", "weapon", "prop"],
  },
  {
    id: "kenney-conveyor-kit",
    name: "Conveyor Kit",
    source: "Kenney",
    modelCount: 40,
    sourceUrl: "https://kenney.nl/assets/conveyor-kit",
    zipGlbPath: "Models/GLTF format",
    categories: ["machine", "factory", "prop"],
  },
  {
    id: "kenney-dungeon-kit",
    name: "Dungeon Kit",
    source: "Kenney",
    modelCount: 90,
    sourceUrl: "https://kenney.nl/assets/dungeon-kit",
    zipGlbPath: "Models/GLTF format",
    categories: ["building", "dungeon", "prop", "fantasy"],
  },
  {
    id: "kenney-racing-kit",
    name: "Racing Kit",
    source: "Kenney",
    modelCount: 110,
    sourceUrl: "https://kenney.nl/assets/racing-kit",
    zipGlbPath: "Models/GLTF format",
    categories: ["vehicle", "car", "track", "prop"],
  },
  {
    id: "kenney-space-station-kit",
    name: "Space Station Kit",
    source: "Kenney",
    modelCount: 80,
    sourceUrl: "https://kenney.nl/assets/space-station-kit",
    zipGlbPath: "Models/GLTF format",
    categories: ["building", "sci-fi", "space", "interior"],
  },
  {
    id: "kenney-food-kit",
    name: "Food Kit",
    source: "Kenney",
    modelCount: 70,
    sourceUrl: "https://kenney.nl/assets/food-kit",
    zipGlbPath: "Models/GLTF format",
    categories: ["item", "food", "prop"],
  },
  {
    id: "kenney-animals-kit",
    name: "Animals Kit",
    source: "Kenney",
    modelCount: 45,
    sourceUrl: "https://kenney.nl/assets/animals-kit",
    zipGlbPath: "Models/GLTF format",
    categories: ["animal", "character", "nature"],
  },
  {
    id: "kenney-tank-kit",
    name: "Tank Kit",
    source: "Kenney",
    modelCount: 50,
    sourceUrl: "https://kenney.nl/assets/tank-kit",
    zipGlbPath: "Models/GLTF format",
    categories: ["vehicle", "tank", "military"],
  },
  {
    id: "kenney-space-shooter-extension",
    name: "Space Shooter Extension",
    source: "Kenney",
    modelCount: 35,
    sourceUrl: "https://kenney.nl/assets/space-shooter-extension",
    zipGlbPath: "Models/GLTF format",
    categories: ["vehicle", "spaceship", "sci-fi"],
  },
];

export const kenneyPackById = new Map(kenneyPacks.map((p) => [p.id, p]));
