import type { ClassDef } from "../model";

export const CLASSES: readonly ClassDef[] = [
  {
    id: "warrior",
    name: "Warrior",
    icon: "sword",
    color: "#C79C6E",
    resource: "rage",
    baseHp: 50,
    hpPerLevel: 18,
    baseResource: 100,
    resourcePerLevel: 0,
    baseStats: { str: 23, agi: 20, sta: 22, int: 10, spi: 11, armor: 50 },
    statsPerLevel: { str: 2, agi: 1, sta: 2, int: 0, spi: 0, armor: 12 },
    startWeapon: "worn_sword",
    abilities: [
      {
        id: "heroic_strike",
        name: "Reaver Strike",
        icon: "sword",
        school: "physical",
        kind: "damage",
        levelReq: 1,
        cost: 15,
        castTime: 0,
        cooldown: 0,
        range: 5,
        base: 11,
        perLevel: 1.8,
      },
      {
        id: "battle_shout",
        name: "Iron Bellow",
        icon: "buffArrow",
        school: "physical",
        kind: "buff",
        levelReq: 1,
        cost: 10,
        castTime: 0,
        cooldown: 0,
        range: 0,
        base: 10,
        perLevel: 0,
        duration: 120,
        selfTarget: true,
        buffStat: "attackPower",
        buffAmount: 10,
        buffPerLevel: 0,
      },
      {
        id: "commanding_shout",
        name: "Bolstering Cry",
        icon: "shield",
        school: "physical",
        kind: "buff",
        levelReq: 14,
        cost: 10,
        castTime: 0,
        cooldown: 0,
        range: 0,
        base: 6,
        perLevel: 0.3,
        duration: 120,
        selfTarget: true,
        buffStat: "sta",
        buffAmount: 6,
        buffPerLevel: 0.3,
      },
      {
        id: "rend",
        name: "Deep Gash",
        icon: "debuffArrow",
        school: "physical",
        kind: "dot",
        levelReq: 4,
        cost: 10,
        castTime: 0,
        cooldown: 0,
        range: 5,
        base: 15,
        perLevel: 1.2,
        duration: 9,
        tickInterval: 3,
      },
      {
        id: "thunder_clap",
        name: "Quaking Blow",
        icon: "lightning",
        school: "physical",
        kind: "aoe",
        levelReq: 6,
        cost: 20,
        castTime: 0,
        cooldown: 4,
        range: 0,
        base: 13,
        perLevel: 1.5,
        aoeRadius: 8,
      },
      {
        id: "hamstring",
        name: "Hobbling Cut",
        icon: "sword",
        school: "physical",
        kind: "damage",
        levelReq: 8,
        cost: 10,
        castTime: 0,
        cooldown: 0,
        range: 5,
        base: 5,
        perLevel: 0.4,
      },
      {
        id: "overpower",
        name: "Redhand",
        icon: "sword",
        school: "physical",
        kind: "damage",
        levelReq: 10,
        cost: 5,
        castTime: 0,
        cooldown: 5,
        range: 5,
        base: 5,
        perLevel: 0.6,
      },
      {
        id: "execute",
        name: "Early Grave",
        icon: "skull",
        school: "physical",
        kind: "damage",
        levelReq: 14,
        cost: 15,
        castTime: 0,
        cooldown: 0,
        range: 5,
        base: 67.5,
        perLevel: 0,
      },
      {
        id: "slam",
        name: "Brute Swing",
        icon: "hammer",
        school: "physical",
        kind: "damage",
        levelReq: 16,
        cost: 15,
        castTime: 1.5,
        cooldown: 0,
        range: 5,
        base: 25,
        perLevel: 0,
      },
      {
        id: "cleave",
        name: "Reaping Arc",
        icon: "axe",
        school: "physical",
        kind: "aoe",
        levelReq: 18,
        cost: 20,
        castTime: 0,
        cooldown: 0,
        range: 0,
        base: 23,
        perLevel: 0,
        aoeRadius: 5,
      },
      {
        id: "defensive_stance",
        name: "Guarded Stance",
        icon: "shield",
        school: "physical",
        kind: "buff",
        levelReq: 10,
        cost: 0,
        castTime: 0,
        cooldown: 1,
        range: 0,
        base: 90,
        perLevel: 0,
        duration: 3600,
        selfTarget: true,
      },
      {
        id: "demoralizing_shout",
        name: "Direhowl",
        icon: "debuffArrow",
        school: "physical",
        kind: "buff",
        levelReq: 14,
        cost: 10,
        castTime: 0,
        cooldown: 0,
        range: 0,
        base: 30,
        perLevel: 0.8,
        duration: 30,
        aoeRadius: 10,
        selfTarget: false,
        buffStat: "attackPower",
        buffAmount: -30,
        buffPerLevel: -0.8,
      },
      {
        id: "taunt",
        name: "Goad",
        icon: "shield",
        school: "physical",
        kind: "buff",
        levelReq: 10,
        cost: 0,
        castTime: 0,
        cooldown: 10,
        range: 8,
        base: 0,
        perLevel: 0,
        selfTarget: true,
        cc: { kind: "taunt", durationSec: 3 },
      },
      {
        id: "sunder_armor",
        name: "Armor Shear",
        icon: "debuffArrow",
        school: "physical",
        kind: "buff",
        levelReq: 10,
        cost: 15,
        castTime: 0,
        cooldown: 0,
        range: 0,
        base: 0,
        perLevel: 0,
        selfTarget: true,
        cc: { kind: "armorShred", durationSec: 30, amount: 25 },
      },
      {
        id: "bloodrage",
        name: "Blood Toll",
        icon: "fire",
        school: "physical",
        kind: "buff",
        levelReq: 10,
        cost: 0,
        castTime: 0,
        cooldown: 60,
        range: 0,
        base: 0,
        perLevel: 0,
        selfTarget: true,
        selfResource: 10,
      },
    ],
  },
  {
    id: "mage",
    name: "Mage",
    icon: "staff",
    color: "#69CCF0",
    resource: "mana",
    baseHp: 40,
    hpPerLevel: 12,
    baseResource: 100,
    resourcePerLevel: 24,
    baseStats: { str: 10, agi: 12, sta: 14, int: 24, spi: 22, armor: 25 },
    statsPerLevel: { str: 0, agi: 0, sta: 1, int: 3, spi: 2, armor: 4 },
    startWeapon: "gnarled_staff",
    abilities: [
      {
        id: "fireball",
        name: "Cinderbolt",
        icon: "fire",
        school: "fire",
        kind: "damage",
        levelReq: 1,
        cost: 30,
        castTime: 1.5,
        cooldown: 0,
        range: 30,
        base: 20.5,
        perLevel: 2.6,
      },
      {
        id: "frost_armor",
        name: "Hoarfrost Mantle",
        icon: "frost",
        school: "frost",
        kind: "buff",
        levelReq: 1,
        cost: 20,
        castTime: 0,
        cooldown: 0,
        range: 0,
        base: 30,
        perLevel: 2.2,
        duration: 1800,
        selfTarget: true,
        buffStat: "armor",
        buffAmount: 30,
        buffPerLevel: 2.2,
      },
      {
        id: "arcane_intellect",
        name: "Aether Insight",
        icon: "tome",
        school: "arcane",
        kind: "buff",
        levelReq: 1,
        cost: 25,
        castTime: 0,
        cooldown: 0,
        range: 0,
        base: 5,
        perLevel: 0,
        duration: 1800,
        selfTarget: true,
        buffStat: "int",
        buffAmount: 5,
        buffPerLevel: 0,
      },
      {
        id: "frostbolt",
        name: "Rimelance",
        icon: "frost",
        school: "frost",
        kind: "damage",
        levelReq: 4,
        cost: 25,
        castTime: 1.5,
        cooldown: 0,
        range: 30,
        base: 19,
        perLevel: 2.8,
      },
      {
        id: "fire_blast",
        name: "Cinderfall",
        icon: "fire",
        school: "fire",
        kind: "damage",
        levelReq: 6,
        cost: 40,
        castTime: 0,
        cooldown: 8,
        range: 20,
        base: 31,
        perLevel: 2.4,
      },
      {
        id: "arcane_missiles",
        name: "Aether Darts",
        icon: "star",
        school: "arcane",
        kind: "dot",
        levelReq: 8,
        cost: 50,
        castTime: 0,
        cooldown: 0,
        range: 30,
        base: 24,
        perLevel: 2.3,
        duration: 3,
        tickInterval: 1,
      },
      {
        id: "frost_nova",
        name: "Icebind",
        icon: "frost",
        school: "frost",
        kind: "aoe",
        levelReq: 10,
        cost: 35,
        castTime: 0,
        cooldown: 22,
        range: 0,
        base: 6.5,
        perLevel: 0.4,
        aoeRadius: 10,
        duration: 8,
        cc: { kind: "root", durationSec: 8 },
      },
      {
        id: "polymorph",
        name: "Bewitch",
        icon: "hourglass",
        school: "arcane",
        kind: "buff",
        levelReq: 8,
        cost: 50,
        castTime: 1.5,
        cooldown: 0,
        range: 30,
        base: 0,
        perLevel: 0,
        selfTarget: true,
        cc: { kind: "stun", durationSec: 15 },
      },
      {
        id: "arcane_explosion",
        name: "Aetherburst",
        icon: "star",
        school: "arcane",
        kind: "aoe",
        levelReq: 14,
        cost: 60,
        castTime: 0,
        cooldown: 0,
        range: 0,
        base: 28.5,
        perLevel: 0,
        aoeRadius: 10,
      },
      {
        id: "scorch",
        name: "Scald",
        icon: "fire",
        school: "fire",
        kind: "damage",
        levelReq: 16,
        cost: 35,
        castTime: 1.5,
        cooldown: 0,
        range: 30,
        base: 36,
        perLevel: 0,
      },
      {
        id: "pyroblast",
        name: "Pyrelance",
        icon: "fire",
        school: "fire",
        kind: "damage",
        levelReq: 20,
        cost: 125,
        castTime: 6.0,
        cooldown: 0,
        range: 30,
        base: 197.5,
        perLevel: 0,
      },
      {
        id: "ice_barrier",
        name: "Frostveil",
        icon: "shield",
        school: "frost",
        kind: "buff",
        levelReq: 20,
        cost: 90,
        castTime: 0,
        cooldown: 30,
        range: 0,
        base: 130,
        perLevel: 0,
        duration: 60,
        selfTarget: true,
      },
      {
        id: "flamestrike",
        name: "Flamestrike",
        icon: "fire",
        school: "fire",
        kind: "aoe",
        levelReq: 20,
        cost: 80,
        castTime: 0,
        cooldown: 12,
        range: 30,
        base: 39,
        perLevel: 0,
        aoeRadius: 7,
      },
    ],
  },
  {
    id: "rogue",
    name: "Rogue",
    icon: "dagger",
    color: "#FFF569",
    resource: "energy",
    baseHp: 45,
    hpPerLevel: 15,
    baseResource: 100,
    resourcePerLevel: 0,
    baseStats: { str: 17, agi: 25, sta: 17, int: 11, spi: 12, armor: 40 },
    statsPerLevel: { str: 1, agi: 3, sta: 1, int: 0, spi: 0, armor: 8 },
    startWeapon: "rusty_dagger",
    abilities: [
      {
        id: "sinister_strike",
        name: "Wicked Slash",
        icon: "dagger",
        school: "physical",
        kind: "damage",
        levelReq: 1,
        cost: 45,
        castTime: 0,
        cooldown: 0,
        range: 5,
        base: 3,
        perLevel: 0.8,
      },
      {
        id: "eviscerate",
        name: "Dirt Nap",
        icon: "dagger",
        school: "physical",
        kind: "damage",
        levelReq: 1,
        cost: 35,
        castTime: 0,
        cooldown: 0,
        range: 5,
        base: 25,
        perLevel: 2.4,
      },
      {
        id: "garrote",
        name: "Throat Wire",
        icon: "dagger",
        school: "physical",
        kind: "dot",
        levelReq: 1,
        cost: 50,
        castTime: 0,
        cooldown: 0,
        range: 5,
        base: 60,
        perLevel: 4.0,
        duration: 18,
        tickInterval: 3,
      },
      {
        id: "backstab",
        name: "Craven Thrust",
        icon: "dagger",
        school: "physical",
        kind: "damage",
        levelReq: 4,
        cost: 60,
        castTime: 0,
        cooldown: 0,
        range: 5,
        base: 11,
        perLevel: 1.2,
      },
      {
        id: "gouge",
        name: "Eye Jab",
        icon: "fist",
        school: "physical",
        kind: "damage",
        levelReq: 6,
        cost: 45,
        castTime: 0,
        cooldown: 10,
        range: 5,
        base: 8.5,
        perLevel: 0.4,
      },
      {
        id: "cheap_shot",
        name: "Gut Punch",
        icon: "fist",
        school: "physical",
        kind: "damage",
        levelReq: 8,
        cost: 60,
        castTime: 0,
        cooldown: 0,
        range: 5,
        base: 7,
        perLevel: 0,
      },
      {
        id: "evasion",
        name: "Ghostfoot",
        icon: "cloak",
        school: "physical",
        kind: "buff",
        levelReq: 8,
        cost: 0,
        castTime: 0,
        cooldown: 300,
        range: 0,
        base: 50,
        perLevel: 0,
        duration: 15,
        selfTarget: true,
      },
      {
        id: "slice_and_dice",
        name: "Cutthroat Tempo",
        icon: "buffArrow",
        school: "physical",
        kind: "buff",
        levelReq: 10,
        cost: 25,
        castTime: 0,
        cooldown: 0,
        range: 0,
        base: 130,
        perLevel: 0,
        duration: 9,
        selfTarget: true,
      },
      {
        id: "sprint",
        name: "Swift Heels",
        icon: "sprint",
        school: "physical",
        kind: "buff",
        levelReq: 10,
        cost: 0,
        castTime: 0,
        cooldown: 300,
        range: 0,
        base: 170,
        perLevel: 0,
        duration: 15,
        selfTarget: true,
      },
      {
        id: "crippling_poison",
        name: "Leaden Venom",
        icon: "poison",
        school: "nature",
        kind: "damage",
        levelReq: 12,
        cost: 40,
        castTime: 0,
        cooldown: 0,
        range: 5,
        base: 4,
        perLevel: 0,
      },
      {
        id: "ambush",
        name: "Lurker's Strike",
        icon: "dagger",
        school: "physical",
        kind: "damage",
        levelReq: 16,
        cost: 60,
        castTime: 0,
        cooldown: 0,
        range: 5,
        base: 28,
        perLevel: 0,
      },
      {
        id: "rupture",
        name: "Bleed Out",
        icon: "debuffArrow",
        school: "physical",
        kind: "dot",
        levelReq: 16,
        cost: 25,
        castTime: 0,
        cooldown: 0,
        range: 5,
        base: 96,
        perLevel: 0,
        duration: 16,
        tickInterval: 2,
      },
      {
        id: "vanish",
        name: "Smokestep",
        icon: "cloak",
        school: "physical",
        kind: "buff",
        levelReq: 18,
        cost: 0,
        castTime: 0,
        cooldown: 300,
        range: 0,
        base: 50,
        perLevel: 0,
        duration: 10,
        selfTarget: true,
      },
      {
        id: "instant_poison",
        name: "Adder's Bite",
        icon: "poison",
        school: "nature",
        kind: "buff",
        levelReq: 18,
        cost: 40,
        castTime: 0,
        cooldown: 0,
        range: 0,
        base: 8,
        perLevel: 0,
        duration: 1800,
        selfTarget: true,
      },
      {
        id: "deadly_poison",
        name: "Festering Venom",
        icon: "poison",
        school: "nature",
        kind: "buff",
        levelReq: 20,
        cost: 40,
        castTime: 0,
        cooldown: 0,
        range: 0,
        base: 14,
        perLevel: 0,
        duration: 1800,
        selfTarget: true,
      },
      {
        id: "stealth",
        name: "Duskveil",
        icon: "eye",
        school: "physical",
        kind: "buff",
        levelReq: 2,
        cost: 0,
        castTime: 0,
        cooldown: 10,
        range: 0,
        base: 50,
        perLevel: 0,
        duration: 3600,
        selfTarget: true,
      },
      {
        id: "kidney_shot",
        name: "Low Blow",
        icon: "hourglass",
        school: "physical",
        kind: "buff",
        levelReq: 14,
        cost: 25,
        castTime: 0,
        cooldown: 20,
        range: 0,
        base: 0,
        perLevel: 0,
        selfTarget: true,
        cc: { kind: "stun", durationSec: 4 },
      },
      {
        id: "sap",
        name: "Sap",
        icon: "hourglass",
        school: "physical",
        kind: "buff",
        levelReq: 10,
        cost: 65,
        castTime: 0,
        cooldown: 0,
        range: 0,
        base: 0,
        perLevel: 0,
        selfTarget: true,
        cc: { kind: "stun", durationSec: 8 },
      },
      {
        id: "adrenaline_rush",
        name: "Quickened Blood",
        icon: "lightning",
        school: "physical",
        kind: "buff",
        levelReq: 20,
        cost: 0,
        castTime: 0,
        cooldown: 180,
        range: 0,
        base: 0,
        perLevel: 0,
        selfTarget: true,
        selfResource: 100,
      },
      {
        id: "expose_armor",
        name: "Armor Breach",
        icon: "debuffArrow",
        school: "physical",
        kind: "buff",
        levelReq: 14,
        cost: 25,
        castTime: 0,
        cooldown: 0,
        range: 0,
        base: 0,
        perLevel: 0,
        selfTarget: true,
        cc: { kind: "armorShred", durationSec: 30, amount: 170 },
      },
    ],
  },
  {
    id: "paladin",
    name: "Paladin",
    icon: "hammer",
    color: "#F58CBA",
    resource: "mana",
    baseHp: 55,
    hpPerLevel: 17,
    baseResource: 80,
    resourcePerLevel: 20,
    baseStats: { str: 22, agi: 17, sta: 22, int: 13, spi: 14, armor: 45 },
    statsPerLevel: { str: 2, agi: 1, sta: 2, int: 1, spi: 1, armor: 12 },
    startWeapon: "training_mace",
    abilities: [
      {
        id: "seal_of_righteousness",
        name: "Oathbrand",
        icon: "star",
        school: "holy",
        kind: "buff",
        levelReq: 1,
        cost: 25,
        castTime: 0,
        cooldown: 0,
        range: 0,
        base: 4,
        perLevel: 0.4,
        duration: 30,
        selfTarget: true,
      },
      {
        id: "holy_light",
        name: "Mending Light",
        icon: "heart",
        school: "holy",
        kind: "heal",
        levelReq: 1,
        cost: 35,
        castTime: 2.5,
        cooldown: 0,
        range: 30,
        base: 46.5,
        perLevel: 8.9,
        selfTarget: true,
      },
      {
        id: "devotion_aura",
        name: "Steadfast Aura",
        icon: "shield",
        school: "holy",
        kind: "buff",
        levelReq: 1,
        cost: 0,
        castTime: 0,
        cooldown: 0,
        range: 0,
        base: 10,
        perLevel: 0,
        duration: 1800,
        selfTarget: true,
        buffStat: "armor",
        buffAmount: 10,
        buffPerLevel: 0,
      },
      {
        id: "blessing_of_might",
        name: "Oath of Iron",
        icon: "buffArrow",
        school: "holy",
        kind: "buff",
        levelReq: 4,
        cost: 25,
        castTime: 0,
        cooldown: 0,
        range: 30,
        base: 10,
        perLevel: 0,
        duration: 1800,
        selfTarget: true,
        buffStat: "attackPower",
        buffAmount: 10,
        buffPerLevel: 0,
      },
      {
        id: "divine_protection",
        name: "Ward of Faith",
        icon: "shield",
        school: "holy",
        kind: "buff",
        levelReq: 6,
        cost: 15,
        castTime: 0,
        cooldown: 180,
        range: 0,
        base: 50,
        perLevel: 3.3,
        duration: 10,
        selfTarget: true,
      },
      {
        id: "lay_on_hands",
        name: "Last Rite",
        icon: "heart",
        school: "holy",
        kind: "heal",
        levelReq: 10,
        cost: 0,
        castTime: 0,
        cooldown: 600,
        range: 30,
        base: 250,
        perLevel: 19.4,
        selfTarget: true,
      },
      {
        id: "flash_of_light",
        name: "Lightmend",
        icon: "heart",
        school: "holy",
        kind: "heal",
        levelReq: 12,
        cost: 35,
        castTime: 1.5,
        cooldown: 0,
        range: 30,
        base: 69,
        perLevel: 0,
        selfTarget: true,
      },
      {
        id: "exorcism",
        name: "Rite of Expulsion",
        icon: "star",
        school: "holy",
        kind: "damage",
        levelReq: 14,
        cost: 55,
        castTime: 0,
        cooldown: 15,
        range: 30,
        base: 51,
        perLevel: 0,
      },
      {
        id: "consecration",
        name: "Holy Ground",
        icon: "fire",
        school: "holy",
        kind: "aoe",
        levelReq: 18,
        cost: 60,
        castTime: 0,
        cooldown: 8,
        range: 0,
        base: 31,
        perLevel: 0,
        aoeRadius: 8,
        duration: 10,
        tickInterval: 2,
      },
      {
        id: "righteous_fury",
        name: "Burning Oath",
        icon: "shield",
        school: "holy",
        kind: "buff",
        levelReq: 16,
        cost: 30,
        castTime: 0,
        cooldown: 0,
        range: 0,
        base: 160,
        perLevel: 0,
        duration: 1800,
        selfTarget: true,
      },
      {
        id: "retribution_aura",
        name: "Requital Aura",
        icon: "buffArrow",
        school: "holy",
        kind: "buff",
        levelReq: 16,
        cost: 0,
        castTime: 0,
        cooldown: 0,
        range: 0,
        base: 5,
        perLevel: 0,
        duration: 1800,
        selfTarget: true,
      },
      {
        id: "hammer_of_justice",
        name: "Sundering Gavel",
        icon: "hourglass",
        school: "holy",
        kind: "buff",
        levelReq: 8,
        cost: 30,
        castTime: 0,
        cooldown: 60,
        range: 10,
        base: 0,
        perLevel: 0,
        selfTarget: true,
        cc: { kind: "stun", durationSec: 3 },
      },
    ],
  },
  {
    id: "hunter",
    name: "Hunter",
    icon: "bow",
    color: "#ABD473",
    resource: "mana",
    baseHp: 50,
    hpPerLevel: 15,
    baseResource: 80,
    resourcePerLevel: 18,
    baseStats: { str: 14, agi: 25, sta: 19, int: 13, spi: 14, armor: 45 },
    statsPerLevel: { str: 1, agi: 3, sta: 2, int: 1, spi: 1, armor: 8 },
    startWeapon: "rusty_hatchet",
    abilities: [
      {
        id: "raptor_strike",
        name: "Gutting Strike",
        icon: "axe",
        school: "physical",
        kind: "damage",
        levelReq: 1,
        cost: 15,
        castTime: 0,
        cooldown: 6,
        range: 5,
        base: 5,
        perLevel: 1.2,
      },
      {
        id: "aspect_of_the_hawk",
        name: "Harrier's Guise",
        icon: "wing",
        school: "nature",
        kind: "buff",
        levelReq: 1,
        cost: 20,
        castTime: 0,
        cooldown: 0,
        range: 0,
        base: 20,
        perLevel: 1.7,
        duration: 1800,
        selfTarget: true,
        buffStat: "attackPower",
        buffAmount: 20,
        buffPerLevel: 1.7,
      },
      {
        id: "serpent_sting",
        name: "Venom Barb",
        icon: "poison",
        school: "nature",
        kind: "dot",
        levelReq: 4,
        cost: 15,
        castTime: 0,
        cooldown: 0,
        range: 35,
        base: 20,
        perLevel: 1.9,
        duration: 15,
        tickInterval: 3,
      },
      {
        id: "arcane_shot",
        name: "Fell Shot",
        icon: "arrow",
        school: "arcane",
        kind: "damage",
        levelReq: 6,
        cost: 25,
        castTime: 0,
        cooldown: 6,
        range: 35,
        base: 15,
        perLevel: 1.5,
      },
      {
        id: "concussive_shot",
        name: "Rattling Shot",
        icon: "arrow",
        school: "physical",
        kind: "damage",
        levelReq: 8,
        cost: 20,
        castTime: 0,
        cooldown: 12,
        range: 35,
        base: 5,
        perLevel: 0,
      },
      {
        id: "mongoose_bite",
        name: "Counterfang",
        icon: "fist",
        school: "physical",
        kind: "damage",
        levelReq: 10,
        cost: 10,
        castTime: 0,
        cooldown: 5,
        range: 5,
        base: 12,
        perLevel: 0.7,
      },
      {
        id: "wing_clip",
        name: "Fettering Slash",
        icon: "axe",
        school: "physical",
        kind: "damage",
        levelReq: 10,
        cost: 20,
        castTime: 0,
        cooldown: 0,
        range: 5,
        base: 4,
        perLevel: 0,
      },
      {
        id: "aspect_of_the_monkey",
        name: "Marten's Guise",
        icon: "wing",
        school: "nature",
        kind: "buff",
        levelReq: 10,
        cost: 20,
        castTime: 0,
        cooldown: 0,
        range: 0,
        base: 8,
        perLevel: 0,
        duration: 1800,
        selfTarget: true,
      },
      {
        id: "aspect_of_the_cheetah",
        name: "Courser's Guise",
        icon: "sprint",
        school: "nature",
        kind: "buff",
        levelReq: 14,
        cost: 20,
        castTime: 0,
        cooldown: 0,
        range: 0,
        base: 130,
        perLevel: 0,
        duration: 1800,
        selfTarget: true,
      },
      {
        id: "aimed_shot",
        name: "Long Draw",
        icon: "bow",
        school: "physical",
        kind: "damage",
        levelReq: 16,
        cost: 50,
        castTime: 3.0,
        cooldown: 6,
        range: 35,
        base: 56,
        perLevel: 0,
      },
      {
        id: "rapid_fire",
        name: "Fevered Draw",
        icon: "sprint",
        school: "physical",
        kind: "buff",
        levelReq: 20,
        cost: 0,
        castTime: 0,
        cooldown: 300,
        range: 0,
        base: 140,
        perLevel: 0,
        duration: 15,
        selfTarget: true,
      },
      {
        id: "volley",
        name: "Volley",
        icon: "bow",
        school: "physical",
        kind: "aoe",
        levelReq: 18,
        cost: 60,
        castTime: 0,
        cooldown: 8,
        range: 35,
        base: 14,
        perLevel: 0,
        aoeRadius: 8,
        duration: 3,
        tickInterval: 0.5,
      },
      {
        id: "call_pet",
        name: "Call Pet",
        icon: "feather",
        school: "nature",
        kind: "buff",
        levelReq: 1,
        cost: 0,
        castTime: 0,
        cooldown: 5,
        range: 0,
        base: 0,
        perLevel: 0,
        selfTarget: true,
      },
      {
        id: "dismiss_pet",
        name: "Dismiss Pet",
        icon: "cloak",
        school: "nature",
        kind: "buff",
        levelReq: 1,
        cost: 0,
        castTime: 0,
        cooldown: 2,
        range: 0,
        base: 0,
        perLevel: 0,
        selfTarget: true,
      },
      {
        id: "revive_pet",
        name: "Revive Pet",
        icon: "heart",
        school: "nature",
        kind: "buff",
        levelReq: 1,
        cost: 40,
        castTime: 2,
        cooldown: 20,
        range: 0,
        base: 0,
        perLevel: 0,
        selfTarget: true,
      },
    ],
  },
  {
    id: "priest",
    name: "Priest",
    icon: "wand",
    color: "#FFFFF0",
    resource: "mana",
    baseHp: 38,
    hpPerLevel: 11,
    baseResource: 110,
    resourcePerLevel: 26,
    baseStats: { str: 10, agi: 11, sta: 13, int: 22, spi: 24, armor: 20 },
    statsPerLevel: { str: 0, agi: 0, sta: 1, int: 2, spi: 3, armor: 4 },
    startWeapon: "gnarled_staff",
    abilities: [
      {
        id: "smite",
        name: "Smite",
        icon: "star",
        school: "holy",
        kind: "damage",
        levelReq: 1,
        cost: 20,
        castTime: 2.0,
        cooldown: 0,
        range: 30,
        base: 17.5,
        perLevel: 3.0,
      },
      {
        id: "lesser_heal",
        name: "Whispered Prayer",
        icon: "heart",
        school: "holy",
        kind: "heal",
        levelReq: 1,
        cost: 30,
        castTime: 2.0,
        cooldown: 0,
        range: 30,
        base: 52.5,
        perLevel: 3.8,
        selfTarget: true,
      },
      {
        id: "power_word_fortitude",
        name: "Litany of Resolve",
        icon: "shield",
        school: "holy",
        kind: "buff",
        levelReq: 1,
        cost: 30,
        castTime: 0,
        cooldown: 0,
        range: 30,
        base: 5,
        perLevel: 0,
        duration: 1800,
        selfTarget: true,
        buffStat: "sta",
        buffAmount: 5,
        buffPerLevel: 0,
      },
      {
        id: "shadow_word_pain",
        name: "Dirge of Decay",
        icon: "skull",
        school: "shadow",
        kind: "dot",
        levelReq: 4,
        cost: 25,
        castTime: 0,
        cooldown: 0,
        range: 30,
        base: 30,
        perLevel: 3.0,
        duration: 18,
        tickInterval: 3,
      },
      {
        id: "power_word_shield",
        name: "Psalm of Warding",
        icon: "shield",
        school: "holy",
        kind: "buff",
        levelReq: 6,
        cost: 45,
        castTime: 0,
        cooldown: 6,
        range: 30,
        base: 48,
        perLevel: 5.4,
        duration: 30,
        selfTarget: true,
      },
      {
        id: "renew",
        name: "Lingering Grace",
        icon: "leaf",
        school: "holy",
        kind: "hot",
        levelReq: 8,
        cost: 30,
        castTime: 0,
        cooldown: 0,
        range: 30,
        base: 45,
        perLevel: 5.3,
        duration: 15,
        tickInterval: 3,
        selfTarget: true,
      },
      {
        id: "mind_blast",
        name: "Mindfracture",
        icon: "skull",
        school: "shadow",
        kind: "damage",
        levelReq: 10,
        cost: 50,
        castTime: 1.5,
        cooldown: 8,
        range: 30,
        base: 44,
        perLevel: 2.6,
      },
      {
        id: "heal",
        name: "Solemn Prayer",
        icon: "heart",
        school: "holy",
        kind: "heal",
        levelReq: 14,
        cost: 95,
        castTime: 2.5,
        cooldown: 0,
        range: 30,
        base: 180,
        perLevel: 3.9,
        selfTarget: true,
      },
      {
        id: "mind_flay",
        name: "Litany of Woe",
        icon: "skull",
        school: "shadow",
        kind: "dot",
        levelReq: 16,
        cost: 45,
        castTime: 0,
        cooldown: 0,
        range: 20,
        base: 36,
        perLevel: 0,
        duration: 3,
        tickInterval: 1,
      },
      {
        id: "flash_heal",
        name: "Urgent Prayer",
        icon: "heart",
        school: "holy",
        kind: "heal",
        levelReq: 20,
        cost: 75,
        castTime: 1.5,
        cooldown: 0,
        range: 30,
        base: 131,
        perLevel: 0,
        selfTarget: true,
      },
    ],
  },
  {
    id: "shaman",
    name: "Shaman",
    icon: "lightning",
    color: "#0070DE",
    resource: "mana",
    baseHp: 48,
    hpPerLevel: 15,
    baseResource: 90,
    resourcePerLevel: 22,
    baseStats: { str: 18, agi: 16, sta: 20, int: 18, spi: 18, armor: 40 },
    statsPerLevel: { str: 1, agi: 1, sta: 2, int: 2, spi: 2, armor: 10 },
    startWeapon: "training_mace",
    abilities: [
      {
        id: "lightning_bolt",
        name: "Arc Bolt",
        icon: "lightning",
        school: "nature",
        kind: "damage",
        levelReq: 1,
        cost: 15,
        castTime: 1.5,
        cooldown: 0,
        range: 30,
        base: 16,
        perLevel: 3.6,
      },
      {
        id: "rockbiter_weapon",
        name: "Stonebound Weapon",
        icon: "stone",
        school: "nature",
        kind: "buff",
        levelReq: 1,
        cost: 20,
        castTime: 0,
        cooldown: 0,
        range: 0,
        base: 5,
        perLevel: 0.5,
        duration: 300,
        selfTarget: true,
      },
      {
        id: "healing_wave",
        name: "Mending Waters",
        icon: "heart",
        school: "nature",
        kind: "heal",
        levelReq: 1,
        cost: 25,
        castTime: 1.5,
        cooldown: 0,
        range: 30,
        base: 40,
        perLevel: 6.2,
        selfTarget: true,
      },
      {
        id: "earth_shock",
        name: "Earthen Jolt",
        icon: "stone",
        school: "nature",
        kind: "damage",
        levelReq: 4,
        cost: 30,
        castTime: 0,
        cooldown: 6,
        range: 20,
        base: 20.5,
        perLevel: 2.1,
      },
      {
        id: "lightning_shield",
        name: "Thunder Ward",
        icon: "lightning",
        school: "nature",
        kind: "buff",
        levelReq: 8,
        cost: 25,
        castTime: 0,
        cooldown: 0,
        range: 0,
        base: 13,
        perLevel: 0.9,
        duration: 600,
        selfTarget: true,
      },
      {
        id: "flame_shock",
        name: "Cinder Jolt",
        icon: "fire",
        school: "fire",
        kind: "dot",
        levelReq: 10,
        cost: 35,
        castTime: 0,
        cooldown: 6,
        range: 20,
        base: 28,
        perLevel: 1.1,
        duration: 12,
        tickInterval: 3,
      },
      {
        id: "flametongue_weapon",
        name: "Pyrebrand Weapon",
        icon: "fire",
        school: "fire",
        kind: "buff",
        levelReq: 10,
        cost: 25,
        castTime: 0,
        cooldown: 0,
        range: 0,
        base: 8,
        perLevel: 0.3,
        duration: 300,
        selfTarget: true,
      },
      {
        id: "frost_shock",
        name: "Rime Jolt",
        icon: "frost",
        school: "frost",
        kind: "damage",
        levelReq: 14,
        cost: 50,
        castTime: 0,
        cooldown: 6,
        range: 20,
        base: 39,
        perLevel: 0,
      },
      {
        id: "frostbrand_weapon",
        name: "Rimebound Weapon",
        icon: "frost",
        school: "frost",
        kind: "buff",
        levelReq: 12,
        cost: 25,
        castTime: 0,
        cooldown: 0,
        range: 0,
        base: 8,
        perLevel: 0.3,
        duration: 300,
        selfTarget: true,
      },
      {
        id: "ghost_wolf",
        name: "Shadewolf",
        icon: "sprint",
        school: "nature",
        kind: "buff",
        levelReq: 16,
        cost: 35,
        castTime: 2.0,
        cooldown: 0,
        range: 0,
        base: 140,
        perLevel: 0,
        duration: 3600,
        selfTarget: true,
      },
      {
        id: "stormstrike",
        name: "Ancestral Strike",
        icon: "hammer",
        school: "physical",
        kind: "damage",
        levelReq: 20,
        cost: 40,
        castTime: 0,
        cooldown: 12,
        range: 5,
        base: 26,
        perLevel: 0,
      },
      {
        id: "earthquake",
        name: "Earthquake",
        icon: "stone",
        school: "nature",
        kind: "aoe",
        levelReq: 18,
        cost: 80,
        castTime: 0,
        cooldown: 12,
        range: 30,
        base: 15,
        perLevel: 0,
        aoeRadius: 8,
        duration: 6,
        tickInterval: 1.5,
      },
    ],
  },
  {
    id: "warlock",
    name: "Warlock",
    icon: "skull",
    color: "#9482C9",
    resource: "mana",
    baseHp: 42,
    hpPerLevel: 12,
    baseResource: 105,
    resourcePerLevel: 25,
    baseStats: { str: 11, agi: 12, sta: 15, int: 21, spi: 21, armor: 22 },
    statsPerLevel: { str: 0, agi: 0, sta: 1, int: 3, spi: 2, armor: 4 },
    startWeapon: "gnarled_staff",
    abilities: [
      {
        id: "shadow_bolt",
        name: "Gloom Bolt",
        icon: "skull",
        school: "shadow",
        kind: "damage",
        levelReq: 1,
        cost: 25,
        castTime: 1.7,
        cooldown: 0,
        range: 30,
        base: 15.5,
        perLevel: 3.4,
      },
      {
        id: "demon_skin",
        name: "Fiendhide",
        icon: "chestplate",
        school: "shadow",
        kind: "buff",
        levelReq: 1,
        cost: 20,
        castTime: 0,
        cooldown: 0,
        range: 0,
        base: 30,
        perLevel: 2.8,
        duration: 1800,
        selfTarget: true,
        buffStat: "armor",
        buffAmount: 30,
        buffPerLevel: 2.8,
      },
      {
        id: "immolate",
        name: "Burning Pact",
        icon: "fire",
        school: "fire",
        kind: "dot",
        levelReq: 1,
        cost: 25,
        castTime: 2.0,
        cooldown: 0,
        range: 30,
        base: 20,
        perLevel: 2.2,
        duration: 15,
        tickInterval: 3,
      },
      {
        id: "corruption",
        name: "Blackrot",
        icon: "poison",
        school: "shadow",
        kind: "dot",
        levelReq: 4,
        cost: 35,
        castTime: 2.0,
        cooldown: 0,
        range: 30,
        base: 40,
        perLevel: 2.5,
        duration: 18,
        tickInterval: 3,
      },
      {
        id: "curse_of_agony",
        name: "Hex of Anguish",
        icon: "skull",
        school: "shadow",
        kind: "dot",
        levelReq: 8,
        cost: 25,
        castTime: 0,
        cooldown: 0,
        range: 30,
        base: 36,
        perLevel: 2.3,
        duration: 24,
        tickInterval: 3,
      },
      {
        id: "drain_life",
        name: "Consume",
        icon: "skull",
        school: "shadow",
        kind: "dot",
        levelReq: 10,
        cost: 35,
        castTime: 0,
        cooldown: 0,
        range: 20,
        base: 35,
        perLevel: 2.8,
        duration: 5,
        tickInterval: 1,
      },
      {
        id: "searing_pain",
        name: "Sear",
        icon: "fire",
        school: "fire",
        kind: "damage",
        levelReq: 16,
        cost: 35,
        castTime: 1.5,
        cooldown: 0,
        range: 30,
        base: 34,
        perLevel: 0,
      },
      {
        id: "shadowburn",
        name: "Duskfire",
        icon: "skull",
        school: "shadow",
        kind: "damage",
        levelReq: 20,
        cost: 70,
        castTime: 0,
        cooldown: 15,
        range: 20,
        base: 61,
        perLevel: 0,
      },
      {
        id: "rain_of_fire",
        name: "Rain of Fire",
        icon: "fire",
        school: "fire",
        kind: "aoe",
        levelReq: 18,
        cost: 85,
        castTime: 0,
        cooldown: 10,
        range: 30,
        base: 16,
        perLevel: 0,
        aoeRadius: 7,
        duration: 4,
        tickInterval: 1,
      },
      {
        id: "life_tap",
        name: "Hard Bargain",
        icon: "heart",
        school: "shadow",
        kind: "buff",
        levelReq: 6,
        cost: 0,
        castTime: 0,
        cooldown: 0,
        range: 0,
        base: 0,
        perLevel: 0,
        selfTarget: true,
        selfResource: 30,
      },
      {
        id: "fear",
        name: "Harrow",
        icon: "hourglass",
        school: "shadow",
        kind: "buff",
        levelReq: 14,
        cost: 40,
        castTime: 1.5,
        cooldown: 0,
        range: 20,
        base: 0,
        perLevel: 0,
        selfTarget: true,
        cc: { kind: "stun", durationSec: 8 },
      },
      {
        id: "summon_imp",
        name: "Summon Imp",
        icon: "fire",
        school: "shadow",
        kind: "buff",
        levelReq: 1,
        cost: 30,
        castTime: 2,
        cooldown: 10,
        range: 0,
        base: 0,
        perLevel: 0,
        selfTarget: true,
      },
      {
        id: "summon_voidwalker",
        name: "Summon Voidwalker",
        icon: "skull",
        school: "shadow",
        kind: "buff",
        levelReq: 10,
        cost: 50,
        castTime: 2.5,
        cooldown: 10,
        range: 0,
        base: 0,
        perLevel: 0,
        selfTarget: true,
      },
      {
        id: "summon_felhunter",
        name: "Summon Felhunter",
        icon: "poison",
        school: "shadow",
        kind: "buff",
        levelReq: 14,
        cost: 50,
        castTime: 2.5,
        cooldown: 10,
        range: 0,
        base: 0,
        perLevel: 0,
        selfTarget: true,
      },
      {
        id: "summon_succubus",
        name: "Summon Succubus",
        icon: "heart",
        school: "shadow",
        kind: "buff",
        levelReq: 16,
        cost: 50,
        castTime: 2.5,
        cooldown: 10,
        range: 0,
        base: 0,
        perLevel: 0,
        selfTarget: true,
      },
    ],
  },
  {
    id: "druid",
    name: "Druid",
    icon: "leaf",
    color: "#FF7D0A",
    resource: "mana",
    baseHp: 45,
    hpPerLevel: 13,
    baseResource: 95,
    resourcePerLevel: 22,
    baseStats: { str: 15, agi: 15, sta: 17, int: 19, spi: 20, armor: 30 },
    statsPerLevel: { str: 1, agi: 1, sta: 2, int: 2, spi: 2, armor: 6 },
    startWeapon: "gnarled_staff",
    abilities: [
      {
        id: "wrath",
        name: "Wildbolt",
        icon: "leaf",
        school: "nature",
        kind: "damage",
        levelReq: 1,
        cost: 20,
        castTime: 1.5,
        cooldown: 0,
        range: 30,
        base: 14.5,
        perLevel: 2.8,
      },
      {
        id: "healing_touch",
        name: "Wildmend",
        icon: "heart",
        school: "nature",
        kind: "heal",
        levelReq: 1,
        cost: 25,
        castTime: 2.5,
        cooldown: 0,
        range: 30,
        base: 44,
        perLevel: 8.2,
        selfTarget: true,
      },
      {
        id: "mark_of_the_wild",
        name: "Wildward",
        icon: "star",
        school: "nature",
        kind: "buff",
        levelReq: 1,
        cost: 20,
        castTime: 0,
        cooldown: 0,
        range: 30,
        base: 5,
        perLevel: 0,
        duration: 1800,
        selfTarget: true,
      },
      {
        id: "moonfire",
        name: "Lunar Tempest",
        icon: "star",
        school: "arcane",
        kind: "dot",
        levelReq: 4,
        cost: 25,
        castTime: 0,
        cooldown: 0,
        range: 30,
        base: 12,
        perLevel: 1.6,
        duration: 9,
        tickInterval: 3,
      },
      {
        id: "rejuvenation",
        name: "Wildbloom",
        icon: "leaf",
        school: "nature",
        kind: "hot",
        levelReq: 4,
        cost: 25,
        castTime: 0,
        cooldown: 0,
        range: 30,
        base: 32,
        perLevel: 4.7,
        duration: 12,
        tickInterval: 3,
        selfTarget: true,
      },
      {
        id: "thorns",
        name: "Briarguard",
        icon: "leaf",
        school: "nature",
        kind: "buff",
        levelReq: 6,
        cost: 20,
        castTime: 0,
        cooldown: 0,
        range: 30,
        base: 3,
        perLevel: 0.3,
        duration: 600,
        selfTarget: true,
      },
      {
        id: "entangling_roots",
        name: "Gripping Roots",
        icon: "leaf",
        school: "nature",
        kind: "dot",
        levelReq: 8,
        cost: 35,
        castTime: 1.5,
        cooldown: 0,
        range: 30,
        base: 0,
        perLevel: 1.8,
        duration: 12,
        tickInterval: 3,
        cc: { kind: "root", durationSec: 12 },
      },
      {
        id: "bear_form",
        name: "Bruin Form",
        icon: "shield",
        school: "physical",
        kind: "buff",
        levelReq: 10,
        cost: 30,
        castTime: 0,
        cooldown: 0,
        range: 0,
        base: 65,
        perLevel: 0,
        duration: 3600,
        selfTarget: true,
      },
      {
        id: "maul",
        name: "Bonecrush",
        icon: "hammer",
        school: "physical",
        kind: "damage",
        levelReq: 10,
        cost: 15,
        castTime: 0,
        cooldown: 0,
        range: 5,
        base: 18,
        perLevel: 0.5,
      },
      {
        id: "demoralizing_roar",
        name: "Craven Roar",
        icon: "debuffArrow",
        school: "physical",
        kind: "buff",
        levelReq: 10,
        cost: 10,
        castTime: 0,
        cooldown: 0,
        range: 0,
        base: 20,
        perLevel: 0.8,
        duration: 20,
        aoeRadius: 8,
        selfTarget: false,
        buffStat: "attackPower",
        buffAmount: -20,
        buffPerLevel: -0.8,
      },
      {
        id: "cat_form",
        name: "Wolf Form",
        icon: "feather",
        school: "physical",
        kind: "buff",
        levelReq: 12,
        cost: 30,
        castTime: 0,
        cooldown: 0,
        range: 0,
        base: 71,
        perLevel: 0,
        duration: 3600,
        selfTarget: true,
      },
      {
        id: "prowl",
        name: "Stalk",
        icon: "eye",
        school: "physical",
        kind: "buff",
        levelReq: 12,
        cost: 0,
        castTime: 0,
        cooldown: 0,
        range: 0,
        base: 50,
        perLevel: 0,
        duration: 3600,
        selfTarget: true,
      },
      {
        id: "rake",
        name: "Flense",
        icon: "fist",
        school: "physical",
        kind: "dot",
        levelReq: 12,
        cost: 35,
        castTime: 0,
        cooldown: 0,
        range: 5,
        base: 30,
        perLevel: 1.0,
        duration: 9,
        tickInterval: 3,
      },
      {
        id: "claw",
        name: "Claw",
        icon: "fist",
        school: "physical",
        kind: "damage",
        levelReq: 12,
        cost: 45,
        castTime: 0,
        cooldown: 0,
        range: 5,
        base: 12,
        perLevel: 0.4,
      },
      {
        id: "regrowth",
        name: "Second Bloom",
        icon: "heart",
        school: "nature",
        kind: "heal",
        levelReq: 14,
        cost: 55,
        castTime: 2.0,
        cooldown: 0,
        range: 30,
        base: 57,
        perLevel: 0,
        selfTarget: true,
      },
      {
        id: "ferocious_bite",
        name: "Gorebite",
        icon: "fist",
        school: "physical",
        kind: "damage",
        levelReq: 14,
        cost: 35,
        castTime: 0,
        cooldown: 0,
        range: 5,
        base: 52,
        perLevel: 0,
      },
      {
        id: "barkskin",
        name: "Oakhide",
        icon: "shield",
        school: "nature",
        kind: "buff",
        levelReq: 16,
        cost: 30,
        castTime: 0,
        cooldown: 60,
        range: 0,
        base: 150,
        perLevel: 0,
        duration: 15,
        selfTarget: true,
        buffStat: "armor",
        buffAmount: 150,
        buffPerLevel: 0,
      },
      {
        id: "swipe",
        name: "Sweeping Claws",
        icon: "fist",
        school: "physical",
        kind: "aoe",
        levelReq: 16,
        cost: 20,
        castTime: 0,
        cooldown: 0,
        range: 0,
        base: 13.5,
        perLevel: 0,
        aoeRadius: 5,
      },
      {
        id: "starfire",
        name: "Skyfall",
        icon: "star",
        school: "arcane",
        kind: "damage",
        levelReq: 18,
        cost: 80,
        castTime: 3.0,
        cooldown: 0,
        range: 30,
        base: 96,
        perLevel: 0,
      },
      {
        id: "travel_form",
        name: "Fleet Form",
        icon: "sprint",
        school: "nature",
        kind: "buff",
        levelReq: 16,
        cost: 30,
        castTime: 0,
        cooldown: 0,
        range: 0,
        base: 140,
        perLevel: 0,
        duration: 3600,
        selfTarget: true,
      },
      {
        id: "dash",
        name: "Dash",
        icon: "sprint",
        school: "physical",
        kind: "buff",
        levelReq: 18,
        cost: 0,
        castTime: 0,
        cooldown: 60,
        range: 0,
        base: 150,
        perLevel: 0,
        duration: 15,
        selfTarget: true,
      },
      {
        id: "insect_swarm",
        name: "Stinging Swarm",
        icon: "poison",
        school: "nature",
        kind: "dot",
        levelReq: 20,
        cost: 45,
        castTime: 0,
        cooldown: 0,
        range: 30,
        base: 48,
        perLevel: 0,
        duration: 12,
        tickInterval: 3,
      },
      {
        id: "tigers_fury",
        name: "Wolfsblood",
        icon: "buffArrow",
        school: "physical",
        kind: "buff",
        levelReq: 20,
        cost: 30,
        castTime: 0,
        cooldown: 0,
        range: 0,
        base: 40,
        perLevel: 0,
        duration: 6,
        selfTarget: true,
        buffStat: "attackPower",
        buffAmount: 40,
        buffPerLevel: 0,
      },
      {
        id: "rip",
        name: "Rip",
        icon: "debuffArrow",
        school: "physical",
        kind: "dot",
        levelReq: 20,
        cost: 30,
        castTime: 0,
        cooldown: 0,
        range: 5,
        base: 60,
        perLevel: 0,
        duration: 12,
        tickInterval: 2,
      },
      {
        id: "hurricane",
        name: "Hurricane",
        icon: "lightning",
        school: "nature",
        kind: "aoe",
        levelReq: 18,
        cost: 90,
        castTime: 0,
        cooldown: 12,
        range: 30,
        base: 14,
        perLevel: 0,
        aoeRadius: 8,
        duration: 6,
        tickInterval: 1,
      },
      {
        id: "growl",
        name: "Menace",
        icon: "shield",
        school: "physical",
        kind: "buff",
        levelReq: 10,
        cost: 0,
        castTime: 0,
        cooldown: 10,
        range: 8,
        base: 0,
        perLevel: 0,
        selfTarget: true,
        cc: { kind: "taunt", durationSec: 3 },
      },
      {
        id: "bash",
        name: "Concuss",
        icon: "hourglass",
        school: "physical",
        kind: "buff",
        levelReq: 16,
        cost: 10,
        castTime: 0,
        cooldown: 60,
        range: 8,
        base: 0,
        perLevel: 0,
        selfTarget: true,
        cc: { kind: "stun", durationSec: 2 },
      },
      {
        id: "enrage",
        name: "Stoke",
        icon: "fire",
        school: "physical",
        kind: "buff",
        levelReq: 16,
        cost: 0,
        castTime: 0,
        cooldown: 60,
        range: 0,
        base: 0,
        perLevel: 0,
        selfTarget: true,
        selfResource: 20,
      },
      {
        id: "pounce",
        name: "Slinkstrike",
        icon: "hourglass",
        school: "physical",
        kind: "buff",
        levelReq: 18,
        cost: 50,
        castTime: 0,
        cooldown: 0,
        range: 8,
        base: 0,
        perLevel: 0,
        selfTarget: true,
        cc: { kind: "stun", durationSec: 2 },
      },
      {
        id: "hibernate",
        name: "Slumber",
        icon: "hourglass",
        school: "nature",
        kind: "buff",
        levelReq: 18,
        cost: 50,
        castTime: 1.5,
        cooldown: 0,
        range: 30,
        base: 0,
        perLevel: 0,
        selfTarget: true,
        cc: { kind: "stun", durationSec: 8 },
      },
    ],
  },
];

export function classById(id: string): ClassDef {
  const found = CLASSES.find((c) => c.id === id);
  if (!found) throw new Error(`Unknown class id: ${id}`);
  return found;
}
