import { existsSync, mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import { readGlbDims } from "./dims";
import type { AssetSource, IndexEntry, ModelDims } from "./manifest";
import { sourceById } from "./sources";

export function keyFromFile(file: string): string {
  return file.replace(/\.gltf\.glb$/i, "").replace(/\.glb$/i, "");
}

export function entryForFile(source: AssetSource, file: string, dims?: ModelDims): IndexEntry {
  return {
    id: `${source.id}/${keyFromFile(file)}`,
    source: source.id,
    categories: source.categories,
    file,
    ...(dims === undefined ? {} : { dims }),
  };
}

function collectGlbFiles(dir: string): { file: string; full: string }[] {
  const found: { file: string; full: string }[] = [];
  for (const name of readdirSync(dir)) {
    const full = join(dir, name);
    if (statSync(full).isDirectory()) {
      found.push(...collectGlbFiles(full));
    } else if (/\.glb$/i.test(name)) {
      found.push({ file: name, full });
    }
  }
  return found;
}

function measureDims(full: string): ModelDims | undefined {
  try {
    return readGlbDims(readFileSync(full)) ?? undefined;
  } catch {
    return undefined;
  }
}

export function indexSourceDir(source: AssetSource, dir: string): IndexEntry[] {
  const seen = new Set<string>();
  const entries: IndexEntry[] = [];
  for (const { file, full } of collectGlbFiles(dir).sort((a, b) => a.file.localeCompare(b.file))) {
    if (seen.has(file)) continue;
    seen.add(file);
    entries.push(entryForFile(source, file, measureDims(full)));
  }
  return entries;
}

function safeIdentifier(sourceId: string): string {
  return `s_${sourceId.replace(/[^a-zA-Z0-9]/g, "_")}`;
}

function renderTsBarrel(sourceIds: readonly string[]): string {
  const ordered = [...sourceIds].sort((a, b) => a.localeCompare(b));
  const imports = ordered
    .map((id) => `import ${safeIdentifier(id)} from "./${id}.json" with { type: "json" };`)
    .join("\n");
  const table = ordered
    .map((id) => `  ${JSON.stringify(id)}: ${safeIdentifier(id)} as IndexEntry[],`)
    .join("\n");
  return `// AUTO-GENERATED by \`assets reindex\`. Do not edit by hand.
import type { IndexEntry } from "../manifest";
${imports}

export const generatedBySource: Record<string, IndexEntry[]> = {
${table}
};

export const generatedIndex: IndexEntry[] = Object.values(generatedBySource).flat();
`;
}

function renderJsBarrel(sourceIds: readonly string[]): string {
  const ordered = [...sourceIds].sort((a, b) => a.localeCompare(b));
  const imports = ordered
    .map((id) => `import ${safeIdentifier(id)} from "./${id}.json" with { type: "json" };`)
    .join("\n");
  const table = ordered.map((id) => `  ${JSON.stringify(id)}: ${safeIdentifier(id)},`).join("\n");
  return `// AUTO-GENERATED by \`assets reindex\`. Do not edit by hand.
${imports}

export const generatedBySource = {
${table}
};

export const generatedIndex = Object.values(generatedBySource).flat();
`;
}

export interface ReindexResult {
  perSource: { source: string; count: number }[];
  total: number;
}

export function reindex(modelsDir: string, outDir: string): ReindexResult {
  mkdirSync(outDir, { recursive: true });
  const perSource: { source: string; count: number }[] = [];

  const subdirs = existsSync(modelsDir)
    ? readdirSync(modelsDir).filter((name) => statSync(join(modelsDir, name)).isDirectory())
    : [];

  for (const sourceId of subdirs.sort((a, b) => a.localeCompare(b))) {
    const source = sourceById.get(sourceId);
    if (source === undefined) {
      perSource.push({ source: `${sourceId} (unknown, skipped)`, count: 0 });
      continue;
    }
    const entries = indexSourceDir(source, join(modelsDir, sourceId));
    writeFileSync(join(outDir, `${sourceId}.json`), `${JSON.stringify(entries, null, 2)}\n`);
    perSource.push({ source: sourceId, count: entries.length });
  }

  const barrelIds = readdirSync(outDir)
    .filter((name) => name.endsWith(".json"))
    .map((name) => name.slice(0, -".json".length))
    .filter((id) => sourceById.has(id));

  writeFileSync(join(outDir, "index.ts"), renderTsBarrel(barrelIds));
  // Published installs only ship dist/; write a JS barrel there so buildCatalog can re-import after reindex.
  // Source-tree reindex keeps the TypeScript barrel that the package build compiles.
  if (!/[/\\]src[/\\]generated$/i.test(outDir)) {
    writeFileSync(join(outDir, "index.js"), renderJsBarrel(barrelIds));
  }
  return { perSource, total: perSource.reduce((sum, entry) => sum + entry.count, 0) };
}
