import { existsSync, mkdirSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import type { AssetSource, IndexEntry } from "./manifest";
import { sourceById } from "./sources";

export function keyFromFile(file: string): string {
  return file.replace(/\.glb$/i, "");
}

export function entryForFile(source: AssetSource, file: string): IndexEntry {
  return {
    id: `${source.id}/${keyFromFile(file)}`,
    source: source.id,
    categories: source.categories,
    file,
  };
}

function collectGlbFiles(dir: string): string[] {
  const found: string[] = [];
  for (const name of readdirSync(dir)) {
    const full = join(dir, name);
    if (statSync(full).isDirectory()) {
      found.push(...collectGlbFiles(full));
    } else if (/\.glb$/i.test(name)) {
      found.push(name);
    }
  }
  return found;
}

export function indexSourceDir(source: AssetSource, dir: string): IndexEntry[] {
  const seen = new Set<string>();
  const entries: IndexEntry[] = [];
  for (const file of collectGlbFiles(dir).sort((a, b) => a.localeCompare(b))) {
    if (seen.has(file)) continue;
    seen.add(file);
    entries.push(entryForFile(source, file));
  }
  return entries;
}

function safeIdentifier(sourceId: string): string {
  return `s_${sourceId.replace(/[^a-zA-Z0-9]/g, "_")}`;
}

function renderBarrel(sourceIds: readonly string[]): string {
  const ordered = [...sourceIds].sort((a, b) => a.localeCompare(b));
  const imports = ordered
    .map((id) => `import ${safeIdentifier(id)} from "./${id}.json" with { type: "json" };`)
    .join("\n");
  const table = ordered
    .map((id) => `  ${JSON.stringify(id)}: ${safeIdentifier(id)} as IndexEntry[],`)
    .join("\n");
  return `// AUTO-GENERATED by \`assets reindex\`. Do not edit by hand.
import type { IndexEntry } from "../manifest";
${imports}

export const generatedBySource: Record<string, IndexEntry[]> = {
${table}
};

export const generatedIndex: IndexEntry[] = Object.values(generatedBySource).flat();
`;
}

export interface ReindexResult {
  perSource: { source: string; count: number }[];
  total: number;
}

export function reindex(modelsDir: string, outDir: string): ReindexResult {
  mkdirSync(outDir, { recursive: true });
  const perSource: { source: string; count: number }[] = [];
  const sourceIds: string[] = [];

  const subdirs = existsSync(modelsDir)
    ? readdirSync(modelsDir).filter((name) => statSync(join(modelsDir, name)).isDirectory())
    : [];

  for (const sourceId of subdirs.sort((a, b) => a.localeCompare(b))) {
    const source = sourceById.get(sourceId);
    if (source === undefined) {
      perSource.push({ source: `${sourceId} (unknown, skipped)`, count: 0 });
      continue;
    }
    const entries = indexSourceDir(source, join(modelsDir, sourceId));
    writeFileSync(join(outDir, `${sourceId}.json`), `${JSON.stringify(entries, null, 2)}\n`);
    sourceIds.push(sourceId);
    perSource.push({ source: sourceId, count: entries.length });
  }

  writeFileSync(join(outDir, "index.ts"), renderBarrel(sourceIds));
  return { perSource, total: perSource.reduce((sum, entry) => sum + entry.count, 0) };
}
