import { existsSync, mkdirSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import type { AssetSource, IndexEntry } from "./manifest";
import { sourceById } from "./sources";

/** Strips the `.svg`/`.png` extension off a pulled sprite/icon filename to get its id suffix. */
export function keyFromSpriteFile(file: string): string {
  return file.replace(/\.(svg|png)$/i, "");
}

/** Builds one sprite/icon `IndexEntry` — same shape as a model entry, minus `dims`. */
export function entryForSpriteFile(source: AssetSource, file: string): IndexEntry {
  return {
    id: `${source.id}/${keyFromSpriteFile(file)}`,
    source: source.id,
    categories: source.categories,
    file,
  };
}

function collectSpriteFiles(dir: string): { file: string; full: string }[] {
  const found: { file: string; full: string }[] = [];
  for (const name of readdirSync(dir)) {
    const full = join(dir, name);
    if (statSync(full).isDirectory()) {
      found.push(...collectSpriteFiles(full));
    } else if (/\.(svg|png)$/i.test(name)) {
      found.push({ file: name, full });
    }
  }
  return found;
}

/** Walks a pulled sprite-pack directory and returns one `IndexEntry` per SVG/PNG, deduped by filename. */
export function indexSpriteSourceDir(source: AssetSource, dir: string): IndexEntry[] {
  const seen = new Set<string>();
  const entries: IndexEntry[] = [];
  for (const { file } of collectSpriteFiles(dir).sort((a, b) => a.file.localeCompare(b.file))) {
    if (seen.has(file)) continue;
    seen.add(file);
    entries.push(entryForSpriteFile(source, file));
  }
  return entries;
}

function safeIdentifier(sourceId: string): string {
  return `s_${sourceId.replace(/[^a-zA-Z0-9]/g, "_")}`;
}

function renderTsBarrel(sourceIds: readonly string[]): string {
  const ordered = [...sourceIds].sort((a, b) => a.localeCompare(b));
  const imports = ordered
    .map((id) => `import ${safeIdentifier(id)} from "./${id}.json" with { type: "json" };`)
    .join("\n");
  const table = ordered
    .map((id) => `  ${JSON.stringify(id)}: ${safeIdentifier(id)} as IndexEntry[],`)
    .join("\n");
  return `// AUTO-GENERATED by \`assets reindex-sprites\`. Do not edit by hand.
import type { IndexEntry } from "../manifest";
${imports}

/** Pulled sprite/icon entries grouped by source id. */
export const generatedSpriteBySource: Record<string, IndexEntry[]> = {
${table}
};

/** Every pulled sprite/icon entry across all sources, flattened. */
export const generatedSpriteIndex: IndexEntry[] = Object.values(generatedSpriteBySource).flat();
`;
}

function renderJsBarrel(sourceIds: readonly string[]): string {
  const ordered = [...sourceIds].sort((a, b) => a.localeCompare(b));
  const imports = ordered
    .map((id) => `import ${safeIdentifier(id)} from "./${id}.json" with { type: "json" };`)
    .join("\n");
  const table = ordered.map((id) => `  ${JSON.stringify(id)}: ${safeIdentifier(id)},`).join("\n");
  return `// AUTO-GENERATED by \`assets reindex-sprites\`. Do not edit by hand.
${imports}

export const generatedSpriteBySource = {
${table}
};

export const generatedSpriteIndex = Object.values(generatedSpriteBySource).flat();
`;
}

/** Per-source and total counts returned by `reindexSprites`. */
export interface ReindexSpritesResult {
  perSource: { source: string; count: number }[];
  total: number;
}

/** Same shape as `reindex` (models) but walks SVG/PNG files and skips dims measurement — sprites have no footprint. */
export function reindexSprites(spritesDir: string, outDir: string): ReindexSpritesResult {
  mkdirSync(outDir, { recursive: true });
  const perSource: { source: string; count: number }[] = [];

  const subdirs = existsSync(spritesDir)
    ? readdirSync(spritesDir).filter((name) => statSync(join(spritesDir, name)).isDirectory())
    : [];

  for (const sourceId of subdirs.sort((a, b) => a.localeCompare(b))) {
    const source = sourceById.get(sourceId);
    if (source === undefined || source.kind !== "sprite") {
      perSource.push({ source: `${sourceId} (unknown, skipped)`, count: 0 });
      continue;
    }
    const entries = indexSpriteSourceDir(source, join(spritesDir, sourceId));
    writeFileSync(join(outDir, `${sourceId}.json`), `${JSON.stringify(entries, null, 2)}\n`);
    perSource.push({ source: sourceId, count: entries.length });
  }

  const barrelIds = readdirSync(outDir)
    .filter((name) => name.endsWith(".json"))
    .map((name) => name.slice(0, -".json".length))
    .filter((id) => sourceById.has(id));

  writeFileSync(join(outDir, "index.ts"), renderTsBarrel(barrelIds));
  if (!/[/\\]src[/\\]generated-sprites$/i.test(outDir)) {
    writeFileSync(join(outDir, "index.js"), renderJsBarrel(barrelIds));
  }
  return { perSource, total: perSource.reduce((sum, entry) => sum + entry.count, 0) };
}
