export const SPECS = [
    {
        id: "warrior_arms",
        classId: "warrior",
        name: "Battlecraft",
        icon: "sword",
        nodes: [
            { id: "arms_imp_overpower", branch: "warrior_arms", maxRank: 2 },
            { id: "arms_deep_wounds", branch: "warrior_arms", maxRank: 3 },
            { id: "arms_imp_slam", branch: "warrior_arms", maxRank: 2, requires: ["arms_imp_overpower"], requiresPointsInBranch: 2 },
            { id: "arms_tactical_mastery", branch: "warrior_arms", maxRank: 2, requiresPointsInBranch: 2, modifiersPerRank: { attackPower: { add: 12 } } },
            { id: "arms_choice", branch: "warrior_arms", maxRank: 1, requiresPointsInBranch: 5 },
            { id: "arms_imp_mortal_strike", branch: "warrior_arms", maxRank: 2, requires: ["arms_choice"], requiresPointsInBranch: 8 },
        ],
    },
    {
        id: "warrior_fury",
        classId: "warrior",
        name: "Bloodrush",
        icon: "axe",
        nodes: [
            { id: "fury_cruelty", branch: "warrior_fury", maxRank: 3, modifiersPerRank: { critPct: { add: 1 } } },
            { id: "fury_unbridled_wrath", branch: "warrior_fury", maxRank: 2, modifiersPerRank: { attackPower: { add: 10 } } },
            { id: "fury_whirlwind", branch: "warrior_fury", maxRank: 1, requires: ["fury_cruelty"], requiresPointsInBranch: 2 },
            { id: "fury_imp_cleave", branch: "warrior_fury", maxRank: 2, requiresPointsInBranch: 2 },
            { id: "fury_choice", branch: "warrior_fury", maxRank: 1, requiresPointsInBranch: 5 },
            { id: "fury_imp_bloodthirst", branch: "warrior_fury", maxRank: 2, requires: ["fury_choice"], requiresPointsInBranch: 8 },
        ],
    },
    {
        id: "warrior_prot",
        classId: "warrior",
        name: "Ironguard",
        icon: "shield",
        nodes: [
            { id: "prot_toughness", branch: "warrior_prot", maxRank: 3, modifiersPerRank: { armor: { multiply: 1.05 } } },
            { id: "prot_anticipation", branch: "warrior_prot", maxRank: 3 },
            { id: "prot_imp_thunder_clap", branch: "warrior_prot", maxRank: 2, requires: ["prot_toughness"], requiresPointsInBranch: 2 },
            { id: "prot_imp_sunder", branch: "warrior_prot", maxRank: 2, requiresPointsInBranch: 2 },
            { id: "prot_choice", branch: "warrior_prot", maxRank: 1, requiresPointsInBranch: 5 },
            { id: "prot_imp_shield_slam", branch: "warrior_prot", maxRank: 2, requires: ["prot_choice"], requiresPointsInBranch: 8 },
        ],
    },
    {
        id: "paladin_holy",
        classId: "paladin",
        name: "Sacrament",
        icon: "heart",
        nodes: [
            { id: "holy_imp_holy_light", branch: "paladin_holy", maxRank: 3 },
            { id: "holy_divine_intellect", branch: "paladin_holy", maxRank: 3, modifiersPerRank: { int: { add: 3 } } },
            { id: "holy_flash_focus", branch: "paladin_holy", maxRank: 2, requires: ["holy_imp_holy_light"], requiresPointsInBranch: 2 },
            { id: "holy_lay_blessing", branch: "paladin_holy", maxRank: 2, requiresPointsInBranch: 2 },
            { id: "holy_choice", branch: "paladin_holy", maxRank: 1, requiresPointsInBranch: 5 },
            { id: "holy_light_mastery", branch: "paladin_holy", maxRank: 2, requires: ["holy_choice"], requiresPointsInBranch: 8, modifiersPerRank: { critPct: { add: 1 } } },
        ],
    },
    {
        id: "paladin_protection",
        classId: "paladin",
        name: "Vigil",
        icon: "shield",
        nodes: [
            { id: "prot_redoubt", branch: "paladin_protection", maxRank: 3, modifiersPerRank: { armor: { multiply: 1.05 } } },
            { id: "prot_anticipation", branch: "paladin_protection", maxRank: 3 },
            { id: "prot_imp_righteous_fury", branch: "paladin_protection", maxRank: 2, requires: ["prot_redoubt"], requiresPointsInBranch: 2 },
            { id: "prot_guardians_favor", branch: "paladin_protection", maxRank: 2, requiresPointsInBranch: 2 },
            { id: "prot_choice", branch: "paladin_protection", maxRank: 1, requiresPointsInBranch: 5 },
            { id: "prot_holy_shield", branch: "paladin_protection", maxRank: 2, requires: ["prot_choice"], requiresPointsInBranch: 8 },
        ],
    },
    {
        id: "paladin_retribution",
        classId: "paladin",
        name: "Requital",
        icon: "hammer",
        nodes: [
            { id: "ret_benediction", branch: "paladin_retribution", maxRank: 3 },
            { id: "ret_conviction", branch: "paladin_retribution", maxRank: 3, modifiersPerRank: { critPct: { add: 1 } } },
            { id: "ret_imp_judgement", branch: "paladin_retribution", maxRank: 2, requires: ["ret_benediction"], requiresPointsInBranch: 2 },
            { id: "ret_seal_command", branch: "paladin_retribution", maxRank: 2, requiresPointsInBranch: 2 },
            { id: "ret_choice", branch: "paladin_retribution", maxRank: 1, requiresPointsInBranch: 5 },
            { id: "ret_crusader_strikes", branch: "paladin_retribution", maxRank: 2, requires: ["ret_choice"], requiresPointsInBranch: 8 },
        ],
    },
    {
        id: "hunter_beast_mastery",
        classId: "hunter",
        name: "Packlord",
        icon: "feather",
        nodes: [
            { id: "bm_thick_hide", branch: "hunter_beast_mastery", maxRank: 3, modifiersPerRank: { armor: { multiply: 1.04 }, sta: { add: 1 } } },
            { id: "bm_unleashed_fury", branch: "hunter_beast_mastery", maxRank: 3, modifiersPerRank: { attackPower: { add: 8 } } },
            { id: "bm_imp_mend", branch: "hunter_beast_mastery", maxRank: 2, requires: ["bm_thick_hide"], requiresPointsInBranch: 2 },
            { id: "bm_ferocity", branch: "hunter_beast_mastery", maxRank: 2, requiresPointsInBranch: 2, modifiersPerRank: { critPct: { add: 1.5 } } },
            { id: "bm_choice", branch: "hunter_beast_mastery", maxRank: 1, requiresPointsInBranch: 5 },
            { id: "bm_focused_fire", branch: "hunter_beast_mastery", maxRank: 2, requires: ["bm_choice"], requiresPointsInBranch: 8, modifiersPerRank: { critPct: { add: 1 } } },
        ],
    },
    {
        id: "hunter_marksmanship",
        classId: "hunter",
        name: "Coldsight",
        icon: "bow",
        nodes: [
            { id: "mm_imp_arcane_shot", branch: "hunter_marksmanship", maxRank: 3 },
            { id: "mm_lethal_shots", branch: "hunter_marksmanship", maxRank: 3, modifiersPerRank: { critPct: { add: 1 } } },
            { id: "mm_aimed_focus", branch: "hunter_marksmanship", maxRank: 2, requires: ["mm_imp_arcane_shot"], requiresPointsInBranch: 2 },
            { id: "mm_barrage", branch: "hunter_marksmanship", maxRank: 2, requiresPointsInBranch: 2 },
            { id: "mm_choice", branch: "hunter_marksmanship", maxRank: 1, requiresPointsInBranch: 5 },
            { id: "mm_marksman_mastery", branch: "hunter_marksmanship", maxRank: 2, requires: ["mm_choice"], requiresPointsInBranch: 8 },
        ],
    },
    {
        id: "hunter_survival",
        classId: "hunter",
        name: "Fieldcraft",
        icon: "crossbow",
        nodes: [
            { id: "surv_humanoid_slaying", branch: "hunter_survival", maxRank: 3, modifiersPerRank: { agi: { add: 1 } } },
            { id: "surv_savage_strikes", branch: "hunter_survival", maxRank: 3, modifiersPerRank: { critPct: { add: 1 } } },
            { id: "surv_imp_wing_clip", branch: "hunter_survival", maxRank: 2, requires: ["surv_humanoid_slaying"], requiresPointsInBranch: 2 },
            { id: "surv_deterrence", branch: "hunter_survival", maxRank: 2, requiresPointsInBranch: 2 },
            { id: "surv_choice", branch: "hunter_survival", maxRank: 1, requiresPointsInBranch: 5 },
            { id: "surv_lightning_reflexes", branch: "hunter_survival", maxRank: 2, requires: ["surv_choice"], requiresPointsInBranch: 8, modifiersPerRank: { agi: { add: 5 } } },
        ],
    },
    {
        id: "rogue_assassination",
        classId: "rogue",
        name: "Knifework",
        icon: "poison",
        nodes: [
            { id: "ass_imp_eviscerate", branch: "rogue_assassination", maxRank: 3 },
            { id: "ass_remorseless", branch: "rogue_assassination", maxRank: 3, modifiersPerRank: { critPct: { add: 1 } } },
            { id: "ass_murder", branch: "rogue_assassination", maxRank: 2, requires: ["ass_imp_eviscerate"], requiresPointsInBranch: 2 },
            { id: "ass_laceration", branch: "rogue_assassination", maxRank: 2, requiresPointsInBranch: 2 },
            { id: "ass_choice", branch: "rogue_assassination", maxRank: 1, requiresPointsInBranch: 5 },
            { id: "ass_vigor", branch: "rogue_assassination", maxRank: 2, requires: ["ass_choice"], requiresPointsInBranch: 8 },
        ],
    },
    {
        id: "rogue_combat",
        classId: "rogue",
        name: "Thuggery",
        icon: "dagger",
        nodes: [
            { id: "combat_imp_gouge", branch: "rogue_combat", maxRank: 3 },
            { id: "combat_precision", branch: "rogue_combat", maxRank: 3, modifiersPerRank: { attackPower: { add: 8 } } },
            { id: "combat_imp_sprint", branch: "rogue_combat", maxRank: 2, requires: ["combat_imp_gouge"], requiresPointsInBranch: 2 },
            { id: "combat_dual_wield", branch: "rogue_combat", maxRank: 2, requiresPointsInBranch: 2 },
            { id: "combat_choice", branch: "rogue_combat", maxRank: 1, requiresPointsInBranch: 5 },
            { id: "combat_weapon_mastery", branch: "rogue_combat", maxRank: 2, requires: ["combat_choice"], requiresPointsInBranch: 8, modifiersPerRank: { attackPower: { multiply: 1.08 } } },
        ],
    },
    {
        id: "rogue_subtlety",
        classId: "rogue",
        name: "Skulduggery",
        icon: "cloak",
        nodes: [
            { id: "sub_master_deception", branch: "rogue_subtlety", maxRank: 3, modifiersPerRank: { agi: { add: 1 } } },
            { id: "sub_opportunity", branch: "rogue_subtlety", maxRank: 3 },
            { id: "sub_elusiveness", branch: "rogue_subtlety", maxRank: 2, requires: ["sub_master_deception"], requiresPointsInBranch: 2 },
            { id: "sub_imp_ambush", branch: "rogue_subtlety", maxRank: 2, requiresPointsInBranch: 2 },
            { id: "sub_choice", branch: "rogue_subtlety", maxRank: 1, requiresPointsInBranch: 5 },
            { id: "sub_shadowstep", branch: "rogue_subtlety", maxRank: 2, requires: ["sub_choice"], requiresPointsInBranch: 8, modifiersPerRank: { agi: { add: 4 }, critPct: { add: 1 } } },
        ],
    },
    {
        id: "priest_discipline",
        classId: "priest",
        name: "Doctrine",
        icon: "shield",
        nodes: [
            { id: "disc_unbreakable_will", branch: "priest_discipline", maxRank: 3, modifiersPerRank: { sta: { add: 2 }, spi: { add: 1 } } },
            { id: "disc_twin_disciplines", branch: "priest_discipline", maxRank: 3 },
            { id: "disc_imp_shield", branch: "priest_discipline", maxRank: 2, requires: ["disc_unbreakable_will"], requiresPointsInBranch: 2 },
            { id: "disc_mental_agility", branch: "priest_discipline", maxRank: 2, requiresPointsInBranch: 2 },
            { id: "disc_choice", branch: "priest_discipline", maxRank: 1, requiresPointsInBranch: 5 },
            { id: "disc_penance", branch: "priest_discipline", maxRank: 2, requires: ["disc_choice"], requiresPointsInBranch: 8 },
        ],
    },
    {
        id: "priest_holy",
        classId: "priest",
        name: "Benison",
        icon: "heart",
        nodes: [
            { id: "holy_healing_focus", branch: "priest_holy", maxRank: 3 },
            { id: "holy_renewal", branch: "priest_holy", maxRank: 3 },
            { id: "holy_divine_fury", branch: "priest_holy", maxRank: 2, requires: ["holy_healing_focus"], requiresPointsInBranch: 2 },
            { id: "holy_inspiration", branch: "priest_holy", maxRank: 2, requiresPointsInBranch: 2, modifiersPerRank: { armor: { multiply: 1.05 } } },
            { id: "holy_priest_choice", branch: "priest_holy", maxRank: 1, requiresPointsInBranch: 5 },
            { id: "holy_spiritual_healing", branch: "priest_holy", maxRank: 2, requires: ["holy_priest_choice"], requiresPointsInBranch: 8, modifiersPerRank: { critPct: { add: 1 } } },
        ],
    },
    {
        id: "priest_shadow",
        classId: "priest",
        name: "Vespers",
        icon: "skull",
        nodes: [
            { id: "shadow_blackout", branch: "priest_shadow", maxRank: 3 },
            { id: "shadow_word_pain", branch: "priest_shadow", maxRank: 3 },
            { id: "shadow_mind_flay", branch: "priest_shadow", maxRank: 2, requires: ["shadow_blackout"], requiresPointsInBranch: 2 },
            { id: "shadow_focus", branch: "priest_shadow", maxRank: 2, requiresPointsInBranch: 2 },
            { id: "shadow_choice", branch: "priest_shadow", maxRank: 1, requiresPointsInBranch: 5 },
            { id: "shadow_shadowform", branch: "priest_shadow", maxRank: 2, requires: ["shadow_choice"], requiresPointsInBranch: 8, modifiersPerRank: { armor: { multiply: 1.05 } } },
        ],
    },
    {
        id: "shaman_elemental",
        classId: "shaman",
        name: "Thundercall",
        icon: "lightning",
        nodes: [
            { id: "ele_concussion", branch: "shaman_elemental", maxRank: 3 },
            { id: "ele_call_flame", branch: "shaman_elemental", maxRank: 3 },
            { id: "ele_reverberation", branch: "shaman_elemental", maxRank: 2, requires: ["ele_concussion"], requiresPointsInBranch: 2 },
            { id: "ele_elemental_focus", branch: "shaman_elemental", maxRank: 2, requiresPointsInBranch: 2 },
            { id: "ele_choice", branch: "shaman_elemental", maxRank: 1, requiresPointsInBranch: 5 },
            { id: "ele_lightning_mastery", branch: "shaman_elemental", maxRank: 2, requires: ["ele_choice"], requiresPointsInBranch: 8 },
        ],
    },
    {
        id: "shaman_enhancement",
        classId: "shaman",
        name: "Warspirit",
        icon: "fist",
        nodes: [
            { id: "enh_ancestral_weapons", branch: "shaman_enhancement", maxRank: 3, modifiersPerRank: { attackPower: { add: 8 } } },
            { id: "enh_shield_spec", branch: "shaman_enhancement", maxRank: 3, modifiersPerRank: { armor: { multiply: 1.04 } } },
            { id: "enh_imp_rockbiter", branch: "shaman_enhancement", maxRank: 2, requires: ["enh_ancestral_weapons"], requiresPointsInBranch: 2 },
            { id: "enh_flurry", branch: "shaman_enhancement", maxRank: 2, requiresPointsInBranch: 2, modifiersPerRank: { critPct: { add: 2 } } },
            { id: "enh_choice", branch: "shaman_enhancement", maxRank: 1, requiresPointsInBranch: 5 },
            { id: "enh_spirit_weapons", branch: "shaman_enhancement", maxRank: 2, requires: ["enh_choice"], requiresPointsInBranch: 8 },
        ],
    },
    {
        id: "shaman_restoration",
        classId: "shaman",
        name: "Spiritmend",
        icon: "potionBlue",
        nodes: [
            { id: "rest_tidal_focus", branch: "shaman_restoration", maxRank: 3 },
            { id: "rest_imp_healing_wave", branch: "shaman_restoration", maxRank: 3 },
            { id: "rest_ancestral_healing", branch: "shaman_restoration", maxRank: 2, requires: ["rest_tidal_focus"], requiresPointsInBranch: 2, modifiersPerRank: { armor: { multiply: 1.05 } } },
            { id: "rest_healing_grace", branch: "shaman_restoration", maxRank: 2, requiresPointsInBranch: 2, modifiersPerRank: { spi: { add: 2 } } },
            { id: "rest_choice", branch: "shaman_restoration", maxRank: 1, requiresPointsInBranch: 5 },
            { id: "rest_chain_focus", branch: "shaman_restoration", maxRank: 2, requires: ["rest_choice"], requiresPointsInBranch: 8, modifiersPerRank: { int: { add: 2 } } },
        ],
    },
    {
        id: "mage_arcane",
        classId: "mage",
        name: "Aethermancy",
        icon: "star",
        nodes: [
            { id: "arc_imp_missiles", branch: "mage_arcane", maxRank: 3 },
            { id: "arc_arcane_concentration", branch: "mage_arcane", maxRank: 3 },
            { id: "arc_imp_polymorph", branch: "mage_arcane", maxRank: 2, requires: ["arc_imp_missiles"], requiresPointsInBranch: 2 },
            { id: "arc_arcane_power", branch: "mage_arcane", maxRank: 2, requiresPointsInBranch: 2, modifiersPerRank: { int: { add: 2 } } },
            { id: "arc_choice", branch: "mage_arcane", maxRank: 1, requiresPointsInBranch: 5 },
            { id: "arc_netherwind", branch: "mage_arcane", maxRank: 2, requires: ["arc_choice"], requiresPointsInBranch: 8 },
        ],
    },
    {
        id: "mage_fire",
        classId: "mage",
        name: "Pyromancy",
        icon: "fire",
        nodes: [
            { id: "fire_imp_fireball", branch: "mage_fire", maxRank: 3 },
            { id: "fire_impact", branch: "mage_fire", maxRank: 3, modifiersPerRank: { critPct: { add: 1 } } },
            { id: "fire_imp_blast", branch: "mage_fire", maxRank: 2, requires: ["fire_imp_fireball"], requiresPointsInBranch: 2 },
            { id: "fire_incinerate", branch: "mage_fire", maxRank: 2, requiresPointsInBranch: 2 },
            { id: "fire_choice", branch: "mage_fire", maxRank: 1, requiresPointsInBranch: 5 },
            { id: "fire_pyromancer", branch: "mage_fire", maxRank: 2, requires: ["fire_choice"], requiresPointsInBranch: 8 },
        ],
    },
    {
        id: "mage_frost",
        classId: "mage",
        name: "Cryomancy",
        icon: "frost",
        nodes: [
            { id: "frost_imp_frostbolt", branch: "mage_frost", maxRank: 3 },
            { id: "frost_permafrost", branch: "mage_frost", maxRank: 3, modifiersPerRank: { armor: { multiply: 1.04 } } },
            { id: "frost_imp_nova", branch: "mage_frost", maxRank: 2, requires: ["frost_imp_frostbolt"], requiresPointsInBranch: 2 },
            { id: "frost_shatter", branch: "mage_frost", maxRank: 2, requiresPointsInBranch: 2, modifiersPerRank: { critPct: { add: 2 } } },
            { id: "frost_choice", branch: "mage_frost", maxRank: 1, requiresPointsInBranch: 5 },
            { id: "frost_winter_chill", branch: "mage_frost", maxRank: 2, requires: ["frost_choice"], requiresPointsInBranch: 8, modifiersPerRank: { critPct: { add: 1 } } },
        ],
    },
    {
        id: "warlock_affliction",
        classId: "warlock",
        name: "Hexcraft",
        icon: "poison",
        nodes: [
            { id: "aff_imp_agony", branch: "warlock_affliction", maxRank: 3 },
            { id: "aff_imp_corruption", branch: "warlock_affliction", maxRank: 3 },
            { id: "aff_fel_concentration", branch: "warlock_affliction", maxRank: 2, requires: ["aff_imp_agony"], requiresPointsInBranch: 2 },
            { id: "aff_amplify_curse", branch: "warlock_affliction", maxRank: 2, requiresPointsInBranch: 2 },
            { id: "aff_choice", branch: "warlock_affliction", maxRank: 1, requiresPointsInBranch: 5 },
            { id: "aff_unstable_affliction", branch: "warlock_affliction", maxRank: 2, requires: ["aff_choice"], requiresPointsInBranch: 8 },
        ],
    },
    {
        id: "warlock_demonology",
        classId: "warlock",
        name: "Pactbound",
        icon: "wing",
        nodes: [
            { id: "demo_demonic_embrace", branch: "warlock_demonology", maxRank: 3, modifiersPerRank: { sta: { add: 3 } } },
            { id: "demo_fel_armor", branch: "warlock_demonology", maxRank: 3, modifiersPerRank: { armor: { multiply: 1.03 } } },
            { id: "demo_health_funnel", branch: "warlock_demonology", maxRank: 2, requires: ["demo_demonic_embrace"], requiresPointsInBranch: 2 },
            { id: "demo_master_summoner", branch: "warlock_demonology", maxRank: 2, requiresPointsInBranch: 2, modifiersPerRank: { maxHp: { multiply: 1.04 } } },
            { id: "demo_choice", branch: "warlock_demonology", maxRank: 1, requiresPointsInBranch: 5 },
            { id: "demo_metamorphosis", branch: "warlock_demonology", maxRank: 2, requires: ["demo_choice"], requiresPointsInBranch: 8, modifiersPerRank: { sta: { multiply: 1.06 }, armor: { multiply: 1.06 } } },
        ],
    },
    {
        id: "warlock_destruction",
        classId: "warlock",
        name: "Ruination",
        icon: "bomb",
        nodes: [
            { id: "dest_cataclysm", branch: "warlock_destruction", maxRank: 3 },
            { id: "dest_bane", branch: "warlock_destruction", maxRank: 3 },
            { id: "dest_devastation", branch: "warlock_destruction", maxRank: 2, requires: ["dest_cataclysm"], requiresPointsInBranch: 2, modifiersPerRank: { critPct: { add: 2 } } },
            { id: "dest_imp_searing", branch: "warlock_destruction", maxRank: 2, requiresPointsInBranch: 2 },
            { id: "dest_choice", branch: "warlock_destruction", maxRank: 1, requiresPointsInBranch: 5 },
            { id: "dest_backdraft", branch: "warlock_destruction", maxRank: 2, requires: ["dest_choice"], requiresPointsInBranch: 8 },
        ],
    },
    {
        id: "druid_balance",
        classId: "druid",
        name: "Moongrove",
        icon: "star",
        nodes: [
            { id: "bal_imp_wrath", branch: "druid_balance", maxRank: 3 },
            { id: "bal_imp_moonfire", branch: "druid_balance", maxRank: 3 },
            { id: "bal_natures_reach", branch: "druid_balance", maxRank: 2, requires: ["bal_imp_wrath"], requiresPointsInBranch: 2 },
            { id: "bal_vengeance", branch: "druid_balance", maxRank: 2, requiresPointsInBranch: 2, modifiersPerRank: { critPct: { add: 2 } } },
            { id: "bal_choice", branch: "druid_balance", maxRank: 1, requiresPointsInBranch: 5 },
            { id: "bal_starfire_mastery", branch: "druid_balance", maxRank: 2, requires: ["bal_choice"], requiresPointsInBranch: 8 },
        ],
    },
    {
        id: "druid_feral",
        classId: "druid",
        name: "Wildfang",
        icon: "fist",
        nodes: [
            { id: "feral_thick_hide", branch: "druid_feral", maxRank: 3, modifiersPerRank: { armor: { multiply: 1.05 } } },
            { id: "feral_ferocity", branch: "druid_feral", maxRank: 3 },
            { id: "feral_brutal_impact", branch: "druid_feral", maxRank: 2, requires: ["feral_thick_hide"], requiresPointsInBranch: 2 },
            { id: "feral_feline_swiftness", branch: "druid_feral", maxRank: 2, requiresPointsInBranch: 2, modifiersPerRank: { agi: { add: 2 } } },
            { id: "feral_choice", branch: "druid_feral", maxRank: 1, requiresPointsInBranch: 5 },
            { id: "feral_heart_wild", branch: "druid_feral", maxRank: 2, requires: ["feral_choice"], requiresPointsInBranch: 8, modifiersPerRank: { sta: { multiply: 1.05 }, attackPower: { multiply: 1.05 } } },
        ],
    },
    {
        id: "druid_restoration",
        classId: "druid",
        name: "Groveheart",
        icon: "leaf",
        nodes: [
            { id: "rest_imp_rejuv", branch: "druid_restoration", maxRank: 3 },
            { id: "rest_druid_naturalist", branch: "druid_restoration", maxRank: 3 },
            { id: "rest_reflection", branch: "druid_restoration", maxRank: 2, requires: ["rest_imp_rejuv"], requiresPointsInBranch: 2 },
            { id: "rest_imp_regrowth", branch: "druid_restoration", maxRank: 2, requiresPointsInBranch: 2 },
            { id: "rest_druid_choice", branch: "druid_restoration", maxRank: 1, requiresPointsInBranch: 5 },
            { id: "rest_tree_life", branch: "druid_restoration", maxRank: 2, requires: ["rest_druid_choice"], requiresPointsInBranch: 8, modifiersPerRank: { spi: { add: 3 } } },
        ],
    },
];
export function specsForClass(classId) {
    return SPECS.filter((spec) => spec.classId === classId);
}
export const TALENT_POINTS_RULE = {
    firstLevel: 10,
    perLevel: 1,
};
